#!/bin/sh
# Regenerates ../n48_fallback_spv.h from fb.vert / fb.frag (glslangValidator, spirv-val vulkan1.2).
set -e
cd "$(dirname "$0")"
glslangValidator -V --target-env vulkan1.2 fb.vert -o fb.vert.spv
glslangValidator -V --target-env vulkan1.2 fb.frag -o fb.frag.spv
spirv-val --target-env vulkan1.2 fb.vert.spv; spirv-val --target-env vulkan1.2 fb.frag.spv
{ echo "/* generated by fallback/gen.sh - do not edit */"
  echo "static const unsigned char n48_fb_vs_spv[] __attribute__((aligned(4))) = {"; xxd -i < fb.vert.spv; echo "};"
  echo "static const unsigned char n48_fb_fs_spv[] __attribute__((aligned(4))) = {"; xxd -i < fb.frag.spv; echo "};"; } > ../n48_fallback_spv.h
rm -f fb.vert.spv fb.frag.spv
