#!/usr/bin/env python3
"""gen_fslearn_fixture.py - build 0.0.548 (, "the learned fill set"): build tests/fixture_fslearn_runs.h from the
REAL captures of the boots's P-slot table cites (1080p run11aa..run11ao, run11ap-r, run11aq = RUN AW, run11ar = RUN AX) and of
every earlier run11 boot that carries the present73 P-slot record, never by hand.

usage: gen_fslearn_fixture.py <runs-dir> > fixture_fslearn_runs.h
   runs-dir  notes/logs/runs of the MAIN checkout (the captures are not in git)

Per boot it reads driverlog-stream.txt ONCE, in order, and records:
  - every judged frame the kext printed in full (`gfx-xlat: frame N pid P (name) stamp S K IB(s) - VERDICT ... IB0 len L`) joined to the
    `FRAME TARGET: ... the first is VA X` line that follows it (the frame's CB0, the kext's tgtVa); the kext prints these for the first
    judged frames of the boot, which is the window the learner needs;
  - the present73 P-slot record (`present73: P CB0 VA X -> VRAM Y (slot I, ...`) - the INDEPENDENT answer: slot 0 and slot 4 are the
    members the learner must find (: "the members are the 1st and 5th distinct CB0 of a 1040-dw single-IB frame").
A frame whose line did not print (shape refused: no IB) never reaches the learner in the kext either, and is absent here too.
Nothing here decides anything; the hypotheses live in gfx_fslearn_test.cpp.
"""
import os
import re
import sys

#'s 19 boots (run11ai printed no P slot and no judged frame, so it is absent: 15 x 1080p of run11aa..run11ao + the three 1440p),
# plus every earlier run11 boot whose log carries the present73 P-slot record (run11a..run11z: 25 more 1080p boots).
RUNS = ['run11aa', 'run11ab', 'run11ac', 'run11ac-r', 'run11ad', 'run11ae', 'run11af', 'run11ag', 'run11ah',
        'run11aj', 'run11ak', 'run11al', 'run11am', 'run11an', 'run11ao', 'run11ap-r', 'run11aq', 'run11ar',
        'run11a', 'run11b', 'run11c', 'run11d', 'run11e', 'run11f', 'run11g', 'run11h', 'run11i', 'run11j', 'run11k', 'run11l',
        'run11m', 'run11n', 'run11o', 'run11p', 'run11q', 'run11r', 'run11s', 'run11u', 'run11v', 'run11w', 'run11x', 'run11y',
        'run11z']
MAXF = 48

FR = re.compile(r'gfx-xlat: frame (\d+) pid (-?\d+) \([^)]*\) stamp \S+ (\d+) IB\(s\) - VERDICT .* IB0 len (\d+) ')
TG = re.compile(r'FRAME TARGET: (\d+) colour target\(s\); the first is VA (0x[0-9a-f]+)')
SL = re.compile(r'present73: P CB0 VA (0x[0-9a-f]+) -> VRAM (0x[0-9a-f]+) \(slot (\d+),')


def run(runs, name):
    frames, slots, cur = [], {}, None
    with open(os.path.join(runs, name, 'driverlog-stream.txt'), 'rb') as fh:
        for raw in fh:
            ln = raw.decode('utf-8', 'replace')
            m = FR.search(ln)
            if m:
                cur = [int(m.group(1)), int(m.group(2)), int(m.group(3)), int(m.group(4)), None]
                continue
            m = TG.search(ln)
            if m and cur is not None:
                cur[4] = int(m.group(2), 16) if int(m.group(1)) else 0
                if len(frames) < MAXF:
                    frames.append(tuple(cur))
                cur = None
                continue
            m = SL.search(ln)
            if m and int(m.group(3)) not in slots:
                slots[int(m.group(3))] = int(m.group(1), 16)
    return frames, slots


def main():
    runs = sys.argv[1]
    print('// fixture_fslearn_runs.h - GENERATED by gen_fslearn_fixture.py from notes/logs/runs (the boots of  + run11a..run11z). Do not edit.')
    print('// Per frame: judged frame number, submitting pid, IB count, IB0 length (dwords), CB0 VA (0 = no colour target).')
    print('#ifndef FIXTURE_FSLEARN_RUNS_H')
    print('#define FIXTURE_FSLEARN_RUNS_H')
    print('#include <stdint.h>')
    print('struct FslFrame { uint32_t frame; int32_t pid; uint32_t nib; uint32_t len0; uint64_t cb0; };')
    print('struct FslRun { const char *name; uint32_t p1440; const FslFrame *f; uint32_t n; uint64_t slot[6]; uint32_t nslots; };')
    tab = []
    for r in RUNS:
        frames, slots = run(runs, r)
        ident = r.replace('-', '_')
        print('static const FslFrame kFsl_%s[] = {' % ident)
        for f in frames:
            print('    { %du, %d, %du, %du, %#xull },' % f)
        print('};')
        sl = [slots.get(i, 0) for i in range(6)]
        n = sum(1 for i in range(6) if i in slots)
        p1440 = 1 if slots.get(0) == 0x400100000 else 0
        tab.append('    { "%s", %du, kFsl_%s, %du, { %s }, %du },' % (r, p1440, ident, len(frames),
                                                                   ', '.join('%#xull' % v for v in sl), n))
    print('static const FslRun kFslRuns[] = {')
    print('\n'.join(tab))
    print('};')
    print('#endif')


if __name__ == '__main__':
    main()
