#!/bin/zsh
# native_disp_plant.sh - planted breaks for tests/native_disp_test.cpp (build 0.0.613, #11 step 11h.2: the display pipe).
# Discipline: copy the sources the test reads into a scratch tree, apply ONE break to the REAL code (a header, a flow, the kernel glue, a call site), build the real test against the copy and demand
# it FAILS (a compile error, a failing check, a crash or a hang all count). A plant whose text is not found exactly once is itself reported as an escape. The CONTROL (no break) must pass.
#   run from anywhere:  src/navi48-bringup/tests/native_disp_plant.sh [first-plant-id last-plant-id]
# The table and the runner are Python (the breaks are multi-line and quote-heavy); this wrapper only hands it the tree root.
ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
exec python3 -u - "$ROOT" "${1:-0}" "${2:-9999}" <<'PY'
import os, shutil, subprocess, sys, tempfile, time

ROOT, FIRST, LAST = sys.argv[1], int(sys.argv[2]), int(sys.argv[3])
K = 'src/navi48-bringup'
FILES = [f'{K}/src/amd/native_disp_pure.h', f'{K}/src/amd/native_disp_flow.h', f'{K}/src/amd/native_metal_pure.h', f'{K}/src/amd/native_disp.cpp', f'{K}/src/amd/native_disp.h',
         f'{K}/src/amd/native_s1c.h', f'{K}/src/Navi48MetalNub.cpp', f'{K}/src/Navi48NativeClient.cpp', f'{K}/src/dcn/navi48_dcn.cpp', f'{K}/src/dcn/navi48_dcn.hpp', f'{K}/src/Navi48Bringup.cpp', f'{K}/src/Navi48UserClient.cpp', f'{K}/src/Navi48Bringup.hpp', f'{K}/src/Navi48MetalOps.h',
         f'{K}/Info.plist', f'{K}/tests/native_disp_test.cpp', f'{K}/tests/native_disp_plant.sh', 'tools/pc/navi48test.c']
PURE, FLOW, GLUE, NUB, BRG, UCL, CLI, PLIST = (f'{K}/src/amd/native_disp_pure.h', f'{K}/src/amd/native_disp_flow.h', f'{K}/src/amd/native_disp.cpp', f'{K}/src/Navi48MetalNub.cpp',
                                              f'{K}/src/Navi48Bringup.cpp', f'{K}/src/Navi48UserClient.cpp', 'tools/pc/navi48test.c', f'{K}/Info.plist')
AUX = os.environ.get('N48_AUX_ROOT', ROOT)

scr = tempfile.mkdtemp(prefix='ndisp-plant.')
def fresh():
    shutil.rmtree(scr, ignore_errors=True)
    for f in FILES:
        d = os.path.join(scr, f); os.makedirs(os.path.dirname(d), exist_ok=True); shutil.copy(os.path.join(ROOT, f), d)
    a = os.path.join(AUX, 'tools/native/navi48accel/src/Navi48MetalOps.h')
    if os.path.exists(a):
        d = os.path.join(scr, 'tools/native/navi48accel/src/Navi48MetalOps.h'); os.makedirs(os.path.dirname(d), exist_ok=True); shutil.copy(a, d)
def build_run():
    r = subprocess.run(['clang++', '-std=c++17', '-Wall', '-Wextra', '-O1', '-fsanitize=address,undefined', '-I', f'{K}/src', '-I', f'{K}/src/amd', f'{K}/tests/native_disp_test.cpp', '-o', os.path.join(scr, 't')],
                       cwd=scr, capture_output=True, text=True)
    if r.returncode != 0:
        first = next((l for l in r.stderr.splitlines() if 'error' in l), '')
        return 2, 'CAUGHT at compile time: ' + first[:140]
    try:
        r = subprocess.run([os.path.join(scr, 't'), '.'], cwd=scr, capture_output=True, text=True, timeout=60)
    except subprocess.TimeoutExpired:
        return 1, 'CAUGHT by a hang'
    if r.returncode == 0: return 0, 'the suite passed: ' + r.stdout.strip().splitlines()[-1]
    if r.returncode < 0: return 1, 'CAUGHT by a crash (signal %d)' % -r.returncode
    fails = [l for l in r.stdout.splitlines() if l.startswith('FAIL')]
    return 1, 'CAUGHT by %d check(s); first: %s' % (len(fails), (fails[0] if fails else r.stdout.strip().splitlines()[-1])[:120])

total = escaped = 0
def control():
    global total, escaped
    fresh(); total += 1
    rc, msg = build_run()
    if rc != 0: print('CONTROL: *** FAILED UNMODIFIED (%s) ***' % msg); escaped += 1
    else: print('CONTROL: ' + msg)
def plant(pid, path, desc, old, new):
    global total, escaped
    if pid < FIRST or pid > LAST: return
    fresh(); total += 1
    f = os.path.join(scr, path); s = open(f).read()
    n = s.count(old)
    if n != 1:
        print('PLANT %d: %s: PLANT TEXT NOT FOUND EXACTLY ONCE (%d)' % (pid, desc, n)); escaped += 1; return
    open(f, 'w').write(s.replace(old, new))
    t0 = time.time(); rc, msg = build_run(); dt = time.time() - t0
    if rc == 0: print('PLANT %d: %s: *** ESCAPED (%s) *** [%.1fs]' % (pid, desc, msg, dt)); escaped += 1
    else: print('PLANT %d: %s: %s [%.1fs]' % (pid, desc, msg, dt))

control()
# ---- the pure decisions --------------------------------------------------------------------------------------------------------------------------------------------------
plant(1, PURE, 'a display verb is admitted with the boot-arg OFF (action bound)', 'return action <= kLastOldAction || (latchOn && action <= kLastAction);', 'return action <= kLastOldAction || (action <= kLastAction);')
plant(2, PURE, 'a native exemption is granted with the boot-arg OFF', 'constexpr bool native_exempt(bool latchOn, uint32_t action, uint64_t arg) { return latchOn && verb_args_ok(action, arg); }', 'constexpr bool native_exempt(bool latchOn, uint32_t action, uint64_t arg) { (void)latchOn; return verb_args_ok(action, arg); }')
plant(3, PURE, 'fbname 2 is exempt', '(action == kActFbname && arg <= 1ull)', '(action == kActFbname && arg <= 2ull)')
plant(4, PURE, 'the OFF ops table is published as ABI 2 (an old table no longer means display off)', 'OpsShape{ 1u, N48_METAL_OPS_MIN, 0u }', 'OpsShape{ 2u, N48_METAL_OPS_V2, N48_DISP_F_ON }')
plant(5, PURE, 'the OFF ops table keeps the 144-byte size', 'OpsShape{ 1u, N48_METAL_OPS_MIN, 0u }', 'OpsShape{ 1u, N48_METAL_OPS_V2, 0u }')
plant(6, PURE, 'the OFF ops table carries the display flag', 'OpsShape{ 1u, N48_METAL_OPS_MIN, 0u }', 'OpsShape{ 1u, N48_METAL_OPS_MIN, N48_DISP_F_ON }')
plant(7, PURE, 'the runtime fact bits leak into the OFF mask', 'return latchOn ? (baseMask | (runtimeBits & kNeedFacts)) : baseMask;', 'return (baseMask | (runtimeBits & kNeedFacts));')
plant(8, PURE, 'facts_ok needs only the RESOURCE bit', 'return (mask & kNeedFacts) == kNeedFacts;', 'return (mask & N48_FACT_RESOURCE) != 0u;')
plant(9, PURE, 'the needed facts drop VIDMEMORY', 'constexpr uint32_t kNeedFacts = N48_FACT_RESOURCE | N48_FACT_SYSMEMORY | N48_FACT_VIDMEMORY;', 'constexpr uint32_t kNeedFacts = N48_FACT_RESOURCE | N48_FACT_SYSMEMORY;')
plant(10, PURE, 'the gate byte is not range checked', 'atCfgF0 == 0x480000u && atCfgF4Low == 8u && pipeGate <= 1u;', 'atCfgF0 == 0x480000u && atCfgF4Low == 8u;')
plant(11, PURE, 'the config +0x08 control is skipped', 'atCfgF0 == 0x480000u && atCfgF4Low == 8u && pipeGate <= 1u;', 'atCfgF4Low == 8u && pipeGate <= 1u;')
plant(12, PURE, 'a pipe the aux kext never traced counts as verified', 'p.classOurs && p.traced && p.backAccel', 'p.classOurs && p.backAccel')
plant(13, PURE, 'several pipes count as verified', 'p.dmReadable && p.count == 1u && p.havePipe', 'p.dmReadable && p.count >= 1u && p.havePipe')
plant(14, PURE, 'the framebuffer back-pointer is not checked', 'p.backAccel && p.backDm && p.backFb && p.fbOurs;', 'p.backAccel && p.backDm && p.fbOurs;')
plant(15, PURE, 'a family pipe (class not ours) counts as verified', 'p.havePipe && p.classOurs && p.traced', 'p.havePipe && p.traced')
plant(16, PURE, 'adopt goes ahead over pipes that are not verified ours', 'before.count == 0u ? kOk : before.nullPipe ? kNullPipe : pipe_ok(before) ? kAlready : kHasPipes;', 'kOk;')
plant(17, PURE, 'disarm needs a pipe (arm 0 not always allowed)', 'arg > 1ull ? kBadArg : arg == 0ull ? kOk :', 'arg > 1ull ? kBadArg : arg == 0ull ? (a.pipeOk ? kOk : kNoPipe) :')
plant(18, PURE, 'arm before the pipe exists', '!a.latchOn ? kOff : !a.factsOk ? kFactsOff : !a.pipeOk ? kNoPipe : !a.accelLayoutOk ? kAccelLayout : kOk;', '!a.latchOn ? kOff : !a.factsOk ? kFactsOff : !a.accelLayoutOk ? kAccelLayout : kOk;')
plant(19, PURE, 'arm without the resource facts', '!a.latchOn ? kOff : !a.factsOk ? kFactsOff : !a.pipeOk', '!a.latchOn ? kOff : !a.pipeOk')
plant(20, PURE, 'arm with the boot-arg OFF', '!a.latchOn ? kOff : !a.factsOk ? kFactsOff : !a.pipeOk', '!a.factsOk ? kFactsOff : !a.pipeOk')
plant(21, PURE, 'submit returns 0 for a zero status', 'return (statusKnown && txnStatus != 0u) ? txnStatus : kWillPerform;', 'return (statusKnown && txnStatus != 0u) ? txnStatus : 0u;')
plant(22, PURE, 'submit swallows a failed prepare (ignores a nonzero status)', 'return (statusKnown && txnStatus != 0u) ? txnStatus : kWillPerform;', 'return kWillPerform;')
plant(23, PURE, 'submit returns 0 when the status is unreadable', 'return (statusKnown && txnStatus != 0u) ? txnStatus : kWillPerform;', 'return statusKnown ? ((txnStatus != 0u) ? txnStatus : kWillPerform) : 0u;')
plant(24, PURE, 'isTransactionComplete is false', 'constexpr uint64_t iscomplete_result() { return 1ull; }', 'constexpr uint64_t iscomplete_result() { return 0ull; }')
plant(25, PURE, 'copy past the console: the destination rows at the console stride are not checked', 'if ((b.height - 1ull) * b.consoleStride + row > b.consoleBytes) return kBDest;', '(void)row;')
plant(26, PURE, 'the w*h*4 console bound is off by one (a frame that exactly fills the console is refused). NOTE: dropping this check outright is an EQUIVALENT mutant, it is implied by the destination-row check once the stride is >= a row', 'if (b.width * b.height * 4ull > b.consoleBytes) return kBDest;', 'if (b.width * b.height * 4ull >= b.consoleBytes) return kBDest;')
plant(27, PURE, 'the source rows are not checked against the source length', 'if ((b.height - 1ull) * b.srcBytesPerRow + row > b.srcBytes) return kBSrc;', '(void)row;')
plant(28, PURE, 'width need not equal the console width', 'if (b.width != b.consoleWidth || b.height > b.consoleHeight) return kBGeom;', 'if (b.height > b.consoleHeight) return kBGeom;')
plant(29, PURE, 'the destination product is computed in 32 bits', 'if ((b.height - 1ull) * b.consoleStride + row > b.consoleBytes) return kBDest;', 'if ((uint32_t)((b.height - 1ull) * b.consoleStride + row) > b.consoleBytes) return kBDest;')
plant(30, PURE, 'a frame taller than the console is admitted', 'if (b.width != b.consoleWidth || b.height > b.consoleHeight) return kBGeom;', 'if (b.width != b.consoleWidth) return kBGeom;')
plant(31, PURE, 'a row wider than the scratch buffer is admitted', 'if (row > kScratchBytes) return kBGeom;', '(void)row;')
plant(32, PURE, 'a console stride narrower than a row is admitted', 'if (b.srcBytesPerRow < row || b.consoleStride < row) return kBStride;', 'if (b.srcBytesPerRow < row) return kBStride;')
plant(33, PURE, 'a source stride narrower than a row is admitted', 'if (b.srcBytesPerRow < row || b.consoleStride < row) return kBStride;', 'if (b.consoleStride < row) return kBStride;')
plant(34, PURE, 'a 2^32 operand is no longer refused up front', 'if (b.width > 0xffffffffull || b.height > 0xffffffffull || b.srcBytesPerRow > 0xffffffffull || b.consoleStride > 0xffffffffull || b.consoleHeight > 0xffffffffull) return kBBadArg;', '(void)b;')
plant(35, PURE, 'a nonzero baseOffset is admitted', 'return baseOffset == 0ull && planeCount <= 1u', 'return planeCount <= 1u')
plant(36, PURE, 'a multi-plane surface is admitted', 'planeCount <= 1u && pixelFormat', 'planeCount <= 8u && pixelFormat')
plant(37, PURE, 'any pixel format is admitted', 'pixelFormat == kFmtBGRA && bytesPerElement == 4u;', 'bytesPerElement == 4u;')
plant(38, PURE, 'any element size is admitted', 'pixelFormat == kFmtBGRA && bytesPerElement == 4u;', 'pixelFormat == kFmtBGRA;')
plant(39, PURE, 'the stride disagreement is ignored', 'return sw == rw && sh == rh && sbpr == rbpr;', 'return sw == rw && sh == rh;')
plant(40, PURE, 'the shortcut is applied when its guard bit is set', 'constexpr bool shortcut_allowed(bool sysMemFlagsKnown, bool bit4Set) { return sysMemFlagsKnown && !bit4Set; }', 'constexpr bool shortcut_allowed(bool sysMemFlagsKnown, bool bit4Set) { (void)bit4Set; return sysMemFlagsKnown; }')
plant(41, PURE, 'the shortcut is applied when the guard byte cannot be read', 'constexpr bool shortcut_allowed(bool sysMemFlagsKnown, bool bit4Set) { return sysMemFlagsKnown && !bit4Set; }', 'constexpr bool shortcut_allowed(bool sysMemFlagsKnown, bool bit4Set) { (void)sysMemFlagsKnown; return !bit4Set; }')
plant(42, PURE, 'the shortcut ignores its switch', 'in.switchOn && shortcut_allowed(in.flagsKnown, in.bit4), in.switchOn && !shortcut_allowed', 'shortcut_allowed(in.flagsKnown, in.bit4), in.switchOn && !shortcut_allowed')
plant(43, PURE, 'slot 62 handles without the IOSurface', 'Res62Plan{ in.smKnown && in.smLen != 0ull && in.surfKnown && in.surfBpr != 0ull,', 'Res62Plan{ in.smKnown && in.smLen != 0ull,')
plant(44, PURE, 'slot 62 hands out the wrong number (allocation size = bytes per row)', '(in.smKnown && in.smLen != 0ull && in.surfKnown && in.surfBpr != 0ull) ? in.smLen : 0ull,', '(in.smKnown && in.smLen != 0ull && in.surfKnown && in.surfBpr != 0ull) ? in.surfBpr : 0ull,')
plant(45, PURE, 'the stand-in does not carry the prune-skip bit', 'o[kObjFlagD] = kObjFlagDValue;', 'o[kObjFlagD] = 0u;')
plant(46, PURE, 'the stand-in fill clobbers the vtable pointer', 'for (uint32_t i = 8u; i < kObjSize; ++i) o[i] = 0u;', 'for (uint32_t i = 0u; i < kObjSize; ++i) o[i] = 0u;')
plant(47, PURE, 'the stand-in fill leaves stale bytes (+0x38 not zeroed)', 'for (uint32_t i = 8u; i < kObjSize; ++i) o[i] = 0u;', '')
plant(48, PURE, 'an empty pipe-table entry matches pointer 0', 'if (t[i] == p && p != 0ull) return (int)i;', 'if (t[i] == p) return (int)i;')
plant(49, PURE, 'the duration minimum is wrong', 'if (d.n == 0ull || ns < d.min) d.min = ns;', 'if (d.n == 0ull || ns > d.min) d.min = ns;')
plant(50, PURE, 'the stamp count is not clamped', 'constexpr uint32_t stamp_walk_bound(uint32_t requested) { return requested > kStampMaxSlots ? kStampMaxSlots : requested; }', 'constexpr uint32_t stamp_walk_bound(uint32_t requested) { return requested; }')
plant(51, PURE, 'the stamp hazard is inverted', 'constexpr bool stamp_hazard(uint32_t completed, uint32_t submitted) { return submitted > completed; }', 'constexpr bool stamp_hazard(uint32_t completed, uint32_t submitted) { return submitted < completed; }')
plant(52, PURE, 'the boot-arg latches ON for any nonzero value', 'return (present && value == 1u) ? kLatchOn : kLatchOff;', 'return (present && value != 0u) ? kLatchOn : kLatchOff;')
plant(53, PURE, 'the plane-0 dirty bit is the wrong bit', 'constexpr uint64_t kDirtyPlane0 = 1ull;', 'constexpr uint64_t kDirtyPlane0 = 2ull;')
plant(54, PURE, 'the pipe-active offset is wrong', 'constexpr uint32_t kPipeActive = 0x298u;', 'constexpr uint32_t kPipeActive = 0x29cu;')
plant(56, PURE, 'the source product is computed in 32 bits', 'if ((b.height - 1ull) * b.srcBytesPerRow + row > b.srcBytes) return kBSrc;', 'if ((uint32_t)((b.height - 1ull) * b.srcBytesPerRow + row) > b.srcBytes) return kBSrc;')
plant(57, PURE, 'the resource system-memory offset is wrong', 'kResSysMem = 0x80u,', 'kResSysMem = 0x88u,')
plant(58, PURE, 'the transaction status offset is wrong', 'kTxnStatus = 0x58u;', 'kTxnStatus = 0x5cu;')
plant(59, PURE, 'the gate byte offset is wrong (accel+0xccf)', 'constexpr uint32_t kAccelCfgBase = 0xc88u;', 'constexpr uint32_t kAccelCfgBase = 0xc80u;')
plant(55, PURE, 'the IOSurface width offset is wrong', 'constexpr uint32_t kSurfW = 0x58u,', 'constexpr uint32_t kSurfW = 0x50u,')
# ---- the flows ------------------------------------------------------------------------------------------------------------------------------------------------------------
plant(60, FLOW, 'adopt without the resource bits (never turns them on)', '    e.facts_add(kNeedFacts);\n', '')
plant(61, FLOW, 'adopt without the resource bits (no refusal when they stay off)', '    if (!facts_ok(e.facts())) return kFactsOff;                              // refuse to run otherwise\n', '')
plant(62, FLOW, 'adopt turns the facts on only AFTER requestProbe', '    e.facts_add(kNeedFacts);\n    if (!facts_ok(e.facts())) return kFactsOff;                              // refuse to run otherwise\n    if (pre == kOk && !e.request_probe()) return kProbeFailed;\n', '    if (pre == kOk && !e.request_probe()) return kProbeFailed;\n    e.facts_add(kNeedFacts);\n    if (!facts_ok(e.facts())) return kFactsOff;\n')
plant(63, FLOW, 'adopt probes again although the verified pipe is already there', 'if (pre == kOk && !e.request_probe()) return kProbeFailed;', 'if (!e.request_probe()) return kProbeFailed;')
plant(64, FLOW, 'adopt records a pipe that failed verification', '    if (v != kOk) return v;\n    if (!e.publish_caps())', '    if (!e.publish_caps())')
plant(65, FLOW, 'adopt records without the capabilities', '    if (!e.publish_caps()) return kCapsFailed;\n', '    (void)e.publish_caps();\n')
plant(66, FLOW, 'adopt has no concurrency guard', '    if (!e.adopt_begin()) return kBusy;\n', '')
plant(67, FLOW, 'adopt skips the accelerator controls', '    if (!e.accel_layout_ok()) return kAccelLayout;\n', '')
plant(68, FLOW, 'adopt over a display machine with foreign pipes (precheck ignored)', '    if (pre != kOk && pre != kAlready) return pre;\n', '')
plant(69, FLOW, 'arm trusts a pipe it never verified', 'a.pipeOk = pipe_ok(e.probe_pipe());', 'a.pipeOk = true;')
plant(70, FLOW, 'arm skips the accelerator controls', 'if (a.pipeOk) a.accelLayoutOk = e.accel_layout_ok();', 'if (a.pipeOk) a.accelLayoutOk = true;')
plant(71, FLOW, 'disarm waits for the probes', '    if (arg == 1ull) {                                                       // the probes run only for an arm: a disarm never depends on them', '    {')
plant(72, FLOW, 'disarm does not disarm', 'if (arg == 0ull) { e.disarm(); mdc_teardown(e); reload_shut(e.rw()); return kOk; }', 'if (arg == 0ull) { return kOk; }')
plant(73, FLOW, 'the arm decision is ignored', '    if (d != kOk) return d;\n    if (arg == 0ull)', '    if (arg == 0ull)')
plant(74, FLOW, 'the dispatcher handles with the boot-arg OFF', '    if (!e.latch_on()) return 0;\n    switch (slot) {', '    switch (slot) {')
plant(75, FLOW, 'perform on a pipe the aux kext never named as its own', 'if (nargs != 1u || !e.known_pipe(self)) return 0;\n        guard_on_perform', 'if (nargs != 1u) return 0;\n        guard_on_perform')
plant(76, FLOW, 'submit returns 0 through the dispatcher', '*ret = submit_result(known, st);', '*ret = 0ull;')
plant(77, FLOW, 'perform returns its reason instead of success (the ring would not retire)', '        (void)perform_flow(e, args[0]);\n        *ret = 0ull;', '        *ret = perform_flow(e, args[0]);')
plant(78, FLOW, 'slot 267 returns no object (a status instead of a pointer)', '    *ret = (uint64_t)(uintptr_t)obj;', '    *ret = 1ull;')
plant(79, FLOW, 'slot 267 does not mark the pipe active', '    if (!e.wr8(pipe + kPipeActive, 1u)) return 0;', '')
plant(80, FLOW, 'slot 267 hands out an unprepared stand-in', '    standin_fill(obj);', '')
plant(81, FLOW, 'slot 267 acts on a pipe it does not know', '    if (!e.known_pipe(pipe)) return 0;                                       // not a pipe we were told is ours: the family\'s own slot runs\n', '')
plant(82, FLOW, 'perform copies while disarmed', '    if (!e.armed()) return kPfDisarmed;', '')
plant(83, FLOW, 'copy past the console: the bounds verdict is ignored', '    if (bv != kBOk) return perf_reason_from_bounds(bv);\n', '')
plant(84, FLOW, 'the source admission is ignored', '    if (!source_admitted(s.base, s.planes, s.fmt, s.bpe)) return kPfFormat;\n', '')
plant(85, FLOW, 'the geometry cross-check is ignored', '    if (!geometry_agrees(s.sw, s.sh, s.sbpr, s.rw, s.rh, s.rbpr)) return kPfMismatch;\n', '')
plant(86, FLOW, 'the scratch buffer is never released', '    e.scratch_release();\n    mdc_release(e.mdc(), ci);\n    return reason;', '    mdc_release(e.mdc(), ci);\n    return reason;')
plant(87, FLOW, 'rows land at the source stride instead of the console stride', 'e.console_write(y * c.stride, buf, row)', 'e.console_write(y * s.sbpr, buf, row)')
plant(88, FLOW, 'rows are read at the row width instead of the source stride', 'e.src_read(md, y * s.sbpr, buf, row)', 'e.src_read(md, y * row, buf, row)')
plant(89, FLOW, 'the plane array is not checked', 'if (!e.rd64(txn + kTxnPlanes, &arr) || !kptr_ok(arr)) return kPfBadArr;', 'if (!e.rd64(txn + kTxnPlanes, &arr)) return kPfBadArr;')
plant(90, FLOW, 'plane 0 need not be dirty', '    if ((dirty & kDirtyPlane0) == 0ull) return kPfNoPlane;\n', '')
plant(91, FLOW, 'the copy writes one row too many', 'for (uint64_t y = 0; y < s.sh; ++y) {', 'for (uint64_t y = 0; y <= s.sh; ++y) {')
plant(92, FLOW, 'the copied byte count is never noted', '        *bytesOut += row;\n', '')
plant(93, FLOW, 'a perform is never noted', '    e.note_perform(r, bytes, e.now_ns() - t0);\n', '')
# (plants 94 / 95, dropping the flow's own kptr_ok(surf) / kptr_ok(sm) test, are EQUIVALENT mutants: the first read through a non-kernel pointer fails inside E::rd (rdT checks kptr_ok) and yields the same reason: defence in depth, not testable)
plant(96, FLOW, 'the shortcut is applied although the plan refuses it', '    if (p.shortcut) {                                                       // independent of the outputs', '    if (true) {                                                             // independent of the outputs')
plant(97, FLOW, 'slot 62 writes through unchecked output pointers', '    if (!kptr_ok(args[0]) || !kptr_ok(args[1]) || args[0] == args[1] || (args[0] & 7ull) != 0ull || (args[1] & 7ull) != 0ull) return 0;\n', '')
plant(98, FLOW, 'slot 62 handles without the RESOURCE fact', '    if ((e.facts() & N48_FACT_RESOURCE) == 0u) return 0;\n', '')
plant(99, FLOW, 'slot 62 swaps the two outputs', 'if (!e.wr64(args[0], p.allocSize) || !e.wr64(args[1], p.bytesPerRow)) return 0;', 'if (!e.wr64(args[0], p.bytesPerRow) || !e.wr64(args[1], p.allocSize)) return 0;')
plant(100, FLOW, 'the shortcut flag is written without the pointer', '            (void)e.wr64(res + kResPrepared, smp);                           // the pointer first, the flag last: a reader that sees the flag sees the pointer\n', '')
plant(101, FLOW, 'stamps accept any object as the event machine', '|| !e.class_is(em, "Navi48EventMachine")) return kNoEventMachine;', ') return kNoEventMachine;')
plant(102, FLOW, 'the stamp count is reported unclamped', 'o->clamped = stamp_walk_bound(o->count);', 'o->clamped = o->count;')
# ---- the kernel glue and its call sites (source pins) ---------------------------------------------------------------------------------------------------------------------
plant(110, GLUE, 'the shortcut switch defaults OFF', 'bool rdy_shortcut() { return __atomic_load_n(&gD.shortcutOff, __ATOMIC_ACQUIRE) == 0u; }', 'bool rdy_shortcut() { return __atomic_load_n(&gD.shortcutOff, __ATOMIC_ACQUIRE) != 0u; }')
plant(111, GLUE, 'the boot-arg latch is not first-writer-wins', 'OSCompareAndSwap(n48disp::kLatchUnset,', 'OSCompareAndSwap(gLatch,')
plant(112, GLUE, 'a second boot-arg read is added', 'uint32_t n48disp_fact_bits(void) {', 'uint32_t n48disp_fact_bits(void) { uint32_t zz = 0; (void)PE_parse_boot_argn("navi48-metal-disp", &zz, sizeof(zz));')
plant(113, GLUE, 'the verbs skip their argument check', '    if (!n48disp::verb_args_ok(action, arg)) { out[0] = n48disp::kBadArg; return n48disp::kBadArg; }', '')
plant(114, GLUE, 'the armed mirror follows an unverified write', 'if (!wr8(a, v) || !rd8(a, &back) || back != v) return false;', 'if (!wr8(a, v)) return false;')
plant(115, GLUE, 'disarm clears the mirror only AFTER the byte write', '        __atomic_store_n(&gD.armed, 0u, __ATOMIC_RELEASE);                // the mirror first: perform stops copying at once\n', '')
plant(116, GLUE, 'the accelerator need not be our nub\'s child', 'if (s->getProvider() != nub) { s->release(); return false; }', '')
plant(117, GLUE, 'the gate opens without a row buffer', 'if (v && !gD.scratch) return false;', '')
plant(118, GLUE, 'adopt runs its own flow replacement (the tested flow is bypassed)', 'st = n48disp::adopt_flow(env);', 'st = n48disp::kOk;')
plant(119, GLUE, 'the hook bypasses the tested dispatcher (the call is gone)', 'const int h = n48disp::hook_dispatch(env, cls, slot, static_cast<uint64_t>(reinterpret_cast<uintptr_t>(self)), args, nargs, ret);', 'const int h = 0; (void)env;')
plant(120, GLUE, 'a lock is taken on the hook path', '    KernelEnv env;\n    const int h = n48disp::hook_dispatch', '    IOLock *lk = nullptr; (void)lk;\n    KernelEnv env;\n    const int h = n48disp::hook_dispatch')
plant(121, NUB, 'the nub always hands out the ABI-2 table', 'n48disp::ops_shape(n48disp_latched_on()).abi >= 2u ? &gOps : &gOpsV1;', '&gOps;')
plant(122, NUB, 'the factory mask drops the fact bits adopt turned on', 'n48disp::fact_mask(n48disp_latched_on(), n48metal::factory_mask(present, v), n48disp_fact_bits())', 'n48metal::factory_mask(present, v)')
plant(123, NUB, 'slot 62 never reaches the display glue', 'h = n48disp_res62(self, args, nargs, ret);', 'h = 0;')
plant(124, NUB, 'withdraw does not reset the display state', '	n48disp_on_withdraw();                                                        // 0.0.613: forget the pipes AFTER', '	// n48disp_on_withdraw();                                                        // 0.0.613: forget the pipes AFTER')
plant(125, NUB, 'the aux trace never reaches the pipe table', '	n48disp_on_trace(event, a, b);', '	(void)0;')
plant(126, NUB, 'the published properties report ABI 2 with the boot-arg OFF', 'OSNumber *abi = OSNumber::withNumber((uint64_t)shape.abi, 32);', 'OSNumber *abi = OSNumber::withNumber((uint64_t)N48_METAL_ABI, 32);')
plant(127, BRG, 'the display exemption is granted regardless of the latch', 'n48disp::native_exempt(n48disp_latched_on(), action, argScalar)', 'n48disp::native_exempt(true, action, argScalar)')
plant(128, BRG, 'the display exemption sits after the native refusal', '	if (!n48scan::accel_exempt(action, argScalar) && !n48disp::native_exempt(n48disp_latched_on(), action, argScalar)) {', '	if (!n48scan::accel_exempt(action, argScalar)) {')
plant(129, BRG, 'the action bound is not repeated in accelExperiment', '	if (action > n48disp::kLastOldAction && !n48disp::action_admitted(n48disp_latched_on(), action)) return kIOReturnBadArgument;', '')
plant(130, BRG, 'a display verb is not dispatched', 'if (action == 83 || action == 84 || action == 85 || action == 86 || action == 87 || action == 89 || action == 90) {', 'if (action == 83 || action == 84 || action == 85 || action == 86 || action == 89 || action == 90) {')
plant(269, BRG, 'V2: pipevbl (89) is not dispatched', 'if (action == 83 || action == 84 || action == 85 || action == 86 || action == 87 || action == 89 || action == 90) {', 'if (action == 83 || action == 84 || action == 85 || action == 86 || action == 87 || action == 90) {')
plant(131, UCL, 'the user client bound opens past 82 with the boot-arg OFF', 'if (action > 82 && !n48disp::action_admitted(n48disp_latched_on(), action)) return kIOReturnBadArgument;', 'if (action > 87) return kIOReturnBadArgument;')
plant(132, UCL, 'the old unconditional bound is back', 'if (action > 82 && !n48disp::action_admitted(n48disp_latched_on(), action)) return kIOReturnBadArgument;', 'if (action > 82) return kIOReturnBadArgument;')
plant(133, UCL, 'the legacy user client takes the exclusive native open', 'if (clientHasPrivilege(securityID, kIOClientPrivilegeAdministrator) != kIOReturnSuccess) {', 'if (amdgpu::n1c_is_open() || clientHasPrivilege(securityID, kIOClientPrivilegeAdministrator) != kIOReturnSuccess) {')
plant(134, BRG, 'every type is routed to the native client', 'if (type == N48N_UC_TYPE) return IOAccelNavi48NativeClient::create(this, owningTask, securityID, type, properties, handler);', 'return IOAccelNavi48NativeClient::create(this, owningTask, securityID, type, properties, handler);')
plant(135, PLIST, 'the version is not bumped', '<key>CFBundleVersion</key>\n\t<string>0.0.620</string>', '<key>CFBundleVersion</key>\n\t<string>0.0.612</string>')
plant(136, CLI, 'the CLI has no pipeadopt', 'else if (what && !strcmp(what, "pipeadopt")) in = 83;', '')
plant(137, CLI, 'the CLI sends the wrong action for pipearm', 'else if (what && !strcmp(what, "pipearm")) in = 84;', 'else if (what && !strcmp(what, "pipearm")) in = 85;')
plant(138, PURE, 'a forbidden pipe-offset spelling is introduced in the pure header', 'constexpr uint32_t kPipeSize = 0x318u;', 'constexpr uint32_t kPipeSize = 0x318u;   // see pipe+' + '0x299')

# ---- 0.0.615: the HIGH-review fixes (P1 pci gate, P2 withdraw, P3 NULL pipe, G1 crash-loop guard, W1 flags) -------------------------------------------------------------------------
HPP = f'{K}/src/Navi48Bringup.hpp'
plant(140, PURE, 'P1: pci_admit ignores the resource facts', 'return latchOn && facts_ok(factoryMask); }', 'return latchOn; }')
plant(141, FLOW, 'P1: the flow hands the PCI device out with the facts off', 'return pci_admit(e.latch_on(), e.facts());', 'return e.latch_on();')
plant(142, GLUE, 'P1: the kernel pci_device is back to the latch alone', 'n48disp::pci_admit_flow(env) ? static_cast<void *>(navi48_bringup_pci()) : nullptr;', 'n48disp_latched_on() ? static_cast<void *>(navi48_bringup_pci()) : nullptr;')
plant(169, NUB, 'P1: the ops hook skips the gate', 'void *op_pci_device(void *ctx) { return n48disp_pci_device(ctx); }', 'void *op_pci_device(void *ctx) { (void)ctx; return navi48_bringup_pci(); }')
plant(143, FLOW, 'P2: withdraw does not disarm', '    e.disarm();\n    mdc_teardown(e);                                                       // 0.0.616: every prepared descriptor completed and released (after the mirror is clear, before anything is forgotten)\n    reload_shut(e.rw());                                                   // 0.0.619 (R1)\n    e.forget_pipes();', '    mdc_teardown(e);                                                       // 0.0.616: every prepared descriptor completed and released (after the mirror is clear, before anything is forgotten)\n    reload_shut(e.rw());                                                   // 0.0.619 (R1)\n    e.forget_pipes();')
plant(144, FLOW, 'P2: withdraw forgets before it disarms', '    e.disarm();\n    mdc_teardown(e);                                                       // 0.0.616: every prepared descriptor completed and released (after the mirror is clear, before anything is forgotten)\n    reload_shut(e.rw());                                                   // 0.0.619 (R1)\n    e.forget_pipes();', '    e.forget_pipes();\n    e.disarm();\n    mdc_teardown(e);')
plant(145, GLUE, 'P2: on_withdraw bypasses the tested flow', 'n48disp::withdraw_flow(env);', '(void)env;')
plant(146, PURE, 'P3: the precheck ignores a counted NULL pipe', 'before.nullPipe ? kNullPipe : ', '')
plant(147, PURE, 'P3: the verdict ignores a counted NULL pipe', 'p.nullPipe ? kNullPipe : ', '')
plant(148, FLOW, 'P3: adopt never logs the NULL-pipe advice', '    if (st == kNullPipe) e.note_null_pipe();', '')
plant(149, GLUE, 'P3: the kernel probe never marks a NULL pipe', 'pipe0 == 0ull) p.nullPipe = true;', 'pipe0 == 1ull) p.nullPipe = true;')
plant(150, CLI, 'P3: the CLI prints no reboot advice', 'NULL pipe stored by the family; REBOOT before', 'pipe stored by the family; REBOOT before')
plant(166, GLUE, 'P3: the log line has lost the advice', '"adopt: NULL pipe stored by the family; reboot before', '"adopt: pipe stored by the family; reboot before')
plant(165, PURE, 'P3: the new status has no name', 's == kNullPipe ? "the family stored a NULL pipe (its init failed): reboot before any WindowServer restart" : ', '')
plant(151, PURE, 'G1: the guard needs four calls', 'constexpr uint32_t kGuardCalls = 3u;', 'constexpr uint32_t kGuardCalls = 4u;')
plant(152, PURE, 'G1: the window is 60 s', 'kGuardWindowNs = 120ull * 1000000000ull;', 'kGuardWindowNs = 60ull * 1000000000ull;')
plant(153, PURE, 'G1: the window edge is exclusive', 'nowNs - oldestNs <= kGuardWindowNs;', 'nowNs - oldestNs < kGuardWindowNs;')
plant(154, FLOW, 'G1: the counter is not reset on arm', '    guard_reset(e.guard());', '    (void)0;')
plant(155, FLOW, 'G1: a perform is never noted', '        guard_on_perform(e.guard());', '        (void)0;')
plant(156, FLOW, 'G1: the trip does not disarm', '{ e.disarm(); mdc_teardown(e); reload_shut(e.rw()); e.note_autodisarm(kAdGuard); }', '{ e.note_autodisarm(kAdGuard); }')
plant(157, FLOW, 'G1: calls are counted while disarmed', 'if (e.armed() && !reload_on_init_fb(e) && guard_on_init_fb(', 'if (!reload_on_init_fb(e) && guard_on_init_fb(')
plant(158, FLOW, 'G1: the guard compares against the wrong stamp', '__atomic_load_n(&g.ts[(idx + 1u) % 3u], __ATOMIC_ACQUIRE);', '__atomic_load_n(&g.ts[idx % 3u], __ATOMIC_ACQUIRE);')
plant(159, FLOW, 'G1: the trip is never evaluated', 'if (e.armed() && !reload_on_init_fb(e) && guard_on_init_fb(e.guard(), e.now_ns())) {', 'if (false && guard_on_init_fb(e.guard(), e.now_ns())) {')
plant(160, PURE, 'W1: the flags word drops the write-combined bit', ' | (bar0Wc ? kFlagBar0Wc : 0u) |', ' |')
plant(161, GLUE, 'W1: the glue always reports uncached', 'navi48_bar0_write_combined(),   // 0.0.615 (W1)', 'false,   // 0.0.615 (W1)')
plant(162, BRG, 'W1: the bring-up accessor is always false', '->bar0WriteCombined();', '->bar0WriteCombined() && false;')
plant(163, HPP, 'W1: the accessor tests the wrong cache bit', '(bar0Map->getMapOptions() & kIOMapWriteCombineCache) != 0; }', '(bar0Map->getMapOptions() & kIOMapWriteCombineCache) == 0; }')
plant(164, CLI, 'W1: the CLI reads the wrong flag bit', '(out[12] & 32) ? "WRITE-COMBINED (perform', '(out[12] & 64) ? "WRITE-COMBINED (perform')

# ---- 0.0.616: the prepared-descriptor cache (m11h4-1: readBytes on an unprepared IOGMD panicked in perform) ------------------------------------------------------------------------
MISS = "    if (ci < 0) { __atomic_add_fetch(&e.mdc().misses, 1ull, __ATOMIC_RELAXED); e.note_md(kMdNoteMiss, md, 0ull); return kPfNotPrepared; }\n"
plant(170, FLOW, 'M1: perform reads on a cache miss (the miss refusal is gone)', MISS, '    if (ci < 0) { }\n')
plant(171, FLOW, 'M2: submit skips the prepare (an entry is marked Ready unprepared)', '    if (!e.md_prepare(md)) {', '    if (false) {')
plant(172, PURE, 'M3: eviction / retire ignores a busy entry', '    if (__atomic_load_n(&c.e[i].busy, __ATOMIC_SEQ_CST) != 0u) { __atomic_store_n(&c.e[i].state, (uint32_t)kMdReady, __ATOMIC_SEQ_CST); return false; }\n', '')
plant(173, FLOW, 'M4: teardown misses the complete', '        e.md_unprepare(old);\n        __atomic_add_fetch(&c.tornDown, 1ull, __ATOMIC_RELAXED);', '        __atomic_add_fetch(&c.tornDown, 1ull, __ATOMIC_RELAXED);')
plant(174, FLOW, 'M5: eviction completes the victim twice', '            e.md_unprepare(old);                                              // complete() + release(): no lock is held here, perform takes none\n', '            e.md_unprepare(old);\n            e.md_unprepare(old);\n')
plant(175, FLOW, 'M6: teardown leaves the entry Ready (a second teardown completes again)', '        __atomic_store_n(&c.e[i].md, 0ull, __ATOMIC_RELEASE);\n        __atomic_store_n(&c.e[i].state, (uint32_t)kMdEmpty, __ATOMIC_RELEASE);\n    }\n}', '        __atomic_store_n(&c.e[i].state, (uint32_t)kMdReady, __ATOMIC_RELEASE);\n    }\n}')
plant(176, FLOW, 'M7: arm 0 does not tear the cache down', 'if (arg == 0ull) { e.disarm(); mdc_teardown(e); reload_shut(e.rw()); return kOk; }', 'if (arg == 0ull) { e.disarm(); return kOk; }')
plant(177, FLOW, 'M8: withdraw does not tear the cache down', '    mdc_teardown(e);                                                       // 0.0.616: every prepared descriptor completed and released (after the mirror is clear, before anything is forgotten)\n', '')
plant(178, FLOW, 'M9: under the HUNG latch the teardown completes instead of leaking', '        if (hung) { __atomic_add_fetch(&c.leaked, 1ull, __ATOMIC_RELAXED);', '        if (false) { __atomic_add_fetch(&c.leaked, 1ull, __ATOMIC_RELAXED);')
plant(179, FLOW, 'M10: submit never prepares (the hook does not call submit_prepare)', '        if (*ret == kWillPerform) (void)submit_prepare(e, args[0]);          // 0.0.616: wire the plane-0 descriptor HERE (thread context), never in perform\n', '')
plant(180, FLOW, 'M11: perform wires the descriptor itself on a miss', MISS, '    if (ci < 0) { if (!e.md_prepare(md)) return kPfNotPrepared; }\n')
plant(181, FLOW, 'M12: teardown does not wait for a perform inside the entry', '        while (__atomic_load_n(&c.e[i].busy, __ATOMIC_SEQ_CST) != 0u && e.now_ns() - t0 < kMdDrainNs) { }\n        if (__atomic_load_n(&c.e[i].busy, __ATOMIC_SEQ_CST) != 0u) {', '        (void)t0;\n        if (false) {')
plant(182, FLOW, 'M13: submit prepares while disarmed', '    if (!e.armed()) return kMdSkipDisarmed;\n', '')
plant(183, FLOW, 'M14: a disarm that races the fill leaves the entry wired', '    if (!e.armed()) mdc_teardown(e);                                          // a disarm raced the fill: nothing stays wired on a disarmed pipe\n', '')
plant(184, FLOW, 'M15: eviction picks the MOST recently used entry', 'if (v < 0 || l < best) { v = (int)i; best = l; }', 'if (v < 0 || l > best) { v = (int)i; best = l; }')
plant(185, PURE, 'M16: src_read\'s "held" assertion ignores the hold', ' && __atomic_load_n(&c.e[i].busy, __ATOMIC_ACQUIRE) != 0u) return true;', ') return true;')
plant(186, GLUE, 'M17: the kernel src_read has no cache assertion', '        if (!n48disp::mdc_held(gD.mdc, md)) return false;', '')
plant(187, GLUE, 'M18: md_prepare retains an object that is not an IOMemoryDescriptor', '        if (!d) return false;\n        d->retain();', '        d->retain();')
plant(188, GLUE, 'M19: the glue never reports the HUNG latch to the cache', 'bool hung() { return amdgpu::n1c_hung(); }', 'bool hung() { return false; }')
plant(189, GLUE, 'M20: a failed prepare keeps the reference', 'if (d->prepare(kIODirectionOut) != kIOReturnSuccess) { d->release(); return false; }', 'if (d->prepare(kIODirectionOut) != kIOReturnSuccess) { return false; }')
plant(190, PURE, 'M21: the new reason has no name', '           r == kPfNotPrepared ? "the source memory descriptor was not prepared by submit (not in the cache)" :\n', '           ')
plant(191, PURE, 'M22: a hit for one descriptor admits another', 'inline int mdc_acquire(MdCache &c, uint64_t md) {\n    if (md == 0ull) return -1;', 'inline int mdc_acquire(MdCache &c, uint64_t md) {\n    if (md == 0ull) return -1;\n    md = c.e[0].md;')
plant(192, FLOW, 'M23: a failed prepare leaves its slot claimed', '        __atomic_store_n(&c.e[slot].state, (uint32_t)kMdEmpty, __ATOMIC_RELEASE);\n        __atomic_add_fetch(&c.prepFail', '        __atomic_add_fetch(&c.prepFail')
plant(193, FLOW, 'M24: perform does not release its hold on the entry', '    e.scratch_release();\n    mdc_release(e.mdc(), ci);\n    return reason;', '    e.scratch_release();\n    return reason;')
plant(195, GLUE, 'M26: stat page 2 loses reason 19', 'out[11] = n48disp::dur_avg(gD.dur); out[12] = gD.dur.max;', 'out[10] = gD.dur.min; out[11] = n48disp::dur_avg(gD.dur); out[12] = gD.dur.max;')

# ---- 0.0.617: K1 (the WindowServer client's close disarms), K2 (HUNG disarms), K3 (the guard ignores 'performed'), K4 (the cause, and only an explicit arm re-arms) ----------------------------------------------
NCL = f'{K}/src/Navi48NativeClient.cpp'
plant(196, FLOW, 'K3: the guard exempts a pipe that has performed (the 0.0.615 rule)', '    return guard_trip(idx, nowNs, oldest);', '    return guard_trip(idx, nowNs, oldest) && __atomic_load_n(&g.performed, __ATOMIC_ACQUIRE) == 0u;')
plant(197, NCL, 'K1: clientClose does not disarm', 'if (opened) { n48disp_on_ws_client_closed(adminClient); amdgpu::n1c_close("clientClose");', 'if (opened) { amdgpu::n1c_close("clientClose");')
plant(198, NCL, 'K1: stop does not disarm', 'if (opened) { n48disp_on_ws_client_closed(adminClient); amdgpu::n1c_close("stop");', 'if (opened) { amdgpu::n1c_close("stop");')
plant(199, NCL, 'K1: clientClose disarms only AFTER n1c_close (the gate stays open through the idle wait)', 'n48disp_on_ws_client_closed(adminClient); amdgpu::n1c_close("clientClose");', 'amdgpu::n1c_close("clientClose"); n48disp_on_ws_client_closed(adminClient);')
plant(200, NCL, 'K1: an administrator client also disarms (the flag is ignored)', 'n48disp_on_ws_client_closed(adminClient); amdgpu::n1c_close("clientClose");', 'n48disp_on_ws_client_closed(false); amdgpu::n1c_close("clientClose");')
plant(201, PURE, 'K1: the decision ignores the admin flag', 'return latchOn && !adminClient; }', 'return latchOn; }')
plant(202, PURE, 'K1: the decision ignores the latch', 'return latchOn && !adminClient; }', 'return !adminClient; }')
plant(203, FLOW, 'K1/K2: the auto-disarm acts (and logs) when the pipe is not armed', '    if (!e.armed()) return false;\n    e.disarm();\n    mdc_teardown(e);\n    reload_shut(e.rw());                                                     // 0.0.619 (R1): a disarmed pipe has no restart to tolerate\n    e.note_autodisarm(cause);', '    e.disarm();\n    mdc_teardown(e);\n    reload_shut(e.rw());                                                     // 0.0.619 (R1): a disarmed pipe has no restart to tolerate\n    e.note_autodisarm(cause);')
plant(204, FLOW, 'K1/K2: the auto-disarm leaves the descriptor cache wired', '    e.disarm();\n    mdc_teardown(e);\n    reload_shut(e.rw());                                                     // 0.0.619 (R1): a disarmed pipe has no restart to tolerate\n    e.note_autodisarm(cause);', '    e.disarm();\n    reload_shut(e.rw());                                                     // 0.0.619 (R1): a disarmed pipe has no restart to tolerate\n    e.note_autodisarm(cause);')
plant(205, FLOW, 'K1/K2: the cache is torn down BEFORE the mirror is cleared', '    e.disarm();\n    mdc_teardown(e);\n    reload_shut(e.rw());                                                     // 0.0.619 (R1): a disarmed pipe has no restart to tolerate\n    e.note_autodisarm(cause);', '    mdc_teardown(e);\n    e.disarm();\n    reload_shut(e.rw());                                                     // 0.0.619 (R1): a disarmed pipe has no restart to tolerate\n    e.note_autodisarm(cause);')
plant(206, FLOW, 'K1: the close records the wrong cause', 'return auto_disarm_flow(e, kAdWsClose);', 'return auto_disarm_flow(e, kAdGuard);')
plant(207, FLOW, 'K2: the HUNG flow ignores the latch', '    if (!e.latch_on()) return false;\n    return auto_disarm_flow(e, kAdHung);', '    return auto_disarm_flow(e, kAdHung);')
plant(208, NUB, 'K2: hungLatched does not disarm', '\tn48disp_on_hung();', '\t(void)0;')
plant(209, GLUE, 'K2: the kernel entry bypasses the tested HUNG flow', '(void)n48disp::hung_latched_flow(env);', '(void)env;')
plant(210, GLUE, 'K1: the kernel entry bypasses the tested close flow', '(void)n48disp::ws_client_closed_flow(env, adminClient);', '(void)env; (void)adminClient;')
plant(211, FLOW, 'K4: an explicit arm does not clear the auto-disarmed mark', '    if (ok) e.clear_autodisarm();', '')
plant(212, FLOW, 'K4: a FAILED arm clears the auto-disarmed mark', '    if (ok) e.clear_autodisarm();', '    e.clear_autodisarm();')
plant(213, PURE, 'K4: the flags word drops the cause', '(autoCause != 0u && autoCause < kAdCount ? (kFlagAutoDisarmed | (autoCause << kFlagCauseShift)) : 0u);', '0u;')
plant(214, GLUE, 'K4: the glue does not pass the cause to the flags word', '__atomic_load_n(&gD.autoCause, __ATOMIC_ACQUIRE));                            // 0.0.617 (K4)', '0u);                            // 0.0.617 (K4)')
plant(215, GLUE, 'K4: the stat line does not say auto-disarmed', 'auto-disarmed: %s (count %llu); ', '')
plant(216, GLUE, 'K4: the note does not keep the cause', '__atomic_store_n(&gD.autoCause, cause < n48disp::kAdCount ? cause : (uint32_t)n48disp::kAdNone, __ATOMIC_RELEASE);', '(void)cause;')
plant(217, PURE, 'K1: the log text no longer names the close', 'c == kAdWsClose ? "the WindowServer GPU client closed while armed"', 'c == kAdWsClose ? "a client closed"')
plant(218, FLOW, 'K3: the guard trip records no cause', 'e.note_autodisarm(kAdGuard); }   // 0.0.619 (R1): inside an operator restart window the call is not counted', 'e.note_autodisarm(kAdNone); }   // 0.0.619 (R1): inside an operator restart window the call is not counted')
plant(220, BRG, 'K5: the VRAM keys are published on every boot (the native latch is dropped)', 'if (amdgpu::native_s1b_latched()) publishNativeVramOn(pciDevice, vramMB);', 'publishNativeVramOn(pciDevice, vramMB);')
plant(221, BRG, 'K5: totalsize is in MiB, not bytes', 'const uint64_t bytes = static_cast<uint64_t>(vramMB) << 20;', 'const uint64_t bytes = static_cast<uint64_t>(vramMB);')
plant(222, BRG, 'K5: the old key is dropped', 'setProperty("VRAM,TotalMB", static_cast<uint64_t>(vramMB), 32);\n	setProperty("MMIO,Verified"', 'setProperty("MMIO,Verified"')
plant(219, GLUE, 'K4: the glue forgets to clear the mark', 'void clear_autodisarm() { __atomic_store_n(&gD.autoCause, 0u, __ATOMIC_RELEASE); }', 'void clear_autodisarm() { }')

# ---- 0.0.617 K6: the v1 copy is skipped while a native client owns the scanout plane; the transaction-interval counters ----------------------------------------------------------------------
DCN = f'{K}/src/dcn/navi48_dcn.cpp'
plant(223, FLOW, 'K6: perform ignores the scanout owner', '    if (e.scan_active()) return kPfScanOwned;', '    (void)0;')
plant(224, FLOW, 'K6: submit wires while the plane is owned', '    if (e.scan_active()) { e.note_scan_owned_submit(); return kMdSkipScanOwned; }', '    (void)0;')
plant(225, FLOW, 'K6: perform copies ONLY while the plane is owned (inverted)', '    if (e.scan_active()) return kPfScanOwned;', '    if (!e.scan_active()) return kPfScanOwned;')
plant(226, FLOW, 'K6: submit skips wiring when the plane is NOT owned (inverted)', '    if (e.scan_active()) { e.note_scan_owned_submit();', '    if (!e.scan_active()) { e.note_scan_owned_submit();')
plant(227, FLOW, 'K6: the skipped submit is not counted', '{ e.note_scan_owned_submit(); return kMdSkipScanOwned; }', '{ return kMdSkipScanOwned; }')
plant(228, FLOW, 'K6: the submit interval is never noted', '        ival_note(e.ivl(), e.now_ns());', '        (void)0;')
plant(229, FLOW, 'K6: the arm does not restart the interval statistics', '    ival_reset(e.ivl());', '    (void)0;')
plant(230, PURE, 'K6: the first submit records a bogus interval', 'if (prev != 0ull && nowNs >= prev) dur_note(', 'if (nowNs >= prev) dur_note(')
plant(231, PURE, 'K6: a backwards clock records a huge interval', 'if (prev != 0ull && nowNs >= prev) dur_note(v.d, nowNs - prev);', 'if (prev != 0ull) dur_note(v.d, nowNs - prev);')
plant(232, PURE, 'K6: the scan-owned reason has no name', 'r == kPfScanOwned ? "the scanout plane is owned by a native client (the v1 copy is skipped)" : "unknown";', '"unknown";')
plant(233, PURE, 'K6: stat page 3 is not admitted', '(action == kActStat && arg <= 4ull)', '(action == kActStat && arg <= 2ull)')
plant(234, GLUE, 'K6: the glue never sees the acquisition', 'bool scan_active() { return n48dcn::scanActive(); }', 'bool scan_active() { return false; }')
plant(235, DCN, 'K6: scanActive reads a different flag (the unlocked, non-atomic acquired bool)', 'bool scanActive() { return __atomic_load_n(&gScan.active, __ATOMIC_ACQUIRE) != 0u; }', 'bool scanActive() { return gScan.acquired; }')
plant(236, GLUE, 'K6: page 3 does not show the acquisition', 'out[9] = n48dcn::scanActive() ? 1u : 0u;', 'out[9] = 0u;')
plant(237, GLUE, 'K6: the skipped-submit counter is not kept', 'void note_scan_owned_submit() { __atomic_add_fetch(&gD.submitScanSkipped, 1ull, __ATOMIC_RELAXED); }', 'void note_scan_owned_submit() { }')
plant(238, CLI, 'K6: the CLI has no page 3', 'strtoull(arg, NULL, 0) == 3) {\n                /* 0.0.617', 'strtoull(arg, NULL, 0) == 4) {\n                /* 0.0.617')
plant(239, PURE, 'K6: the count of reasons is not grown (the reason has no slot)', 'kPfScanOwned = 20, kPfCount = 21', 'kPfScanOwned = 20, kPfCount = 20')

# ---- 0.0.618 V1/V2: the vblank timestamps (txn+0x178 / +0x188) written by the perform hook, behind the `pipevbl` switch ----------------------------------------------------------------------
plant(240, FLOW, 'V1: the stamp is skipped on the scan-owned path', 'const uint32_t v = vbl_stamp_flow(e, txn, r);', 'const uint32_t v = (r == kPfScanOwned) ? (uint32_t)kVblOff : vbl_stamp_flow(e, txn, r);')
plant(241, FLOW, 'V1: the stamp is skipped on the copy path', 'const uint32_t v = vbl_stamp_flow(e, txn, r);', 'const uint32_t v = (r == kPfCopied) ? (uint32_t)kVblOff : vbl_stamp_flow(e, txn, r);')
plant(242, PURE, 'V1: the vblank-time word offset is wrong', 'kTxnVblTime = 0x178u, kTxnVblNext = 0x188u;', 'kTxnVblTime = 0x170u, kTxnVblNext = 0x180u;')
plant(243, PURE, 'V1: the next-vblank word offset is wrong (+0x190)', 'kTxnVblTime = 0x178u, kTxnVblNext = 0x188u;', 'kTxnVblTime = 0x178u, kTxnVblNext = 0x190u;')
plant(244, PURE, 'V1: a period that converts to 0 ticks is planned (P = 0 written)', 'if (!ns_to_abs(delayNs, numer, denom, &dAbs) || !ns_to_abs(periodNs, numer, denom, &pAbs) || pAbs == 0ull) return p;', 'if (!ns_to_abs(delayNs, numer, denom, &dAbs) || !ns_to_abs(periodNs, numer, denom, &pAbs)) return p;')
plant(245, FLOW, 'V1: the refused plan is written anyway', '    if (!p.ok) return kVblBadMath;\n', '')
plant(246, FLOW, 'V1: +0x188 gets the vblank time itself (no period)', 'e.wr64(txn + kTxnVblNext, p.next)', 'e.wr64(txn + kTxnVblNext, p.t)')
plant(247, FLOW, 'V1: the stamp is taken BEFORE the copy', 'const uint32_t r = perform_inner(e, txn, &bytes);\n    const uint32_t v = vbl_stamp_flow(e, txn, r);', 'const uint32_t v = vbl_stamp_flow(e, txn, kPfCopied);\n    const uint32_t r = perform_inner(e, txn, &bytes);')
plant(248, FLOW, 'V1: no identity check on the transaction', '    if (!e.class_derives(txn, kTxnClass)) return kVblNotTxn;\n', '')
plant(249, FLOW, 'V2: the switch is ignored', '    if (!e.vbl_on()) return kVblOff;\n', '')
plant(250, FLOW, 'V1: the HUNG latch does not stop the register read', '    if (e.hung()) return kVblHung;                                           // the HUNG latch: no register is read\n', '')
plant(251, FLOW, 'V1: a disarmed pipe is stamped', '    if (performReason == kPfDisarmed) return kVblDisarmed;', '    (void)performReason;')
plant(252, FLOW, 'V1: +0x190 is also written', 'e.note_vbl(kVblWrote, p, s.periodNs, s.delayNs);\n    return kVblWrote;', '(void)e.wr64(txn + 0x190u, p.next);\n    e.note_vbl(kVblWrote, p, s.periodNs, s.delayNs);\n    return kVblWrote;')
plant(253, PURE, 'V1: the next-vblank delay forgets the wrap', 'total - (cur - start);', '(cur - start);')
plant(254, PURE, 'V1: the unit conversion is inverted (ns * numer / denom)', 'const uint64_t hi = q * denom, lo = r * denom / numer;', 'const uint64_t hi = q * numer, lo = r * numer / denom;')
plant(255, PURE, 'V2: verb 89 is not admitted', 'constexpr uint32_t kLastAction = 90u;', 'constexpr uint32_t kLastAction = 88u;')
plant(256, PURE, 'V2: pipevbl takes any argument', '(action == kActVbl && arg <= 1ull)', '(action == kActVbl && arg <= 2ull)')
plant(257, PURE, 'V2: pipe stat page 4 is not admitted', '(action == kActStat && arg <= 4ull)', '(action == kActStat && arg <= 3ull)')
plant(258, GLUE, 'V2: the switch defaults OFF', 'bool vbl_on() { return __atomic_load_n(&gD.vblOff, __ATOMIC_ACQUIRE) == 0u; }', 'bool vbl_on() { return __atomic_load_n(&gD.vblOff, __ATOMIC_ACQUIRE) != 0u; }')
plant(259, GLUE, 'V2: pipevbl 1 turns it OFF (inverted store)', '__atomic_store_n(&gD.vblOff, arg ? 0u : 1u, __ATOMIC_RELEASE);', '__atomic_store_n(&gD.vblOff, arg ? 1u : 0u, __ATOMIC_RELEASE);')
plant(260, GLUE, 'V1: the timebase words are swapped', 's->numer = 1000000000u; s->denom = (uint32_t)perSec;', 's->numer = (uint32_t)perSec; s->denom = 1000000000u;')
plant(261, GLUE, 'V2: stat page 4 is not served', '} else if (arg == 4ull) {', '} else if (arg == 9ull) {')
plant(262, DCN, 'V1: vblSample reads while a mode trial reprograms the raster', 'if (modeTrialBusy()) return false;                                  // the raster is being reprogrammed: nothing coherent to read', '')
plant(263, DCN, 'V1: vblSample reads through the bound (writing) device', 'dcn41_otg_get_scanoutpos(&gLr.d, gVbl.otg', 'dcn41_otg_get_scanoutpos(&gDcn.d, gVbl.otg')
plant(264, CLI, 'V2: the CLI has no pipevbl', 'in = 89;', 'in = 90;')
plant(265, CLI, 'V2: the CLI has no page 4', 'page 4 - kernel out[3..12] arrive as out[6..15] here', 'page X - kernel out[3..12] arrive as out[6..15] here')
plant(266, PURE, 'V1: the period range check is gone (a wrong clock is written)', 'return (p >= kVblPeriodMinNs && p <= kVblPeriodMaxNs) ? p : 0ull;', 'return p;')
plant(267, PURE, 'V1: an incoherent position is accepted', 'v >= vTot || h >= hTot || vBlankStart >= vTot ||', 'false ||')
plant(268, GLUE, 'V1: the identity check matches the exact class only', 'for (uint32_t depth = 0; mc && depth < 12u; ++depth, mc = mc->getSuperClass()) {', 'for (uint32_t depth = 0; mc && depth < 1u; ++depth, mc = mc->getSuperClass()) {')

# ---- 0.0.619 R1: the operator restart window (`pipereload`) -------------------------------------------------------------------------------------------------------------------------------
plant(270, FLOW, 'R1: K1 never tolerates the close (the window is ignored)', '    if (e.armed() && reload_tolerate_close(e)) return false;', '')
plant(271, FLOW, 'R1: K3 counts slot-267 calls inside the window', 'if (e.armed() && !reload_on_init_fb(e) && guard_on_init_fb(', 'if (e.armed() && guard_on_init_fb(')
plant(272, PURE, 'R1: the window is honoured while HUNG', 'constexpr bool reload_honoured(bool live, bool hung) { return live && !hung; }', 'constexpr bool reload_honoured(bool live, bool hung) { (void)hung; return live; }')
plant(273, PURE, 'R1: the window lasts one nanosecond too long (<=)', 'nowNs - openNs < kReloadWindowNs; }', 'nowNs - openNs <= kReloadWindowNs; }')
plant(274, PURE, 'R1: a closed window (open = 0) counts as live', 'return open != 0u && nowNs >= openNs && nowNs - openNs < kReloadWindowNs; }', 'return nowNs >= openNs && nowNs - openNs < kReloadWindowNs; }')
plant(275, PURE, 'R1: the window is 30 s', 'constexpr uint64_t kReloadWindowNs = 15ull * 1000000000ull;', 'constexpr uint64_t kReloadWindowNs = 30ull * 1000000000ull;')
plant(276, FLOW, 'R1: the new client\'s slot 267 does not close the window (not one-shot)', 'if (__atomic_load_n(&w.closeSeen, __ATOMIC_ACQUIRE) != 0u) {\n        uint32_t exp = 1u;', 'if (false) {\n        uint32_t exp = 1u;')
plant(277, FLOW, 'R1: ANY slot 267 closes the window (the old client\'s too)', 'if (__atomic_load_n(&w.closeSeen, __ATOMIC_ACQUIRE) != 0u) {\n        uint32_t exp = 1u;', '{\n        uint32_t exp = 1u;')
plant(278, FLOW, 'R1: the expiry is not logged', '            e.note_reload(kRwExpired);\n', '')
plant(279, FLOW, 'R1: an expired window is not shut (it stays honoured as a zombie)', '        if (__atomic_compare_exchange_n(&w.open, &exp, 0u, false, __ATOMIC_ACQ_REL, __ATOMIC_ACQUIRE)) {\n            __atomic_store_n(&w.closeSeen, 0u, __ATOMIC_RELEASE);\n            __atomic_add_fetch(&w.expired', '        if (false) {\n            __atomic_store_n(&w.closeSeen, 0u, __ATOMIC_RELEASE);\n            __atomic_add_fetch(&w.expired')
plant(280, FLOW, 'R1: an auto-disarm leaves the window open', '    reload_shut(e.rw());                                                     // 0.0.619 (R1): a disarmed pipe has no restart to tolerate\n', '')
plant(281, FLOW, 'R1: `pipearm 0` leaves the window open', 'mdc_teardown(e); reload_shut(e.rw()); return kOk; }', 'mdc_teardown(e); return kOk; }')
plant(282, FLOW, 'R1: withdraw leaves the window open', '    reload_shut(e.rw());                                                   // 0.0.619 (R1)\n', '')
plant(283, FLOW, 'R1: a close on a disarmed pipe is "tolerated" (consumes the window)', 'if (e.armed() && reload_tolerate_close(e)) return false;', 'if (reload_tolerate_close(e)) return false;')
plant(284, FLOW, 'R1: a slot 267 while NOT armed closes the window', 'if (e.armed() && !reload_on_init_fb(e) && guard_on_init_fb(e.guard(), e.now_ns()))', 'if (!reload_on_init_fb(e) && e.armed() && guard_on_init_fb(e.guard(), e.now_ns()))')
plant(285, FLOW, 'R1: re-issuing the verb keeps a stale "close seen"', '    __atomic_store_n(&w.closeSeen, 0u, __ATOMIC_RELEASE);\n    __atomic_store_n(&w.openNs, e.now_ns(), __ATOMIC_RELEASE);', '    __atomic_store_n(&w.openNs, e.now_ns(), __ATOMIC_RELEASE);')
plant(286, FLOW, 'R1: K2 (HUNG) is held back by an open window', 'template <class E> bool hung_latched_flow(E &e) {                           // K2\n    if (!e.latch_on()) return false;', 'template <class E> bool hung_latched_flow(E &e) {                           // K2\n    if (!e.latch_on()) return false;\n    if (__atomic_load_n(&e.rw().open, __ATOMIC_ACQUIRE)) return false;')
plant(287, FLOW, 'R1: a tolerated close is not recorded (the new 267 can never close the window)', '    __atomic_store_n(&w.closeSeen, 1u, __ATOMIC_RELEASE);\n    __atomic_add_fetch(&w.tolerated', '    __atomic_add_fetch(&w.tolerated')
plant(288, PURE, 'R1: pipereload takes any argument', '(action == kActReload && arg <= 1ull)', '(action == kActReload && arg <= 2ull)')
plant(289, PURE, 'R1: n48disp_verb does not answer 90', '|| action == kActVbl || action == kActReload; }', '|| action == kActVbl; }')
plant(290, GLUE, 'R1: the verb opens the window on the READ argument (inverted)', 'if (arg == 0ull) n48disp::reload_open_flow(env);', 'if (arg == 1ull) n48disp::reload_open_flow(env);')
plant(291, GLUE, 'R1: the verb never opens the window', 'if (arg == 0ull) n48disp::reload_open_flow(env);', 'if (arg == 0ull) { }')
plant(292, BRG, 'R1: action 90 is not dispatched', 'action == 87 || action == 89 || action == 90) {', 'action == 87 || action == 89) {')
plant(293, CLI, 'R1: the CLI has no pipereload', 'else if (what && !strcmp(what, "pipereload")) in = 90;', 'else if (what && !strcmp(what, "pipereload")) in = 91;')
plant(294, CLI, 'R1: the CLI does not document the operator sequence', '//     killall -9 WindowServer            (within 15 s;', '//     (restart WindowServer)             (within 15 s;')
plant(295, CLI, 'R1: the CLI prints nothing for pipereload', 'if ((in >= 83 && in <= 87) || in == 89 || in == 90) {', 'if ((in >= 83 && in <= 87) || in == 89) {')
plant(296, GLUE, 'R1: the tolerated-close log line is missing', 'operator restart window: client close tolerated (the pipe stays armed)', 'operator restart window: close seen')
plant(297, FLOW, 'R1: the HUNG check is bypassed at the call site', 'return reload_honoured(true, e.hung());', 'return reload_honoured(true, false);')
plant(298, GLUE, 'R1: the latch gate is gone from the close entry point', 'void n48disp_on_ws_client_closed(bool adminClient) {\n    if (!n48disp_latched_on()) return;', 'void n48disp_on_ws_client_closed(bool adminClient) {')

shutil.rmtree(scr, ignore_errors=True)
print('native_disp_plant: %d plant(s), %d escaped' % (total, escaped))
sys.exit(1 if escaped else 0)
PY
