/* linuxshim: amd/include/ObjectID.h is NOT in the sparse clone.
 * PLACEHOLDER VALUES, NOT AMD'S: distinct numbers so command_table_helper2.c compiles and its translations stay
 * distinguishable. The DMUB harness only compares how a translated value is PACKED, so these numbers never become
 * evidence; the real ENCODER_OBJECT_ID_* values are not established on the host Mac (notes/DISPLAY-DESIGN.md). */
#ifndef DCN41_SHIM_OBJECTID_H
#define DCN41_SHIM_OBJECTID_H
#define ENCODER_OBJECT_ID_NONE 0xA0
#define ENCODER_OBJECT_ID_INTERNAL_LVDS 0xA1
#define ENCODER_OBJECT_ID_INTERNAL_TMDS1 0xA2
#define ENCODER_OBJECT_ID_INTERNAL_TMDS2 0xA3
#define ENCODER_OBJECT_ID_INTERNAL_DAC1 0xA4
#define ENCODER_OBJECT_ID_INTERNAL_DAC2 0xA5
#define ENCODER_OBJECT_ID_INTERNAL_LVTM1 0xA6
#define ENCODER_OBJECT_ID_HDMI_INTERNAL 0xA7
#define ENCODER_OBJECT_ID_TRAVIS 0xA8
#define ENCODER_OBJECT_ID_NUTMEG 0xA9
#define ENCODER_OBJECT_ID_INTERNAL_KLDSCP_TMDS1 0xAA
#define ENCODER_OBJECT_ID_INTERNAL_KLDSCP_DAC1 0xAB
#define ENCODER_OBJECT_ID_INTERNAL_KLDSCP_DAC2 0xAC
#define ENCODER_OBJECT_ID_MVPU_FPGA 0xAD
#define ENCODER_OBJECT_ID_INTERNAL_DDI 0xAE
#define ENCODER_OBJECT_ID_INTERNAL_UNIPHY 0xAF
#define ENCODER_OBJECT_ID_INTERNAL_KLDSCP_LVTMA 0xB0
#define ENCODER_OBJECT_ID_INTERNAL_UNIPHY1 0xB1
#define ENCODER_OBJECT_ID_INTERNAL_UNIPHY2 0xB2
#define ENCODER_OBJECT_ID_INTERNAL_UNIPHY3 0xB3
#define ENCODER_OBJECT_ID_INTERNAL_VCE 0xB4
#endif
