//
//  fw_table.h — plain lookup table over the embedded firmware blobs in
//  src/fw/*.c (generated by tools/embed-firmware.py). No allocation, no
//  STL, no exceptions/RTTI — kernel-safe, C++17 aggregate data only.
//
//  Implementation: src/amd/fw_table.cpp (see that file for why — the
//  Makefile globs src/fw/*.c and src/amd/*.cpp, but NOT src/fw/*.cpp, so
//  a same-directory fw_table.cpp would silently never be compiled).
//
#pragma once

#include <stdint.h>
#include <stddef.h>

namespace amdgpu {

// Stable index space for every firmware blob the gfx1201 (Navi 48)
// bring-up ladder can name. Not every id has embedded data on this card:
// GC_MES / GC_MES1 (legacy split MES packaging — superseded here by
// GC_UNI_MES) and GC_TOC (only loaded for psp_14_0_5, not psp_14_0_3)
// have a table entry with data=nullptr, size=0. Always check
// FwBlob::data before use. See PORTING.md and firmware/WHENCE.*.txt.
enum class FwId : uint32_t {
    PSP_SOS,
    PSP_TA,
    GC_IMU,
    GC_PFP,
    GC_ME,
    GC_MEC,
    GC_MES,
    GC_MES1,
    GC_UNI_MES,
    GC_RLC,
    GC_TOC,
    SMU,
    SDMA,
    Count
};

struct FwBlob {
    const uint8_t *data;  // nullptr if this id has no embedded blob
    size_t size;          // 0 if this id has no embedded blob
    const char *name;     // bare blob name, e.g. "gc_12_0_1_imu"
    FwId id;
};

// Returns the table entry for `id`, or nullptr if `id` is out of range
// (i.e. >= FwId::Count). Never returns nullptr for any in-range id —
// check ->data for blobs with no embedded bytes (see FwId comment above).
const FwBlob *fw_get(FwId id);

// Looks up by bare name (e.g. "smu_14_0_3"); returns nullptr if not found.
const FwBlob *fw_find_by_name(const char *name);

} // namespace amdgpu
