/* navi48_modetrial_tables.h - GENERATED by tools/native/gen_modetrial_tables.py from tools/dcn41/harness/goldens/goldens-{60,50,120}.json; do not edit
 * (regenerate, then --check). Kext 0.0.605, native S2d (the timed mode trial). Plain data: no kernel header, no code.
 *
 * kCap: every register a trial can write, ABSOLUTE BAR5 dwords (the DMU segment bases the write allowlist is generated for: 0x12 0xc0 0x34c0 0x9000 0x2403c00), in the order
 * they are written (Linux's order, group comments below); the restore runs the reverse. mask = the golden's written_mask: a write changes exactly those bits.
 * kGold60 = the 60 Hz golden (the census raster; timing, MSA and DTO equal the live 60 Hz hardware); kGold50 / kGold120 = the row's values, indexed like kCap.
 * kRow50Idx / kRow120Idx = the registers a row may write (indexes into kCap, ascending = write order). DLG/TTU of row 50 are NOT in it: the live 60 Hz block stays. */
#pragma once
#include <stdint.h>

namespace n48mt { namespace tab {

struct RegDef { uint32_t abs; uint32_t mask; const char *name; };
constexpr uint32_t kCapN = 56u;
constexpr RegDef kCap[kCapN] = {
    /* dccg401_set_dp_dto (dcn401_dccg.c): REG_WRITE PHASE, REG_WRITE MODULO, REG_UPDATE OTG_PIXEL_RATE_DIV.DPDTO0_INT; the DP_DTO_ENABLE toggle is not repeated (already 1) */
    { 0x00000141u, 0xffffffffu, "DP_DTO0_PHASE" },  /* [0] */
    { 0x00000142u, 0xffffffffu, "DP_DTO0_MODULO" },  /* [1] */
    { 0x0000012fu, 0x0000001eu, "OTG_PIXEL_RATE_DIV" },  /* [2] */
    /* optc1_program_timing (dcn10_optc.c): H_TOTAL, H_SYNC_A, H_BLANK_START_END, H_SYNC_A_CNTL, V_TOTAL, V_TOTAL_MIN/MAX (set_vtotal_min_max), V_SYNC_A, V_BLANK_START_END, V_SYNC_A_CNTL */
    { 0x00004feau, 0xffffffffu, "OTG0_OTG_H_TOTAL" },  /* [3] */
    { 0x00004fecu, 0x7fff7fffu, "OTG0_OTG_H_SYNC_A" },  /* [4] */
    { 0x00004febu, 0x7fff7fffu, "OTG0_OTG_H_BLANK_START_END" },  /* [5] */
    { 0x00004fedu, 0x00000001u, "OTG0_OTG_H_SYNC_A_CNTL" },  /* [6] */
    { 0x00004fefu, 0xffffffffu, "OTG0_OTG_V_TOTAL" },  /* [7] */
    { 0x00004ff0u, 0xffffffffu, "OTG0_OTG_V_TOTAL_MIN" },  /* [8] */
    { 0x00004ff1u, 0xffffffffu, "OTG0_OTG_V_TOTAL_MAX" },  /* [9] */
    { 0x00004ff9u, 0x7fff7fffu, "OTG0_OTG_V_SYNC_A" },  /* [10] */
    { 0x00004ff8u, 0x7fff7fffu, "OTG0_OTG_V_BLANK_START_END" },  /* [11] */
    { 0x00004ffau, 0x00000001u, "OTG0_OTG_V_SYNC_A_CNTL" },  /* [12] */
    /* optc401_program_global_sync (dcn401_optc.c): VSTARTUP, VUPDATE, VREADY, PSTATE_REGISTER; then optc1_set_vtg_params (VTG0_CONTROL: FP2 + VCOUNT_INIT only; VTG0_ENABLE bit 31 is NOT in the write mask) and OTG_H_TIMING_CNTL (last in optc1_program_timing) */
    { 0x00005045u, 0xffffffffu, "OTG0_OTG_VSTARTUP_PARAM" },  /* [13] */
    { 0x00005046u, 0xffffffffu, "OTG0_OTG_VUPDATE_PARAM" },  /* [14] */
    { 0x00005047u, 0xffffffffu, "OTG0_OTG_VREADY_PARAM" },  /* [15] */
    { 0x0000505fu, 0x00007fffu, "OTG0_OTG_PSTATE_REGISTER" },  /* [16] */
    { 0x000039f0u, 0x7fff7fffu, "VTG0_CONTROL" },  /* [17] */
    { 0x00004feeu, 0x00000003u, "OTG0_OTG_H_TIMING_CNTL" },  /* [18] */
    /* dcn401_stream_encoder_dp_set_stream_attribute (transcribed in golden_regs.c): DP1_DP_MSA_TIMING_PARAM1..4 */
    { 0x00005746u, 0xffffffffu, "DP1_DP_MSA_TIMING_PARAM1" },  /* [19] */
    { 0x00005747u, 0xffffffffu, "DP1_DP_MSA_TIMING_PARAM2" },  /* [20] */
    { 0x00005748u, 0xffffffffu, "DP1_DP_MSA_TIMING_PARAM3" },  /* [21] */
    { 0x00005749u, 0xffffffffu, "DP1_DP_MSA_TIMING_PARAM4" },  /* [22] */
    /* hubp401_setup -> hubp401_program_deadline (dcn401_hubp.c): DST_DIMENSIONS, BLANK_OFFSET, DST_AFTER_SCALER, PER_LINE_DELIVERY, REF_FREQ_TO_PIX_FREQ, NOM_PARAMETERS, the TTU set */
    { 0x00003afbu, 0xffffffffu, "HUBPREQ0_BLANK_OFFSET_0" },  /* [23] */
    { 0x00003afcu, 0xffffffffu, "HUBPREQ0_BLANK_OFFSET_1" },  /* [24] */
    { 0x00003afdu, 0xffffffffu, "HUBPREQ0_DST_DIMENSIONS" },  /* [25] */
    { 0x00003afeu, 0xffffffffu, "HUBPREQ0_DST_AFTER_SCALER" },  /* [26] */
    { 0x00003b11u, 0xffffffffu, "HUBPREQ0_PER_LINE_DELIVERY_PRE" },  /* [27] */
    { 0x00003b12u, 0xffffffffu, "HUBPREQ0_PER_LINE_DELIVERY" },  /* [28] */
    { 0x00003b14u, 0xffffffffu, "HUBPREQ0_REF_FREQ_TO_PIX_FREQ" },  /* [29] */
    { 0x00003b09u, 0xffffffffu, "HUBPREQ0_NOM_PARAMETERS_0" },  /* [30] */
    { 0x00003b0au, 0xffffffffu, "HUBPREQ0_NOM_PARAMETERS_1" },  /* [31] */
    { 0x00003b0bu, 0xffffffffu, "HUBPREQ0_NOM_PARAMETERS_2" },  /* [32] */
    { 0x00003b0cu, 0xffffffffu, "HUBPREQ0_NOM_PARAMETERS_3" },  /* [33] */
    { 0x00003b0du, 0xffffffffu, "HUBPREQ0_NOM_PARAMETERS_4" },  /* [34] */
    { 0x00003b0eu, 0xffffffffu, "HUBPREQ0_NOM_PARAMETERS_5" },  /* [35] */
    { 0x00003b0fu, 0xffffffffu, "HUBPREQ0_NOM_PARAMETERS_6" },  /* [36] */
    { 0x00003b10u, 0xffffffffu, "HUBPREQ0_NOM_PARAMETERS_7" },  /* [37] */
    { 0x00003ae1u, 0xffffffffu, "HUBPREQ0_DCN_TTU_QOS_WM" },  /* [38] */
    { 0x00003ae2u, 0xffffffffu, "HUBPREQ0_DCN_GLOBAL_TTU_CNTL" },  /* [39] */
    { 0x00003ae3u, 0xffffffffu, "HUBPREQ0_DCN_SURF0_TTU_CNTL0" },  /* [40] */
    { 0x00003ae4u, 0xffffffffu, "HUBPREQ0_DCN_SURF0_TTU_CNTL1" },  /* [41] */
    { 0x00003ae5u, 0xffffffffu, "HUBPREQ0_DCN_SURF1_TTU_CNTL0" },  /* [42] */
    { 0x00003ae6u, 0xffffffffu, "HUBPREQ0_DCN_SURF1_TTU_CNTL1" },  /* [43] */
    { 0x00003ae7u, 0xffffffffu, "HUBPREQ0_DCN_CUR0_TTU_CNTL0" },  /* [44] */
    { 0x00003ae8u, 0xffffffffu, "HUBPREQ0_DCN_CUR0_TTU_CNTL1" },  /* [45] */
    /* hubp401_setup_interdependent (dcn401_hubp.c): PREFETCH_SETTINGS(_C), VBLANK_PARAMETERS_0..4, FLIP_PARAMETERS_0..2 */
    { 0x00003affu, 0xffffffffu, "HUBPREQ0_PREFETCH_SETTINGS" },  /* [46] */
    { 0x00003b00u, 0xffffffffu, "HUBPREQ0_PREFETCH_SETTINGS_C" },  /* [47] */
    { 0x00003b01u, 0xffffffffu, "HUBPREQ0_VBLANK_PARAMETERS_0" },  /* [48] */
    { 0x00003b02u, 0xffffffffu, "HUBPREQ0_VBLANK_PARAMETERS_1" },  /* [49] */
    { 0x00003b03u, 0xffffffffu, "HUBPREQ0_VBLANK_PARAMETERS_2" },  /* [50] */
    { 0x00003b04u, 0xffffffffu, "HUBPREQ0_VBLANK_PARAMETERS_3" },  /* [51] */
    { 0x00003b05u, 0xffffffffu, "HUBPREQ0_VBLANK_PARAMETERS_4" },  /* [52] */
    { 0x00003b06u, 0xffffffffu, "HUBPREQ0_FLIP_PARAMETERS_0" },  /* [53] */
    { 0x00003b07u, 0xffffffffu, "HUBPREQ0_FLIP_PARAMETERS_1" },  /* [54] */
    { 0x00003b08u, 0xffffffffu, "HUBPREQ0_FLIP_PARAMETERS_2" },  /* [55] */
};

constexpr uint32_t kGold60[kCapN] = {
    0x0e64ff60u, 0x2aea5400u, 0x00000000u, 0x00000a9fu, 0x00200000u, 0x00700a70u,
    0x00000000u, 0x000005c8u, 0x000005c8u, 0x000005c8u, 0x00050000u, 0x002605c6u,
    0x00000000u, 0x00000028u, 0x00f702a8u, 0x00000148u, 0x00000026u, 0x05c60001u,
    0x00000000u, 0x0aa005c9u, 0x00700026u, 0x00200005u, 0x0a0005a0u, 0x00260017u,
    0x0000171cu, 0x00023325u, 0x0000002du, 0x00000212u, 0x00000212u, 0x0001a804u,
    0x00000200u, 0x00002eedu, 0x00000000u, 0x00000000u, 0x00000080u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x08cc0000u, 0xe0000eacu, 0x08003500u, 0x00003500u,
    0x08000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x35080000u, 0x00080000u,
    0x00000c15u, 0x00000119u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000510u,
    0x00000075u, 0x00000000u,
};
constexpr uint32_t kGold50[kCapN] = {
    0x0bfb0440u, 0x2aea5400u, 0x00000000u, 0x00000a9fu, 0x00200000u, 0x00700a70u,
    0x00000000u, 0x000005c8u, 0x000005c8u, 0x000005c8u, 0x00050000u, 0x002605c6u,
    0x00000000u, 0x00000028u, 0x00f702a8u, 0x00000148u, 0x0000001fu, 0x05c60001u,
    0x00000000u, 0x0aa005c9u, 0x00700026u, 0x00200005u, 0x0a0005a0u, 0x0026001bu,
    0x0000171cu, 0x0002a49du, 0x00000036u, 0x0000027cu, 0x0000027cu, 0x0001fd73u,
    0x00000200u, 0x00003862u, 0x00000000u, 0x00000000u, 0x00000080u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x0a920000u, 0xe0000ebau, 0x08003faeu, 0x00003faeu,
    0x08000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x32080000u, 0x00080000u,
    0x00000c12u, 0x00000152u, 0x00000000u, 0x00000000u, 0x00000000u, 0x0000040eu,
    0x00000070u, 0x00000000u,
};
constexpr uint32_t kGold120[kCapN] = {
    0x1dab0ff0u, 0x2aea5400u, 0x00000000u, 0x00000a9fu, 0x00200000u, 0x00700a70u,
    0x00000000u, 0x000005f4u, 0x000005f4u, 0x000005f4u, 0x00050000u, 0x005205f2u,
    0x00000000u, 0x00000054u, 0x00f602a8u, 0x00000148u, 0x0000004du, 0x05f20001u,
    0x00000000u, 0x0aa005f5u, 0x00700052u, 0x00200005u, 0x0a0005a0u, 0x0052000bu,
    0x000017ccu, 0x0001113au, 0x00000015u, 0x00000101u, 0x00000101u, 0x0000cdb9u,
    0x00000200u, 0x000016c4u, 0x00000000u, 0x00000000u, 0x00000080u, 0x00000000u,
    0x00000000u, 0x00000000u, 0x04440000u, 0xe0000e88u, 0x080019b7u, 0x000019b7u,
    0x08000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x4b080000u, 0x00080000u,
    0x00000c2bu, 0x00000088u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000a21u,
    0x00000071u, 0x00000000u,
};

constexpr uint32_t kRow50N = 3u;
constexpr uint16_t kRow50Idx[kRow50N] = { 0, 1, 2 };
constexpr uint32_t kRow120N = 55u;
constexpr uint16_t kRow120Idx[kRow120N] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55 };

/* row 60: DML required DISPCLK 246575 / DPPCLK 243243 kHz (dml_required_clocks_khz), DTO 241500000 / 720000000 (+ 0 * modulo), raster 2720x1481 */
constexpr uint32_t kRow60PixHz = 241500000u, kRow60Modulo = 720000000u, kRow60Phase = 241500000u, kRow60DtoInt = 0u, kRow60HTotal = 2720u, kRow60VTotal = 1481u, kRow60NeedDispKhz = 246575u, kRow60NeedDppKhz = 243243u;
/* row 50: DML required DISPCLK 204545 / DPPCLK 202247 kHz (dml_required_clocks_khz), DTO 201000000 / 720000000 (+ 0 * modulo), raster 2720x1481 */
constexpr uint32_t kRow50PixHz = 201000000u, kRow50Modulo = 720000000u, kRow50Phase = 201000000u, kRow50DtoInt = 0u, kRow50HTotal = 2720u, kRow50VTotal = 1481u, kRow50NeedDispKhz = 204545u, kRow50NeedDppKhz = 202247u;
/* row 120: DML required DISPCLK 514285 / DPPCLK 500000 kHz (dml_required_clocks_khz), DTO 497750000 / 720000000 (+ 0 * modulo), raster 2720x1525 */
constexpr uint32_t kRow120PixHz = 497750000u, kRow120Modulo = 720000000u, kRow120Phase = 497750000u, kRow120DtoInt = 0u, kRow120HTotal = 2720u, kRow120VTotal = 1525u, kRow120NeedDispKhz = 514285u, kRow120NeedDppKhz = 500000u;

} }  /* namespace n48mt::tab */
