// VERBATIM from lemonade-sdk/mac-amdgpu (MIT) dext/amdgpu/amdgpu_field_defs.h @ 3bdeed2 — platform-independent; keep in sync, do not fork.
//
//  amdgpu_field_defs.h — Vendored register field SHIFT/MASK pairs.
//
//  Hand-curated subset of upstream AMD sh_mask.h headers, copied
//  in for the fields actually written by our gart_enable port.
//  Sources:
//      drivers/gpu/drm/amd/include/asic_reg/mmhub/mmhub_4_1_0_sh_mask.h
//      drivers/gpu/drm/amd/include/asic_reg/gc/gc_12_0_0_sh_mask.h
//
//  Convention from upstream: every (reg, field) has a
//      <reg>__<field>__SHIFT  — bit offset
//      <reg>__<field>_MASK    — bit mask (already pre-shifted)
//  pair. For single-bit fields the MASK is `1 << SHIFT`. The mask
//  literal uses an `L` suffix in Linux but we'll use plain hex.
//
//  Add to this file as more registers get ported — keep it tight,
//  don't copy the entire 200 KB sh_mask.h headers.
//

#pragma once

// ---------------- MMHUB v4_1_0 ----------------

// MMMC_VM_MX_L1_TLB_CNTL
#define MMMC_VM_MX_L1_TLB_CNTL__ENABLE_L1_TLB__SHIFT                       0x0
#define MMMC_VM_MX_L1_TLB_CNTL__ENABLE_L1_TLB_MASK                         0x00000001
#define MMMC_VM_MX_L1_TLB_CNTL__SYSTEM_ACCESS_MODE__SHIFT                  0x3
#define MMMC_VM_MX_L1_TLB_CNTL__SYSTEM_ACCESS_MODE_MASK                    0x00000018
#define MMMC_VM_MX_L1_TLB_CNTL__SYSTEM_APERTURE_UNMAPPED_ACCESS__SHIFT     0x5
#define MMMC_VM_MX_L1_TLB_CNTL__SYSTEM_APERTURE_UNMAPPED_ACCESS_MASK       0x00000020
#define MMMC_VM_MX_L1_TLB_CNTL__ENABLE_ADVANCED_DRIVER_MODEL__SHIFT        0x6
#define MMMC_VM_MX_L1_TLB_CNTL__ENABLE_ADVANCED_DRIVER_MODEL_MASK          0x00000040
#define MMMC_VM_MX_L1_TLB_CNTL__ECO_BITS__SHIFT                            0x7
#define MMMC_VM_MX_L1_TLB_CNTL__ECO_BITS_MASK                              0x00000780
#define MMMC_VM_MX_L1_TLB_CNTL__MTYPE__SHIFT                               0xb
#define MMMC_VM_MX_L1_TLB_CNTL__MTYPE_MASK                                 0x00001800

// MTYPE encoding (from atombios/mttypes): 0=NC (cached), 2=UC (uncached)
#define MMHUB_MTYPE_UC                                                     0x2

// MMVM_L2_CNTL
#define MMVM_L2_CNTL__ENABLE_L2_CACHE__SHIFT                                    0x0
#define MMVM_L2_CNTL__ENABLE_L2_CACHE_MASK                                      0x00000001
#define MMVM_L2_CNTL__ENABLE_L2_FRAGMENT_PROCESSING__SHIFT                      0x1
#define MMVM_L2_CNTL__ENABLE_L2_FRAGMENT_PROCESSING_MASK                        0x00000002
#define MMVM_L2_CNTL__L2_PDE0_CACHE_TAG_GENERATION_MODE__SHIFT                  0x8
#define MMVM_L2_CNTL__L2_PDE0_CACHE_TAG_GENERATION_MODE_MASK                    0x00000100
#define MMVM_L2_CNTL__ENABLE_DEFAULT_PAGE_OUT_TO_SYSTEM_MEMORY__SHIFT           0xb
#define MMVM_L2_CNTL__ENABLE_DEFAULT_PAGE_OUT_TO_SYSTEM_MEMORY_MASK             0x00000800
#define MMVM_L2_CNTL__PDE_FAULT_CLASSIFICATION__SHIFT                           0x12
#define MMVM_L2_CNTL__PDE_FAULT_CLASSIFICATION_MASK                             0x00040000
#define MMVM_L2_CNTL__CONTEXT1_IDENTITY_ACCESS_MODE__SHIFT                      0x13
#define MMVM_L2_CNTL__CONTEXT1_IDENTITY_ACCESS_MODE_MASK                        0x00180000
#define MMVM_L2_CNTL__IDENTITY_MODE_FRAGMENT_SIZE__SHIFT                        0x15
#define MMVM_L2_CNTL__IDENTITY_MODE_FRAGMENT_SIZE_MASK                          0x03E00000

// MMVM_L2_CNTL2
#define MMVM_L2_CNTL2__INVALIDATE_ALL_L1_TLBS__SHIFT                            0x0
#define MMVM_L2_CNTL2__INVALIDATE_ALL_L1_TLBS_MASK                              0x00000001
#define MMVM_L2_CNTL2__INVALIDATE_L2_CACHE__SHIFT                               0x1
#define MMVM_L2_CNTL2__INVALIDATE_L2_CACHE_MASK                                 0x00000002

// MMVM_L2_CNTL3
#define MMVM_L2_CNTL3__BANK_SELECT__SHIFT                                       0x0
#define MMVM_L2_CNTL3__BANK_SELECT_MASK                                         0x0000003F
#define MMVM_L2_CNTL3__L2_CACHE_BIGK_FRAGMENT_SIZE__SHIFT                       0xf
#define MMVM_L2_CNTL3__L2_CACHE_BIGK_FRAGMENT_SIZE_MASK                         0x000F8000

// MMVM_L2_CNTL4 — shifts from upstream mmhub_4_1_0_sh_mask.h lines 4676-4686.
// Audit #4 F12 fix: these were 0x1 / 0x2 (wrong IP gen); correct is 0x6 / 0x7.
#define MMVM_L2_CNTL4__VMC_TAP_PDE_REQUEST_PHYSICAL__SHIFT                      0x6
#define MMVM_L2_CNTL4__VMC_TAP_PDE_REQUEST_PHYSICAL_MASK                        0x00000040
#define MMVM_L2_CNTL4__VMC_TAP_PTE_REQUEST_PHYSICAL__SHIFT                      0x7
#define MMVM_L2_CNTL4__VMC_TAP_PTE_REQUEST_PHYSICAL_MASK                        0x00000080

// MMVM_L2_CNTL5
#define MMVM_L2_CNTL5__L2_CACHE_SMALLK_FRAGMENT_SIZE__SHIFT                     0x0
#define MMVM_L2_CNTL5__L2_CACHE_SMALLK_FRAGMENT_SIZE_MASK                       0x0000003F

// MMVM_CONTEXT0_CNTL (and CONTEXT1 has identical layout)
#define MMVM_CONTEXT0_CNTL__ENABLE_CONTEXT__SHIFT                               0x0
#define MMVM_CONTEXT0_CNTL__ENABLE_CONTEXT_MASK                                 0x00000001
#define MMVM_CONTEXT0_CNTL__PAGE_TABLE_DEPTH__SHIFT                             0x1
#define MMVM_CONTEXT0_CNTL__PAGE_TABLE_DEPTH_MASK                               0x00000006
#define MMVM_CONTEXT0_CNTL__PAGE_TABLE_BLOCK_SIZE__SHIFT                        0x4
#define MMVM_CONTEXT0_CNTL__PAGE_TABLE_BLOCK_SIZE_MASK                          0x000000F0
#define MMVM_CONTEXT0_CNTL__RETRY_PERMISSION_OR_INVALID_PAGE_FAULT__SHIFT       0x8
#define MMVM_CONTEXT0_CNTL__RETRY_PERMISSION_OR_INVALID_PAGE_FAULT_MASK         0x00000100
#define MMVM_CONTEXT0_CNTL__RANGE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT        0xb
#define MMVM_CONTEXT0_CNTL__RANGE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK          0x00000800
#define MMVM_CONTEXT0_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT   0xd
#define MMVM_CONTEXT0_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK     0x00002000
#define MMVM_CONTEXT0_CNTL__PDE0_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT         0xf
#define MMVM_CONTEXT0_CNTL__PDE0_PROTECTION_FAULT_ENABLE_DEFAULT_MASK           0x00008000
#define MMVM_CONTEXT0_CNTL__VALID_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT        0x11
#define MMVM_CONTEXT0_CNTL__VALID_PROTECTION_FAULT_ENABLE_DEFAULT_MASK          0x00020000
#define MMVM_CONTEXT0_CNTL__READ_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT         0x13
#define MMVM_CONTEXT0_CNTL__READ_PROTECTION_FAULT_ENABLE_DEFAULT_MASK           0x00080000
#define MMVM_CONTEXT0_CNTL__WRITE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT        0x15
#define MMVM_CONTEXT0_CNTL__WRITE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK          0x00200000
#define MMVM_CONTEXT0_CNTL__EXECUTE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT      0x17
#define MMVM_CONTEXT0_CNTL__EXECUTE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK        0x00800000

// CONTEXT1 fields are identical to CONTEXT0 except for the register name.
// We just alias them here to keep REG_SET_FIELD calls clean.
#define MMVM_CONTEXT1_CNTL__ENABLE_CONTEXT__SHIFT                               MMVM_CONTEXT0_CNTL__ENABLE_CONTEXT__SHIFT
#define MMVM_CONTEXT1_CNTL__ENABLE_CONTEXT_MASK                                 MMVM_CONTEXT0_CNTL__ENABLE_CONTEXT_MASK
#define MMVM_CONTEXT1_CNTL__PAGE_TABLE_DEPTH__SHIFT                             MMVM_CONTEXT0_CNTL__PAGE_TABLE_DEPTH__SHIFT
#define MMVM_CONTEXT1_CNTL__PAGE_TABLE_DEPTH_MASK                               MMVM_CONTEXT0_CNTL__PAGE_TABLE_DEPTH_MASK
#define MMVM_CONTEXT1_CNTL__PAGE_TABLE_BLOCK_SIZE__SHIFT                        MMVM_CONTEXT0_CNTL__PAGE_TABLE_BLOCK_SIZE__SHIFT
#define MMVM_CONTEXT1_CNTL__PAGE_TABLE_BLOCK_SIZE_MASK                          MMVM_CONTEXT0_CNTL__PAGE_TABLE_BLOCK_SIZE_MASK
#define MMVM_CONTEXT1_CNTL__RETRY_PERMISSION_OR_INVALID_PAGE_FAULT__SHIFT       MMVM_CONTEXT0_CNTL__RETRY_PERMISSION_OR_INVALID_PAGE_FAULT__SHIFT
#define MMVM_CONTEXT1_CNTL__RETRY_PERMISSION_OR_INVALID_PAGE_FAULT_MASK         MMVM_CONTEXT0_CNTL__RETRY_PERMISSION_OR_INVALID_PAGE_FAULT_MASK
#define MMVM_CONTEXT1_CNTL__RANGE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT        MMVM_CONTEXT0_CNTL__RANGE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define MMVM_CONTEXT1_CNTL__RANGE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK          MMVM_CONTEXT0_CNTL__RANGE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define MMVM_CONTEXT1_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT   MMVM_CONTEXT0_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define MMVM_CONTEXT1_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK     MMVM_CONTEXT0_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define MMVM_CONTEXT1_CNTL__PDE0_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT         MMVM_CONTEXT0_CNTL__PDE0_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define MMVM_CONTEXT1_CNTL__PDE0_PROTECTION_FAULT_ENABLE_DEFAULT_MASK           MMVM_CONTEXT0_CNTL__PDE0_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define MMVM_CONTEXT1_CNTL__VALID_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT        MMVM_CONTEXT0_CNTL__VALID_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define MMVM_CONTEXT1_CNTL__VALID_PROTECTION_FAULT_ENABLE_DEFAULT_MASK          MMVM_CONTEXT0_CNTL__VALID_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define MMVM_CONTEXT1_CNTL__READ_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT         MMVM_CONTEXT0_CNTL__READ_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define MMVM_CONTEXT1_CNTL__READ_PROTECTION_FAULT_ENABLE_DEFAULT_MASK           MMVM_CONTEXT0_CNTL__READ_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define MMVM_CONTEXT1_CNTL__WRITE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT        MMVM_CONTEXT0_CNTL__WRITE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define MMVM_CONTEXT1_CNTL__WRITE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK          MMVM_CONTEXT0_CNTL__WRITE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define MMVM_CONTEXT1_CNTL__EXECUTE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT      MMVM_CONTEXT0_CNTL__EXECUTE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define MMVM_CONTEXT1_CNTL__EXECUTE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK        MMVM_CONTEXT0_CNTL__EXECUTE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK

// MMVM_L2_PROTECTION_FAULT_CNTL — full set from mmhub_4_1_0_sh_mask.h
// lines 4567-4581. Used by set_fault_enable_default (mmhub_v4_1_0.c:415).
#define MMVM_L2_PROTECTION_FAULT_CNTL__RANGE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT        0x2
#define MMVM_L2_PROTECTION_FAULT_CNTL__RANGE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK          0x00000004
#define MMVM_L2_PROTECTION_FAULT_CNTL__PDE0_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT         0x3
#define MMVM_L2_PROTECTION_FAULT_CNTL__PDE0_PROTECTION_FAULT_ENABLE_DEFAULT_MASK           0x00000008
#define MMVM_L2_PROTECTION_FAULT_CNTL__PDE1_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT         0x4
#define MMVM_L2_PROTECTION_FAULT_CNTL__PDE1_PROTECTION_FAULT_ENABLE_DEFAULT_MASK           0x00000010
#define MMVM_L2_PROTECTION_FAULT_CNTL__PDE2_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT         0x5
#define MMVM_L2_PROTECTION_FAULT_CNTL__PDE2_PROTECTION_FAULT_ENABLE_DEFAULT_MASK           0x00000020
#define MMVM_L2_PROTECTION_FAULT_CNTL__TRANSLATE_FURTHER_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT  0x6
#define MMVM_L2_PROTECTION_FAULT_CNTL__TRANSLATE_FURTHER_PROTECTION_FAULT_ENABLE_DEFAULT_MASK    0x00000040
#define MMVM_L2_PROTECTION_FAULT_CNTL__NACK_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT         0x7
#define MMVM_L2_PROTECTION_FAULT_CNTL__NACK_PROTECTION_FAULT_ENABLE_DEFAULT_MASK           0x00000080
#define MMVM_L2_PROTECTION_FAULT_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT   0x8
#define MMVM_L2_PROTECTION_FAULT_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK     0x00000100
#define MMVM_L2_PROTECTION_FAULT_CNTL__VALID_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT        0x9
#define MMVM_L2_PROTECTION_FAULT_CNTL__VALID_PROTECTION_FAULT_ENABLE_DEFAULT_MASK          0x00000200
#define MMVM_L2_PROTECTION_FAULT_CNTL__READ_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT         0xa
#define MMVM_L2_PROTECTION_FAULT_CNTL__READ_PROTECTION_FAULT_ENABLE_DEFAULT_MASK           0x00000400
#define MMVM_L2_PROTECTION_FAULT_CNTL__WRITE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT        0xb
#define MMVM_L2_PROTECTION_FAULT_CNTL__WRITE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK          0x00000800
#define MMVM_L2_PROTECTION_FAULT_CNTL__EXECUTE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT      0xc
#define MMVM_L2_PROTECTION_FAULT_CNTL__EXECUTE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK        0x00001000
#define MMVM_L2_PROTECTION_FAULT_CNTL__CRASH_ON_NO_RETRY_FAULT__SHIFT                      0x1e
#define MMVM_L2_PROTECTION_FAULT_CNTL__CRASH_ON_NO_RETRY_FAULT_MASK                        0x40000000
#define MMVM_L2_PROTECTION_FAULT_CNTL__CRASH_ON_RETRY_FAULT__SHIFT                         0x1f
#define MMVM_L2_PROTECTION_FAULT_CNTL__CRASH_ON_RETRY_FAULT_MASK                           0x80000000

// MMVM_L2_PROTECTION_FAULT_CNTL2 (sh_mask line 4603) — programmed in
// init_system_aperture_regs to enable PTE-read retry for in-flight migrations.
#define MMVM_L2_PROTECTION_FAULT_CNTL2__ACTIVE_PAGE_MIGRATION_PTE_READ_RETRY__SHIFT        0x12
#define MMVM_L2_PROTECTION_FAULT_CNTL2__ACTIVE_PAGE_MIGRATION_PTE_READ_RETRY_MASK          0x00040000

// MMVM_INVALIDATE_ENG0_REQ — used to assemble the request word for
// flush_gpu_tlb. Shifts from mmhub_4_1_0_sh_mask.h lines 5889-5908.
// Audit #4 F24 fix: previously we hand-coded bit positions 0,4..12
// (off by 12-13). Correct shifts are 0 (PER_VMID, 16-bit), 16 (FLUSH_TYPE),
// 19-23 (L2/L1 invalidates), 24 (CLEAR_PFS).
#define MMVM_INVALIDATE_ENG0_REQ__PER_VMID_INVALIDATE_REQ__SHIFT           0x0
#define MMVM_INVALIDATE_ENG0_REQ__PER_VMID_INVALIDATE_REQ_MASK             0x0000FFFF
#define MMVM_INVALIDATE_ENG0_REQ__FLUSH_TYPE__SHIFT                        0x10
#define MMVM_INVALIDATE_ENG0_REQ__FLUSH_TYPE_MASK                          0x00070000
#define MMVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PTES__SHIFT                0x13
#define MMVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PTES_MASK                  0x00080000
#define MMVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PDE0__SHIFT                0x14
#define MMVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PDE0_MASK                  0x00100000
#define MMVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PDE1__SHIFT                0x15
#define MMVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PDE1_MASK                  0x00200000
#define MMVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PDE2__SHIFT                0x16
#define MMVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PDE2_MASK                  0x00400000
#define MMVM_INVALIDATE_ENG0_REQ__INVALIDATE_L1_PTES__SHIFT                0x17
#define MMVM_INVALIDATE_ENG0_REQ__INVALIDATE_L1_PTES_MASK                  0x00800000
#define MMVM_INVALIDATE_ENG0_REQ__CLEAR_PROTECTION_FAULT_STATUS_ADDR__SHIFT 0x18
#define MMVM_INVALIDATE_ENG0_REQ__CLEAR_PROTECTION_FAULT_STATUS_ADDR_MASK  0x01000000

// ---------------- GC (GFXHUB) v12_0 ----------------
// GFXHUB register field layouts mirror MMHUB exactly — same field
// names, same shifts, same masks. The register names differ
// (GCVM_* vs MMVM_*, GCMC_VM_* vs MMMC_VM_*). We alias each.
// This keeps gfxhub_v12_0_*() porting near-verbatim from upstream.

#define GCMC_VM_MX_L1_TLB_CNTL__ENABLE_L1_TLB__SHIFT                       MMMC_VM_MX_L1_TLB_CNTL__ENABLE_L1_TLB__SHIFT
#define GCMC_VM_MX_L1_TLB_CNTL__ENABLE_L1_TLB_MASK                         MMMC_VM_MX_L1_TLB_CNTL__ENABLE_L1_TLB_MASK
#define GCMC_VM_MX_L1_TLB_CNTL__SYSTEM_ACCESS_MODE__SHIFT                  MMMC_VM_MX_L1_TLB_CNTL__SYSTEM_ACCESS_MODE__SHIFT
#define GCMC_VM_MX_L1_TLB_CNTL__SYSTEM_ACCESS_MODE_MASK                    MMMC_VM_MX_L1_TLB_CNTL__SYSTEM_ACCESS_MODE_MASK
#define GCMC_VM_MX_L1_TLB_CNTL__SYSTEM_APERTURE_UNMAPPED_ACCESS__SHIFT     MMMC_VM_MX_L1_TLB_CNTL__SYSTEM_APERTURE_UNMAPPED_ACCESS__SHIFT
#define GCMC_VM_MX_L1_TLB_CNTL__SYSTEM_APERTURE_UNMAPPED_ACCESS_MASK       MMMC_VM_MX_L1_TLB_CNTL__SYSTEM_APERTURE_UNMAPPED_ACCESS_MASK
#define GCMC_VM_MX_L1_TLB_CNTL__ENABLE_ADVANCED_DRIVER_MODEL__SHIFT        MMMC_VM_MX_L1_TLB_CNTL__ENABLE_ADVANCED_DRIVER_MODEL__SHIFT
#define GCMC_VM_MX_L1_TLB_CNTL__ENABLE_ADVANCED_DRIVER_MODEL_MASK          MMMC_VM_MX_L1_TLB_CNTL__ENABLE_ADVANCED_DRIVER_MODEL_MASK
#define GCMC_VM_MX_L1_TLB_CNTL__ECO_BITS__SHIFT                            MMMC_VM_MX_L1_TLB_CNTL__ECO_BITS__SHIFT
#define GCMC_VM_MX_L1_TLB_CNTL__ECO_BITS_MASK                              MMMC_VM_MX_L1_TLB_CNTL__ECO_BITS_MASK
#define GCMC_VM_MX_L1_TLB_CNTL__MTYPE__SHIFT                               MMMC_VM_MX_L1_TLB_CNTL__MTYPE__SHIFT
#define GCMC_VM_MX_L1_TLB_CNTL__MTYPE_MASK                                 MMMC_VM_MX_L1_TLB_CNTL__MTYPE_MASK

#define GCVM_L2_CNTL__ENABLE_L2_CACHE__SHIFT                               MMVM_L2_CNTL__ENABLE_L2_CACHE__SHIFT
#define GCVM_L2_CNTL__ENABLE_L2_CACHE_MASK                                 MMVM_L2_CNTL__ENABLE_L2_CACHE_MASK
#define GCVM_L2_CNTL__ENABLE_L2_FRAGMENT_PROCESSING__SHIFT                 MMVM_L2_CNTL__ENABLE_L2_FRAGMENT_PROCESSING__SHIFT
#define GCVM_L2_CNTL__ENABLE_L2_FRAGMENT_PROCESSING_MASK                   MMVM_L2_CNTL__ENABLE_L2_FRAGMENT_PROCESSING_MASK
#define GCVM_L2_CNTL__L2_PDE0_CACHE_TAG_GENERATION_MODE__SHIFT             MMVM_L2_CNTL__L2_PDE0_CACHE_TAG_GENERATION_MODE__SHIFT
#define GCVM_L2_CNTL__L2_PDE0_CACHE_TAG_GENERATION_MODE_MASK               MMVM_L2_CNTL__L2_PDE0_CACHE_TAG_GENERATION_MODE_MASK
#define GCVM_L2_CNTL__ENABLE_DEFAULT_PAGE_OUT_TO_SYSTEM_MEMORY__SHIFT      MMVM_L2_CNTL__ENABLE_DEFAULT_PAGE_OUT_TO_SYSTEM_MEMORY__SHIFT
#define GCVM_L2_CNTL__ENABLE_DEFAULT_PAGE_OUT_TO_SYSTEM_MEMORY_MASK        MMVM_L2_CNTL__ENABLE_DEFAULT_PAGE_OUT_TO_SYSTEM_MEMORY_MASK
#define GCVM_L2_CNTL__PDE_FAULT_CLASSIFICATION__SHIFT                      MMVM_L2_CNTL__PDE_FAULT_CLASSIFICATION__SHIFT
#define GCVM_L2_CNTL__PDE_FAULT_CLASSIFICATION_MASK                        MMVM_L2_CNTL__PDE_FAULT_CLASSIFICATION_MASK
#define GCVM_L2_CNTL__CONTEXT1_IDENTITY_ACCESS_MODE__SHIFT                 MMVM_L2_CNTL__CONTEXT1_IDENTITY_ACCESS_MODE__SHIFT
#define GCVM_L2_CNTL__CONTEXT1_IDENTITY_ACCESS_MODE_MASK                   MMVM_L2_CNTL__CONTEXT1_IDENTITY_ACCESS_MODE_MASK
#define GCVM_L2_CNTL__IDENTITY_MODE_FRAGMENT_SIZE__SHIFT                   MMVM_L2_CNTL__IDENTITY_MODE_FRAGMENT_SIZE__SHIFT
#define GCVM_L2_CNTL__IDENTITY_MODE_FRAGMENT_SIZE_MASK                     MMVM_L2_CNTL__IDENTITY_MODE_FRAGMENT_SIZE_MASK

#define GCVM_L2_CNTL2__INVALIDATE_ALL_L1_TLBS__SHIFT                       MMVM_L2_CNTL2__INVALIDATE_ALL_L1_TLBS__SHIFT
#define GCVM_L2_CNTL2__INVALIDATE_ALL_L1_TLBS_MASK                         MMVM_L2_CNTL2__INVALIDATE_ALL_L1_TLBS_MASK
#define GCVM_L2_CNTL2__INVALIDATE_L2_CACHE__SHIFT                          MMVM_L2_CNTL2__INVALIDATE_L2_CACHE__SHIFT
#define GCVM_L2_CNTL2__INVALIDATE_L2_CACHE_MASK                            MMVM_L2_CNTL2__INVALIDATE_L2_CACHE_MASK

#define GCVM_L2_CNTL3__BANK_SELECT__SHIFT                                  MMVM_L2_CNTL3__BANK_SELECT__SHIFT
#define GCVM_L2_CNTL3__BANK_SELECT_MASK                                    MMVM_L2_CNTL3__BANK_SELECT_MASK
#define GCVM_L2_CNTL3__L2_CACHE_BIGK_FRAGMENT_SIZE__SHIFT                  MMVM_L2_CNTL3__L2_CACHE_BIGK_FRAGMENT_SIZE__SHIFT
#define GCVM_L2_CNTL3__L2_CACHE_BIGK_FRAGMENT_SIZE_MASK                    MMVM_L2_CNTL3__L2_CACHE_BIGK_FRAGMENT_SIZE_MASK

#define GCVM_L2_CNTL4__VMC_TAP_PDE_REQUEST_PHYSICAL__SHIFT                 MMVM_L2_CNTL4__VMC_TAP_PDE_REQUEST_PHYSICAL__SHIFT
#define GCVM_L2_CNTL4__VMC_TAP_PDE_REQUEST_PHYSICAL_MASK                   MMVM_L2_CNTL4__VMC_TAP_PDE_REQUEST_PHYSICAL_MASK
#define GCVM_L2_CNTL4__VMC_TAP_PTE_REQUEST_PHYSICAL__SHIFT                 MMVM_L2_CNTL4__VMC_TAP_PTE_REQUEST_PHYSICAL__SHIFT
#define GCVM_L2_CNTL4__VMC_TAP_PTE_REQUEST_PHYSICAL_MASK                   MMVM_L2_CNTL4__VMC_TAP_PTE_REQUEST_PHYSICAL_MASK

#define GCVM_L2_CNTL5__L2_CACHE_SMALLK_FRAGMENT_SIZE__SHIFT                MMVM_L2_CNTL5__L2_CACHE_SMALLK_FRAGMENT_SIZE__SHIFT
#define GCVM_L2_CNTL5__L2_CACHE_SMALLK_FRAGMENT_SIZE_MASK                  MMVM_L2_CNTL5__L2_CACHE_SMALLK_FRAGMENT_SIZE_MASK

#define GCVM_CONTEXT0_CNTL__ENABLE_CONTEXT__SHIFT                          MMVM_CONTEXT0_CNTL__ENABLE_CONTEXT__SHIFT
#define GCVM_CONTEXT0_CNTL__ENABLE_CONTEXT_MASK                            MMVM_CONTEXT0_CNTL__ENABLE_CONTEXT_MASK
#define GCVM_CONTEXT0_CNTL__PAGE_TABLE_DEPTH__SHIFT                        MMVM_CONTEXT0_CNTL__PAGE_TABLE_DEPTH__SHIFT
#define GCVM_CONTEXT0_CNTL__PAGE_TABLE_DEPTH_MASK                          MMVM_CONTEXT0_CNTL__PAGE_TABLE_DEPTH_MASK
#define GCVM_CONTEXT0_CNTL__RETRY_PERMISSION_OR_INVALID_PAGE_FAULT__SHIFT  MMVM_CONTEXT0_CNTL__RETRY_PERMISSION_OR_INVALID_PAGE_FAULT__SHIFT
#define GCVM_CONTEXT0_CNTL__RETRY_PERMISSION_OR_INVALID_PAGE_FAULT_MASK    MMVM_CONTEXT0_CNTL__RETRY_PERMISSION_OR_INVALID_PAGE_FAULT_MASK

#define GCVM_CONTEXT1_CNTL__ENABLE_CONTEXT__SHIFT                          MMVM_CONTEXT1_CNTL__ENABLE_CONTEXT__SHIFT
#define GCVM_CONTEXT1_CNTL__ENABLE_CONTEXT_MASK                            MMVM_CONTEXT1_CNTL__ENABLE_CONTEXT_MASK
#define GCVM_CONTEXT1_CNTL__PAGE_TABLE_DEPTH__SHIFT                        MMVM_CONTEXT1_CNTL__PAGE_TABLE_DEPTH__SHIFT
#define GCVM_CONTEXT1_CNTL__PAGE_TABLE_DEPTH_MASK                          MMVM_CONTEXT1_CNTL__PAGE_TABLE_DEPTH_MASK
#define GCVM_CONTEXT1_CNTL__PAGE_TABLE_BLOCK_SIZE__SHIFT                   MMVM_CONTEXT1_CNTL__PAGE_TABLE_BLOCK_SIZE__SHIFT
#define GCVM_CONTEXT1_CNTL__PAGE_TABLE_BLOCK_SIZE_MASK                     MMVM_CONTEXT1_CNTL__PAGE_TABLE_BLOCK_SIZE_MASK
#define GCVM_CONTEXT1_CNTL__RETRY_PERMISSION_OR_INVALID_PAGE_FAULT__SHIFT  MMVM_CONTEXT1_CNTL__RETRY_PERMISSION_OR_INVALID_PAGE_FAULT__SHIFT
#define GCVM_CONTEXT1_CNTL__RETRY_PERMISSION_OR_INVALID_PAGE_FAULT_MASK    MMVM_CONTEXT1_CNTL__RETRY_PERMISSION_OR_INVALID_PAGE_FAULT_MASK
#define GCVM_CONTEXT1_CNTL__RANGE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT   MMVM_CONTEXT1_CNTL__RANGE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define GCVM_CONTEXT1_CNTL__RANGE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK     MMVM_CONTEXT1_CNTL__RANGE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define GCVM_CONTEXT1_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT MMVM_CONTEXT1_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define GCVM_CONTEXT1_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK   MMVM_CONTEXT1_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define GCVM_CONTEXT1_CNTL__PDE0_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT    MMVM_CONTEXT1_CNTL__PDE0_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define GCVM_CONTEXT1_CNTL__PDE0_PROTECTION_FAULT_ENABLE_DEFAULT_MASK      MMVM_CONTEXT1_CNTL__PDE0_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define GCVM_CONTEXT1_CNTL__VALID_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT   MMVM_CONTEXT1_CNTL__VALID_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define GCVM_CONTEXT1_CNTL__VALID_PROTECTION_FAULT_ENABLE_DEFAULT_MASK     MMVM_CONTEXT1_CNTL__VALID_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define GCVM_CONTEXT1_CNTL__READ_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT    MMVM_CONTEXT1_CNTL__READ_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define GCVM_CONTEXT1_CNTL__READ_PROTECTION_FAULT_ENABLE_DEFAULT_MASK      MMVM_CONTEXT1_CNTL__READ_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define GCVM_CONTEXT1_CNTL__WRITE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT   MMVM_CONTEXT1_CNTL__WRITE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define GCVM_CONTEXT1_CNTL__WRITE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK     MMVM_CONTEXT1_CNTL__WRITE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define GCVM_CONTEXT1_CNTL__EXECUTE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT MMVM_CONTEXT1_CNTL__EXECUTE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define GCVM_CONTEXT1_CNTL__EXECUTE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK   MMVM_CONTEXT1_CNTL__EXECUTE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK

// GFXHUB v12_0 versions of L2_PROTECTION_FAULT_CNTL fields — identical
// layout per gc_12_0_0_sh_mask.h; alias to MMHUB names.
#define GCVM_L2_PROTECTION_FAULT_CNTL__RANGE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT          MMVM_L2_PROTECTION_FAULT_CNTL__RANGE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define GCVM_L2_PROTECTION_FAULT_CNTL__RANGE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK            MMVM_L2_PROTECTION_FAULT_CNTL__RANGE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define GCVM_L2_PROTECTION_FAULT_CNTL__PDE0_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT           MMVM_L2_PROTECTION_FAULT_CNTL__PDE0_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define GCVM_L2_PROTECTION_FAULT_CNTL__PDE0_PROTECTION_FAULT_ENABLE_DEFAULT_MASK             MMVM_L2_PROTECTION_FAULT_CNTL__PDE0_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define GCVM_L2_PROTECTION_FAULT_CNTL__PDE1_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT           MMVM_L2_PROTECTION_FAULT_CNTL__PDE1_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define GCVM_L2_PROTECTION_FAULT_CNTL__PDE1_PROTECTION_FAULT_ENABLE_DEFAULT_MASK             MMVM_L2_PROTECTION_FAULT_CNTL__PDE1_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define GCVM_L2_PROTECTION_FAULT_CNTL__PDE2_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT           MMVM_L2_PROTECTION_FAULT_CNTL__PDE2_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define GCVM_L2_PROTECTION_FAULT_CNTL__PDE2_PROTECTION_FAULT_ENABLE_DEFAULT_MASK             MMVM_L2_PROTECTION_FAULT_CNTL__PDE2_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define GCVM_L2_PROTECTION_FAULT_CNTL__TRANSLATE_FURTHER_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT MMVM_L2_PROTECTION_FAULT_CNTL__TRANSLATE_FURTHER_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define GCVM_L2_PROTECTION_FAULT_CNTL__TRANSLATE_FURTHER_PROTECTION_FAULT_ENABLE_DEFAULT_MASK   MMVM_L2_PROTECTION_FAULT_CNTL__TRANSLATE_FURTHER_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define GCVM_L2_PROTECTION_FAULT_CNTL__NACK_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT           MMVM_L2_PROTECTION_FAULT_CNTL__NACK_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define GCVM_L2_PROTECTION_FAULT_CNTL__NACK_PROTECTION_FAULT_ENABLE_DEFAULT_MASK             MMVM_L2_PROTECTION_FAULT_CNTL__NACK_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define GCVM_L2_PROTECTION_FAULT_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT     MMVM_L2_PROTECTION_FAULT_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define GCVM_L2_PROTECTION_FAULT_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK       MMVM_L2_PROTECTION_FAULT_CNTL__DUMMY_PAGE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define GCVM_L2_PROTECTION_FAULT_CNTL__VALID_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT          MMVM_L2_PROTECTION_FAULT_CNTL__VALID_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define GCVM_L2_PROTECTION_FAULT_CNTL__VALID_PROTECTION_FAULT_ENABLE_DEFAULT_MASK            MMVM_L2_PROTECTION_FAULT_CNTL__VALID_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define GCVM_L2_PROTECTION_FAULT_CNTL__READ_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT           MMVM_L2_PROTECTION_FAULT_CNTL__READ_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define GCVM_L2_PROTECTION_FAULT_CNTL__READ_PROTECTION_FAULT_ENABLE_DEFAULT_MASK             MMVM_L2_PROTECTION_FAULT_CNTL__READ_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define GCVM_L2_PROTECTION_FAULT_CNTL__WRITE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT          MMVM_L2_PROTECTION_FAULT_CNTL__WRITE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define GCVM_L2_PROTECTION_FAULT_CNTL__WRITE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK            MMVM_L2_PROTECTION_FAULT_CNTL__WRITE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define GCVM_L2_PROTECTION_FAULT_CNTL__EXECUTE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT        MMVM_L2_PROTECTION_FAULT_CNTL__EXECUTE_PROTECTION_FAULT_ENABLE_DEFAULT__SHIFT
#define GCVM_L2_PROTECTION_FAULT_CNTL__EXECUTE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK          MMVM_L2_PROTECTION_FAULT_CNTL__EXECUTE_PROTECTION_FAULT_ENABLE_DEFAULT_MASK
#define GCVM_L2_PROTECTION_FAULT_CNTL__CRASH_ON_NO_RETRY_FAULT__SHIFT                        MMVM_L2_PROTECTION_FAULT_CNTL__CRASH_ON_NO_RETRY_FAULT__SHIFT
#define GCVM_L2_PROTECTION_FAULT_CNTL__CRASH_ON_NO_RETRY_FAULT_MASK                          MMVM_L2_PROTECTION_FAULT_CNTL__CRASH_ON_NO_RETRY_FAULT_MASK
#define GCVM_L2_PROTECTION_FAULT_CNTL__CRASH_ON_RETRY_FAULT__SHIFT                           MMVM_L2_PROTECTION_FAULT_CNTL__CRASH_ON_RETRY_FAULT__SHIFT
#define GCVM_L2_PROTECTION_FAULT_CNTL__CRASH_ON_RETRY_FAULT_MASK                             MMVM_L2_PROTECTION_FAULT_CNTL__CRASH_ON_RETRY_FAULT_MASK

#define GCVM_L2_PROTECTION_FAULT_CNTL2__ACTIVE_PAGE_MIGRATION_PTE_READ_RETRY__SHIFT          MMVM_L2_PROTECTION_FAULT_CNTL2__ACTIVE_PAGE_MIGRATION_PTE_READ_RETRY__SHIFT
#define GCVM_L2_PROTECTION_FAULT_CNTL2__ACTIVE_PAGE_MIGRATION_PTE_READ_RETRY_MASK            MMVM_L2_PROTECTION_FAULT_CNTL2__ACTIVE_PAGE_MIGRATION_PTE_READ_RETRY_MASK

#define GCVM_INVALIDATE_ENG0_REQ__PER_VMID_INVALIDATE_REQ__SHIFT           MMVM_INVALIDATE_ENG0_REQ__PER_VMID_INVALIDATE_REQ__SHIFT
#define GCVM_INVALIDATE_ENG0_REQ__PER_VMID_INVALIDATE_REQ_MASK             MMVM_INVALIDATE_ENG0_REQ__PER_VMID_INVALIDATE_REQ_MASK
#define GCVM_INVALIDATE_ENG0_REQ__FLUSH_TYPE__SHIFT                        MMVM_INVALIDATE_ENG0_REQ__FLUSH_TYPE__SHIFT
#define GCVM_INVALIDATE_ENG0_REQ__FLUSH_TYPE_MASK                          MMVM_INVALIDATE_ENG0_REQ__FLUSH_TYPE_MASK
#define GCVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PTES__SHIFT                MMVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PTES__SHIFT
#define GCVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PTES_MASK                  MMVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PTES_MASK
#define GCVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PDE0__SHIFT                MMVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PDE0__SHIFT
#define GCVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PDE0_MASK                  MMVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PDE0_MASK
#define GCVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PDE1__SHIFT                MMVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PDE1__SHIFT
#define GCVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PDE1_MASK                  MMVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PDE1_MASK
#define GCVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PDE2__SHIFT                MMVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PDE2__SHIFT
#define GCVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PDE2_MASK                  MMVM_INVALIDATE_ENG0_REQ__INVALIDATE_L2_PDE2_MASK
#define GCVM_INVALIDATE_ENG0_REQ__INVALIDATE_L1_PTES__SHIFT                MMVM_INVALIDATE_ENG0_REQ__INVALIDATE_L1_PTES__SHIFT
#define GCVM_INVALIDATE_ENG0_REQ__INVALIDATE_L1_PTES_MASK                  MMVM_INVALIDATE_ENG0_REQ__INVALIDATE_L1_PTES_MASK
#define GCVM_INVALIDATE_ENG0_REQ__CLEAR_PROTECTION_FAULT_STATUS_ADDR__SHIFT MMVM_INVALIDATE_ENG0_REQ__CLEAR_PROTECTION_FAULT_STATUS_ADDR__SHIFT
#define GCVM_INVALIDATE_ENG0_REQ__CLEAR_PROTECTION_FAULT_STATUS_ADDR_MASK  MMVM_INVALIDATE_ENG0_REQ__CLEAR_PROTECTION_FAULT_STATUS_ADDR_MASK
