//
//  gfx12_formats.h — GENERATED by tools/gen-format-table.py, do not edit.
//
//  MTLPixelFormat numeric values come from the macOS SDK header of the same
//  name; GFX12 format values from Mesa's register database, via
//  gfx12_descriptors.h. Only the pairing is a judgement, and it is made only
//  where both names describe the same channel layout unambiguously.
//
//  Packed formats (10:10:10:2 and similar) are deliberately ABSENT: their
//  component order differs between APIs and guessing rotates the channels.
//  gfx12FormatForMetal() returns false for anything not listed, which is the
//  correct answer for a format we have not established.
//
#ifndef NAVI48_GFX12_FORMATS_H
#define NAVI48_GFX12_FORMATS_H

#include "gfx12_descriptors.h"

struct Gfx12FormatEntry {
    uint32_t metalFormat;
    uint32_t gfxFormat;
    uint32_t dstSel[4];
};

static const Gfx12FormatEntry kGfx12FormatTable[] = {
    {   10, kGfx12Fmt_8_UNORM, { kGfx12SelX, kGfx12SelZero, kGfx12SelZero, kGfx12SelOne } },   // MTLPixelFormatR8Unorm
    {   13, kGfx12Fmt_8_UINT, { kGfx12SelX, kGfx12SelZero, kGfx12SelZero, kGfx12SelOne } },   // MTLPixelFormatR8Uint
    {   25, kGfx12Fmt_16_FLOAT, { kGfx12SelX, kGfx12SelZero, kGfx12SelZero, kGfx12SelOne } },   // MTLPixelFormatR16Float
    {   30, kGfx12Fmt_8_8_UNORM, { kGfx12SelX, kGfx12SelY, kGfx12SelZero, kGfx12SelOne } },   // MTLPixelFormatRG8Unorm
    {   53, kGfx12Fmt_32_UINT, { kGfx12SelX, kGfx12SelZero, kGfx12SelZero, kGfx12SelOne } },   // MTLPixelFormatR32Uint
    {   55, kGfx12Fmt_32_FLOAT, { kGfx12SelX, kGfx12SelZero, kGfx12SelZero, kGfx12SelOne } },   // MTLPixelFormatR32Float
    {   65, kGfx12Fmt_16_16_FLOAT, { kGfx12SelX, kGfx12SelY, kGfx12SelZero, kGfx12SelOne } },   // MTLPixelFormatRG16Float
    {   70, kGfx12Fmt_8_8_8_8_UNORM, { kGfx12SelX, kGfx12SelY, kGfx12SelZ, kGfx12SelW } },   // MTLPixelFormatRGBA8Unorm
    {   71, kGfx12Fmt_8_8_8_8_SRGB, { kGfx12SelX, kGfx12SelY, kGfx12SelZ, kGfx12SelW } },   // MTLPixelFormatRGBA8Unorm_sRGB
    {   73, kGfx12Fmt_8_8_8_8_UINT, { kGfx12SelX, kGfx12SelY, kGfx12SelZ, kGfx12SelW } },   // MTLPixelFormatRGBA8Uint
    {   80, kGfx12Fmt_8_8_8_8_UNORM, { kGfx12SelZ, kGfx12SelY, kGfx12SelX, kGfx12SelW } },   // MTLPixelFormatBGRA8Unorm
    {   81, kGfx12Fmt_8_8_8_8_SRGB, { kGfx12SelZ, kGfx12SelY, kGfx12SelX, kGfx12SelW } },   // MTLPixelFormatBGRA8Unorm_sRGB
    {  105, kGfx12Fmt_32_32_FLOAT, { kGfx12SelX, kGfx12SelY, kGfx12SelZero, kGfx12SelOne } },   // MTLPixelFormatRG32Float
    {  115, kGfx12Fmt_16_16_16_16_FLOAT, { kGfx12SelX, kGfx12SelY, kGfx12SelZ, kGfx12SelW } },   // MTLPixelFormatRGBA16Float
    {  125, kGfx12Fmt_32_32_32_32_FLOAT, { kGfx12SelX, kGfx12SelY, kGfx12SelZ, kGfx12SelW } },   // MTLPixelFormatRGBA32Float
};

static inline bool gfx12FormatForMetal(uint32_t metalFormat,
                                       uint32_t *gfxFormat,
                                       uint32_t dstSel[4])
{
    const unsigned n = sizeof(kGfx12FormatTable) / sizeof(kGfx12FormatTable[0]);
    for (unsigned i = 0; i < n; i++) {
        if (kGfx12FormatTable[i].metalFormat != metalFormat)
            continue;
        *gfxFormat = kGfx12FormatTable[i].gfxFormat;
        for (int c = 0; c < 4; c++)
            dstSel[c] = kGfx12FormatTable[i].dstSel[c];
        return true;
    }
    return false;
}

#endif // NAVI48_GFX12_FORMATS_H
