#!/usr/bin/env python3
"""Generate build/gen/n48_tramp.inc: for every trampoline leaf class of gates/leaves.py TRAMP, the member declarations (N48_TR_DECLS_<Leaf>) and the definitions
(N48_TR_DEFS_<Leaf>(Leaf)) of the hooked slots plus forwarders for the parent's remaining non-exported slots. Usage: gen_tramp.py <out.inc>

A hooked slot's definition:  kill switch first; widen the arguments to 64 bits; ask the ops table's generic vhook (n48_vhook); handled -> return its value; otherwise the
default: 'zero' (a constant), or 'base' = the family's OWN implementation, called through the parent's exported vtable (same thing the family would have run without us).
"""
import json, os, re, sys
from common import *
sys.path.insert(0, LAYOUT)
import gen_header as G

def slots_json():
    return json.load(open(os.path.join(LAYOUT, 'generated', 'slots.json')))['classes']

def visible(SJ, c, i):
    while c in SJ:
        e = SJ[c]['slots'].get(str(i))
        if e:
            return e
        c = SJ[c]['super']
    return None

def sig_of(e, i):
    """-> (ret, name, args[list of type strings], cv)"""
    if e['kind'] == 'sdk':
        m = re.match(r'^(.*?)(\w+)\((.*)\)(\s*const)?$', e['name'])
        ret, name, args, cv = m.group(1).strip(), m.group(2), m.group(3), (m.group(4) or '')
    elif e['kind'] == 'real':
        ret, name, args, cv = 'N48_R_%s_%d' % (G.san(e['owner']), i), e['name'], e['args'], e['cv'] or ''
    else:
        raise SystemExit('slot %d has no signature (placeholder): cannot hook it' % i)
    al = [a for a in G.split_args(args) if a and a != 'void']
    return ret, name, al, cv

def main():
    out = sys.argv[1]
    C = model(); SJ = slots_json(); fwd = forwarded()
    L = ['// GENERATED by gates/gen_tramp.py. DO NOT EDIT.']
    for leaf, parent, extra in LEAVES:
        if leaf not in TRAMP:
            continue
        vc, hooks = TRAMP[leaf][0], TRAMP[leaf][1]
        hookfn = TRAMP[leaf][2] if len(TRAMP[leaf]) > 2 else 'n48_vhook'
        hand = set(HAND.get(leaf, []))
        vt = ztv(parent)
        decls, defs = [], []
        for slot in sorted(hooks):
            mode = hooks[slot]
            e = visible(SJ, parent, slot)
            if e is None:
                raise SystemExit('%s slot %d: no declaration visible in %s' % (leaf, slot, parent))
            ret, name, al, cv = sig_of(e, slot)
            if len(al) > 6:
                raise SystemExit('%s slot %d: more than 6 arguments' % (leaf, slot))
            decls.append('    virtual %s %s(%s)%s override;' % (ret, name, ', '.join(al), cv))
            params = ', '.join('%s p%d' % (t, k) if '(' not in t else t for k, t in enumerate(al))
            wid = []
            for k, t in enumerate(al):
                if '&' in t:
                    wid.append('(uint64_t)(uintptr_t)&p%d' % k)
                elif '*' in t:
                    wid.append('(uint64_t)(uintptr_t)p%d' % k)
                else:
                    wid.append('(uint64_t)(int64_t)p%d' % k)
            args = ', '.join('p%d' % k for k in range(len(al)))
            if mode == 'base':
                ftype = '%s (*)(%s%s *%s)' % (ret, 'const ' if 'const' in cv else '', leaf, ''.join(', ' + t for t in al))
                dflt = 'return ((%s)(n48_ztvfam_%s[%d]))(this%s);' % (ftype, parent, 2 + slot, (', ' + args) if args else '')
                ks = 'N48_AUX_ENTER((%s)0);' % ret
            elif mode == 'zero':
                dflt = 'return (%s)0;' % ret
                ks = 'N48_AUX_ENTER((%s)0);' % ret
            else:
                dflt = 'return (%s)%s;' % (ret, mode)
                ks = 'N48_AUX_ENTER((%s)%s);' % (ret, mode)
            body = ('%s %s Leaf::%s(%s)%s {\\\n        %s\\\n        uint64_t a[6] = { %s }; uint64_t r = 0;\\\n        if (%s(%s, %d, (void *)this, a, %d, &r)) return (%s)r;\\\n        %s\\\n    }'
                    % ('', ret, name, params, cv, ks, ', '.join(wid + ['0'] * (6 - len(wid))) if wid else '0', hookfn, vc, slot, len(al), ret, dflt))
            defs.append('    ' + body.strip())
        # forwarders for the parent's non-exported slots that are neither hooked nor hand-written
        for slot in fwd.get(parent, []):
            if slot in hooks or slot in hand:
                continue
            e = visible(SJ, parent, slot)
            ret, name, al, cv = sig_of(e, slot)
            decls.append('    virtual %s %s(%s)%s override; /* non-exported: forwarded */' % (ret, name, ', '.join(al), cv))
            defs.append('    __attribute__((naked)) %s Leaf::%s(%s)%s { __asm__("movq %s@GOTPCREL(%%rip), %%rax\\n\\tmovq %d(%%rax), %%rax\\n\\tjmpq *%%rax"); }'
                        % (ret, name, ', '.join(al), cv, vt, 16 + 8 * slot))
        L.append('#define N48_TR_DECLS_%s \\' % leaf)
        L.append(' \\\n'.join(decls))
        L.append('#define N48_TR_DEFS_%s(Leaf) \\' % leaf)
        L.append(' \\\n'.join(d.replace('\n', '\n') for d in defs))
    open(out, 'w').write('\n'.join(L) + '\n')

if __name__ == '__main__':
    main()
