#!/usr/bin/env python3
"""Generate build/gen/n48_gate.inc: the runtime layout-gate tables of Navi48Accel.cpp (vtable symbols, override slot lists, sizes) from the same model
that produced IOAccelFamily2_decl.h. Usage: gen_gate.py <out.inc>"""
import sys
from common import *

def main():
    out = sys.argv[1]
    C = model(); fwd = forwarded()
    L = ['// GENERATED by gates/gen_gate.py from tools/native/ioaccel-layout/generated/model.json. DO NOT EDIT.']
    for leaf, parent, extra in LEAVES:
        L.append('extern "C" const uintptr_t n48_ztv_%s[] __asm__("%s");' % (leaf, ztv(leaf)))
        L.append('extern "C" const uintptr_t n48_ztvfam_%s[] __asm__("%s");' % (parent, ztv(parent)))
        ovr = override_slots(leaf, parent, extra, C, fwd)
        L.append('static const uint16_t n48_ovr_%s[] = { %s };' % (leaf, ', '.join(str(x) for x in ovr)))
    L.append('static const ClassGate kGate[] = {')
    for leaf, parent, extra in LEAVES:
        L.append('    { "%s", "%s", n48_ztv_%s, n48_ztvfam_%s, N48_%s_NSLOTS, n48_ovr_%s, (uint32_t)(sizeof(n48_ovr_%s) / sizeof(uint16_t)), (uint32_t)sizeof(%s), N48_%s_SIZE, &%s::gMetaClass },'
                 % (leaf, parent, leaf, parent, parent, leaf, leaf, leaf, parent, leaf))
    L.append('};')
    open(out, 'w').write('\n'.join(L) + '\n')

if __name__ == '__main__':
    main()
