/* GENERATED by src/xlat12/gen/gen_tables.py - do not edit. Regenerate instead. */
#ifndef XLAT12_PROVENANCE_H
#define XLAT12_PROVENANCE_H
#define XLAT12_SRC_MESA_COMMIT  "4519cc5645880023ed1c83417d33c4cad99e88ee"
#define XLAT12_SRC_LINUX_COMMIT "587858367581b9c55c3690f4e63382ad622719d4"
/*
 * entries 668 (Apple union names 257 + census names + index-form addrs + census-unknown 28)
 * identical    144
 * moved        174
 * field_repack 164
 * absent       139
 * legacy_vs    16
 * unknown      31
 * Linux bases gfx10.3 {0: '0x1260 (294/300 names)', 1: '0xa000 (1567/1567 names)'}  gfx12 {1: '0xa000 (1428/1428 names)', 0: '0x1260 (247/247 names)'}
 * Linux cross-check: gfx10.3 agree 640, not named 0; gfx12 agree 485, not named 0; contradictions (refused) 0
 * no shared field (refused): SPI_SHADER_PGM_RSRC4_PS 0x0b004: gfx10.3 gfx103.json:14442 ['CU_EN'] | gfx12 gfx12.json:13347 ['WAVE_LIMIT', 'LDS_GROUP_SIZE', 'INST_PREF_SIZE', 'IMAGE_OP']
 * no shared field (refused): SPI_SHADER_PGM_RSRC4_HS 0x0b404: gfx10.3 gfx103.json:14442 ['CU_EN'] | gfx12 gfx12.json:13338 ['WAVE_LIMIT', 'GLG_EN_OVERRIDE', 'GLG_FORCE_DISABLE', 'INST_PREF_SIZE', 'IMAGE_OP']
 * no shared field (refused): RLC_SPM_PERFMON_SEGMENT_SIZE 0x37210: gfx10.3 gfx103.json:14057 ['PERFMON_SEGMENT_SIZE', 'RESERVED1', 'GLOBAL_NUM_LINE', 'SE0_NUM_LINE', 'SE1_NUM_LINE', 'SE2_NUM_LINE', 'RESERVED'] | gfx12 gfx12.json:12809 ['TOTAL_NUM_SEGMENT', 'GLOBAL_NUM_SEGMENT', 'SE_NUM_SEGMENT']
 * NGG rule: VGT_SHADER_STAGES_EN g10 0x28b54 PRIMGEN_EN bit 13 (gfx103.json:15066)
 */
#endif
