/* xlat12_shader_ids_candidates.h - GENERATED by tools/gfx-shader-ids.py --candidates-out; do not edit.
 * OFFLINE ONLY: the shipped rows of xlat12_shader_ids.h, byte for byte and in the same order, followed
 * by CANDIDATE rows that are NOT reviewed and NOT in the kext. Included by xlat12_ib.c only under
 * -DXLAT12_SHADER_IDS_HEADER (tools/m4-xlat/Makefile replay-candidate). The kext's Makefile never defines it.
 * Original header text follows.
 * Our packed gfx1201 programs the translated draw accepts, by exact code identity: ndw = ISA dwords through the last
 * s_endpgm, fnv = FNV-1a over them, head = the first four; w = the register words from the record's .registers note
 * (vertex: RSRC1_GS, RSRC2_GS, 0, 0; fragment: RSRC1_PS, RSRC2_PS, SPI_PS_INPUT_ENA, SPI_PS_INPUT_ADDR); io = vertex:
 * parameter exports, fragment: used interpolants (SPI_SHADER_GS_OUT_CONFIG_PS, an earlier analysis). */
#ifndef XLAT12_SHADER_IDS_H
#define XLAT12_SHADER_IDS_H
#include <stdint.h>
typedef struct { const char *name; uint32_t stage; uint32_t ndw; uint32_t fnv; uint32_t head[4]; uint32_t w[4]; uint32_t io;
                 uint8_t desc_slot, tex_slot, samp_slot; } xlat12_shader_id;   /* sampling user-data indices, 0xff = none */
static const xlat12_shader_id kXlat12ShaderIds[] = {
    { "m2_tri_vs", 1u, 37u, 0x370518c0u, { 0xbefe00c1u, 0xd71f0001u, 0x020100c1u, 0x9300ff03u }, { 0x020f0000u, 0x00000000u, 0x00000000u, 0x00000000u }, 0u, 255u, 255u, 255u },   /* packed sha256 efa5d2247b9e054c */
    { "m2_tri_fs=m2_mvp_fs", 0u, 9u, 0x8dbf3af3u, { 0xa400fff2u, 0x3e800000u, 0xa401f280u, 0xbf87051au }, { 0x020f0000u, 0x00000000u, 0x00000001u, 0x00000001u }, 0u, 255u, 255u, 255u },   /* packed sha256 27089d1c6ed56053 */
    { "m2_mvp_vs", 1u, 55u, 0xe4bcf795u, { 0xbefe00c1u, 0xd71f0001u, 0x020100c1u, 0x9300ff03u }, { 0x020f0000u, 0x00000000u, 0x00000000u, 0x00000000u }, 0u, 255u, 255u, 255u },   /* packed sha256 62ca98711ae4b0a2 */
    { "m2_col_vs", 1u, 72u, 0x22e24693u, { 0xbefe00c1u, 0xd71f0005u, 0x020100c1u, 0x9302ff03u }, { 0x020f0000u, 0x00000000u, 0x00000000u, 0x00000000u }, 1u, 255u, 255u, 255u },   /* packed sha256 921c3a2d979bae43 */
    { "m2_col_fs", 0u, 32u, 0x6aa72846u, { 0xbe80017eu, 0xbefe1d7eu, 0xbefd0002u, 0xce8f0002u }, { 0x020f0002u, 0x00000000u, 0x00000002u, 0x00000002u }, 1u, 255u, 255u, 255u },   /* packed sha256 3632a93388b98b8b */
    { "m2_half_fs", 0u, 8u, 0xbbd550c3u, { 0xa400f280u, 0xa401f080u, 0xbf87051au, 0x7e000200u }, { 0x020f0000u, 0x00000000u, 0x00000001u, 0x00000001u }, 0u, 255u, 255u, 255u },   /* packed sha256 7e1d035dd8a756a3 */
    { "SimpleVertex", 1u, 81u, 0x1bc1021du, { 0xbefe00c1u, 0xd71f0004u, 0x020100c1u, 0x9302ff03u }, { 0x020f0000u, 0x00000000u, 0x00000000u, 0x00000000u }, 1u, 255u, 255u, 255u },   /* packed sha256 f64be30749eb4deb */
    { "SimpleTextureFragment", 0u, 47u, 0x0085850bu, { 0xbe90017eu, 0xbefe1d7eu, 0xbefd0008u, 0xbe82017eu }, { 0x020f0001u, 0x00000000u, 0x00000002u, 0x00000002u }, 1u, 0u, 4u, 6u },   /* packed sha256 3e0121d5013ad547 */
    { "UberCompositeVertex", 1u, 85u, 0x7ae1aa19u, { 0xbefe00c1u, 0xd71f0004u, 0x020100c1u, 0x9302ff03u }, { 0x020f0000u, 0x00000000u, 0x00000000u, 0x00000000u }, 1u, 255u, 255u, 255u },   /* packed sha256 5ba1c560ab54b441 */
    { "UberCompositeFragment", 0u, 50u, 0x4912346bu, { 0xbe90017eu, 0xbefe1d7eu, 0xbefd000au, 0xbe82017eu }, { 0x020f0001u, 0x00000000u, 0x00000002u, 0x00000002u }, 1u, 0u, 4u, 8u },   /* packed sha256 ce42b60b1285afe1 */
    { "m2_tri_vs_rec", 1u, 60u, 0x2d808c40u, { 0xbefe00c1u, 0x7e0e0300u, 0xd71f0000u, 0x020100c1u }, { 0x020f0000u, 0x00000000u, 0x00000000u, 0x00000000u }, 0u, 255u, 255u, 255u },   /* packed sha256 f043a9fc617fbf14 */
    { "fca15jbebia3", 0u, 13u, 0x6088c6b1u, { 0x7e020280u, 0xee080002u, 0x00000000u, 0x00002201u }, { 0x020f0000u, 0x00000000u, 0x00000001u, 0x00000001u }, 0u, 255u, 255u, 255u },   /* packed sha256 4938df33f9561bed */
    { "plane__vertex", 1u, 56u, 0x290f33cdu, { 0xbefe00c1u, 0xd71f0001u, 0x020100c1u, 0x9300ff03u }, { 0x020f0000u, 0x00000000u, 0x00000000u, 0x00000000u }, 0u, 255u, 255u, 255u },   /* packed sha256 73b9aa954f701aba */
    { "path_distance_fragment", 0u, 97u, 0x2d01b1fdu, { 0xbe80017eu, 0xbefe1d7eu, 0xbefd0002u, 0xce8f0002u }, { 0x020f0003u, 0x00000000u, 0x00000020u, 0x00000020u }, 3u, 255u, 255u, 255u },   /* packed sha256 80276ed5096c5f7a */
    { "vkba6pa7jbebia3=vkba6pa8feba4", 1u, 403u, 0x813e8fbcu, { 0xbefe00c1u, 0xd71f000bu, 0x020100c1u, 0x9302ff03u }, { 0x020f0002u, 0x00000000u, 0x00000000u, 0x00000000u }, 3u, 255u, 255u, 255u },   /* packed sha256 812ecc565c56b412 */
    { "path_interior_fragment", 0u, 12u, 0x61f10c0eu, { 0x7c220480u, 0x7e0038ffu, 0xffffbc00u, 0x7e020280u }, { 0x020f0000u, 0x00000000u, 0x00001001u, 0x00001001u }, 0u, 255u, 255u, 255u },   /* packed sha256 4294e92a2f59ca17 */
    { "viba6la7jbebia3=viba6la8feba4", 1u, 195u, 0xffb11885u, { 0xbefe00c1u, 0xd71f0001u, 0x020100c1u, 0x9300ff03u }, { 0x020f0001u, 0x00000000u, 0x00000000u, 0x00000000u }, 0u, 255u, 255u, 255u },   /* packed sha256 4ed9a1f6219eb587 */
    { "fcja6ca7jbebia3", 0u, 50u, 0x08ec5c20u, { 0xf4002000u, 0xf8000000u, 0x84028506u, 0x7e000f02u }, { 0x020f0001u, 0x00000000u, 0x00000f01u, 0x00000f01u }, 0u, 255u, 255u, 255u },   /* packed sha256 c98b2b37837a5737 */
    { "fcjba5lca6jbebia3", 0u, 63u, 0x625a0c18u, { 0xf4002000u, 0xf8000000u, 0x84028506u, 0x7e000f02u }, { 0x020f0001u, 0x00000000u, 0x00000f01u, 0x00000f01u }, 0u, 255u, 255u, 255u },   /* packed sha256 89e5a9ca793863a2 */
    { "fca15ofeba4=fca15dheba4=fca16feba4=fca15ge2ba4", 0u, 20u, 0xd8b9a500u, { 0xf4002001u, 0xf800001cu, 0x7e000280u, 0xbfc70000u }, { 0x020f0000u, 0x00000000u, 0x00000001u, 0x00000001u }, 0u, 255u, 255u, 255u },   /* packed sha256 98ce525252411244 */
    { "ffgea5cia6ofeb2a3", 0u, 240u, 0xf335713au, { 0xbe86017eu, 0xbefe1d7eu, 0xbe82017eu, 0xbefd000au }, { 0x020f0003u, 0x00000000u, 0x00000020u, 0x00000020u }, 1u, 255u, 255u, 255u },   /* packed sha256 ab382b02c64bb851 */
    { "custom_effect_vertex", 1u, 90u, 0x55d9d6c6u, { 0xbefe00c1u, 0xd71f0002u, 0x020100c1u, 0x9302ff03u }, { 0x020f0000u, 0x00000000u, 0x00000000u, 0x00000000u }, 1u, 255u, 255u, 255u },   /* packed sha256 1e3cc515012ba85a */
    { "path_exterior_fragment", 0u, 89u, 0xa77ba49du, { 0xbe80017eu, 0xbefd0002u, 0xbefe1d7eu, 0xce8f0000u }, { 0x020f0003u, 0x00000000u, 0x00000f21u, 0x00000f21u }, 4u, 255u, 255u, 255u },   /* packed sha256 afbc938ac32e0106 */
    { "vjba6la7dheba4=vjba6la8feba4", 1u, 298u, 0x104c320fu, { 0xbefe00c1u, 0xd71f000bu, 0x020100c1u, 0x9302ff03u }, { 0x020f0002u, 0x00000000u, 0x00000000u, 0x00000000u }, 4u, 255u, 255u, 255u },   /* packed sha256 962621b25eb04882 */
    { "fcfa6ca7dheba4=fcfa6ca8feba4", 0u, 42u, 0xa713654bu, { 0xf4002000u, 0xf8000000u, 0x84028506u, 0x7e000f02u }, { 0x020f0001u, 0x00000000u, 0x00000f01u, 0x00000f01u }, 0u, 255u, 255u, 255u },   /* packed sha256 80e3ea72c0ce8bac */
    { "fpba14dheba4=fpba15feba4", 0u, 71u, 0xbcf89610u, { 0xbe82017eu, 0xbefe1d7eu, 0xf4002000u, 0xf8000000u }, { 0x020f0001u, 0x00000000u, 0x00000f01u, 0x00000f01u }, 0u, 255u, 255u, 255u },   /* packed sha256 1efc18787be08fba */
    { "fpba2ia11bea6", 0u, 227u, 0x5e3c3eadu, { 0xbe8a017eu, 0xbefe1d7eu, 0xf4002600u, 0xf8000000u }, { 0x020f0005u, 0x00000000u, 0x00000f01u, 0x00000f01u }, 0u, 255u, 255u, 255u },   /* packed sha256 587808400083a07b */
    { "fpba2ma11bea6", 0u, 257u, 0x36072565u, { 0xbe94017eu, 0xbefe1d7eu, 0xf4002000u, 0xf8000000u }, { 0x020f0005u, 0x00000000u, 0x00000f01u, 0x00000f01u }, 0u, 255u, 255u, 255u },   /* packed sha256 674b53c3a4f2370b */
    { "fpba3ba10bea6", 0u, 364u, 0xf9173ea5u, { 0xbe8e017eu, 0xbefe1d7eu, 0xf4002000u, 0xf8000000u }, { 0x020f0006u, 0x00000000u, 0x00000f01u, 0x00000f01u }, 0u, 255u, 255u, 255u },   /* packed sha256 6003ed0ce4679b5b */
    { "fpba2iba10bea6", 0u, 106u, 0xcd6e4822u, { 0xbe90017eu, 0xbefe1d7eu, 0xf4002000u, 0xf8000000u }, { 0x020f0001u, 0x00000000u, 0x00000f01u, 0x00000f01u }, 0u, 255u, 255u, 255u },   /* packed sha256 b97ebfc6e82e0931 */
    { "foba3bia9bea6", 0u, 243u, 0xc42d7b66u, { 0xbe98017eu, 0xbefe1d7eu, 0xf4008202u, 0xf800001cu }, { 0x020f0007u, 0x00000001u, 0x00000f01u, 0x00000f01u }, 0u, 255u, 255u, 255u },   /* packed sha256 ca906e0f8a2d91f5 */
    { "fpba2eca10dheba4", 0u, 199u, 0xa9cf0ad1u, { 0xbe98017eu, 0xbefe1d7eu, 0xf4002000u, 0xf8000000u }, { 0x020f0002u, 0x00000000u, 0x00000f01u, 0x00000f01u }, 0u, 255u, 255u, 255u },   /* packed sha256 f76c93cf8531c2b5 */
    { "fhe2ae2a2ca7ofeba4=fhe2ae2a2ca7ge2ba4", 0u, 106u, 0xba291585u, { 0xbe90017eu, 0xbefe1d7eu, 0xf4000482u, 0xf8000050u }, { 0x020f0003u, 0x00000000u, 0x00000020u, 0x00000020u }, 1u, 0u, 6u, 8u },   /* packed sha256 b6f5a5b2bfaf0af7 */
    { "vhe2ae2a2ca7ofeba4=vhe2ae2a2ca7ge2ba4", 1u, 139u, 0x589026c8u, { 0xbefe00c1u, 0xd71f0002u, 0x020100c1u, 0x9302ff03u }, { 0x020f0000u, 0x00000000u, 0x00000000u, 0x00000000u }, 2u, 255u, 255u, 255u },   /* packed sha256 d6bb1dbafb759695 */
    { "fcja6ca8feba4", 0u, 57u, 0x312aed4fu, { 0xf4002000u, 0xf8000000u, 0x84028506u, 0x7e000f02u }, { 0x020f0001u, 0x00000000u, 0x00000f01u, 0x00000f01u }, 0u, 255u, 255u, 255u },   /* packed sha256 02784a7a78f0b743 */
    { "fcjba5la8feba4", 0u, 57u, 0xf6a95834u, { 0xf4002000u, 0xf8000000u, 0x84028506u, 0x7e000f02u }, { 0x020f0001u, 0x00000000u, 0x00000f01u, 0x00000f01u }, 0u, 255u, 255u, 255u },   /* packed sha256 9f0a33f3619ce0b8 */
    { "fpba2eba11feba4", 0u, 100u, 0xc86e4470u, { 0xbe88017eu, 0xbefe1d7eu, 0xf4002500u, 0xf8000000u }, { 0x020f0001u, 0x00000000u, 0x00000f01u, 0x00000f01u }, 0u, 255u, 255u, 255u },   /* packed sha256 afc4cdf006fa39b6 */
    { "ws_B_ColorFill", 0u, 11u, 0x2b838958u, { 0xf4004001u, 0xf8000000u, 0xbfc70000u, 0xa4000100u }, { 0x020f0000u, 0x00000000u, 0x00000001u, 0x00000001u }, 0u, 255u, 255u, 255u },   /* packed sha256 420ca6c9c287dcc9 */
    { "ws_C_Xh", 0u, 44u, 0xe2a4684fu, { 0xbe80017eu, 0xbefe1d7eu, 0xbefd0004u, 0xce8f0002u }, { 0x020f0002u, 0x00000000u, 0x00000020u, 0x00000020u }, 1u, 255u, 255u, 255u },   /* packed sha256 f6e18f06b2f6b267 */
    { "ws_D_GPUPass", 0u, 83u, 0xd3d36bb9u, { 0xbe98017eu, 0xbefe1d7eu, 0xbefd000eu, 0xbe82017eu }, { 0x020f0002u, 0x00000000u, 0x00000002u, 0x00000002u }, 1u, 0u, 4u, 8u },   /* packed sha256 6b573e483c4ee5cf */
    { "ws_E_ViewportToNDC=ws_F_ViewportToNDC", 1u, 96u, 0xc05bae9au, { 0xbefe00c1u, 0xd71f0002u, 0x020100c1u, 0x9302ff03u }, { 0x020f0002u, 0x00000000u, 0x00000000u, 0x00000000u }, 1u, 255u, 255u, 255u },   /* packed sha256 2fdf2ec5a44aa8dc */
    { "ws_H_UberCompositeVertex", 1u, 85u, 0xea6ac219u, { 0xbefe00c1u, 0xd71f0004u, 0x020100c1u, 0x9302ff03u }, { 0x020f0000u, 0x00000000u, 0x00000000u, 0x00000000u }, 1u, 255u, 255u, 255u },   /* packed sha256 81b6210f35837af2 */
    { "RectPosTexFast_VS_gfx1201", 1u, 50u, 0xbf0feccau, { 0xbefe00c1u, 0xd71f0001u, 0x020100c1u, 0x9300ff03u }, { 0x020f0000u, 0x00000000u, 0x00000000u, 0x00000000u }, 0u, 255u, 255u, 255u },   /* packed sha256 6087d0f4a3d7e75e */
    { "Const_PS_gfx1201", 0u, 11u, 0x4da38bb8u, { 0x7e000200u, 0x7e020201u, 0x7e040202u, 0x7e060203u }, { 0x020f0000u, 0x00000000u, 0x00000001u, 0x00000001u }, 0u, 255u, 255u, 255u },   /* packed sha256 a3cf8a61d6087806 */
    { "Zero_PS_gfx1201", 0u, 8u, 0x859a7ae5u, { 0x7e000280u, 0xbf800000u, 0xbf800000u, 0xbf800000u }, { 0x020f0000u, 0x00000000u, 0x00000001u, 0x00000001u }, 0u, 255u, 255u, 255u },   /* packed sha256 f308ce5b3678b701 */
    { "Const_PS_unorm16_gfx1201", 0u, 12u, 0x70ee8613u, { 0x7e000200u, 0x7e020201u, 0x7e040202u, 0x7e060203u }, { 0x020f0000u, 0x00000000u, 0x00000001u, 0x00000001u }, 0u, 255u, 255u, 255u },   /* packed sha256 9f9e4efbcd53c178 */
    { "RectPosTexFast_VS_attr_gfx1201", 1u, 64u, 0xa74b276au, { 0xbefe00c1u, 0xd71f0001u, 0x020100c1u, 0x9302ff03u }, { 0x020f0000u, 0x00000000u, 0x00000000u, 0x00000000u }, 1u, 255u, 255u, 255u },   /* packed sha256 eaa34406bafa3e16 */
    { "Tex_PS_gfx1201", 0u, 22u, 0x4376be3cu, { 0xbefd000cu, 0xbe8e017eu, 0xbefe1d7eu, 0xce000002u }, { 0x020f0000u, 0x00000000u, 0x00000002u, 0x00000002u }, 1u, 255u, 255u, 255u },   /* packed sha256 b435a1d477550904 */
    { "ws_G_VfxXh", 1u, 112u, 0x6e51013fu, { 0xbefe00c1u, 0xd71f0004u, 0x020100c1u, 0x9302ff03u }, { 0x020f0001u, 0x00000000u, 0x00000000u, 0x00000000u }, 1u, 255u, 255u, 255u },   /* packed sha256 3963362420738f1c */
    { "ws_AA_TimgXh_Icir", 0u, 90u, 0x290890a3u, { 0xbe82017eu, 0xbefe1d7eu, 0xbf870009u, 0xbe80017eu }, { 0x020f0001u, 0x00000000u, 0x00000020u, 0x00000020u }, 1u, 255u, 255u, 255u },   /* packed sha256 6e0ea5c49b5da5a3 */
    { "ws_AD_narrow_blur_23_frag_lph", 0u, 199u, 0x3dbe4294u, { 0xbea2017eu, 0xbefe1d7eu, 0xbefd000cu, 0xbe82017eu }, { 0x020f0006u, 0x00000000u, 0x00000002u, 0x00000002u }, 1u, 0u, 4u, 6u },   /* packed sha256 4bfcd7c0450dcf81 */
    { "ws_AE_downsample_4_frag_lph", 0u, 104u, 0xdbf619c2u, { 0xbefd000cu, 0xbe82017eu, 0xbefe1d7eu, 0xce8f0002u }, { 0x020f0003u, 0x00000000u, 0x00000002u, 0x00000002u }, 1u, 0u, 4u, 6u },   /* packed sha256 7c44d541e66eb00d */
    { "ws_AF_variable_blur_downsample_frag_lph", 0u, 173u, 0x1051f3f6u, { 0xbefd000cu, 0xbe82017eu, 0xbefe1d7eu, 0xce8f0002u }, { 0x020f0007u, 0x00000000u, 0x00000002u, 0x00000002u }, 1u, 0u, 4u, 6u },   /* packed sha256 486c417372323df8 */
    { "ws_AG_TimgXh_Icir", 0u, 88u, 0xd7da98f7u, { 0xbe82017eu, 0xbefe1d7eu, 0xbf870009u, 0xbe80017eu }, { 0x020f0001u, 0x00000000u, 0x00000020u, 0x00000020u }, 1u, 255u, 255u, 255u },   /* packed sha256 7aecdbd8a2f1e6bc */
    { "ws_AH_Xh", 0u, 41u, 0xdb98e8d3u, { 0xbe80017eu, 0xbefe1d7eu, 0xbefd0004u, 0xce8f0002u }, { 0x020f0002u, 0x00000000u, 0x00000020u, 0x00000020u }, 1u, 255u, 255u, 255u },   /* packed sha256 0ab6cfe44e8418e1 */
    { "ws_AI_TmuaXh_Isrc_Isrc", 0u, 119u, 0xae6c50d3u, { 0xbe82017eu, 0xbefe1d7eu, 0xbefd000eu, 0xbe86017eu }, { 0x020f0003u, 0x00000000u, 0x00000020u, 0x00000020u }, 3u, 255u, 255u, 255u },   /* packed sha256 8dc29f17de9f3532 */
    { "ws_AJ_TcimXh_Isrc", 0u, 83u, 0x5a2f0cb6u, { 0xbe90017eu, 0xbefe1d7eu, 0xbefd000cu, 0xbe82017eu }, { 0x020f0003u, 0x00000000u, 0x00000020u, 0x00000020u }, 2u, 0u, 8u, 10u },   /* packed sha256 a00543c19fed3ed1 */
    { "ws_AK_TsplXh_Isrc", 0u, 88u, 0xaa26070eu, { 0xbe90017eu, 0xbefe1d7eu, 0xbefd000cu, 0xbe82017eu }, { 0x020f0002u, 0x00000000u, 0x00000020u, 0x00000020u }, 2u, 0u, 8u, 10u },   /* packed sha256 57316610b481d973 */
    { "ws_AL_TimgXh_Isrc", 0u, 49u, 0xfd012f2fu, { 0xbe90017eu, 0xbefe1d7eu, 0xbefd000cu, 0xbe82017eu }, { 0x020f0001u, 0x00000000u, 0x00000020u, 0x00000020u }, 1u, 0u, 8u, 10u },   /* packed sha256 0a1f2719817fdf24 */
    { "ws_AM_narrow_blur_11_frag_lph", 0u, 142u, 0x2519bf29u, { 0xbe98017eu, 0xbefe1d7eu, 0xbefd000cu, 0xbe82017eu }, { 0x020f0003u, 0x00000000u, 0x00000002u, 0x00000002u }, 1u, 0u, 4u, 6u },   /* packed sha256 f633242bd238cfff */
    { "ws_AN_TmuaXh_Isrc_Isrc", 0u, 122u, 0x7b3a6dfeu, { 0xbe82017eu, 0xbefe1d7eu, 0xbefd000eu, 0xbe86017eu }, { 0x020f0003u, 0x00000000u, 0x00000020u, 0x00000020u }, 3u, 255u, 255u, 255u },   /* packed sha256 437cb090c1c1ce5b */
    { "ws_AO_TmuaXh_IsrcCcl_Icir", 0u, 168u, 0xb4fc3c24u, { 0xbe82017eu, 0xbefe1d7eu, 0xbefd000cu, 0xbe86017eu }, { 0x020f0004u, 0x00000000u, 0x00000020u, 0x00000020u }, 3u, 0u, 8u, 10u },   /* packed sha256 2a1753382055b2ad */
    { "ws_I_VfxU10Xh", 1u, 112u, 0xf4d2f24eu, { 0xbefe00c1u, 0xd71f0006u, 0x020100c1u, 0x9302ff03u }, { 0x020f0001u, 0x00000000u, 0x00000000u, 0x00000000u }, 2u, 255u, 255u, 255u },   /* packed sha256 95fbe799ea213cbc */
    { "ws_K_VfxU11Xh", 1u, 126u, 0x0d6797cfu, { 0xbefe00c1u, 0xd71f0008u, 0x020100c1u, 0x9302ff03u }, { 0x020f0001u, 0x00000000u, 0x00000000u, 0x00000000u }, 2u, 255u, 255u, 255u },   /* packed sha256 5bc6b79af6ebf7e1 */
    { "ws_L_Xh", 0u, 46u, 0xe8ac2fb4u, { 0xbe80017eu, 0xbefe1d7eu, 0xbefd0004u, 0xce8f0002u }, { 0x020f0002u, 0x00000000u, 0x00000020u, 0x00000020u }, 1u, 255u, 255u, 255u },   /* packed sha256 bbf38052d15aeb58 */
    { "ws_P_TimgXh_Ialp", 0u, 46u, 0xebaa377cu, { 0xbe90017eu, 0xbefe1d7eu, 0xbefd000cu, 0xbe82017eu }, { 0x020f0001u, 0x00000000u, 0x00000020u, 0x00000020u }, 1u, 0u, 8u, 10u },   /* packed sha256 6149d600676130d9 */
    { "ws_U_TvcmXh_Isrc", 0u, 192u, 0x92c6ae13u, { 0xbe86017eu, 0xbefe1d7eu, 0xbf870009u, 0xbe82017eu }, { 0x020f0002u, 0x00000000u, 0x00000f21u, 0x00000f21u }, 1u, 0u, 8u, 12u },   /* packed sha256 56714a847298e8f3 */
    { "ws_V_VfxU10Xh", 1u, 124u, 0x78195974u, { 0xbefe00c1u, 0xd71f0006u, 0x020100c1u, 0x9302ff03u }, { 0x020f0001u, 0x00000000u, 0x00000000u, 0x00000000u }, 2u, 255u, 255u, 255u },   /* packed sha256 bb7a81c27f7ccd91 */
    { "ws_Y_TkfhBvcmXh_Isrc", 0u, 372u, 0x5276813bu, { 0xbe82017eu, 0xbefe1d7eu, 0xbf870009u, 0xbe86017eu }, { 0x020f0003u, 0x00000000u, 0x00000f21u, 0x00000f21u }, 1u, 0u, 8u, 12u },   /* packed sha256 93ab8e021da04999 */
    { "ws_Z_TimgXh_Isrc", 0u, 54u, 0xf91e4deeu, { 0xbe90017eu, 0xbefe1d7eu, 0xbefd000cu, 0xbe82017eu }, { 0x020f0001u, 0x00000000u, 0x00000020u, 0x00000020u }, 1u, 0u, 8u, 10u },   /* packed sha256 9bb18ffec8c0070c */
    { "ws_M_TextureCopy_cand", 0u, 42u, 0x1ddbfcadu, { 0xbe88017eu, 0xbefe1d7eu, 0xbefd0006u, 0xbe82017eu }, { 0x020f0001u, 0x00000000u, 0x00000002u, 0x00000002u }, 1u, 255u, 255u, 255u },   /* packed sha256 19e96c598e0c0e34 */
    { "ws_O_TimgXh_Ialp_cand", 0u, 48u, 0x2c3e5423u, { 0xbe90017eu, 0xbefe1d7eu, 0xbefd000cu, 0xbe82017eu }, { 0x020f0001u, 0x00000000u, 0x00000020u, 0x00000020u }, 1u, 0u, 8u, 10u },   /* packed sha256 8777f3dcd33532ed */
    { "ws_Q_TimgXh_Isrc_cand", 0u, 52u, 0x10d37dfdu, { 0xbe90017eu, 0xbefe1d7eu, 0xbefd000cu, 0xbe82017eu }, { 0x020f0001u, 0x00000000u, 0x00000020u, 0x00000020u }, 1u, 0u, 8u, 10u },   /* packed sha256 2492d54ad0db6416 */
    { "ws_R_TsplXh_Isrc_cand", 0u, 86u, 0xd79fb515u, { 0xbe90017eu, 0xbefe1d7eu, 0xbefd000cu, 0xbe82017eu }, { 0x020f0002u, 0x00000000u, 0x00000020u, 0x00000020u }, 2u, 0u, 8u, 10u },   /* packed sha256 548de95ca7f10a4b */
    { "ws_S_TimgXhu_Idfr_cand", 0u, 85u, 0xd0a62abeu, { 0xbe86017eu, 0xbefe1d7eu, 0xbefd000cu, 0xbe82017eu }, { 0x020f0001u, 0x00000000u, 0x00000020u, 0x00000020u }, 1u, 0u, 8u, 10u },   /* packed sha256 e4a9bee821360aa4 */
    { "ws_W_downsample_8_frag_lph_cand", 0u, 246u, 0xcdd8abb9u, { 0xbefd000cu, 0xbe82017eu, 0xbefe1d7eu, 0xce8f0002u }, { 0x020f0008u, 0x00000000u, 0x00000002u, 0x00000002u }, 1u, 0u, 4u, 6u },   /* packed sha256 2be4f4b321a3b95d */
    { "ws_X_narrow_blur_7_frag_lph_cand", 0u, 118u, 0xc5e80d66u, { 0xbe98017eu, 0xbefe1d7eu, 0xbefd000cu, 0xbe82017eu }, { 0x020f0002u, 0x00000000u, 0x00000002u, 0x00000002u }, 1u, 0u, 4u, 6u },   /* packed sha256 139af10654cf0a37 */
};
#define XLAT12_SHADER_ID_COUNT 77u
#define XLAT12_SHADER_ID_MAX_NDW 403u
#endif
