/* xlat12_shader_desc.h - GENERATED by tools/gfx-shader-desc.py; do not edit .
 * Per identity row (keyed by stage, ndw and fnv, exactly as xlat12_shader_id_match identifies code), whether the program
 * reads a resource DESCRIPTOR out of the client's data, read from its gfx1201 machine code: 1 NONE, 2 RING (vertex; its only
 * descriptor is the attribute-ring record at s[0:1]+0xa0, ours), 3 IMAGE (image_*: a T#/S# the client wrote), 4 BUFFER.
 * A program not listed is UNPROVEN (0). Only NONE and RING are descriptor-free; nothing on the Apple-frame path translates
 * a client's descriptor, so every other class refuses at the ladder's `descriptor` rung. Rows cover the shipped AND the
 * candidate identity tables, so either build of xlat12_ib.c finds its rows here; names appear in comments only.
 * inl_tex / inl_samp : a class-3 FRAGMENT row whose only T# (and S#) are user-data SGPRs it never
 * writes - the first user-data slot of each record, 0xff = not inline. An ANNOTATION: the class is unchanged, so the
 * rung still refuses such a row unless XLAT12_EXTRA_INLINE_DESC (default OFF) translated its records. */
#ifndef XLAT12_SHADER_DESC_H
#define XLAT12_SHADER_DESC_H
#include <stdint.h>
enum { XLAT12_DESCCLS_UNPROVEN = 0, XLAT12_DESCCLS_NONE = 1, XLAT12_DESCCLS_RING = 2, XLAT12_DESCCLS_IMAGE = 3,
       XLAT12_DESCCLS_BUFFER = 4 };
typedef struct { uint32_t stage, ndw, fnv; uint8_t cls, n_image, n_buffer, n_ring, inl_tex, inl_samp; } xlat12_shader_desc_row;
static const xlat12_shader_desc_row kXlat12ShaderDesc[] = {
    { 1u, 37u, 0x370518c0u, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   m2_tri_vs */
    { 0u, 9u, 0x8dbf3af3u, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   m2_tri_fs=m2_mvp_fs */
    { 1u, 55u, 0xe4bcf795u, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   m2_mvp_vs */
    { 1u, 72u, 0x22e24693u, 2u, 0u, 1u, 1u, 0xffu, 0xffu },   /* RING   m2_col_vs */
    { 0u, 32u, 0x6aa72846u, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   m2_col_fs */
    { 0u, 8u, 0xbbd550c3u, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   m2_half_fs */
    { 1u, 81u, 0x1bc1021du, 2u, 0u, 1u, 1u, 0xffu, 0xffu },   /* RING   SimpleVertex */
    { 0u, 47u, 0x0085850bu, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  SimpleTextureFragment */
    { 1u, 85u, 0x7ae1aa19u, 2u, 0u, 1u, 1u, 0xffu, 0xffu },   /* RING   UberCompositeVertex */
    { 0u, 50u, 0x4912346bu, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  UberCompositeFragment */
    { 1u, 60u, 0x2d808c40u, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   m2_tri_vs_rec */
    { 0u, 13u, 0x6088c6b1u, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   fca15jbebia3 */
    { 1u, 56u, 0x290f33cdu, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   plane__vertex */
    { 0u, 97u, 0x2d01b1fdu, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   path_distance_fragment */
    { 1u, 403u, 0x813e8fbcu, 2u, 0u, 3u, 3u, 0xffu, 0xffu },   /* RING   vkba6pa7jbebia3=vkba6pa8feba4 */
    { 0u, 12u, 0x61f10c0eu, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   path_interior_fragment */
    { 1u, 195u, 0xffb11885u, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   viba6la7jbebia3=viba6la8feba4 */
    { 0u, 50u, 0x08ec5c20u, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  fcja6ca7jbebia3 */
    { 0u, 63u, 0x625a0c18u, 3u, 2u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  fcjba5lca6jbebia3 */
    { 0u, 20u, 0xd8b9a500u, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   fca15ofeba4=fca15dheba4=fca16feba4=fca15ge2ba4 */
    { 0u, 240u, 0xf335713au, 3u, 5u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ffgea5cia6ofeb2a3 */
    { 1u, 90u, 0x55d9d6c6u, 2u, 0u, 1u, 1u, 0xffu, 0xffu },   /* RING   custom_effect_vertex */
    { 0u, 89u, 0xa77ba49du, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   path_exterior_fragment */
    { 1u, 298u, 0x104c320fu, 2u, 0u, 4u, 4u, 0xffu, 0xffu },   /* RING   vjba6la7dheba4=vjba6la8feba4 */
    { 0u, 42u, 0xa713654bu, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  fcfa6ca7dheba4=fcfa6ca8feba4 */
    { 0u, 71u, 0xbcf89610u, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  fpba14dheba4=fpba15feba4 */
    { 0u, 227u, 0x5e3c3eadu, 3u, 10u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  fpba2ia11bea6 */
    { 0u, 257u, 0x36072565u, 3u, 9u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  fpba2ma11bea6 */
    { 0u, 364u, 0xf9173ea5u, 3u, 10u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  fpba3ba10bea6 */
    { 0u, 106u, 0xcd6e4822u, 3u, 2u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  fpba2iba10bea6 */
    { 0u, 243u, 0xc42d7b66u, 3u, 2u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  foba3bia9bea6 */
    { 0u, 199u, 0xa9cf0ad1u, 3u, 5u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  fpba2eca10dheba4 */
    { 0u, 106u, 0xba291585u, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  fhe2ae2a2ca7ofeba4=fhe2ae2a2ca7ge2ba4 */
    { 1u, 139u, 0x589026c8u, 2u, 0u, 2u, 2u, 0xffu, 0xffu },   /* RING   vhe2ae2a2ca7ofeba4=vhe2ae2a2ca7ge2ba4 */
    { 0u, 57u, 0x312aed4fu, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  fcja6ca8feba4 */
    { 0u, 57u, 0xf6a95834u, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  fcjba5la8feba4 */
    { 0u, 100u, 0xc86e4470u, 3u, 2u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  fpba2eba11feba4 */
    { 0u, 11u, 0x2b838958u, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   ws_B_ColorFill */
    { 0u, 44u, 0xe2a4684fu, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   ws_C_Xh */
    { 0u, 83u, 0xd3d36bb9u, 3u, 4u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_D_GPUPass */
    { 1u, 96u, 0xc05bae9au, 2u, 0u, 1u, 1u, 0xffu, 0xffu },   /* RING   ws_E_ViewportToNDC=ws_F_ViewportToNDC */
    { 1u, 85u, 0xea6ac219u, 2u, 0u, 1u, 1u, 0xffu, 0xffu },   /* RING   ws_H_UberCompositeVertex */
    { 1u, 50u, 0xbf0feccau, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   RectPosTexFast_VS_gfx1201 */
    { 0u, 11u, 0x4da38bb8u, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   Const_PS_gfx1201 */
    { 0u, 8u, 0x859a7ae5u, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   Zero_PS_gfx1201 */
    { 0u, 12u, 0x70ee8613u, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   Const_PS_unorm16_gfx1201 */
    { 1u, 64u, 0xa74b276au, 2u, 0u, 1u, 1u, 0xffu, 0xffu },   /* RING   RectPosTexFast_VS_attr_gfx1201 */
    { 0u, 22u, 0x4376be3cu, 3u, 1u, 0u, 0u, 0x00u, 0x08u },   /* IMAGE  Tex_PS_gfx1201 INLINE T# s0 S# s8 */
    { 1u, 112u, 0x6e51013fu, 2u, 0u, 1u, 1u, 0xffu, 0xffu },   /* RING   ws_G_VfxXh */
    { 0u, 90u, 0x290890a3u, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   ws_AA_TimgXh_Icir */
    { 0u, 96u, 0xb5f82cf4u, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   ws_AB_TcimXh_Icir */
    { 1u, 101u, 0x0f5fd702u, 2u, 0u, 1u, 1u, 0xffu, 0xffu },   /* RING   ws_AC_variable_blur_vert_lph */
    { 0u, 199u, 0x3dbe4294u, 3u, 12u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_AD_narrow_blur_23_frag_lph */
    { 0u, 104u, 0xdbf619c2u, 3u, 4u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_AE_downsample_4_frag_lph */
    { 0u, 173u, 0x1051f3f6u, 3u, 13u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_AF_variable_blur_downsample_frag_lph */
    { 0u, 88u, 0xd7da98f7u, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   ws_AG_TimgXh_Icir */
    { 0u, 41u, 0xdb98e8d3u, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   ws_AH_Xh */
    { 0u, 119u, 0xae6c50d3u, 3u, 2u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_AI_TmuaXh_Isrc_Isrc */
    { 0u, 83u, 0x5a2f0cb6u, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_AJ_TcimXh_Isrc */
    { 0u, 88u, 0xaa26070eu, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_AK_TsplXh_Isrc */
    { 0u, 49u, 0xfd012f2fu, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_AL_TimgXh_Isrc */
    { 0u, 142u, 0x2519bf29u, 3u, 6u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_AM_narrow_blur_11_frag_lph */
    { 0u, 122u, 0x7b3a6dfeu, 3u, 2u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_AN_TmuaXh_Isrc_Isrc */
    { 0u, 168u, 0xb4fc3c24u, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_AO_TmuaXh_IsrcCcl_Icir */
    { 0u, 56u, 0xdd2af62du, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_AP_Tc4pXh_Idst */
    { 0u, 99u, 0x3a82204fu, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   ws_AQ_TcimXh_Icir */
    { 0u, 138u, 0xa5000f40u, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_AR_TcimBltnXh_Icir */
    { 0u, 120u, 0x71ab2622u, 3u, 2u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_AS_TbdsXh_Icir_Isrc */
    { 0u, 191u, 0xafe6b4ecu, 3u, 2u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_AT_TbdsXh_Isup_Isrc */
    { 0u, 86u, 0x0e94d9e2u, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_AU_TcimXh_Isrc */
    { 0u, 84u, 0x4c6d57deu, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_AV_BdsoXh */
    { 0u, 88u, 0x814caab6u, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_AW_BlsoXh */
    { 0u, 170u, 0x0e3b2d5au, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_AX_BvcmXh */
    { 0u, 279u, 0x46e5cc0eu, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_AY_TimgXh_IsrcN3Oc3mtc3nlnlnl */
    { 0u, 181u, 0xf27e9612u, 3u, 3u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_AZ_TimgBdrkXhn_IsrcCrd */
    { 0u, 120u, 0x8e1812e4u, 3u, 2u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_BA_TdfgXh_Isrc */
    { 0u, 207u, 0x6be37df7u, 3u, 2u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_BB_TbvcXh_Isrc_Isrc */
    { 0u, 60u, 0xd53dee91u, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_BC_TimgXh_IsrcCcl */
    { 0u, 1271u, 0x3858ea3au, 3u, 7u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_BD_glass_background_lph */
    { 0u, 1269u, 0x0ca63b3cu, 3u, 7u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_BE_glass_background_lph */
    { 1u, 112u, 0xf4d2f24eu, 2u, 0u, 2u, 2u, 0xffu, 0xffu },   /* RING   ws_I_VfxU10Xh */
    { 1u, 291u, 0xfa0982efu, 2u, 0u, 3u, 3u, 0xffu, 0xffu },   /* RING   ws_J_VfxXghb */
    { 1u, 126u, 0x0d6797cfu, 2u, 0u, 2u, 2u, 0xffu, 0xffu },   /* RING   ws_K_VfxU11Xh */
    { 0u, 46u, 0xe8ac2fb4u, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   ws_L_Xh */
    { 0u, 48u, 0x2c3e5423u, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_O_TimgXh_Ialp */
    { 0u, 46u, 0xebaa377cu, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_P_TimgXh_Ialp */
    { 0u, 52u, 0x10d37dfdu, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_Q_TimgXh_Isrc */
    { 0u, 86u, 0xd79fb515u, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_R_TsplXh_Isrc */
    { 0u, 85u, 0xd0a62abeu, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_S_TimgXhu_Idfr */
    { 0u, 103u, 0xdb5bb19du, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_T_Tc3sXhu_Idst */
    { 0u, 192u, 0x92c6ae13u, 3u, 2u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_U_TvcmXh_Isrc */
    { 1u, 124u, 0x78195974u, 2u, 0u, 2u, 2u, 0xffu, 0xffu },   /* RING   ws_V_VfxU10Xh */
    { 0u, 246u, 0xcdd8abb9u, 3u, 16u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_W_downsample_8_frag_lph */
    { 0u, 118u, 0xc5e80d66u, 3u, 4u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_X_narrow_blur_7_frag_lph */
    { 0u, 372u, 0x5276813bu, 3u, 2u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_Y_TkfhBvcmXh_Isrc */
    { 0u, 54u, 0xf91e4deeu, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_Z_TimgXh_Isrc */
    { 1u, 50u, 0x029d50b1u, 1u, 0u, 0u, 0u, 0xffu, 0xffu },   /* NONE   RectPosTexFast_VS_v3_gfx1201 */
    { 1u, 64u, 0x451698c1u, 2u, 0u, 1u, 1u, 0xffu, 0xffu },   /* RING   RectPosTexFast_VS_attr_v3_gfx1201 */
    { 0u, 42u, 0x1ddbfcadu, 3u, 1u, 0u, 0u, 0xffu, 0xffu },   /* IMAGE  ws_M_TextureCopy_cand */
};
#define XLAT12_SHADER_DESC_COUNT 99u
#endif
