/* xlat12_readset.h - GENERATED by tools/gfx-readset.py; do not edit (notes/design/D4-PRIME.md item 2).
 *
 * ONE ROW PER PROGRAM this tool was told to cover, keyed EXACTLY as xlat12_shader_ids.h keys code identity
 * (stage, ndw, fnv over the packed gfx1201 image). A program not listed here is UNKNOWN, never "declares no
 * pointers" - see src/xlat12/xlat12_abi_ptrs.h's banner: an invented zero-pointer row is the fail-OPEN
 * direction. `slot[]` is the first USER-DATA SLOT of every 64-bit pointer this program's OWN code
 * dereferences: for a FRAGMENT row (stage 0) this is the SGPR number unchanged; for a VERTEX row (stage 1)
 * it is the raw SGPR number MINUS 8 (D4-8, notes/design/D4-PRIME-FIXES.md), because these programs' vertex-
 * stage user data starts at s8 - xlat12_ib.c indexes the vertex stage's OWN 0-based user-data array with this
 * value, never the raw SGPR. Each row's printed comment below still names the RAW SGPR the disassembly
 * actually used, for traceability; only this numeric field carries the -8. Where a row's identity also has a
 * src/xlat12/xlat12_abi_ptrs.h entry (same ndw/fnv/stage), this tool ASSERTS the two slot lists agree and
 * refuses to write a header that disagrees with it. (The vertex-stage ring-offsets read at s0:s1 is OUR OWN
 * mapping, never counted - see this file's own generator banner.) `vector[]` is 0 for a scalar SMEM load
 * (s_load_ / s_buffer_load_) and 1 for a vector VMEM load (global_load_ / buffer_load_ / flat_load_);
 * `aspace[]` is the LLVM address space of that pointer's AIR argument (1 = device/global, 4 = constant),
 * 0xff when the program has no AIR/LLVM ABI to read (hand-written) or the pointer's argument could not be
 * matched. `inl_tex`/`inl_samp` and `desc_table` are the SAME classes tools/gfx-shader-desc.py emits into
 * xlat12_shader_desc.h (INLINE annotation vs. a class-19 descriptor-table path), reused here so the two
 * tables cannot disagree. XLAT12_READSET_PROOF_VERSION 2 (D4-PRIME-FIXES.md item 3(a)): `proof_depth1_data_
 * only` is 1 ONLY when EVERY scalar/vector LOAD's address derives directly from a user-data pointer plus a
 * constant or per-lane offset and no loaded value is ever used as an address, the program has NO atomic
 * instruction, and NO disqualifying STORE (global_store/flat_store/scratch_store/image_store always
 * disqualify; buffer_store disqualifies UNLESS tools/gfx-shader-desc.py's classifier proves the WHOLE
 * program is CLS_RING - i.e. its only store is OUR OWN attribute-ring write, never a client page).
 * CONDUCTOR-APPROVED EXCEPTION: this CLS_RING carve-out is the one case where 'NO STORES'
 * does not mean zero store instructions - the attribute ring is OUR OWN mapping (d_rings writes it, the
 * kext never treats it as client-owned), and gfx-shader-desc.py's classifier already proves the store IS
 * that mapping before this bit ever looks at it, so nothing here is asserted without that proof. Image
 * SAMPLE/LOAD operations no longer zero this bit by themselves - a program with a T#/S# resource read can
 * still get proof_depth1_data_only 1 (Tex_PS_gfx1201: its only image op reads an INLINE T#/S#, no other
 * load); `proof_images_inline` is a SECOND, INDEPENDENT bit answering a narrower question over the SAME
 * image ops: is every one of them reading its declared INLINE T#/S# (inl_tex/inl_samp) still unmodified
 * from user-data launch state, never a descriptor loaded from a table (desc_table)? 1 when every image op's
 * T#/S# is the unmodified inline slot, or trivially when the program has no image op at all; 0 for any
 * table-sourced descriptor, any traced mismatch, or a row that is not INLINE to begin with. The kext admits
 * a program only when proof_depth1_data_only && (no image op || proof_images_inline) - xlat12_ib.c's
 * d_readset_stage. */
#ifndef XLAT12_READSET_H
#define XLAT12_READSET_H
#include <stdint.h>
#define XLAT12_READSET_PROOF_VERSION 2u   /* D4-PRIME-FIXES.md item 3(a): pd1 no longer zeroed by an image
                                             op alone (pii covers those); pd1 now also requires NO STORES */
#define XLAT12_READSET_PTR_MAX 5u
typedef struct {
    const char *name; uint32_t stage, ndw, fnv;
    uint8_t nptr, slot[XLAT12_READSET_PTR_MAX], vector[XLAT12_READSET_PTR_MAX], aspace[XLAT12_READSET_PTR_MAX];
    uint8_t inl_tex, inl_samp, desc_table, proof_depth1_data_only, proof_images_inline;
} xlat12_readset_row;
static const xlat12_readset_row kXlat12Readset[] = {
    { "ws_B_ColorFill", 0u, 11u, 0x2b838958u, 1u,
      { 2u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /*: PS slot 2 (s2:s3), s_load_b128 out of WindowServer's memory - the fill colour
     * pointers: s2:3 scalar aspace 0x1 <- s_load_b128 s[0:3], s[2:3], 0x0
     * proof: all 1 load(s) trace directly to a user-data SGPR pair plus constant/lane offset
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: re/pc-26.6.2/xlat/windowserver/work/B/ColorFill.abi.json, re/pc-26.6.2/xlat/windowserver/work/B/ColorFill.opt.ll (address space) */
    { "Const_PS_gfx1201", 0u, 11u, 0x4da38bb8u, 0u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x00u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /* STRICT-OK NONE: a positive '0 pointers' row, held only while the code proves no memory read at all
     * pointers: none
     * proof: zero loads: the program performs no data-only memory read (any image op is covered separately by proof_images_inline)
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "Const_PS_unorm16_gfx1201", 0u, 12u, 0x70ee8613u, 0u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x00u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /* COVERAGE TASK S4 (notes/design/MIB-COMMIT.md): the UNORM16 sibling of Const_PS_gfx1201 (Apple's gShaderCode_gfx10_Const_PS[patch 5@4]) - same source (s0..s3), same STRICT-OK NONE proof, only the export pack differs
     * pointers: none
     * proof: zero loads: the program performs no data-only memory read (any image op is covered separately by proof_images_inline)
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "Tex_PS_gfx1201", 0u, 22u, 0x4376be3cu, 0u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x00u, 0x00u, 0x00u, 0x00u, 0x00u },
      0x00u, 0x08u, 0u, 1u, 1u },
    /* xlat12_shader_desc.h: INLINE T# s0 S# s8 - no descriptor-table path
     * pointers: none
     * proof: zero loads: the program performs no data-only memory read (any image op is covered separately by proof_images_inline)
     * proof_images_inline: every image op's T#/S# is exactly the row's declared unmodified inline slot
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "RectPosTexFast_VS_gfx1201", 1u, 50u, 0xbf0feccau, 0u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x00u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /* STRICT-OK NONE, the only STRICT-OK vertex row, and ours
     * pointers: none
     * proof: zero loads: the program performs no data-only memory read (any image op is covered separately by proof_images_inline)
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "RectPosTexFast_VS_attr_gfx1201", 1u, 64u, 0xa74b276au, 0u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x00u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /*/design/D4-PRIME.md item 2: the attribute-ring VS; its one load is the ring-offsets read, not a client pointer
     * pointers: none
     * proof: all 1 load(s) trace directly to a user-data SGPR pair plus constant/lane offset
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_G_VfxXh", 1u, 112u, 0x6e51013fu, 2u,
      { 4u, 6u, 0u, 0u, 0u }, { 0u, 1u, 0u, 0u, 0u }, { 0x04u, 0x01u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /* D4-PRIME item 2 'G' - tools/gfx-shader-ids.py 0.0.429 comment: shipped for Family A coverage (arm32 F48/F75/F159)
     * pointers: s12:13 scalar aspace 0x4 <- s_load_b512 s[8:23], s[12:13], 0x0; s14:15 vector aspace 0x1 <- global_load_b128 v[0:3], v[5:6], off
     * proof: all 4 load(s) trace directly to a user-data SGPR pair plus constant/lane offset
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: re/pc-26.6.2/xlat/windowserver-766-all/work/G/VfxXh.abi.json, re/pc-26.6.2/xlat/windowserver-766-all/work/G/VfxXh.opt.ll (address space) */
    { "ws_I_VfxU10Xh", 1u, 112u, 0xf4d2f24eu, 3u,
      { 4u, 6u, 8u, 0u, 0u }, { 0u, 0u, 1u, 0u, 0u }, { 0x04u, 0x04u, 0x01u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /* D4-PRIME item 2 'I' - tools/gfx-shader-ids.py-PLAN S1 comment (key 0xa4fd87c27c05c862, 285 frames)
     * pointers: s12:13 scalar aspace 0x4 <- s_load_b512 s[16:31], s[12:13], 0x0; s14:15 scalar aspace 0x4 <- s_load_b128 s[8:11], s[14:15], 0x0; s16:17 vector aspace 0x1 <- global_load_b128 v[0:3], v[4:5], off
     * proof: all 6 load(s) trace directly to a user-data SGPR pair plus constant/lane offset
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/I/VfxU10Xh.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/I/VfxU10Xh.opt.ll (address space) */
    { "ws_V_VfxU10Xh", 1u, 124u, 0x78195974u, 3u,
      { 4u, 6u, 8u, 0u, 0u }, { 0u, 0u, 1u, 0u, 0u }, { 0x04u, 0x04u, 0x01u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /* D4-PRIME item 2 'V' - tools/gfx-shader-ids.py-PLAN S1 comment (key 0x1906fe39ce165c44, 46 frames)
     * pointers: s12:13 scalar aspace 0x4 <- s_load_b512 s[16:31], s[12:13], 0x0; s14:15 scalar aspace 0x4 <- s_load_b128 s[8:11], s[14:15], 0x0; s16:17 vector aspace 0x1 <- global_load_b128 v[0:3], v[4:5], off
     * proof: all 6 load(s) trace directly to a user-data SGPR pair plus constant/lane offset
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/V/VfxU10Xh.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/V/VfxU10Xh.opt.ll (address space) */
    { "ws_L_Xh", 0u, 46u, 0xe8ac2fb4u, 0u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x00u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /* D4-PRIME item 2, Family A's Xh fragment (notes/design/MIB-COMMIT.md: 'L at 0x400595a00')
     * pointers: none
     * proof: zero loads: the program performs no data-only memory read (any image op is covered separately by proof_images_inline)
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/L/Xh.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/L/Xh.opt.ll (address space) */
    { "ws_P_TimgXh_Ialp", 0u, 46u, 0xebaa377cu, 1u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* D4-PRIME item 2, Family A's second Xh fragment - tools/gfx-shader-ids.py 0.0.429 comment ('P...joins it...a Family-A frame...binding either [G or P] refused NO-IDENTITY')
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[2:3], s[0:1], 0x10
     * proof: load not depth-1/data-only: s_load_b128 s[12:15], s[2:3], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s10
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/P/TimgXh_Ialp.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/P/TimgXh_Ialp.opt.ll (address space) */
    { "ws_C_Xh", 0u, 44u, 0xe2a4684fu, 0u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x00u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /* D4-PRIME-FIXES.md item 3(b): a LUT producer's Xh fragment (tools/m4-xlat/ws-programs.tsv label C) - zero memory instructions, NONE class, STRICT-OK by the same shape as Const_PS
     * pointers: none
     * proof: zero loads: the program performs no data-only memory read (any image op is covered separately by proof_images_inline)
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: re/pc-26.6.2/xlat/windowserver/work/C/Xh.abi.json, re/pc-26.6.2/xlat/windowserver/work/C/Xh.opt.ll (address space) */
    { "ws_AA_TimgXh_Icir", 0u, 90u, 0x290890a3u, 0u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x00u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /* D4-PRIME-FIXES.md item 3(b): F48's AA fragment (ws-programs-r2.tsv, WS_SHIP_LABELS) - zero memory instructions, NONE class, STRICT-OK
     * pointers: none
     * proof: zero loads: the program performs no data-only memory read (any image op is covered separately by proof_images_inline)
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/AA/TimgXh_Icir.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/AA/TimgXh_Icir.opt.ll (address space) */
    { "ws_AG_TimgXh_Icir", 0u, 88u, 0xd7da98f7u, 0u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x00u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /* D4-PRIME-FIXES.md item 3(b): F48's AG fragment (ws-programs-r2.tsv, WS_SHIP_LABELS) - zero memory instructions, NONE class, STRICT-OK
     * pointers: none
     * proof: zero loads: the program performs no data-only memory read (any image op is covered separately by proof_images_inline)
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/AG/TimgXh_Icir.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/AG/TimgXh_Icir.opt.ll (address space) */
    { "ws_H_UberCompositeVertex", 1u, 85u, 0xea6ac219u, 2u,
      { 4u, 6u, 0u, 0u, 0u }, { 0u, 1u, 0u, 0u, 0u }, { 0x04u, 0x01u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /* D4-PRIME-FIXES.md item 3(b): the SkyLight UberComposite pair's vertex half (ws-programs.tsv label H) - CLS_RING (its one store is the proven attribute-ring write), both loads trace to P(s12:s13)/P(s14:s15)
     * pointers: s12:13 scalar aspace 0x4 <- s_load_b256 s[16:23], s[12:13], 0x0; s14:15 vector aspace 0x1 <- global_load_b128 v[0:3], v[0:1], off
     * proof: all 4 load(s) trace directly to a user-data SGPR pair plus constant/lane offset
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: re/pc-26.6.2/xlat/windowserver/work/H/UberCompositeVertex.abi.json, re/pc-26.6.2/xlat/windowserver/work/H/UberCompositeVertex.opt.ll (address space) */
    { "UberCompositeVertex", 1u, 85u, 0x7ae1aa19u, 2u,
      { 4u, 6u, 0u, 0u, 0u }, { 0u, 1u, 0u, 0u, 0u }, { 0x04u, 0x01u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /* D4-PRIME-FIXES.md item 3(b): the SAME UberComposite vertex program under g2's OWN argument order (re/graphics/g2/pairs/uber) - a separate code identity, same shape
     * pointers: s12:13 scalar aspace 0x4 <- s_load_b256 s[16:23], s[12:13], 0x0; s14:15 vector aspace 0x1 <- global_load_b128 v[0:3], v[0:1], off
     * proof: all 4 load(s) trace directly to a user-data SGPR pair plus constant/lane offset
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: re/graphics/g2/pairs/uber/UberCompositeVertex.abi.json, re/graphics/g2/pairs/uber/UberCompositeVertex.opt.ll (address space) */
    { "ws_AH_Xh", 0u, 41u, 0xdb98e8d3u, 0u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x00u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /* COVERAGE TASK S5: F48's third Xh fragment (tools/gfx-shader-ids.py WS_SHIP_LABELS comment) - zero memory instructions, NONE class, STRICT-OK by the same shape as ws_C_Xh/ws_L_Xh
     * pointers: none
     * proof: zero loads: the program performs no data-only memory read (any image op is covered separately by proof_images_inline)
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/AH/Xh.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/AH/Xh.opt.ll (address space) */
    { "ws_AJ_TcimXh_Isrc", 0u, 83u, 0x5a2f0cb6u, 1u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* COVERAGE TASK S5: F48's TcimXh_Isrc fragment - IMAGE class, the same code shape as ws_P_TimgXh_Ialp/ws_Z_TimgXh_Isrc (shared 4-dword head), so the same class-19 descriptor-table proof applies
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[2:3], s[0:1], 0x10
     * proof: load not depth-1/data-only: s_load_b128 s[12:15], s[2:3], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s10
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/AJ/TcimXh_Isrc.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/AJ/TcimXh_Isrc.opt.ll (address space) */
    { "ws_AK_TsplXh_Isrc", 0u, 88u, 0xaa26070eu, 1u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* COVERAGE TASK S5: F48's second TsplXh_Isrc fragment - IMAGE class, same shape as ws_AJ_TcimXh_Isrc/ws_P_TimgXh_Ialp
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[2:3], s[0:1], 0x10
     * proof: load not depth-1/data-only: s_load_b128 s[12:15], s[2:3], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s10
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/AK/TsplXh_Isrc.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/AK/TsplXh_Isrc.opt.ll (address space) */
    { "ws_AL_TimgXh_Isrc", 0u, 49u, 0xfd012f2fu, 1u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* COVERAGE TASK S5: F48's third TimgXh_Isrc fragment - IMAGE class, same shape as ws_AJ_TcimXh_Isrc/ws_P_TimgXh_Ialp
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[2:3], s[0:1], 0x10
     * proof: load not depth-1/data-only: s_load_b128 s[12:15], s[2:3], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s10
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/AL/TimgXh_Isrc.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/AL/TimgXh_Isrc.opt.ll (address space) */
    { "ws_AM_narrow_blur_11_frag_lph", 0u, 142u, 0x2519bf29u, 3u,
      { 0u, 8u, 10u, 0u, 0u }, { 0u, 0u, 1u, 0u, 0u }, { 0x01u, 0x04u, 0x04u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* COVERAGE TASK S5 PART 2a: F48's own 0x40002b800, identified by arm32's driver-log upload census (never a capture region) and CONFIRMED against WindowServer's own Metal function cache - IMAGE class, the same class-19 table shape as its family AD/AE
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[12:13], s[0:1], 0x10; s8:9 scalar aspace 0x4 <- s_load_b64 s[26:27], s[8:9], 0x10; s10:11 vector aspace 0x4 <- global_load_d16_b16 v4, v4, s[10:11]
     * proof: load not depth-1/data-only: s_load_b128 s[20:23], s[12:13], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s6
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/AM/narrow_blur_11_frag_lph.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/AM/narrow_blur_11_frag_lph.opt.ll (address space) */
    { "ws_AE_downsample_4_frag_lph", 0u, 104u, 0xdbf619c2u, 3u,
      { 0u, 8u, 10u, 0u, 0u }, { 0u, 0u, 1u, 0u, 0u }, { 0x01u, 0x04u, 0x04u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* build 0.0.447 (MIB-A1-PATH.md Q4 step 2): AM's family sibling - IMAGE class, the SAME class-19 table shape as ws_AM_narrow_blur_11_frag_lph (desc table + two buffer pointers beyond the table's own class-1/class-2 texture/sampler index words), CONFIRMED against its own ABI JSON and gfx1201 disassembly
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[2:3], s[0:1], 0x10; s8:9 scalar aspace 0x4 <- s_load_b256 s[12:19], s[8:9], 0x0; s10:11 vector aspace 0x4 <- global_load_d16_b16 v10, v10, s[10:11]
     * proof: load not depth-1/data-only: s_load_b128 s[0:3], s[2:3], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s6
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/AE/downsample_4_frag_lph.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/AE/downsample_4_frag_lph.opt.ll (address space) */
    { "ws_AD_narrow_blur_23_frag_lph", 0u, 199u, 0x3dbe4294u, 3u,
      { 0u, 8u, 10u, 0u, 0u }, { 0u, 0u, 1u, 0u, 0u }, { 0x01u, 0x04u, 0x04u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* build 0.0.447 (MIB-A1-PATH.md Q4 step 2): AM's family sibling - IMAGE class, the SAME class-19 table shape as ws_AM_narrow_blur_11_frag_lph/ws_AE_downsample_4_frag_lph, CONFIRMED against its own ABI JSON and gfx1201 disassembly
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[20:21], s[0:1], 0x10; s8:9 scalar aspace 0x4 <- s_load_b128 s[0:3], s[8:9], 0x20; s10:11 vector aspace 0x4 <- global_load_d16_b16 v4, v4, s[10:11]
     * proof: load not depth-1/data-only: s_load_b128 s[36:39], s[20:21], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s6
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/AD/narrow_blur_23_frag_lph.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/AD/narrow_blur_23_frag_lph.opt.ll (address space) */
    { "ws_K_VfxU11Xh", 1u, 126u, 0x0d6797cfu, 3u,
      { 4u, 6u, 8u, 0u, 0u }, { 0u, 0u, 1u, 0u, 0u }, { 0x04u, 0x04u, 0x01u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /* COVERAGE TASK S5 PART 2b (design notes/design/S5-COVERAGE-PART2.md): F48's last real gap (IB0 seg1), closed by a PER-KEY given varying layout (tools/air-gfx.py varying_layout, tools/m4-xlat/ws_programs.py VARYING_LAYOUTS) - RING class, the same attribute-ring shape as ws_I_VfxU10Xh/ws_V_VfxU10Xh, unaffected by the packing (only the STORE COUNT changes, 2 not 3, since two of K's three vertex outputs share one packed param)
     * pointers: s12:13 scalar aspace 0x4 <- s_load_b512 s[16:31], s[12:13], 0x0; s14:15 scalar aspace 0x4 <- s_load_b256 s[8:15], s[14:15], 0x0; s16:17 vector aspace 0x1 <- global_load_b128 v[0:3], v[4:5], off
     * proof: all 6 load(s) trace directly to a user-data SGPR pair plus constant/lane offset
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/K/VfxU11Xh.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/K/VfxU11Xh.opt.ll (address space) */
    { "ws_AI_TmuaXh_Isrc_Isrc", 0u, 119u, 0xae6c50d3u, 2u,
      { 0u, 4u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x04u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* COVERAGE TASK S5 PART 2c: class 11 in air-gfx.py's _fragment_apple_layout - a POINTER TO A SAMPLER-INDEX TABLE at s4:s5 (apiSlot 0), the class-11 word AI's own record carries in place of any class-2 sampler word. IMAGE class, unchanged by class 11 (it still samples via image_sample).
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[14:15], s[0:1], 0x0; s4:5 scalar aspace 0x4 <- s_load_b128 s[20:23], s[4:5], 0x0
     * proof: load not depth-1/data-only: s_load_b128 s[24:27], s[6:7], 0x0 -> base *[P(s0:s1)+0x10] terms 16*M[P(s4:s5)+0x0]
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/AI/TmuaXh_Isrc_Isrc.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/AI/TmuaXh_Isrc_Isrc.opt.ll (address space) */
    { "ws_AN_TmuaXh_Isrc_Isrc", 0u, 122u, 0x7b3a6dfeu, 2u,
      { 0u, 4u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x04u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* COVERAGE TASK S5 PART 2c: a second compile of AI's own function (AIR module ws_04b040), udes word-for-word identical to AI's (the same class-11 sampler table at s4:s5) - IMAGE class, same shape as AI.
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[14:15], s[0:1], 0x0; s4:5 scalar aspace 0x4 <- s_load_b128 s[20:23], s[4:5], 0x0
     * proof: load not depth-1/data-only: s_load_b128 s[24:27], s[6:7], 0x0 -> base *[P(s0:s1)+0x10] terms 16*M[P(s4:s5)+0x0]
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/AN/TmuaXh_Isrc_Isrc.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/AN/TmuaXh_Isrc_Isrc.opt.ll (address space) */
    { "ws_AO_TmuaXh_IsrcCcl_Icir", 0u, 168u, 0xb4fc3c24u, 2u,
      { 0u, 4u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x04u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* COVERAGE TASK S5 PART 2c: K's third named F48 partner - a distinct function (AIR module ws_065a80) needing ONLY the packed varying layout, not class 11 (its own record's udes carry a plain class-2 sampler word). IMAGE class, same class-19 table shape as ws_AJ/ws_AK/ws_AL/ws_P.
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[12:13], s[0:1], 0x10; s4:5 scalar aspace 0x4 <- s_load_b128 s[4:7], s[4:5], 0xc0
     * proof: load not depth-1/data-only: s_load_b128 s[20:23], s[12:13], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s10
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/AO/TmuaXh_IsrcCcl_Icir.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/AO/TmuaXh_IsrcCcl_Icir.opt.ll (address space) */
    { "ws_O_TimgXh_Ialp", 0u, 48u, 0x2c3e5423u, 1u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* COVERAGE TASK S6 (decide44 survey): a further compile of ws_P_TimgXh_Ialp's/ws_AL's function - IMAGE class, same class-19 table shape as ws_P_TimgXh_Ialp/ws_AL_TimgXh_Isrc, CONFIRMED against its own ABI JSON
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[2:3], s[0:1], 0x10
     * proof: load not depth-1/data-only: s_load_b128 s[12:15], s[2:3], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s10
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_Q_TimgXh_Isrc", 0u, 52u, 0x10d37dfdu, 1u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* COVERAGE TASK S6 (decide44 survey): a further compile of ws_AL_TimgXh_Isrc's/ws_Z's function - IMAGE class, same class-19 table shape as ws_AL_TimgXh_Isrc, CONFIRMED against its own ABI JSON
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[2:3], s[0:1], 0x10
     * proof: load not depth-1/data-only: s_load_b128 s[12:15], s[2:3], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s10
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_R_TsplXh_Isrc", 0u, 86u, 0xd79fb515u, 1u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* COVERAGE TASK S6 (decide44 survey): a further compile of ws_AK_TsplXh_Isrc's function - IMAGE class, same class-19 table shape as ws_AK_TsplXh_Isrc, CONFIRMED against its own ABI JSON
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[2:3], s[0:1], 0x10
     * proof: load not depth-1/data-only: s_load_b128 s[12:15], s[2:3], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s10
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_S_TimgXhu_Idfr", 0u, 85u, 0xd0a62abeu, 2u,
      { 0u, 4u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x04u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* COVERAGE TASK S6 (decide44 survey): a new function of the P/AJ/AK/AL/O/Q/R shape - IMAGE class, table s0:s1/buf1 s4:s5/buf2 s6:s7/tex s8:9/samp s10:11, and the only one of this batch whose compiled body dereferences buf1 directly (`s_load_b128 s[0:3], s[4:5], 0x0`, CONFIRMED by llvm-objdump --mcpu=gfx1201)
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[2:3], s[0:1], 0x10; s4:5 scalar aspace 0x4 <- s_load_b128 s[0:3], s[4:5], 0x0
     * proof: load not depth-1/data-only: s_load_b128 s[0:3], s[2:3], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s10
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_W_downsample_8_frag_lph", 0u, 246u, 0xcdd8abb9u, 3u,
      { 0u, 8u, 10u, 0u, 0u }, { 0u, 0u, 1u, 0u, 0u }, { 0x01u, 0x04u, 0x04u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* COVERAGE TASK S6 (decide44 survey): a further compile of the ws_AE_downsample_4_frag_lph/ws_AM/ws_AD blur family - IMAGE class, same class-19 table shape (table s0:s1, tex s4:5, samp s6:7, buf1 s8:9, buf2 s10:11), CONFIRMED by llvm-objdump: `s_load_b256 s[20:27], s[8:9], 0x0` and `global_load_d16_b16 v34, v34, s[10:11]`
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[2:3], s[0:1], 0x10; s8:9 scalar aspace 0x4 <- s_load_b256 s[20:27], s[8:9], 0x0; s10:11 vector aspace 0x4 <- global_load_d16_b16 v34, v34, s[10:11]
     * proof: load not depth-1/data-only: s_load_b128 s[0:3], s[2:3], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s6
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_X_narrow_blur_7_frag_lph", 0u, 118u, 0xc5e80d66u, 3u,
      { 0u, 8u, 10u, 0u, 0u }, { 0u, 0u, 1u, 0u, 0u }, { 0x01u, 0x04u, 0x04u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* COVERAGE TASK S6 (decide44 survey): a further compile of the same blur family (ws_AM_narrow_blur_11_frag_lph's own shape) - IMAGE class, CONFIRMED by llvm-objdump: `s_load_b64 s[4:5], s[8:9], 0x40` and `global_load_d16_b16 v4, v4, s[10:11]`
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[12:13], s[0:1], 0x10; s8:9 scalar aspace 0x4 <- s_load_b128 s[0:3], s[8:9], 0x0; s10:11 vector aspace 0x4 <- global_load_d16_b16 v4, v4, s[10:11]
     * proof: load not depth-1/data-only: s_load_b128 s[20:23], s[12:13], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s6
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_T_Tc3sXhu_Idst", 0u, 103u, 0xdb5bb19du, 2u,
      { 0u, 4u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x04u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* COVERAGE TASK S6 batch 1 (notes/design/S6-COVERAGE-PART2.md Q4): the class-19 'no sampler' table shape - table s0 (class 19), buffer s4 (class 3), texture index s6 (class 1), no class-2 word. IMAGE class, table-indirected, same reasoning as P/AJ/AK/AL - CONFIRMED against its own ABI JSON and gfx1201 disassembly.
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[0:1], s[0:1], 0x0; s4:5 scalar aspace 0x4 <- s_load_b128 s[0:3], s[4:5], 0xd0
     * proof: load not depth-1/data-only: s_load_b256 s[8:15], s[0:1], 0x0 -> base *[P(s0:s1)+0x0] terms 32*s6
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_AP_Tc4pXh_Idst", 0u, 56u, 0xdd2af62du, 2u,
      { 0u, 4u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x04u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* S6-COVERAGE-PART2.md Q5/Q8 batch 2: T's own no-sampler shape (table s0, buffer s4, texture index s6, no class-2 word) - CONFIRMED against its own ABI JSON.
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[0:1], s[0:1], 0x0; s4:5 scalar aspace 0x4 <- s_load_b256 s[8:15], s[4:5], 0xd0
     * proof: load not depth-1/data-only: s_load_b256 s[8:15], s[0:1], 0x0 -> base *[P(s0:s1)+0x0] terms 32*s6
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_AQ_TcimXh_Icir", 0u, 99u, 0x3a82204fu, 0u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x00u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /* S6-COVERAGE-PART2.md Q1/Q8 batch 2: TcimXh_Icir's second Apple record (AB's own function ws_068780) - AB has NO descriptor table at all (NONE class), so this row characterises the same NONE shape, native-fast-math opted in.
     * pointers: none
     * proof: zero loads: the program performs no data-only memory read (any image op is covered separately by proof_images_inline)
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_AR_TcimBltnXh_Icir", 0u, 138u, 0xa5000f40u, 1u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* S6-COVERAGE-PART2.md Q1/Q8 batch 2: T's no-sampler shape (table s0, buffer s4, texture index s6, no class-2 word), native-fast-math opted in - CONFIRMED against its own ABI JSON.
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[0:1], s[0:1], 0x0
     * proof: load not depth-1/data-only: s_load_b256 s[0:7], s[0:1], 0x0 -> base *[P(s0:s1)+0x0] terms 32*s6
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_AS_TbdsXh_Icir_Isrc", 0u, 120u, 0x71ab2622u, 1u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* S6-COVERAGE-PART2.md Q1/Q2/Q8 batch 2, AC's fragment partner: table s0 (class 19), TWO textures s8/s10 (class 3, table-indirected), direct sampler s12 (class 2) - P/AJ/AK/AL's own shape with a second texture, native-fast-math opted in, AC's producer-traced varying layout - CONFIRMED against its own ABI JSON.
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[4:5], s[0:1], 0x0
     * proof: load not depth-1/data-only: s_load_b128 s[24:27], s[0:1], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s12
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_AT_TbdsXh_Isup_Isrc", 0u, 191u, 0xafe6b4ecu, 2u,
      { 0u, 4u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x04u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* S6-COVERAGE-PART2.md Q1/Q2/Q8 batch 2, AC's other fragment partner: same shape as AS (table s0, two textures class 3, direct sampler class 2), native-fast-math opted in, AC's producer-traced varying layout - CONFIRMED against its own ABI JSON.
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[6:7], s[0:1], 0x0; s4:5 scalar aspace 0x4 <- s_load_b128 s[4:7], s[4:5], 0x0
     * proof: load not depth-1/data-only: s_load_b128 s[8:11], s[0:1], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s12
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_AU_TcimXh_Isrc", 0u, 86u, 0x0e94d9e2u, 1u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* S6-COVERAGE-PART2.md Q6/Q8 batch 2: Q/R/S/AJ's own shape (table s0, one texture class 3, direct sampler class 2) - a SEPARATE Apple record from AJ's (different L and record_sha256, CONFIRMED by this file's own apple_records(), so it needs its own row even though it shares AJ's function/AIR module).
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[2:3], s[0:1], 0x10
     * proof: load not depth-1/data-only: s_load_b128 s[12:15], s[2:3], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s10
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_AV_BdsoXh", 0u, 84u, 0x4c6d57deu, 1u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* S6-COVERAGE-PART2.md Q5/Q8 batch 3: T's own no-sampler shape - CONFIRMED against its own ABI JSON.
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[0:1], s[0:1], 0x0
     * proof: load not depth-1/data-only: s_load_b256 s[0:7], s[0:1], 0x0 -> base *[P(s0:s1)+0x0] terms 32*s6
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_AW_BlsoXh", 0u, 88u, 0x814caab6u, 1u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* S6-COVERAGE-PART2.md Q5/Q8 batch 3 (famcov defect D1: this is 0x400607500's captured body, not the census's 'ws_X_narrow_blur_7'): T's own no-sampler shape - CONFIRMED against its own ABI JSON.
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[0:1], s[0:1], 0x0
     * proof: load not depth-1/data-only: s_load_b256 s[0:7], s[0:1], 0x0 -> base *[P(s0:s1)+0x0] terms 32*s6
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_AX_BvcmXh", 0u, 170u, 0x0e3b2d5au, 2u,
      { 0u, 4u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x04u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* S6-COVERAGE-PART2.md Q5/Q8 batch 3: T's own no-sampler shape - CONFIRMED against its own ABI JSON.
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[0:1], s[0:1], 0x0; s4:5 scalar aspace 0x4 <- s_load_b256 s[8:15], s[4:5], 0x60
     * proof: load not depth-1/data-only: s_load_b256 s[8:15], s[0:1], 0x0 -> base *[P(s0:s1)+0x0] terms 32*s6
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_AY_TimgXh_IsrcN3Oc3mtc3nlnlnl", 0u, 279u, 0x46e5cc0eu, 2u,
      { 0u, 10u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x04u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* S6-COVERAGE-PART2.md Q5/Q8 batch 3: Q/R/S/AJ's own shape (table s0, one texture class 3, direct sampler class 2) - CONFIRMED against its own ABI JSON.
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[2:3], s[0:1], 0x10; s10:11 scalar aspace 0x4 <- s_load_b64 s[0:1], s[10:11], 0x20
     * proof: load not depth-1/data-only: s_load_b128 s[16:19], s[2:3], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s12
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_AZ_TimgBdrkXhn_IsrcCrd", 0u, 181u, 0xf27e9612u, 3u,
      { 0u, 4u, 10u, 0u, 0u }, { 0u, 0u, 1u, 0u, 0u }, { 0x01u, 0x04u, 0x04u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* S6-COVERAGE-PART2.md Q5/Q8 batch 3, design/NO-SAMPLER-CLASS10.md section 2 (class 10): table s0 (class 19), a class-10 texture-index-table pointer s4 (NOT class 1 - CONFIRMED, this program's udes carry no class-1 word at all), buffers s6/s8/s10 (class 3), direct sampler s12 (class 2), native-fast-math (fast_rsqrt) opted in - CONFIRMED against its own ABI JSON, which now carries a texture_table entry (tools/air-gfx.py _fragment_apple_layout's new class-10 branch).
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[6:7], s[0:1], 0x10; s4:5 scalar aspace 0x4 <- s_load_b32 s14, s[4:5], 0x18; s10:11 vector aspace 0x4 <- global_load_d16_b16 v8, v8, s[10:11]
     * proof: load not depth-1/data-only: s_load_b128 s[4:7], s[4:5], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s12
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_BA_TdfgXh_Isrc", 0u, 120u, 0x8e1812e4u, 3u,
      { 0u, 4u, 6u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x04u, 0x04u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* S6-COVERAGE-PART2.md Q5/Q8 batch 4: AI's own class-11 shape (table s0, TWO textures s10/s12 class 3 (table-indirected), class-11 sampler-index-table pointer s4, apiSlot 0) - CONFIRMED against its own ABI JSON.
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[8:9], s[0:1], 0x10; s4:5 scalar aspace 0x4 <- s_load_b64 s[4:5], s[4:5], 0x0; s6:7 scalar aspace 0x4 <- s_load_b128 s[16:19], s[6:7], 0xd0
     * proof: load not depth-1/data-only: s_load_b128 s[8:11], s[8:9], 0x0 -> base *[P(s0:s1)+0x10] terms 16*M[P(s4:s5)+0x0]
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_BB_TbvcXh_Isrc_Isrc", 0u, 207u, 0x6be37df7u, 3u,
      { 0u, 4u, 6u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x04u, 0x04u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* S6-COVERAGE-PART2.md Q1/Q2/Q5/Q8 batch 4, AC's THIRD fragment draw partner at F00044 0x400603900 (pairs.py): AI's own class-11 shape (same as BA), AC's own producer-traced varying layout (same reasoning as AS/AT) - CONFIRMED against its own ABI JSON.
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[4:5], s[0:1], 0x10; s4:5 scalar aspace 0x4 <- s_load_b128 s[20:23], s[4:5], 0x0; s6:7 scalar aspace 0x4 <- s_load_b256 s[8:15], s[6:7], 0xd0
     * proof: load not depth-1/data-only: s_load_b128 s[0:3], s[0:1], 0x0 -> base *[P(s0:s1)+0x10] terms 16*M[P(s4:s5)+0x0]
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_BC_TimgXh_IsrcCcl", 0u, 60u, 0xd53dee91u, 2u,
      { 0u, 4u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x04u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* S6-COVERAGE-PART2.md Q5/Q8 batch 4: AO's own shape (table s0, one texture class 3, direct sampler class 2, no class-11 word) - CONFIRMED against its own ABI JSON.
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[2:3], s[0:1], 0x10; s4:5 scalar aspace 0x4 <- s_load_b128 s[12:15], s[4:5], 0xc0
     * proof: load not depth-1/data-only: s_load_b128 s[16:19], s[2:3], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s10
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "ws_U_TvcmXh_Isrc", 0u, 192u, 0x92c6ae13u, 2u,
      { 0u, 4u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x04u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* COORDINATOR ADDITION (notes/design/LOGIN-SCREEN-PATH.md item (iii)): login-screen foreground family 'a' (1152|14944) - IMAGE class, table-indirected, CONFIRMED against its own ABI JSON (re/pc-26.6.2/xlat/windowserver-r2/work/U/TvcmXh_Isrc).
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[2:3], s[0:1], 0x0; s4:5 scalar aspace 0x4 <- s_load_b256 s[8:15], s[4:5], 0xd0
     * proof: load not depth-1/data-only: s_load_b256 s[16:23], s[8:9], 0x0 -> base *[P(s0:s1)+0x0] terms 32*s8
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/U/TvcmXh_Isrc.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/U/TvcmXh_Isrc.opt.ll (address space) */
    { "ws_Y_TkfhBvcmXh_Isrc", 0u, 372u, 0x5276813bu, 2u,
      { 0u, 4u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x04u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* COORDINATOR ADDITION (notes/design/LOGIN-SCREEN-PATH.md item (iii)): login-screen foreground family 'a' - udes WORD-FOR-WORD IDENTICAL to ws_U_TvcmXh_Isrc's own six words (CONFIRMED), same IMAGE table-indirected shape.
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[6:7], s[0:1], 0x10; s4:5 scalar aspace 0x4 <- s_load_b256 s[8:15], s[4:5], 0xd0
     * proof: load not depth-1/data-only: s_load_b128 s[24:27], s[6:7], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s12
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/Y/TkfhBvcmXh_Isrc.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/Y/TkfhBvcmXh_Isrc.opt.ll (address space) */
    { "ws_Z_TimgXh_Isrc", 0u, 54u, 0xf91e4deeu, 1u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* COORDINATOR ADDITION (notes/design/LOGIN-SCREEN-PATH.md item (iii)): login-screen foreground family 'a' - the P/AJ/AK/AL/O/Q/R/S family's own shape (table s0:s1, buf1 s4:s5, buf2 s6:s7, tex s8:9, samp s10:11), IMAGE class, table-indirected, CONFIRMED against its own ABI JSON.
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[2:3], s[0:1], 0x10
     * proof: load not depth-1/data-only: s_load_b128 s[12:15], s[2:3], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s10
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/Z/TimgXh_Isrc.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/Z/TimgXh_Isrc.opt.ll (address space) */
    { "ws_BD_glass_background_lph", 0u, 1271u, 0x3858ea3au, 3u,
      { 0u, 8u, 10u, 0u, 0u }, { 0u, 0u, 1u, 0u, 0u }, { 0x01u, 0x04u, 0x04u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* GLASS.md Q4: no-sampler, two-texture shape (table s0, source_texture s4 apiSlot 3, sdf_texture s6 apiSlot 4, buffers s8/s10) - IMAGE class, table-indirected, CONFIRMED against its own ABI JSON (re/pc-26.6.2/xlat/windowserver-r2/work/BD/glass_background_lph).
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[24:25], s[0:1], 0x0; s8:9 scalar aspace 0x4 <- s_load_b64 s[26:27], s[8:9], 0x40; s10:11 vector aspace 0x4 <- global_load_d16_b16 v0, v0, s[10:11]
     * proof: load not depth-1/data-only: s_load_b256 s[16:23], s[0:1], 0x0 -> base *[P(s0:s1)+0x0] terms 32*s6
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/BD/glass_background_lph.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/BD/glass_background_lph.opt.ll (address space) */
    { "ws_BE_glass_background_lph", 0u, 1269u, 0x0ca63b3cu, 3u,
      { 0u, 8u, 10u, 0u, 0u }, { 0u, 0u, 1u, 0u, 0u }, { 0x01u, 0x04u, 0x04u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* GLASS.md Q4: glass_background_lph's second Apple record (BD's own AIR module, a different compilation) - same no-sampler two-texture shape as BD, CONFIRMED against its own ABI JSON.
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[24:25], s[0:1], 0x0; s8:9 scalar aspace 0x4 <- s_load_b64 s[26:27], s[8:9], 0x40; s10:11 vector aspace 0x4 <- global_load_d16_b16 v0, v0, s[10:11]
     * proof: load not depth-1/data-only: s_load_b256 s[16:23], s[0:1], 0x0 -> base *[P(s0:s1)+0x0] terms 32*s6
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/BE/glass_background_lph.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/BE/glass_background_lph.opt.ll (address space) */
    { "ws_J_VfxXghb", 1u, 291u, 0xfa0982efu, 5u,
      { 4u, 6u, 8u, 10u, 12u }, { 1u, 1u, 0u, 0u, 0u }, { 0x01u, 0x04u, 0x04u, 0x04u, 0x04u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /* build 0.0.504: J = VfxXghb vertex (key 0xfcc6342ea8db283f), startup frame F20's program (the login panel's material producer). ABI (CONFIRMED against its own ABI JSON): user data from s8, class 7 s8 (vertex start), FIVE class-3 buffers s12:13 vertex_buffer / s14:15 config / s16:17 mvp_matrix / s18:19 texture_matrix / s20:21 chroma_matrix; no table, no image op.
     * pointers: s12:13 vector aspace 0x1 <- global_load_b128 v[0:3], v[0:1], off; s14:15 vector aspace 0x4 <- global_load_d16_u8 v0, v0, s[14:15] offset:2; s16:17 scalar aspace 0x4 <- s_load_b512 s[36:51], s[16:17], 0x0; s18:19 scalar aspace 0x4 <- s_load_b128 s[8:11], s[18:19], 0x0; s20:21 scalar aspace 0x4 <- s_load_b128 s[8:11], s[20:21], 0x0
     * proof: all 14 load(s) trace directly to a user-data SGPR pair plus constant/lane offset
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: re/pc-26.6.2/xlat/windowserver-r2/work/J/VfxXghb.abi.json, re/pc-26.6.2/xlat/windowserver-r2/work/J/VfxXghb.opt.ll (address space) */
    { "auto_0c6ee068ac7f864d_ViewportToNDC", 1u, 96u, 0xc05bae9au, 3u,
      { 4u, 6u, 8u, 0u, 0u }, { 1u, 1u, 1u, 0u, 0u }, { 0x01u, 0x01u, 0x01u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /* auto-ws (adopt): 0x0c6ee068ac7f864d ViewportToNDC@CoreDisplay, generated for every PASS program (the shipped generator's program list is a hand list)
     * pointers: s12:13 vector aspace 0x1 <- global_load_b64 v[17:18], v[7:8], off; s14:15 vector aspace 0x1 <- global_load_b64 v[0:1], v[0:1], off; s16:17 vector aspace 0x1 <- global_load_b128 v[3:6], v1, s[16:17] offset:48
     * proof: all 6 load(s) trace directly to a user-data SGPR pair plus constant/lane offset
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: re/auto/auto-ws/cache/0b6e34324420dc3a1b6dbdd0/ViewportToNDC.abi.json, .opt.ll (address space) */
    { "auto_0e6c91555b1473e2_variable_blur_downsample_frag_lph", 0u, 173u, 0x1051f3f6u, 2u,
      { 0u, 8u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x04u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* auto-ws (adopt): 0x0e6c91555b1473e2 variable_blur_downsample_frag_lph@QuartzCore, generated for every PASS program (the shipped generator's program list is a hand list)
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[0:1], s[0:1], 0x0; s8:9 scalar aspace 0x4 <- s_load_b96 s[8:10], s[8:9], 0x0
     * proof: load not depth-1/data-only: s_load_b256 s[0:7], s[0:1], 0x0 -> base *[P(s0:s1)+0x0] terms 32*s4
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: re/auto/auto-ws/cache/e78878f836dc45e6ce1e5c15/variable_blur_downsample_frag_lph.abi.json, .opt.ll (address space) */
    { "auto_48a620ac0cd34f7b_TextureCopy", 0u, 42u, 0x1ddbfcadu, 1u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* auto-ws (adopt): 0x48a620ac0cd34f7b TextureCopy@CoreDisplay, generated for every PASS program (the shipped generator's program list is a hand list)
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[0:1], s[0:1], 0x0
     * proof: load not depth-1/data-only: s_load_b256 s[0:7], s[0:1], 0x0 -> base *[P(s0:s1)+0x0] terms 32*s4
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: re/auto/auto-ws/cache/0f6ae68113542240537b1277/TextureCopy.abi.json, .opt.ll (address space) */
    { "auto_6d4c04b20ed5fbab_GPUPass", 0u, 83u, 0xd3d36bb9u, 3u,
      { 0u, 10u, 12u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x04u, 0x04u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* auto-ws (adopt): 0x6d4c04b20ed5fbab GPUPass@ws_07a040, generated for every PASS program (the shipped generator's program list is a hand list)
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[2:3], s[0:1], 0x10; s10:11 scalar aspace 0x4 <- s_load_b32 s11, s[10:11], 0x0; s12:13 scalar aspace 0x4 <- s_load_b32 s12, s[12:13], 0x0
     * proof: load not depth-1/data-only: s_load_b128 s[0:3], s[0:1], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s8
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: re/auto/auto-ws/cache/bb79d1aefca98831733cd439/GPUPass.abi.json, .opt.ll (address space) */
    { "auto_7df6c9c062f37797_variable_blur_vert_lph", 1u, 101u, 0x0f5fd702u, 3u,
      { 4u, 6u, 8u, 0u, 0u }, { 0u, 0u, 1u, 0u, 0u }, { 0x04u, 0x04u, 0x01u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /* auto-ws (adopt): 0x7df6c9c062f37797 variable_blur_vert_lph@QuartzCore, generated for every PASS program (the shipped generator's program list is a hand list)
     * pointers: s12:13 scalar aspace 0x4 <- s_load_b512 s[16:31], s[12:13], 0x0; s14:15 scalar aspace 0x4 <- s_load_b256 s[8:15], s[14:15], 0x0; s16:17 vector aspace 0x1 <- global_load_b128 v[0:3], v[5:6], off
     * proof: all 5 load(s) trace directly to a user-data SGPR pair plus constant/lane offset
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: re/auto/auto-ws/cache/8254e182f1dbf9e2ecfcc787/variable_blur_vert_lph.abi.json, .opt.ll (address space) */
    { "auto_9405a098d0dbc6cb_UberCompositeFragment", 0u, 50u, 0x4912346bu, 1u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x01u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 1u, 0u, 0u },
    /* auto-ws (adopt): 0x9405a098d0dbc6cb UberCompositeFragment@ws_007b40, generated for every PASS program (the shipped generator's program list is a hand list)
     * pointers: s0:1 scalar aspace 0x1 <- s_load_b64 s[2:3], s[0:1], 0x10
     * proof: load not depth-1/data-only: s_load_b128 s[12:15], s[2:3], 0x0 -> base *[P(s0:s1)+0x10] terms 16*s8
     * proof_images_inline: not an INLINE row (gfx-shader-desc.py's inline_slots found no single inline T#/S#)
     * evidence: re/auto/auto-ws/cache/d8356f939bffc1219f5d7ea4/UberCompositeFragment.abi.json, .opt.ll (address space) */
    { "auto_f9e37fc286b8b3a3_TcimXh_Icir", 0u, 96u, 0xb5f82cf4u, 0u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x00u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /* auto-ws (adopt): 0xf9e37fc286b8b3a3 TcimXh_Icir@ws_068780, generated for every PASS program (the shipped generator's program list is a hand list)
     * pointers: none
     * proof: zero loads: the program performs no data-only memory read (any image op is covered separately by proof_images_inline)
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: re/auto/auto-ws/cache/6e7442fd6ba71bc2195a4459/TcimXh_Icir.abi.json, .opt.ll (address space) */
    { "RectPosTexFast_VS_v3_gfx1201", 1u, 50u, 0x029d50b1u, 0u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x00u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /* build 0.0.536: RectPosTexFast_VS_gfx1201 with the vertex ID read from v3 - STRICT-OK NONE like the original
     * pointers: none
     * proof: zero loads: the program performs no data-only memory read (any image op is covered separately by proof_images_inline)
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
    { "RectPosTexFast_VS_attr_v3_gfx1201", 1u, 64u, 0x451698c1u, 0u,
      { 0u, 0u, 0u, 0u, 0u }, { 0u, 0u, 0u, 0u, 0u }, { 0x00u, 0x00u, 0x00u, 0x00u, 0x00u },
      0xffu, 0xffu, 0u, 1u, 1u },
    /* build 0.0.536: RectPosTexFast_VS_attr_gfx1201 with the vertex ID read from v3 - its one load is the ring-offsets read, not a client pointer
     * pointers: none
     * proof: all 1 load(s) trace directly to a user-data SGPR pair plus constant/lane offset
     * proof_images_inline: no image_sample/image_load instructions: trivially true (nothing to disprove)
     * evidence: hand-written (src/shadercache/shaders, assembly sources, via tools/gfx-shader-ids.py HAND[]); no AIR/LLVM ABI */
};
#define XLAT12_READSET_COUNT 63u
#endif
