/* xlat12_desc.h - GENERATED by tools/gen-desc-xlat.py; do not edit .
 * gfx10.3 -> gfx12 IMAGE (8 dword) and SAMPLER (4 dword) descriptor translation, field by field, from Mesa's
 * register database (src/amd/registers/gfx10-rsrc.json, gfx12-rsrc.json @ mesa 4519cc56).
 * Apple writes GFX10 descriptors; gfx12's image_sample reads a different layout, which is why r68's textured quad
 * sampled transparent black .
 * SW_MODE (tiling) is mapped by name from addrlib's two swizzle enums, NOT from the register databases, which
 * carry only the field position . TYPE is still passed through unchanged: its enum is in
 * neither source, and TYPE 9 (2D) is the only value exercised.
 * Refuses (returns non-zero, writes nothing) on a FORMAT with no same-named gfx12 entry, a SW_MODE with no gfx12
 * counterpart, or a dropped/unnamed gfx10 field that is not zero. */
#ifndef XLAT12_DESC_H
#define XLAT12_DESC_H
#include <stdint.h>

enum { XLAT12_DESC_OK = 0, XLAT12_DESC_ERR_FORMAT = 1, XLAT12_DESC_ERR_DROPPED_NONZERO = 2, XLAT12_DESC_ERR_ARG = 3,
       XLAT12_DESC_ERR_NARROW = 4, XLAT12_DESC_ERR_SWMODE = 5, XLAT12_DESC_ERR_UNMAPPED = 6 };

/* gfx10 SW_MODE (AddrSwizzleMode) -> gfx12 SW_MODE (Addr3SwizzleMode), matched BY NAME through addrlib's own
 * per-mode flag tables: same block size, same dimensionality. The register databases carry only the field
 * position [24:20], which is why 0.0.232/0.0.233 passed the raw value through and r70 faulted .
 * gfx12 dropped the Z/S/D/R micro-tile distinction and the _X pipe-XOR, so this preserves the BLOCK SIZE, not
 * the within-block texel order; gfx12's three 3D modes are never a target (gfx10 says 3D in TYPE, not here). */
static const uint8_t kXlat12SwModeG10ToG12[][2] = {
    { 0u, 0u },   /* ADDR_SW_LINEAR -> ADDR3_LINEAR (Linear) */
    { 1u, 1u },   /* ADDR_SW_256B_S -> ADDR3_256B_2D (256B) */
    { 2u, 1u },   /* ADDR_SW_256B_D -> ADDR3_256B_2D (256B) */
    { 5u, 2u },   /* ADDR_SW_4KB_S -> ADDR3_4KB_2D (4KB) */
    { 6u, 2u },   /* ADDR_SW_4KB_D -> ADDR3_4KB_2D (4KB) */
    { 9u, 3u },   /* ADDR_SW_64KB_S -> ADDR3_64KB_2D (64KB) */
    { 10u, 3u },   /* ADDR_SW_64KB_D -> ADDR3_64KB_2D (64KB) */
    { 17u, 3u },   /* ADDR_SW_64KB_S_T -> ADDR3_64KB_2D (64KB) */
    { 18u, 3u },   /* ADDR_SW_64KB_D_T -> ADDR3_64KB_2D (64KB) */
    { 21u, 2u },   /* ADDR_SW_4KB_S_X -> ADDR3_4KB_2D (4KB) */
    { 22u, 2u },   /* ADDR_SW_4KB_D_X -> ADDR3_4KB_2D (4KB) */
    { 23u, 2u },   /* ADDR_SW_4KB_R_X -> ADDR3_4KB_2D (4KB) */
    { 24u, 3u },   /* ADDR_SW_64KB_Z_X -> ADDR3_64KB_2D (64KB) */
    { 25u, 3u },   /* ADDR_SW_64KB_S_X -> ADDR3_64KB_2D (64KB) */
    { 26u, 3u },   /* ADDR_SW_64KB_D_X -> ADDR3_64KB_2D (64KB) */
    { 27u, 3u },   /* ADDR_SW_64KB_R_X -> ADDR3_64KB_2D (64KB) */
};
#define XLAT12_SWMODE_MAP_COUNT 16u
/* REFUSED: gfx10 SW_MODE 28 ADDR_SW_VAR_Z_X - gfx10 VAR block size is ASIC-specific; gfx12 has no variable-size block */
/* REFUSED: gfx10 SW_MODE 31 ADDR_SW_VAR_R_X - gfx10 VAR block size is ASIC-specific; gfx12 has no variable-size block */
/* REFUSED: gfx10 SW_MODE 32 ADDR_SW_LINEAR_GENERAL - gfx9 unaligned linear; gfx10 never selects it and 32 does not fit the 5-bit SW_MODE field */
/* every other SW_MODE value is a reserved gfx10 slot and is refused by absence from the table above */

/* gfx10 FORMAT value -> gfx12 FORMAT value, matched by enum name (values are renumbered: 8_8_8_8_UNORM is 56 then 42). */
static const uint16_t kXlat12FormatG10ToG12[][2] = {
    { 0u, 0u },   /* INVALID */
    { 1u, 1u },   /* 8_UNORM */
    { 2u, 2u },   /* 8_SNORM */
    { 3u, 3u },   /* 8_USCALED */
    { 4u, 4u },   /* 8_SSCALED */
    { 5u, 5u },   /* 8_UINT */
    { 6u, 6u },   /* 8_SINT */
    { 7u, 7u },   /* 16_UNORM */
    { 8u, 8u },   /* 16_SNORM */
    { 9u, 9u },   /* 16_USCALED */
    { 10u, 10u },   /* 16_SSCALED */
    { 11u, 11u },   /* 16_UINT */
    { 12u, 12u },   /* 16_SINT */
    { 13u, 13u },   /* 16_FLOAT */
    { 14u, 14u },   /* 8_8_UNORM */
    { 15u, 15u },   /* 8_8_SNORM */
    { 16u, 16u },   /* 8_8_USCALED */
    { 17u, 17u },   /* 8_8_SSCALED */
    { 18u, 18u },   /* 8_8_UINT */
    { 19u, 19u },   /* 8_8_SINT */
    { 20u, 20u },   /* 32_UINT */
    { 21u, 21u },   /* 32_SINT */
    { 22u, 22u },   /* 32_FLOAT */
    { 23u, 23u },   /* 16_16_UNORM */
    { 24u, 24u },   /* 16_16_SNORM */
    { 25u, 25u },   /* 16_16_USCALED */
    { 26u, 26u },   /* 16_16_SSCALED */
    { 27u, 27u },   /* 16_16_UINT */
    { 28u, 28u },   /* 16_16_SINT */
    { 29u, 29u },   /* 16_16_FLOAT */
    { 36u, 30u },   /* 10_11_11_FLOAT */
    { 43u, 31u },   /* 11_11_10_FLOAT */
    { 44u, 32u },   /* 10_10_10_2_UNORM */
    { 45u, 33u },   /* 10_10_10_2_SNORM */
    { 48u, 34u },   /* 10_10_10_2_UINT */
    { 49u, 35u },   /* 10_10_10_2_SINT */
    { 50u, 36u },   /* 2_10_10_10_UNORM */
    { 51u, 37u },   /* 2_10_10_10_SNORM */
    { 52u, 38u },   /* 2_10_10_10_USCALED */
    { 53u, 39u },   /* 2_10_10_10_SSCALED */
    { 54u, 40u },   /* 2_10_10_10_UINT */
    { 55u, 41u },   /* 2_10_10_10_SINT */
    { 56u, 42u },   /* 8_8_8_8_UNORM */
    { 57u, 43u },   /* 8_8_8_8_SNORM */
    { 58u, 44u },   /* 8_8_8_8_USCALED */
    { 59u, 45u },   /* 8_8_8_8_SSCALED */
    { 60u, 46u },   /* 8_8_8_8_UINT */
    { 61u, 47u },   /* 8_8_8_8_SINT */
    { 62u, 48u },   /* 32_32_UINT */
    { 63u, 49u },   /* 32_32_SINT */
    { 64u, 50u },   /* 32_32_FLOAT */
    { 65u, 51u },   /* 16_16_16_16_UNORM */
    { 66u, 52u },   /* 16_16_16_16_SNORM */
    { 67u, 53u },   /* 16_16_16_16_USCALED */
    { 68u, 54u },   /* 16_16_16_16_SSCALED */
    { 69u, 55u },   /* 16_16_16_16_UINT */
    { 70u, 56u },   /* 16_16_16_16_SINT */
    { 71u, 57u },   /* 16_16_16_16_FLOAT */
    { 72u, 58u },   /* 32_32_32_UINT */
    { 73u, 59u },   /* 32_32_32_SINT */
    { 74u, 60u },   /* 32_32_32_FLOAT */
    { 75u, 61u },   /* 32_32_32_32_UINT */
    { 76u, 62u },   /* 32_32_32_32_SINT */
    { 77u, 63u },   /* 32_32_32_32_FLOAT */
    { 128u, 64u },   /* 8_SRGB */
    { 129u, 65u },   /* 8_8_SRGB */
    { 130u, 66u },   /* 8_8_8_8_SRGB */
    { 132u, 67u },   /* 5_9_9_9_FLOAT */
    { 133u, 68u },   /* 5_6_5_UNORM */
    { 134u, 69u },   /* 1_5_5_5_UNORM */
    { 135u, 70u },   /* 5_5_5_1_UNORM */
    { 136u, 71u },   /* 4_4_4_4_UNORM */
    { 137u, 72u },   /* 4_4_UNORM */
    { 138u, 73u },   /* 1_UNORM */
    { 139u, 74u },   /* 1_REVERSED_UNORM */
    { 140u, 75u },   /* 32_FLOAT_CLAMP */
    { 141u, 76u },   /* 8_24_UNORM */
    { 142u, 77u },   /* 8_24_UINT */
    { 143u, 78u },   /* 24_8_UNORM */
    { 144u, 79u },   /* 24_8_UINT */
    { 145u, 80u },   /* X24_8_32_UINT */
    { 146u, 81u },   /* X24_8_32_FLOAT */
    { 147u, 82u },   /* GB_GR_UNORM */
    { 148u, 83u },   /* GB_GR_SNORM */
    { 149u, 84u },   /* GB_GR_UINT */
    { 150u, 85u },   /* GB_GR_SRGB */
    { 151u, 86u },   /* BG_RG_UNORM */
    { 152u, 87u },   /* BG_RG_SNORM */
    { 153u, 88u },   /* BG_RG_UINT */
    { 154u, 89u },   /* BG_RG_SRGB */
    { 169u, 109u },   /* BC1_UNORM */
    { 170u, 110u },   /* BC1_SRGB */
    { 171u, 111u },   /* BC2_UNORM */
    { 172u, 112u },   /* BC2_SRGB */
    { 173u, 113u },   /* BC3_UNORM */
    { 174u, 114u },   /* BC3_SRGB */
    { 175u, 115u },   /* BC4_UNORM */
    { 176u, 116u },   /* BC4_SNORM */
    { 177u, 117u },   /* BC5_UNORM */
    { 178u, 118u },   /* BC5_SNORM */
    { 179u, 119u },   /* BC6_UFLOAT */
    { 180u, 120u },   /* BC6_SFLOAT */
    { 181u, 121u },   /* BC7_UNORM */
    { 182u, 122u },   /* BC7_SRGB */
};
#define XLAT12_FORMAT_MAP_COUNT 104u
/* 56 gfx10 formats have no same-named gfx12 entry and are refused, e.g. 10_10_10_2_SSCALED, 10_10_10_2_USCALED, 10_11_11_SINT, 10_11_11_SNORM */

/* build 0.0.451 item 2 (S4, review of 0.0.450): bytes per element for a gfx10 FORMAT value, THE TRANSLATOR'S
 * OWN FORMAT TABLE (the brief's own words) - derived from each format's own enum name above (the sum of the
 * channel bit widths the name lists, divided by 8), for the formats this project has actually measured or needs
 * for its own resprov collision tests: 1 (8_UNORM, ws_resprov.h's P samples), 71 (16_16_16_16_FLOAT, AL's samples),
 * plus 14 (8_8_UNORM, 16 bpp) and 77 (32_32_32_32_FLOAT, 128 bpp), the two bit widths S4's own collision report
 * names ("a 16 bpp w <= 32" and "a 128 bpp ... w <= 16"). EVERY OTHER FORMAT RETURNS 0 (unknown) - fail-closed,
 * matching this file's own philosophy throughout: a resprov ask never assumes a format it was not told to know,
 * and 0 can never equal a real re-tiled kind's own nonzero elemBytes (ws_resprov.h n48_rp_kind_geom), so an
 * unrecognised format always refuses the ask rather than risk a false match. */
static inline uint32_t xlat12_format_elem_bytes(uint32_t f10)
{
    switch (f10) {
    case 1u:  return 1u;    /* 8_UNORM */
    case 14u: return 2u;    /* 8_8_UNORM */
    case 56u: return 4u;    /* 8_8_8_8_UNORM */
    case 71u: return 8u;    /* 16_16_16_16_FLOAT */
    case 77u: return 16u;   /* 32_32_32_32_FLOAT */
    default:  return 0u;    /* unknown format: fail-closed, never assumed to match a recorded elemBytes */
    }
}

/* image descriptor: 25 field(s) moved, 2 split, 4 zeroed (no gfx10 source), 12 dropped */
 /*   dropped: ALPHA_IS_ON_MSB (gfx10 word 6 bits 22:22) - gfx10 DCC hint, no gfx12 field */
 /*   dropped: ARRAY_PITCH (gfx10 word 5 bits 3:0) - gfx12 has no ARRAY_PITCH field in SQ_IMG_RSRC_WORD5 */
 /*   dropped: BIG_PAGE (gfx10 word 5 bits 31:31) - gfx10.3 paging hint, no gfx12 field */
 /*   dropped: COLOR_TRANSFORM (gfx10 word 6 bits 23:23) - gfx10 DCC hint, no gfx12 field */
 /*   dropped: COUNTER_BANK_ID (gfx10 word 6 bits 7:0) - gfx10 performance counter binding, no gfx12 field */
 /*   dropped: ITERATE_256 (gfx10 word 6 bits 10:10) - gfx10.3 DCC iteration hint, no gfx12 field */
 /*   dropped: LLC_NOALLOC (gfx10 word 6 bits 9:8) - gfx10.3 cache hint, no gfx12 field */
 /*   dropped: LOD_HDW_CNT_EN (gfx10 word 5 bits 25:25) - gfx10 only, no gfx12 field */
 /*   dropped: META_DATA_ADDRESS_LO (gfx10 word 6 bits 31:24) - gfx10 DCC metadata address, gfx12 has no separate metadata surface */
 /*   dropped: META_PIPE_ALIGNED (gfx10 word 6 bits 19:19) - gfx10 DCC metadata, gfx12 has no separate metadata surface */
 /*   dropped: PRT_DEFAULT (gfx10 word 5 bits 26:26) - gfx10 PRT behaviour, no gfx12 field */
 /*   dropped, value ignored: RESOURCE_LEVEL (gfx10 word 2 bits 31:31) - gfx10-rsrc.json annotates it "must be 1" and ac_descriptors.c:847 writes it straight from has_desc_resource_level, so it is a constant carrying no information; gfx12 removed the field (no RESOURCE_LEVEL anywhere in gfx12-rsrc.json). Dropped even when set (r69, an earlier analysis) */
static inline uint32_t xlat12_img_desc_g10_to_g12(const uint32_t *in, uint32_t *dst)
{
    if (!in || !dst) return XLAT12_DESC_ERR_ARG;
    uint32_t out[8] = { 0 };   /* commit only after every field passes; permits in == dst */
    if (in[1] & 0x20000000u) return XLAT12_DESC_ERR_UNMAPPED;   /* no named source field */
    if (in[2] & 0x70003000u) return XLAT12_DESC_ERR_UNMAPPED;   /* no named source field */
    if (in[4] & 0xe000c000u) return XLAT12_DESC_ERR_UNMAPPED;   /* no named source field */
    if (in[5] & 0x79000000u) return XLAT12_DESC_ERR_UNMAPPED;   /* no named source field */
    if (in[6] & 0x00007800u) return XLAT12_DESC_ERR_UNMAPPED;   /* no named source field */
    if (in[7] & 0xffffffffu) return XLAT12_DESC_ERR_UNMAPPED;   /* no named source field */
    if ((in[6] >> 22) & 0x1u) return XLAT12_DESC_ERR_DROPPED_NONZERO;   /* ALPHA_IS_ON_MSB */
    if ((in[5] >> 0) & 0xfu) return XLAT12_DESC_ERR_DROPPED_NONZERO;   /* ARRAY_PITCH */
    if ((in[5] >> 31) & 0x1u) return XLAT12_DESC_ERR_DROPPED_NONZERO;   /* BIG_PAGE */
    if ((in[6] >> 23) & 0x1u) return XLAT12_DESC_ERR_DROPPED_NONZERO;   /* COLOR_TRANSFORM */
    if ((in[6] >> 0) & 0xffu) return XLAT12_DESC_ERR_DROPPED_NONZERO;   /* COUNTER_BANK_ID */
    if ((in[6] >> 10) & 0x1u) return XLAT12_DESC_ERR_DROPPED_NONZERO;   /* ITERATE_256 */
    if ((in[6] >> 8) & 0x3u) return XLAT12_DESC_ERR_DROPPED_NONZERO;   /* LLC_NOALLOC */
    if ((in[5] >> 25) & 0x1u) return XLAT12_DESC_ERR_DROPPED_NONZERO;   /* LOD_HDW_CNT_EN */
    if ((in[6] >> 24) & 0xffu) return XLAT12_DESC_ERR_DROPPED_NONZERO;   /* META_DATA_ADDRESS_LO */
    if ((in[6] >> 19) & 0x1u) return XLAT12_DESC_ERR_DROPPED_NONZERO;   /* META_PIPE_ALIGNED */
    if ((in[5] >> 26) & 0x1u) return XLAT12_DESC_ERR_DROPPED_NONZERO;   /* PRT_DEFAULT */
    out[0] = in[0];   /* base address low 32 */
    out[1] |= (((in[1] >> 0) & 0xffu) & 0xffu) << 0;   /* BASE_ADDRESS_HI */
    out[1] |= (((in[5] >> 4) & 0xfu) & 0x1fu) << 12;   /* MAX_MIP */
    {   /* FORMAT: gfx10 word 1 [28:20] -> gfx12 word 1 [24:17], BY NAME */
        const uint32_t f10 = (in[1] >> 20) & 0x1ffu;
        uint32_t f12 = 0xFFFFu;
        for (uint32_t i = 0; i < XLAT12_FORMAT_MAP_COUNT; i++)
            if (kXlat12FormatG10ToG12[i][0] == f10) { f12 = kXlat12FormatG10ToG12[i][1]; break; }
        if (f12 == 0xFFFFu) return XLAT12_DESC_ERR_FORMAT;
        out[1] |= (f12 & 0xffu) << 17;
    }
    out[1] |= (((in[3] >> 12) & 0xfu) & 0x1fu) << 25;   /* BASE_LEVEL */
    out[1] |= (((in[1] >> 30) & 0x3u) & 0x3u) << 30;   /* WIDTH_LO */
    out[2] |= (((in[2] >> 0) & 0xfffu) & 0x3fffu) << 0;   /* WIDTH_HI */
    out[2] |= (((in[2] >> 14) & 0x3fffu) & 0xffffu) << 14;   /* HEIGHT */
    out[3] |= (((in[3] >> 0) & 0x7u) & 0x7u) << 0;   /* DST_SEL_X */
    out[3] |= (((in[3] >> 3) & 0x7u) & 0x7u) << 3;   /* DST_SEL_Y */
    out[3] |= (((in[3] >> 6) & 0x7u) & 0x7u) << 6;   /* DST_SEL_Z */
    out[3] |= (((in[3] >> 9) & 0x7u) & 0x7u) << 9;   /* DST_SEL_W */
    out[3] |= (((in[3] >> 16) & 0xfu) & 0x1fu) << 15;   /* LAST_LEVEL */
    {   /* SW_MODE: gfx10 word 3 [24:20] -> gfx12 word 3 [24:20], BY NAME (addrlib) */
        const uint32_t s10 = (in[3] >> 20) & 0x1fu;
        uint32_t s12 = 0xFFFFu;
        for (uint32_t i = 0; i < XLAT12_SWMODE_MAP_COUNT; i++)
            if (kXlat12SwModeG10ToG12[i][0] == s10) { s12 = kXlat12SwModeG10ToG12[i][1]; break; }
        if (s12 == 0xFFFFu) return XLAT12_DESC_ERR_SWMODE;
        out[3] |= (s12 & 0x1fu) << 20;
    }
    out[3] |= (((in[3] >> 25) & 0x7u) & 0x7u) << 25;   /* BC_SWIZZLE */
    out[3] |= (((in[3] >> 28) & 0xfu) & 0xfu) << 28;   /* TYPE */
    out[4] |= (((in[4] >> 0) & 0x1fffu) & 0x3fffu) << 0;   /* DEPTH */
    out[4] |= (((in[4] >> 13) & 0x1u) & 0x3u) << 14;   /* PITCH_MSB */
    out[4] |= (((in[4] >> 16) & 0x1fffu) & 0x3fffu) << 16;   /* BASE_ARRAY */
    out[5] |= (((in[5] >> 8) & 0xfffu) & 0x1fffu) << 5;   /* MIN_LOD_WARN */
    out[5] |= (((in[5] >> 20) & 0x7u) & 0x7u) << 20;   /* PERF_MOD */
    out[5] |= (((in[5] >> 23) & 0x1u) & 0x1u) << 23;   /* CORNER_SAMPLES */
    if ((((in[6] >> 15) & 0x3u) & ~0x1u) != 0u) return XLAT12_DESC_ERR_NARROW;   /* MAX_UNCOMPRESSED_BLOCK_SIZE narrows 2 -> 1 bits */
    out[6] |= (((in[6] >> 15) & 0x3u) & 0x1u) << 15;   /* MAX_UNCOMPRESSED_BLOCK_SIZE */
    out[6] |= (((in[6] >> 17) & 0x3u) & 0x3u) << 17;   /* MAX_COMPRESSED_BLOCK_SIZE */
    out[6] |= (((in[6] >> 20) & 0x1u) & 0x1u) << 20;   /* WRITE_COMPRESS_ENABLE */
    out[6] |= (((in[6] >> 21) & 0x1u) & 0x1u) << 21;   /* COMPRESSION_EN */
    out[5] |= ((((in[1] >> 8) & 0xfffu) >> 0) & 0x3fu) << 26;   /* MIN_LOD -> MIN_LOD_LO */
    out[6] |= ((((in[1] >> 8) & 0xfffu) >> 6) & 0x7fu) << 0;   /* MIN_LOD -> MIN_LOD_HI */
    /* NO_EDGE_CLAMP (gfx12 word 3 bits 12:12): no gfx10 source, left zero */
    /* UAV3D (gfx12 word 5 bits 4:4): no gfx10 source, left zero */
    /* SAMPLE_PATTERN_OFFSET (gfx12 word 6 bits 14:11): no gfx10 source, left zero */
    /* COMPRESSION_ACCESS_MODE (gfx12 word 6 bits 23:22): no gfx10 source, left zero */
    for (uint32_t i = 0; i < 8u; i++) dst[i] = out[i];
    return XLAT12_DESC_OK;
}

/* sampler descriptor: 26 field(s) moved, 2 split, 0 zeroed (no gfx10 source), 2 dropped */
 /*   dropped: BLEND_ZERO_PRT (gfx10 word 2 bits 30:30) - sampler: gfx10 only, no gfx12 field */
 /*   dropped: MIP_POINT_PRECLAMP (gfx10 word 2 bits 28:28) - sampler: gfx10 only, no gfx12 field */
static inline uint32_t xlat12_samp_desc_g10_to_g12(const uint32_t *in, uint32_t *dst)
{
    if (!in || !dst) return XLAT12_DESC_ERR_ARG;
    uint32_t out[4] = { 0 };   /* commit only after every field passes; permits in == dst */
    if (in[2] & 0x80000000u) return XLAT12_DESC_ERR_UNMAPPED;   /* no named source field */
    if (in[3] & 0x3ffff000u) return XLAT12_DESC_ERR_UNMAPPED;   /* no named source field */
    if ((in[2] >> 30) & 0x1u) return XLAT12_DESC_ERR_DROPPED_NONZERO;   /* BLEND_ZERO_PRT */
    if ((in[2] >> 28) & 0x1u) return XLAT12_DESC_ERR_DROPPED_NONZERO;   /* MIP_POINT_PRECLAMP */

    out[0] |= (((in[0] >> 0) & 0x7u) & 0x7u) << 0;   /* CLAMP_X */
    out[0] |= (((in[0] >> 3) & 0x7u) & 0x7u) << 3;   /* CLAMP_Y */
    out[0] |= (((in[0] >> 6) & 0x7u) & 0x7u) << 6;   /* CLAMP_Z */
    out[0] |= (((in[0] >> 9) & 0x7u) & 0x7u) << 9;   /* MAX_ANISO_RATIO */
    out[0] |= (((in[0] >> 12) & 0x7u) & 0x7u) << 12;   /* DEPTH_COMPARE_FUNC */
    out[0] |= (((in[0] >> 15) & 0x1u) & 0x1u) << 15;   /* FORCE_UNNORMALIZED */
    out[0] |= (((in[0] >> 16) & 0x7u) & 0x7u) << 16;   /* ANISO_THRESHOLD */
    out[0] |= (((in[0] >> 19) & 0x1u) & 0x1u) << 19;   /* MC_COORD_TRUNC */
    out[0] |= (((in[0] >> 20) & 0x1u) & 0x1u) << 20;   /* FORCE_DEGAMMA */
    out[0] |= (((in[0] >> 21) & 0x3fu) & 0x3fu) << 21;   /* ANISO_BIAS */
    out[0] |= (((in[0] >> 27) & 0x1u) & 0x1u) << 27;   /* TRUNC_COORD */
    out[0] |= (((in[0] >> 28) & 0x1u) & 0x1u) << 28;   /* DISABLE_CUBE_WRAP */
    out[0] |= (((in[0] >> 29) & 0x3u) & 0x3u) << 29;   /* FILTER_MODE */
    out[0] |= (((in[0] >> 31) & 0x1u) & 0x1u) << 31;   /* SKIP_DEGAMMA */
    out[1] |= (((in[1] >> 0) & 0xfffu) & 0x1fffu) << 0;   /* MIN_LOD */
    out[1] |= (((in[1] >> 12) & 0xfffu) & 0x1fffu) << 13;   /* MAX_LOD */
    out[1] |= (((in[1] >> 28) & 0xfu) & 0xfu) << 28;   /* PERF_Z */
    out[2] |= (((in[2] >> 0) & 0x3fffu) & 0x3fffu) << 0;   /* LOD_BIAS */
    out[2] |= (((in[2] >> 14) & 0x3fu) & 0x3fu) << 14;   /* LOD_BIAS_SEC */
    out[2] |= (((in[2] >> 20) & 0x3u) & 0x3u) << 20;   /* XY_MAG_FILTER */
    out[2] |= (((in[2] >> 22) & 0x3u) & 0x3u) << 22;   /* XY_MIN_FILTER */
    out[2] |= (((in[2] >> 24) & 0x3u) & 0x3u) << 24;   /* Z_FILTER */
    out[2] |= (((in[2] >> 26) & 0x3u) & 0x3u) << 26;   /* MIP_FILTER */
    out[2] |= (((in[2] >> 29) & 0x1u) & 0x1u) << 29;   /* ANISO_OVERRIDE */
    out[3] |= (((in[3] >> 0) & 0xfffu) & 0xfffu) << 18;   /* BORDER_COLOR_PTR */
    out[3] |= (((in[3] >> 30) & 0x3u) & 0x3u) << 30;   /* BORDER_COLOR_TYPE */
    out[2] |= ((((in[1] >> 24) & 0xfu) >> 0) & 0x3u) << 30;   /* PERF_MIP -> PERF_MIP_LO */
    out[3] |= ((((in[1] >> 24) & 0xfu) >> 2) & 0x3u) << 0;   /* PERF_MIP -> PERF_MIP_HI */
    for (uint32_t i = 0; i < 4u; i++) dst[i] = out[i];
    return XLAT12_DESC_OK;
}

#endif
