/* xlat12_reused.h - HAND-WRITTEN, NOT GENERATED. The gfx10.3 addresses gfx12 REUSES for a different register.
 *
 * WHY THIS FILE EXISTS AND WHY IT IS NOT IN xlat12_tables.h. That file carries the banner "GENERATED by
 * src/xlat12/gen/gen_tables.py - do not edit. Regenerate instead.", and its classifier is NAME-driven: a gfx10.3
 * register whose NAME is absent from gfx12.json is classed ABSENT and its write is DROPPED. That is right for a
 * register gfx12 deleted. It is WRONG for an address gfx12 REUSED, because dropping the write leaves the gfx12
 * register that now lives at that address holding whatever its context slot last held - and gfx12 has NO
 * CLEAR_STATE (ac_gpu_info.c: has_clear_state = gfx_level >= GFX7 && gfx_level < GFX11), so "whatever it last
 * held" is power-on SRAM on a card nothing else has driven. A hand edit inside the generated file would be lost
 * the next time anyone runs `make gen`; these rows therefore live here and xlat12.c's lookup() consults them
 * FIRST, so they supersede the generated row for the same address whatever the generator later says.
 * tests/test_xlat12.c asserts BOTH halves: that the override wins, and that the generated row is still the ABSENT
 * one it supersedes (so a regeneration that changes it is caught loudly instead of silently agreeing).
 *
 * THE TWO ADDRESSES (notes 880, 881; every number CONFIRMED against the sources named):
 *
 *   0x28b94  gfx10.3 VGT_STRMOUT_CONFIG          -> gfx12 PA_SC_HIZ_INFO
 *   0x28b98  gfx10.3 VGT_STRMOUT_BUFFER_CONFIG   -> gfx12 PA_SC_HIS_INFO
 *
 * PROVENANCE.
 *   - ref/linux-asic-reg/gc_12_0_0_offset.h: regPA_SC_HIZ_INFO 0x02e5 BASE_IDX 1, regPA_SC_HIS_INFO 0x02e6
 *     BASE_IDX 1. The context block's MMIO base is 0x28000, so 0x28000 + 0x2e5*4 = 0x28b94 and
 *     0x28000 + 0x2e6*4 = 0x28b98. CONFIRMED.
 *   - re/graphics/src/mesa/src/amd/common/ac_cmdbuf.c uses BOTH spellings of the same address in the same file:
 *     the pre-gfx12 preamble writes `R_028B98_VGT_STRMOUT_BUFFER_CONFIG, 0x0` and the gfx12 preamble writes
 *     `R_028B98_PA_SC_HIS_INFO, S_028B98_SURFACE_ENABLE(0)`. CONFIRMED.
 *   - re/graphics/src/mesa/src/amd/vulkan/radv_cmd_buffer.c, radv_gfx12_emit_null_ds_state():
 *     `gfx12_set_context_reg(R_028B94_PA_SC_HIZ_INFO, S_028B94_SURFACE_ENABLE(0))` - i.e. a gfx12 pass with NO
 *     depth/stencil attachment writes exactly this zero. CONFIRMED.
 *   - gfx12.json PA_SC_HIZ_INFO fields: SURFACE_ENABLE [0], FORMAT [1], SW_MODE [2:4], DST_OUTSIDE_ZERO_TO_ONE
 *     [25]. PA_SC_HIS_INFO: SURFACE_ENABLE [0], SW_MODE [1:3]. CONFIRMED.
 *
 * THE VALUE MAPPING, AND WHY IT IS NOT A RAW PASS-THROUGH. The gfx10.3 and gfx12 field lists share NO field
 * name, so the generator's own documented repack rule applies verbatim - "gfx10.3-only fields are dropped,
 * gfx12-only fields are left 0" - and the mapping is the constant 0. That is also mesa's value for a
 * colour-only pass. It is deliberately NOT `value`: VGT_STRMOUT_CONFIG bit 0 is STREAMOUT_0_EN, and on gfx12
 * that same bit is PA_SC_HIZ_INFO.SURFACE_ENABLE, so a raw pass-through of a non-zero streamout enable would
 * switch a HiZ surface ON at a base nobody has written. Apple's compositor writes 0 to both (measured on the
 * arm13/14/15 capture, frame 1 dword 105: `c0026900 000002e5 00000000 00000000`), so on the armed path the
 * mapping is the identity anyway; `reused_nonzero` in xlat12_draw_stats counts any frame where it is not.
 */
#ifndef XLAT12_REUSED_H
#define XLAT12_REUSED_H

#include <stdint.h>
#include "xlat12.h"
#include "xlat12_tables.h"

/* gfx12 PA_SC_HIZ_INFO / PA_SC_HIS_INFO for a colour-only pass: SURFACE_ENABLE 0, every other field 0.
 * radv_gfx12_emit_null_ds_state / ac_cmdbuf.c's gfx12 preamble. */
static uint32_t xlat12_reuse_sc_surface_disable(uint32_t v) { (void)v; return 0u; }

static const Xlat12Entry kXlat12Reused[] = {
    { 0x28b94u, 0x28b94u, xlat12_reuse_sc_surface_disable, XLAT12_CLS_REUSED,
      "VGT_STRMOUT_CONFIG -> gfx12 PA_SC_HIZ_INFO",
      "gfx12 reuses this address for PA_SC_HIZ_INFO (ctx 0x2e5); emitted as SURFACE_ENABLE 0 (radv null-DS)" },
    { 0x28b98u, 0x28b98u, xlat12_reuse_sc_surface_disable, XLAT12_CLS_REUSED,
      "VGT_STRMOUT_BUFFER_CONFIG -> gfx12 PA_SC_HIS_INFO",
      "gfx12 reuses this address for PA_SC_HIS_INFO (ctx 0x2e6); emitted as SURFACE_ENABLE 0 (ac_cmdbuf.c)" },
};
#define XLAT12_REUSED_LEN ((uint32_t)(sizeof(kXlat12Reused) / sizeof(kXlat12Reused[0])))

/* The override for `g10`, or 0. Linear over two rows - deliberately not a binary search, because the array is
 * hand-written and its order must not become load-bearing. */
static const Xlat12Entry *xlat12_reused_lookup(uint32_t g10)
{
    for (uint32_t i = 0; i < XLAT12_REUSED_LEN; i++)
        if (kXlat12Reused[i].g10 == g10) return &kXlat12Reused[i];
    return 0;
}

#endif /* XLAT12_REUSED_H */
