/* xlat12_abi_ptrs.h — 0.0.390 ( part 5 (ii)): THE RAW-POINTER SLOTS OUR PROGRAMS DECLARE, transcribed from the
 * ABI JSON `role` strings under re/ and from nothing else.
 *
 * WHY THIS IS A SEPARATE FILE AND NOT A COLUMN IN xlat12_shader_ids.h. (ii) asks for "raw-pointer slots generated
 * from the ABI JSON roles" IN xlat12_shader_ids.h. That file's own banner reads `GENERATED by tools/gfx-shader-ids.py;
 * do not edit`, and the generator does not emit these roles. Editing a generated file by hand makes it disagree with its
 * generator and the data is lost the next time it runs. So the rows live here, keyed by the SAME identity
 * xlat12_shader_ids.h uses - (ndw, fnv) over the packed gfx1201 image - and this file says exactly which JSON each row
 * came from. WHEN tools/gfx-shader-ids.py LEARNS THE ROLES, THIS FILE SHOULD BE DELETED AND THE COLUMN GENERATED.
 *
 * WHAT A ROW IS. `slot` is a USER-DATA slot index in the stage's own user-data space - the index xlat12_ib.c's
 * DPair.ud_pos is keyed by for a fragment program. Each entry is the FIRST of a 64-bit pair (slot, slot+1), because every
 * one of these arguments is `ptr addrspace(1)` or `ptr addrspace(4)` and is passed as two SGPRs.
 *
 * WHAT IS **NOT** HERE, ON PURPOSE:
 *   - ring_offsets (the vertex stage's s0:s1). It is a SYSTEM SGPR and on our armed path it is OUR OWN mapping, written
 *     by d_rings into the translated stream. It is not a client page and there is nothing about it to prove.
 *   - the attribute-ring descriptor, for the same reason.
 *   - every program whose ABI JSON I did not read. A row for a program nobody read would be an invention, and an
 *     invented row reads as "this program declares no pointers", which is the fail-OPEN direction. A caller that finds
 *     no row must treat the program as UNKNOWN and refuse - see xlat12_abi_ptr_row's null return.
 *
 * (ii) LISTS `GPUPass s0:s1/s2:s3/s10:s11/s12:s13`. **s2:s3 IS NOT A POINTER ARGUMENT** and this file does not
 * carry it: GPUPass's own ABI JSON gives s2 and s3 the roles `s2 unused (Apple's record leaves it free)` and
 * `s3 unused ...`. s[2:3] appears in xlat12_ib.c's disassembly note as the DESTINATION of
 * `s_load_b64 s[2:3], s[0:1], 0x10` - the sampler heap base the program DERIVES from the table - not as an argument.
 * The derived heap bases are exported by the translator as `in_img_va` / `in_samp_va` instead, so nothing is lost.
 */
#ifndef XLAT12_ABI_PTRS_H
#define XLAT12_ABI_PTRS_H

#include <stdint.h>

/* build 0.0.470 (notes/design/NO-SAMPLER-CLASS10.md section 2): 4 -> 6. ws_AZ_TimgBdrkXhn_IsrcCrd (class 10) and
 * ws_J_VfxXghb each declare FIVE 64-bit pointers; the largest row in this file is now 5. A row whose `nptr` exceeds this
 * cap is NOT silently truncated any more: xlat12_abi_ptr_n (below) is the one place every reader of a row takes its
 * count from, and it sets the caller's `over` flag (xlat12_draw_stats.in_over) when the row declares more pointers
 * than a reader can carry - an incomplete pointer list is the fail-OPEN direction, so it must refuse, never shrink. */
#define XLAT12_ABI_PTR_MAX 6u

typedef struct {
    const char *name;
    uint32_t ndw, fnv;          /* the identity xlat12_shader_ids.h keys on */
    uint32_t stage;             /* 1 vertex, 0 fragment — as xlat12_shader_ids.h uses it */
    uint32_t nptr;
    uint8_t  slot[XLAT12_ABI_PTR_MAX];   /* first user-data slot of each 64-bit pointer argument */
} xlat12_abi_ptrs;

static const xlat12_abi_ptrs kXlat12AbiPtrs[] = {
    /* re/pc-26.6.2/xlat/windowserver/work/D/GPUPass.abi.json —
     *   "s0:s1 descriptor table (class 19)", "s10:s11 buffer location 3 (combinedLUTTexelAlignmentScale)",
     *   "s12:s13 buffer location 4 (combinedLUTTexelAlignmentOffset)". Fragment: s_n is user-data slot n. */
    { "ws_D_GPUPass", 83u, 0xd3d36bb9u, 0u, 3u, { 0u, 10u, 12u, 0u } },
    /* re/graphics/g2/work/UberCompositeFragment.abi.json —
     *   "s0:s1 descriptor table (class 19): +0x00 image table, +0x10 sampler table", "s6:s7 buffer location 0 (args)". */
    { "UberCompositeFragment", 50u, 0x4912346bu, 0u, 2u, { 0u, 6u, 0u, 0u } },
    /* re/pc-26.6.2/xlat/windowserver/work/{E,F}/ViewportToNDC.abi.json (both files, identical role lists) —
     *   user data starts at s8 ("s8 user data 0: vertex start"), so s12:s13 / s14:s15 / s16:s17 are user-data slots
     *   4 / 6 / 8: "buffer location 0 (vertexArray)", "buffer location 1 (texCoords)", "buffer location 2 (mvpMatrix)". */
    { "ws_E_ViewportToNDC=ws_F_ViewportToNDC", 96u, 0xc05bae9au, 1u, 3u, { 4u, 6u, 8u, 0u } },
    /* re/pc-26.6.2/xlat/windowserver/work/H/UberCompositeVertex.abi.json — user data at s8 again, so
     *   "s12:s13 buffer location 1 (mvp_matrix)" and "s14:s15 vertex buffer 0" are user-data slots 4 and 6. */
    { "ws_H_UberCompositeVertex", 85u, 0xea6ac219u, 1u, 2u, { 4u, 6u, 0u, 0u } },
    /* re/graphics/g2/work/UberCompositeVertex.abi.json — a DIFFERENT argument order: this one lists user data FIRST
     *   ("s0 vertex start ...") and the system SGPRs after, so "s4:s5 buffer location 1 (mvp_matrix)" and
     *   "s6:s7 vertex buffer 0" are already user-data slots 4 and 6. */
    { "UberCompositeVertex", 85u, 0x7ae1aa19u, 1u, 2u, { 4u, 6u, 0u, 0u } },
    /* re/pc-26.6.2/xlat/windowserver-r2/work/P/TimgXh_Ialp.abi.json (reviewer-transcribed) —
     *   "s0:s1 descriptor table (class 19)", "s4:s5 buffer location 1 (uniforms)", "s6:s7 buffer location 2
     *   (lod_bias)". Fragment: s_n is user-data slot n. D4-PRIME-FIXES item 3b proposed {0} only; the JSON declares
     *   THREE pointers, and a row that lists fewer than the program declares is the fail-open direction. */
    { "ws_P_TimgXh_Ialp", 46u, 0xebaa377cu, 0u, 3u, { 0u, 4u, 6u, 0u } },
    /* COVERAGE TASK S5, re/pc-26.6.2/xlat/windowserver-r2/work/AH/Xh.abi.json — ONE user_data entry:
     *   "s2:s3 buffer location 1 (uniforms)" (class 3). No descriptor table (the program samples nothing: AH is a
     *   plain uncompressed f32 export, NONE class in xlat12_shader_desc.h). Fragment: s_n is user-data slot n. */
    { "ws_AH_Xh", 41u, 0xdb98e8d3u, 0u, 1u, { 2u, 0u, 0u, 0u } },
    /* COVERAGE TASK S5, re/pc-26.6.2/xlat/windowserver-r2/work/AJ,AK,AL abi.json files — all three
     *   declare the SAME shape as P above: "s0:s1 descriptor table (class 19)", "s4:s5 buffer location 1
     *   (uniforms)", "s6:s7 buffer location 2 (lod_bias)". The texture (s8:s9, class 1) and sampler (s10:s11,
     *   class 2) entries their JSON also carries are NOT raw-pointer arguments (they are indices into the
     *   descriptor table the class-19 slot already names), so they are not transcribed here, exactly as P's are
     *   not. Fragment: s_n is user-data slot n. */
    { "ws_AJ_TcimXh_Isrc", 83u, 0x5a2f0cb6u, 0u, 3u, { 0u, 4u, 6u, 0u } },
    { "ws_AK_TsplXh_Isrc", 88u, 0xaa26070eu, 0u, 3u, { 0u, 4u, 6u, 0u } },
    { "ws_AL_TimgXh_Isrc", 49u, 0xfd012f2fu, 0u, 3u, { 0u, 4u, 6u, 0u } },
    /* build 0.0.447 (MIB-A1-PATH.md Q4 step 2), re/pc-26.6.2/xlat/windowserver-r2/work/AE/downsample_4_frag_lph
     *   .abi.json — the SAME shape as AM below: "s0:s1 descriptor table (class 19)", "s4 texture location 3
     *   (texture0): image table index" (i32, not a pointer) and "s6 sampler location 0 (sampler0): sampler table
     *   index" (i32, not a pointer); the two raw pointers beyond the table are "s8:s9 buffer location 1 (u)" and
     *   "s10:s11 buffer location 6 (edr_scale)" (both `ptr addrspace(4)` in the JSON `args` array). Fragment: s_n
     *   is user-data slot n. Disassembly (CONFIRMED, `llvm-objdump --mcpu=gfx1201` over the same
     *   work/AE/downsample_4_frag_lph.pal.o): +0xF8 `s_load_b64 s[0:1], s[8:9], 0x40` (a direct load through the
     *   s8:s9 pointer) and +0xEC `global_load_d16_b16 v10, v10, s[10:11]` (a direct load through the s10:s11
     *   pointer) — both dereferenced as pointers, not table indices; `s_endpgm` at +0x19C (+4 = 416B = 104dw,
     *   matching xlat12_shader_ids.h's own ndw). The JSON declares THREE pointers total; all three are
     *   transcribed here. */
    { "ws_AE_downsample_4_frag_lph", 104u, 0xdbf619c2u, 0u, 3u, { 0u, 8u, 10u, 0u } },
    /* COVERAGE TASK S5 PART 2a, re/pc-26.6.2/xlat/windowserver-r2/work/AM/narrow_blur_11_frag_lph
     *   .abi.json — a DIFFERENT shape from P/AJ/AK/AL: "s0:s1 descriptor table (class 19)", "s4 texture location 3
     *   (texture0): image table index" (i32, not a pointer) and "s6 sampler location 0 (sampler0): sampler table
     *   index" (i32, not a pointer) sit where AJ/AK/AL had buffer pointers; the two raw pointers beyond the table
     *   are "s8:s9 buffer location 1 (u)" and "s10:s11 buffer location 6 (edr_scale)". Fragment: s_n is user-data
     *   slot n. The JSON declares THREE pointers total; all three are transcribed here. */
    { "ws_AM_narrow_blur_11_frag_lph", 142u, 0x2519bf29u, 0u, 3u, { 0u, 8u, 10u, 0u } },
    /* build 0.0.447 (MIB-A1-PATH.md Q4 step 2), re/pc-26.6.2/xlat/windowserver-r2/work/AD/narrow_blur_23_frag_lph
     *   .abi.json — the SAME shape as AE/AM above: "s0:s1 descriptor table (class 19)", "s4 texture location 3
     *   (texture0): image table index" (i32, not a pointer), "s6 sampler location 0 (sampler0): sampler table
     *   index" (i32, not a pointer), "s8:s9 buffer location 1 (u)" and "s10:s11 buffer location 6 (edr_scale)"
     *   (both `ptr addrspace(4)`). Fragment: s_n is user-data slot n. Disassembly (CONFIRMED, `llvm-objdump
     *   --mcpu=gfx1201` over the same work/AD/narrow_blur_23_frag_lph.pal.o): four direct loads through s[8:9]
     *   (+0x38 `s_load_b128 s[0:3], s[8:9], 0x20`; +0x40 `s_load_b256 s[12:19], s[8:9], 0x0`; +0x68 `s_load_b128
     *   s[28:31], s[8:9], 0x40`; +0x1F8 `s_load_b32 s0, s[8:9], 0x50`) and one through s[10:11] (+0x2CC
     *   `global_load_d16_b16 v4, v4, s[10:11]`); `s_endpgm` at +0x318 (+4 = 796B = 199dw, matching
     *   xlat12_shader_ids.h's own ndw). The JSON declares THREE pointers total; all three are transcribed here. */
    { "ws_AD_narrow_blur_23_frag_lph", 199u, 0x3dbe4294u, 0u, 3u, { 0u, 8u, 10u, 0u } },
    /* COVERAGE TASK S5 PART 2b, re/pc-26.6.2/xlat/windowserver-r2/work/K/VfxU11Xh.abi.json —
     *   user data at s8 (vertex; "s8 user data 0: vertex start"), so "s12:s13 buffer location 2 (mvp_matrix)",
     *   "s14:s15 buffer location 3 (texture_matrix)" and "s16:s17 vertex buffer at API slot 1" are user-data slots
     *   4, 6 and 8 - the SAME shape as ws_E_ViewportToNDC=ws_F_ViewportToNDC's {4, 6, 8} above. The packed varying
     *   layout (S5-COVERAGE-PART2.md Q2) changes only how K's vertex OUTPUTS are stored to the attribute ring; it
     *   does not add, remove or move any of these three raw-pointer INPUT arguments. Vertex: s_n is user-data
     *   slot n (GS_USER_SGPR0 = 8 already subtracted, as user_data_index already carries it). */
    { "ws_K_VfxU11Xh", 126u, 0x0d6797cfu, 1u, 3u, { 4u, 6u, 8u, 0u } },
    /* COVERAGE TASK S5 PART 2c, re/pc-26.6.2/xlat/windowserver-r2/work/AI,AN/TmuaXh_Isrc_Isrc
     *   .abi.json (both files, identical role lists - AN is a second compile of AI's own function) — "s0:s1
     *   descriptor table (class 19)", "s4:s5 sampler-index table (class 11 - S5-COVERAGE-PART2.md Q1, a POINTER
     *   the program dereferences exactly like any class-2/class-3 word, never excluded the way the ring-offsets
     *   load is)", "s6:s7 buffer location 1 (uniforms)", "s8:s9 buffer location 2 (lod_bias)". The two texture
     *   words (s10:s11, s12:s13, class 1) are i32 image-table INDICES, not raw pointers, exactly as every other
     *   texture argument in this file is excluded. Fragment: s_n is user-data slot n. The JSON declares FOUR
     *   pointers total (the class-11 table makes a fourth where AJ/AK/AL/P had three); all four are transcribed
     *   here, at XLAT12_ABI_PTR_MAX. */
    { "ws_AI_TmuaXh_Isrc_Isrc", 119u, 0xae6c50d3u, 0u, 4u, { 0u, 4u, 6u, 8u } },
    { "ws_AN_TmuaXh_Isrc_Isrc", 122u, 0x7b3a6dfeu, 0u, 4u, { 0u, 4u, 6u, 8u } },
    /* COVERAGE TASK S5 PART 2c, re/pc-26.6.2/xlat/windowserver-r2/work/AO/
     *   TmuaXh_IsrcCcl_Icir.abi.json — a DIFFERENT function from AI/AN, with NO class-11 word: "s0:s1 descriptor
     *   table (class 19)", "s4:s5 buffer location 1 (uniforms)", "s6:s7 buffer location 2 (lod_bias)" - the same
     *   shape as ws_AJ/ws_AK/ws_AL/ws_P above. Its texture (s8:s9, class 1) and sampler (s10:s11, class 2) are
     *   i32 index pairs into the descriptor table, not raw pointers, so they are not transcribed here either.
     *   Fragment: s_n is user-data slot n. */
    { "ws_AO_TmuaXh_IsrcCcl_Icir", 168u, 0xb4fc3c24u, 0u, 3u, { 0u, 4u, 6u, 0u } },
    /* COVERAGE TASK S6 (decide44 survey, notes/logs/runs/decide44/coverage/), re/pc-26.6.2/xlat/windowserver-r2/
     *   work/{O,Q,R}/(each label).abi.json — all three declare the SAME shape as P/AJ/AK/AL above: "s0:s1 descriptor table
     *   (class 19)", "s4:s5 buffer location 1 (uniforms)", "s6:s7 buffer location 2 (lod_bias)"; the texture
     *   (s8:s9, class 1) and sampler (s10:s11, class 2) entries are index pairs into the table, not raw pointers,
     *   so they are not transcribed here, exactly as P/AJ/AK/AL's are not. O is a further compile of
     *   ws_P_TimgXh_Ialp's function, Q of ws_AL_TimgXh_Isrc's, R of ws_AK_TsplXh_Isrc's. Disassembly
     *   (`llvm-objdump --mcpu=gfx1201` over each .pal.o) shows O and R overwrite s4/s6 with computed table
     *   offsets before any load (the declared buf1/buf2 pointers are unused by these two compiles, same as
     *   AJ/AK/AL); Q likewise. Fragment: s_n is user-data slot n. */
    { "ws_O_TimgXh_Ialp", 48u, 0x2c3e5423u, 0u, 3u, { 0u, 4u, 6u, 0u } },
    { "ws_Q_TimgXh_Isrc", 52u, 0x10d37dfdu, 0u, 3u, { 0u, 4u, 6u, 0u } },
    { "ws_R_TsplXh_Isrc", 86u, 0xd79fb515u, 0u, 3u, { 0u, 4u, 6u, 0u } },
    /* COVERAGE TASK S6 (decide44 survey), re/pc-26.6.2/xlat/windowserver-r2/work/S/TimgXhu_Idfr.abi.json — the
     *   SAME shape as O/Q/R above ("s0:s1 descriptor table (class 19)", "s4:s5 buffer location 1 (uniforms)",
     *   "s6:s7 buffer location 2 (lod_bias)"), but UNLIKE O/Q/R this compile actually DEREFERENCES buf1: `llvm-
     *   objdump --mcpu=gfx1201` shows `s_load_b128 s[0:3], s[4:5], 0x0` at +0xAC (CONFIRMED), proving the shape
     *   live for this family, not merely declared. Fragment: s_n is user-data slot n. */
    { "ws_S_TimgXhu_Idfr", 85u, 0xd0a62abeu, 0u, 3u, { 0u, 4u, 6u, 0u } },
    /* COVERAGE TASK S6 (decide44 survey), re/pc-26.6.2/xlat/windowserver-r2/work/{W,X}/(each label).abi.json — both declare
     *   the SAME shape as AE/AM/AD above: "s0:s1 descriptor table (class 19)", "s4 texture location 3 (texture0):
     *   image table index" (i32, not a pointer), "s6 sampler location 0 (sampler0): sampler table index" (i32,
     *   not a pointer), "s8:s9 buffer location 1 (u)" and "s10:s11 buffer location 6 (edr_scale)" (both raw
     *   pointers). W is a further compile of ws_AE_downsample_4_frag_lph's/ws_AF's family; X is a further compile
     *   of ws_AM_narrow_blur_11_frag_lph's family. Disassembly (`llvm-objdump --mcpu=gfx1201`, CONFIRMED): W has
     *   `s_load_b256 s[20:27], s[8:9], 0x0` and `global_load_d16_b16 v34, v34, s[10:11]`; X has
     *   `s_load_b64 s[4:5], s[8:9], 0x40` and `global_load_d16_b16 v4, v4, s[10:11]`. Both dereference their
     *   declared pointers directly, like AE/AD. Fragment: s_n is user-data slot n. */
    { "ws_W_downsample_8_frag_lph", 246u, 0xcdd8abb9u, 0u, 3u, { 0u, 8u, 10u, 0u } },
    { "ws_X_narrow_blur_7_frag_lph", 118u, 0xc5e80d66u, 0u, 3u, { 0u, 8u, 10u, 0u } },
    /* COVERAGE TASK S6 batch 1 (notes/design/S6-COVERAGE-PART2.md Q1/Q2/Q4), transcribed from the JUST-REBUILT
     * re/pc-26.6.2/xlat/windowserver-r2/work/{AB,AC,T}/ (each label's own .abi.json, tools/m4-xlat/ws_programs.py
     * translate --round 2):
     *   AB (TcimXh_Icir.abi.json) — ONE user_data entry: "s2:s3 buffer location 1 (uniforms)" (class 3, evidence
     *     apple_record). No descriptor table (AB samples nothing: same shape as AH/AA/AG - class NONE per
     *     tools/gfx-shader-desc.py, so this buffer is declared but not dereferenced by this compile, same as
     *     O/Q/R's above - still transcribed, fail-open direction). Fragment: s_n is user-data slot n.
     *   AC (variable_blur_vert_lph.abi.json) — a VERTEX row, user data starting at s8 (vs_vertex_start), so THREE
     *     64-bit pointers at user-data slots 4/6/8 (sgprs [12:13]/[14:15]/[16:17]): "s12:s13 buffer location 2
     *     (mvp_matrix)", "s14:s15 buffer location 3 (texmat)", "s16:s17 vertex buffer at API slot 1 (fetch, stride
     *     48)" - the CLIENT's own vertex attribute data, never the ring-offsets/attribute-ring this file's own
     *     banner excludes (those are s0:s1, OUR mapping, and do not appear here). The class-7 apiSlot-1 word
     *     (u32 0x00001070, role "SUSPECTED, never read") carries no sgprs at all (a single-word marker, not a
     *     64-bit pointer pair) and is not transcribed, same reasoning as every non-pointer class already excluded
     *     above.
     *   T (Tc3sXhu_Idst.abi.json) — TWO user_data pointer entries: "s0:s1 descriptor table" (class 19) and "s4:s5
     *     buffer location 1 (uniforms)" (class 3). The texture-index word ("s6:s7 texture location 0
     *     (attachment_0)", class 1) is an INDEX into the descriptor table the class-19 slot already names, not a
     *     raw pointer - excluded, exactly as every class-1/class-2 table-indexed entry above is excluded. This is
     *     the SAME class-19 "no sampler" shape S6-COVERAGE-PART2.md Q4/Q8 names for the kext's own batch-2 work
     *     (no class-2 sampler word at all); this row exists only for tools/gfx-readset.py's proof and the kext
     *     track's future kDTableAbi row - it changes nothing translatable today (T has no kDTableAbi row).
     *     Fragment: s_n is user-data slot n. */
    { "ws_AB_TcimXh_Icir", 96u, 0xb5f82cf4u, 0u, 1u, { 2u, 0u, 0u, 0u } },
    { "ws_AC_variable_blur_vert_lph", 101u, 0x0f5fd702u, 1u, 3u, { 4u, 6u, 8u, 0u } },
    { "ws_T_Tc3sXhu_Idst", 103u, 0xdb5bb19du, 0u, 2u, { 0u, 4u, 0u, 0u } },
    /* COVERAGE TASK S6 batches 2 + 3 (notes/design/S6-COVERAGE-PART2.md Q7/Q8, design/NO-SAMPLER-CLASS10.md
     * section 4), transcribed from the JUST-REBUILT re/pc-26.6.2/xlat/windowserver-r2/work/{AP..AY}/ (each
     * label's own .abi.json, tools/m4-xlat/ws_programs.py translate --round 2). Every row excludes class-1
     * (texture index) and class-2 (sampler index) words - not raw pointers, same reasoning as every row above.
     * Fragment: s_n is user-data slot n. [build 0.0.470: XLAT12_ABI_PTR_MAX is now 6 and AZ's and J's rows are
     * at the end of this table; the paragraph below is the 5636278/7f075b2 record of why they were held back.]
     * AZ (TimgBdrkXhn_IsrcCrd, class 10) is DELIBERATELY NOT ADDED: its own
     * ABI JSON declares FIVE pointers (table s0, class-10 texture-table s4, buffers s6/s8/s10) and
     * XLAT12_ABI_PTR_MAX is 4 (this file, line ~34) - a row here would either silently drop one pointer (the
     * exact latent truncation design/NO-SAMPLER-CLASS10.md section 2 already names, xlat12_ib.c's
     * `q < ap->nptr && q < XLAT12_ABI_PTR_MAX` with no `in_over`, OFF LIMITS in this task) or require growing
     * XLAT12_ABI_PTR_MAX, which resizes `in_ptr`/`in_vptr` in xlat12_ib.h and is read throughout xlat12_ib.c -
     * both off limits here. STOPPED; see the report. AZ's ndw/fnv (181 / 0xf27e9612) and its texture_table
     * (reg [4,5], api_slot 0, entries {0:0x00, 3:0x18, 9:0x48}) are recorded in the report for the kext track.
     * COVERAGE TASK S6 batch 5 (S6-COVERAGE-PART2.md Q3, J = VfxXghb, 0xfcc6342ea8db283f): the SAME limit
     * stops J too, for the SAME reason - its own re-transcribed .abi.json (tools/m4-xlat/ws_programs.py
     * translate --round 2 --only '^VfxXghb$', this task) declares FIVE 64-bit pointers, no table/texture/
     * sampler at all: two class-7 words (s0, s1 - unread, S6 batch 1's "role SUSPECTED, never read" class)
     * plus five class-3 buffers at s4:5/s6:7/s8:9/s10:11/s12:13 (apiSlot 0-4). NOT ADDED here, same STOPPED
     * reasoning as AZ. J's own ndw/fnv were NOT computed in this task (out of scope: xlat12_shader_ids.h is
     * not in this task's edit list) - apple_L 291, key 0xfcc6342ea8db283f, no table/tex/samp classes are
     * recorded in the S6 report for the kext track to compute them from.
     *   AP (Tc4pXh_Idst) — table (class 19) + buffer location 1 (class 3); texture location 0 excluded (class 1).
     *   AQ (TcimXh_Icir, second Apple record 0x024d2750cb0180d5) — ONE pointer, buffer location 1 (class 3);
     *     NO descriptor table at all (AB's own NONE shape - AB/AQ share AIR module ws_068780).
     *   AR (TcimBltnXh_Icir) — table + buffer location 1; texture location 0 excluded. Same shape as AP.
     *   AS (TbdsXh_Icir_Isrc) — table + buffer location 1 (lod_bias source) + buffer location 2; texture
     *     locations 0/4 and the sampler excluded (classes 1/2).
     *   AT (TbdsXh_Isup_Isrc) — same shape as AS.
     *   AU (TcimXh_Isrc, key 0x24c79680c102f46f) — table + buffer location 1 + buffer location 2; texture
     *     location 3 and the sampler excluded. CHECKED not AJ's object (different L/record_sha256, see
     *     tools/m4-xlat/ws_programs.py's ROUND2 comment for this key) - its own ndw 86 differs from AJ's 83.
     *   AV/AW/AX (BdsoXh/BlsoXh/BvcmXh) — table + buffer location 1; texture location 0 excluded. Same shape
     *     as AP/AR (T's no-sampler shape).
     *   AY (TimgXh_IsrcN3Oc3mtc3nlnlnl) — table + buffer location 1 + buffer location 2 + buffer location 4
     *     (colorP); texture location 3 and the sampler excluded. */
    { "ws_AP_Tc4pXh_Idst", 56u, 0xdd2af62du, 0u, 2u, { 0u, 4u, 0u, 0u } },
    { "ws_AQ_TcimXh_Icir", 99u, 0x3a82204fu, 0u, 1u, { 2u, 0u, 0u, 0u } },
    { "ws_AR_TcimBltnXh_Icir", 138u, 0xa5000f40u, 0u, 2u, { 0u, 4u, 0u, 0u } },
    { "ws_AS_TbdsXh_Icir_Isrc", 120u, 0x71ab2622u, 0u, 3u, { 0u, 4u, 6u, 0u } },
    { "ws_AT_TbdsXh_Isup_Isrc", 191u, 0xafe6b4ecu, 0u, 3u, { 0u, 4u, 6u, 0u } },
    { "ws_AU_TcimXh_Isrc", 86u, 0x0e94d9e2u, 0u, 3u, { 0u, 4u, 6u, 0u } },
    { "ws_AV_BdsoXh", 84u, 0x4c6d57deu, 0u, 2u, { 0u, 4u, 0u, 0u } },
    { "ws_AW_BlsoXh", 88u, 0x814caab6u, 0u, 2u, { 0u, 4u, 0u, 0u } },
    { "ws_AX_BvcmXh", 170u, 0x0e3b2d5au, 0u, 2u, { 0u, 4u, 0u, 0u } },
    { "ws_AY_TimgXh_IsrcN3Oc3mtc3nlnlnl", 279u, 0x46e5cc0eu, 0u, 4u, { 0u, 4u, 6u, 10u } },
    /* COVERAGE TASK S6 batch 4 (notes/design/S6-COVERAGE-PART2.md Q5/Q7/Q8), re/pc-26.6.2/xlat/windowserver-r2/
     *   work/{BA,BB}/(each label).abi.json — WORD-FOR-WORD IDENTICAL role lists to ws_AI_TmuaXh_Isrc_Isrc's own:
     *   "s0:s1 descriptor table (class 19)", "s4:s5 sampler-index table (class 11)", "s6:s7 buffer location 1
     *   (uniforms)", "s8:s9 buffer location 2 (lod_bias)" - the SAME four raw pointers at the SAME slots as AI/AN
     *   above (the two texture words at s10:s11/s12:s13, class 1, are i32 image-table indices, not raw pointers,
     *   excluded the same way). BA is TdfgXh_Isrc; BB is TbvcXh_Isrc_Isrc (AC's third fragment draw partner,
     *   F00044 0x400603900). Fragment: s_n is user-data slot n. */
    { "ws_BA_TdfgXh_Isrc", 120u, 0x8e1812e4u, 0u, 4u, { 0u, 4u, 6u, 8u } },
    { "ws_BB_TbvcXh_Isrc_Isrc", 207u, 0x6be37df7u, 0u, 4u, { 0u, 4u, 6u, 8u } },
    /* COVERAGE TASK S6 batch 4 (notes/design/S6-COVERAGE-PART2.md Q5/Q7/Q8), re/pc-26.6.2/xlat/windowserver-r2/
     *   work/BC/TimgXh_IsrcCcl.abi.json — WORD-FOR-WORD IDENTICAL role list to ws_AO_TmuaXh_IsrcCcl_Icir's own
     *   (NO class-11 word): "s0:s1 descriptor table (class 19)", "s4:s5 buffer location 1 (uniforms)", "s6:s7
     *   buffer location 2 (lod_bias)" - the same shape as ws_AJ/ws_AK/ws_AL/ws_P/ws_AO above. Its texture (s8:s9,
     *   class 1) and sampler (s10:s11, class 2) are i32 index pairs into the descriptor table, not raw pointers,
     *   so they are not transcribed here either. Fragment: s_n is user-data slot n. */
    { "ws_BC_TimgXh_IsrcCcl", 60u, 0xd53dee91u, 0u, 3u, { 0u, 4u, 6u, 0u } },
    /* build 0.0.470 (notes/design/NO-SAMPLER-CLASS10.md section 2, XLAT12_ABI_PTR_MAX 4 -> 6), re/pc-26.6.2/xlat/
     *   windowserver-r2/work/AZ/TimgBdrkXhn_IsrcCrd.abi.json `args` (CONFIRMED, read by this build): "s0:s1 descriptor
     *   table (class 19)", "s4:s5 texture-index table (class 10, apiSlot 0)", "s6:s7 buffer location 1 (uniforms)",
     *   "s8:s9 buffer location 2 (lod_bias)", "s10:s11 buffer location 5 (noise_scale)" - FIVE pointers; the class-2
     *   sampler word (s12, i32 index) is not a pointer, excluded as everywhere above. The class-10 pointer IS a pointer
     *   the program dereferences (its .pal.o, llvm-objdump --mcpu=gfx1201: +0x24 F4000382 `s_load_b32 s14, s[4:5],
     *   0x18`, +0x2C F40003C2 `s_load_b32 s15, s[4:5], 0x48`, +0x5C F4000842 `s_load_b32 s33, s[4:5], 0x0`), so its
     *   page is Apple's texture-entry table - xlat12_ib.c's class-10 step REQUIRES this row to declare slot 4 (the
     *   entry-table page is otherwise named by nothing). ndw/fnv: this .pal.o's own .text to s_endpgm (+0x2D0 + 4 =
     *   181 dw, FNV-1a 0xf27e9612), equal to xlat12_shader_ids.h's ws_AZ_TimgBdrkXhn_IsrcCrd row.
     * work/J/VfxXghb.abi.json `user_data` (CONFIRMED): a VERTEX program, user data from s8, FIVE class-3 buffers at
     *   sgprs 12:13 / 14:15 / 16:17 / 18:19 / 20:21 = user_data_index 4 / 6 / 8 / 10 / 12 ("buffer location 1
     *   (vertex_buffer)", "0 (config)", "2 (mvp_matrix)", "3 (texture_matrix)", "4 (chroma_matrix)"); the two class-7
     *   words (vertex start s8, apiSlot 1 never read) carry no pointer. Disassembly: `global_load_d16_u8 ... s[14:15]`
     *   (+0x58), `v_mad_co_u64_u32 ... s[12:13]` (+0x16C), `s_load_b128 s[8:11], s[18:19], 0x0` (+0x2D0), `s_load_b512
     *   s[36:51], s[16:17], 0x0` (+0x354), `s_load_b128 s[8:11], s[20:21], 0x0` (+0x338). ndw/fnv from its .pal.o
     *   (+0x488 + 4 = 291 dw, FNV-1a 0xfa0982ef - computed by this build; J has NO xlat12_shader_ids.h identity row yet,
     *   so this row is reachable by nothing until the tools track ships one: it changes no translation today).
     *   build 0.0.504: J's identity row ships (tools/gfx-shader-ids.py WS_SHIP_LABELS), so this row is
     *   now REACHED (d_vs_abi_ptr_of); re-checked against the .pal.o (llvm-objdump --mcpu=gfx1201): +0x58 EE07800E
     *   00000000 00000200 `global_load_d16_u8 v0, v0, s[14:15] offset:2`, +0x2D0 F4004209 F8000000 `s_load_b128 s[8:11],
     *   s[18:19], 0x0`, +0x338 F400420A F8000000 `s_load_b128 s[8:11], s[20:21], 0x0`, +0x354 F4008908 F8000000
     *   `s_load_b512 s[36:51], s[16:17], 0x0`, +0x488 BFB00000 s_endpgm; xlat12_readset.h's J row (the generator's own
     *   trace, pd1 1) names exactly these five slots. */
    { "ws_AZ_TimgBdrkXhn_IsrcCrd", 181u, 0xf27e9612u, 0u, 5u, { 0u, 4u, 6u, 8u, 10u, 0u } },
    { "ws_J_VfxXghb", 291u, 0xfa0982efu, 1u, 5u, { 4u, 6u, 8u, 10u, 12u, 0u } },
    /* build 0.0.484 (notes/design/GLASS.md Q4) — ws_BD_glass_background_lph / ws_BE_glass_background_lph, FRAGMENT,
     * the GLASS v3 build's work/{BD,BE}/glass_background_lph.abi.json `user_data` (CONFIRMED, identical for the two):
     * "descriptor table" class 19 at sgprs [0,1]; "buffer location 1 (u)" class 3 at [8,9]; "buffer location 6
     * (edr_scale)" class 3 at [10,11] - THREE 64-bit pointers. The two class-1 words (s4 source_texture, s6 sdf_texture)
     * are i32 image indices, not pointers, excluded as everywhere above. Each is dereferenced in the program's own .pal.o
     * (llvm-objdump --mcpu=gfx1201; each offset read in BOTH objects - the two images first differ at +0x27C): +0x20 F4002600 `s_load_b64 s[24:25],
     * s[0:1], 0x0` (the table), +0x144 F4004004 `s_load_b128 s[0:3], s[8:9], 0x0` and +0x3D8 EE08C008 `global_load_d16_hi_b16
     * v4, v9, s[8:9] offset:206` (u), BD +0x138C / BE +0x1388 EE08000A `global_load_d16_b16 v0, v0, s[10:11]` (edr_scale).
     * ndw/fnv: 1271/0x3858ea3a (BD), 1269/0x0ca63b3c (BE), recomputed from each .pal.o's .text - xlat12_ib.c's kDTableAbi
     * rows 33-34 carry the same pair. 3 <= XLAT12_ABI_PTR_MAX. */
    { "ws_BD_glass_background_lph", 1271u, 0x3858ea3au, 0u, 3u, { 0u, 8u, 10u, 0u, 0u, 0u } },
    { "ws_BE_glass_background_lph", 1269u, 0x0ca63b3cu, 0u, 3u, { 0u, 8u, 10u, 0u, 0u, 0u } },
    /* build 0.0.491 — the two of the four new kDTableAbi rows (xlat12_ib.c, indices 35-38) that had NO row
     * here (AO and AN already do, above). FRAGMENT; s_n is user-data slot n; class-1/class-2 words are i32 table indices,
     * not pointers, excluded as everywhere above.
     *   ws_Z_TimgXh_Isrc - re/pc-26.6.2/xlat/windowserver-r2/work/Z/TimgXh_Isrc.abi.json `user_data` (CONFIRMED, read by this
     *     build): "descriptor table" class 19 [0,1]; "buffer location 1 (uniforms)" class 3 [4,5]; "buffer location 2
     *     (lod_bias)" class 3 [6,7] - THREE pointers, the SAME shape as ws_AL/ws_Q/ws_BC above. Like O/Q/R, this compile
     *     overwrites s4/s6 with computed table offsets before any load (+0x34 8404840A s_lshl_b32 s4, s10, 4; +0x38
     *     84068508 s_lshl_b32 s6, s8, 5), so the two buffers are declared but not dereferenced - still transcribed (a row
     *     that lists fewer than the JSON declares is the fail-open direction). ndw/fnv 54/0xf91e4dee from its .pal.o.
     *   ws_AF_variable_blur_downsample_frag_lph - work/AF/variable_blur_downsample_frag_lph.abi.json `user_data` (CONFIRMED):
     *     "descriptor table" class 19 [0,1]; "buffer location 1 (u)" class 3 [8,9]; "buffer location 6 (edr_scale)" class 3
     *     [10,11] - THREE pointers, the SAME shape as ws_AE/ws_W above. u is dereferenced: +0x20 F400A204 F8000000
     *     `s_load_b96 s[8:10], s[8:9], 0x0`; ndw/fnv 173/0x1051f3f6 from its .pal.o. */
    { "ws_Z_TimgXh_Isrc", 54u, 0xf91e4deeu, 0u, 3u, { 0u, 4u, 6u, 0u, 0u, 0u } },
    { "ws_AF_variable_blur_downsample_frag_lph", 173u, 0x1051f3f6u, 0u, 3u, { 0u, 8u, 10u, 0u, 0u, 0u } },
    /* build 0.0.507 (: frame a's "consumer-inputs-unproven" was THIS gap) - the two kDTableAbi rows
     * (xlat12_ib.c, ws_U_TvcmXh_Isrc and ws_Y_TkfhBvcmXh_Isrc, 0.0.445) that had NO row here, so xlat12_abi_ptr_row
     * returned NULL for them, d_table_desc left in_ptr_known 0 and d_readset_from_table declined every U/Y segment.
     * FRAGMENT; s_n is user-data slot n; class-1/class-2 words are i32 table indices, not pointers, excluded as
     * everywhere above.
     *   ws_U_TvcmXh_Isrc - re/pc-26.6.2/xlat/windowserver-r2/work/U/TvcmXh_Isrc.abi.json `user_data` (CONFIRMED, read by
     *     this build): "descriptor table" class 19 sgprs [0,1]; "buffer location 1 (uniforms)" class 3 [4,5]; "buffer
     *     location 2 (lod_bias)" class 3 [6,7] - THREE pointers (the JSON `args` agree: `ptr addrspace(1)` "s0:s1
     *     descriptor table (class 19)", `ptr addrspace(4)` "s4:s5 buffer location 1 (uniforms)" and "s6:s7 buffer
     *     location 2 (lod_bias)"); the class-1 words s8/s10 and the class-2 word s12 are indices. The SAME shape as
     *     ws_AO/ws_AL/ws_Z above. Disassembly (llvm-objdump --mcpu=gfx1201 over work/U/TvcmXh_Isrc.pal.o, CONFIRMED):
     *     the table - +0x24 F4002080 F8000000 `s_load_b64 s[2:3], s[0:1], 0x0`, +0x3C F4002000 F8000010 `s_load_b64
     *     s[0:1], s[0:1], 0x10`; uniforms, s4/s5 not written before - +0xD8 F4006202 F80000D0 `s_load_b256 s[8:15],
     *     s[4:5], 0xd0`, +0xE0 F4004002 F80000F0 `s_load_b128 s[0:3], s[4:5], 0xf0`, +0x1A4 EE080004 00000002 0000FA02
     *     `global_load_d16_b16 v2, v2, s[4:5] offset:250`; lod_bias - the FIRST instruction, +0x0 BE86017E `s_mov_b64
     *     s[6:7], exec`, overwrites s6:s7, so this compile never dereferences it (as O/Q/R/Z above): still transcribed,
     *     a row listing fewer than the JSON declares is the fail-open direction. ndw/fnv from the .pal.o's .text to its
     *     s_endpgm (+0x2FC BFB00000, +4 = 192 dw), FNV-1a 0x92c6ae13 - equal to xlat12_shader_ids.h's row.
     *   ws_Y_TkfhBvcmXh_Isrc - work/Y/TkfhBvcmXh_Isrc.abi.json `user_data` and `args` (CONFIRMED): WORD-FOR-WORD the same
     *     six entries as U's (class 19 [0,1], class 3 [4,5] uniforms, class 3 [6,7] lod_bias, class 1 [8,9] [10,11],
     *     class 2 [12,13]) - THREE pointers. Disassembly (work/Y/TkfhBvcmXh_Isrc.pal.o, CONFIRMED): table - +0x28
     *     F4002180 F8000010 `s_load_b64 s[6:7], s[0:1], 0x10`, +0x30 F4002000 F8000000 `s_load_b64 s[0:1], s[0:1],
     *     0x0`; uniforms - +0xD0 F4006202 F80000D0 `s_load_b256 s[8:15], s[4:5], 0xd0`, +0x29C F4002182 F80000F0
     *     `s_load_b64 s[6:7], s[4:5], 0xf0`, +0x320 F4006402 F8000060 `s_load_b256 s[16:23], s[4:5], 0x60`, +0x328
     *     F4004002 F8000080 `s_load_b128 s[0:3], s[4:5], 0x80`; lod_bias - +0xC BE86017E `s_mov_b64 s[6:7], exec`
     *     overwrites s6:s7 before any read (declared, not dereferenced, transcribed as U's). ndw/fnv 372/0x5276813b from
     *     its .pal.o (last s_endpgm +0x5CC). xlat12_readset.h's U and Y rows (the generator's trace) name {0, 4}, a
     *     subset of these rows, which is what tests/test_xlat12_readset.py's T9 requires. */
    { "ws_U_TvcmXh_Isrc", 192u, 0x92c6ae13u, 0u, 3u, { 0u, 4u, 6u, 0u, 0u, 0u } },
    { "ws_Y_TkfhBvcmXh_Isrc", 372u, 0x5276813bu, 0u, 3u, { 0u, 4u, 6u, 0u, 0u, 0u } },
    { "auto_30175339f228ee40_ColorFill", 11u, 0x2b838958u, 0u, 1u, { 2u, 0u, 0u, 0u, 0u, 0u } },
    { "auto_48a620ac0cd34f7b_TextureCopy", 42u, 0x1ddbfcadu, 0u, 1u, { 0u, 0u, 0u, 0u, 0u, 0u } },
    { "auto_84d569f083beebcf_Xh", 44u, 0xe2a4684fu, 0u, 1u, { 2u, 0u, 0u, 0u, 0u, 0u } },
    { "auto_a9d10afff5119cf7_TimgXh_Icir", 88u, 0xd7da98f7u, 0u, 1u, { 2u, 0u, 0u, 0u, 0u, 0u } },
    { "auto_aced7bbdf1364f5b_Xh", 46u, 0xe8ac2fb4u, 0u, 1u, { 2u, 0u, 0u, 0u, 0u, 0u } },
    { "auto_ae2b837529686a1c_TimgXh_Icir", 90u, 0x290890a3u, 0u, 1u, { 2u, 0u, 0u, 0u, 0u, 0u } },
};
#define XLAT12_ABI_PTR_ROWS (sizeof kXlat12AbiPtrs / sizeof kXlat12AbiPtrs[0])

/* 0.0.391 — THE ROW FOR A PROGRAM IDENTITY **AT A NAMED STAGE**, or NULL; NULL means UNKNOWN,
 * never "declares no pointers".
 *
 * WHY THE STAGE IS NOW PART OF THE KEY. Through 0.0.390 the only lookup was by (ndw, fnv), and its ONE non-test caller
 * passed a FRAGMENT identity (xlat12_ib.c's kDTableAbi rows) - so the three vertex rows below were reachable by nothing
 * and checked by nothing: the adversarial review of 0.0.390 found them dead data. They are wired now
 * (d_table_desc gathers the vertex stage's declared pointers beside the fragment's), and a stage-keyed lookup is what
 * makes it impossible for one stage's row to be served to the other if two programs ever collide on (ndw, fnv). */
static inline const xlat12_abi_ptrs *xlat12_abi_ptr_row_stage(uint32_t ndw, uint32_t fnv, uint32_t stage)
{
    for (uint32_t i = 0; i < XLAT12_ABI_PTR_ROWS; i++)
        if (kXlat12AbiPtrs[i].ndw == ndw && kXlat12AbiPtrs[i].fnv == fnv && kXlat12AbiPtrs[i].stage == stage)
            return &kXlat12AbiPtrs[i];
    return 0;
}

/* The FRAGMENT row for an identity, or NULL. 0.0.390's spelling, now stage-keyed: every caller it ever had passed a
 * fragment identity, so this is a tightening and not a change of behaviour for any of them. */
static inline const xlat12_abi_ptrs *xlat12_abi_ptr_row(uint32_t ndw, uint32_t fnv)
{
    return xlat12_abi_ptr_row_stage(ndw, fnv, 0u);
}

/* build 0.0.470 (notes/design/NO-SAMPLER-CLASS10.md section 2, "the latent silent truncation"): THE ONE PLACE A
 * ROW'S POINTER COUNT IS READ. Returns how many of `ap`'s pointers a reader may walk (min(nptr, XLAT12_ABI_PTR_MAX))
 * and, when the row declares MORE than that, sets `*over` to 1 - the reader's list is then incomplete, which every
 * consumer of xlat12_draw_stats.in_over already refuses on. Through 0.0.455 every loop read `q < ap->nptr && q <
 * XLAT12_ABI_PTR_MAX` and a longer row simply lost its tail with nothing set. `ap` NULL returns 0 and leaves *over
 * alone (no row is UNKNOWN, a separate fact the callers already carry as in_ptr_known / in_vptr_known). */
static inline uint32_t xlat12_abi_ptr_n(const xlat12_abi_ptrs *ap, uint32_t *over)
{
    if (!ap) return 0u;
    if (ap->nptr > XLAT12_ABI_PTR_MAX) { if (over) *over = 1u; return XLAT12_ABI_PTR_MAX; }
    return ap->nptr;
}

#endif
