#!/bin/zsh
# census-run.sh <runname> — T1: the read-only DCN 4.1 register census on the PC.
#
#   tools/dcn41/census-run.sh t1a
#
# READ ONLY. The only thing it makes the PC do is `navi48test regs`, whose only kernel call is
# kNavi48SelRegRead (a bare BAR5 dword read, bounds-checked in amd/amdgpu_regs.h). It arms nothing,
# writes no register, loads nothing, and needs no reboot and no deploy: it runs on whatever boot is
# up. The address list is src/dcn41/dcn41_census.tsv, generated by tools/dcn41/gen_census.py from
# dcn_4_1_0_offset.h — no address is typed here.
#
# Two passes. Pass A reads every row; pass B, PASS_GAP seconds later, re-reads the rows the TSV
# marks passes=2 (the OTG status / position / frame-count registers). Every line carries its own
# CLOCK_MONOTONIC_RAW microsecond stamp taken immediately before the read, so the refresh derived
# from two OTG_STATUS_FRAME_COUNT samples uses that register's own elapsed time.
#
# Positive control (rule 25: an empty read set is a claim about the reader): three extra rows are
# appended to each pass — one register whose value is known non-zero and stable on this card
# (MP1 is not read; the control is inside the GC block our ladder already proves), one deliberately
# out-of-window address, and one re-read of the first census row. See CONTROLS below.
set -eu
P=${0:A:h:h:h}
HOST=${NAVI48_HOST:-navi48}
RUN=${1:-t1}
GAP=${PASS_GAP:-10}
TSV="$P/src/dcn41/dcn41_census.tsv"
OUT="$P/notes/logs/runs/$RUN"

[[ -f "$TSV" ]] || { echo "missing $TSV"; exit 1; }
if ! ssh -o BatchMode=yes -o ConnectTimeout=6 "$HOST" true 2>/dev/null; then
  echo "PC ($HOST) not reachable — is it on and booted into macOS?"; exit 1; fi

if [[ -d "$OUT" ]]; then mv "$OUT" "$OUT.$(date +%Y%m%d-%H%M%S)"; fi
mkdir -p "$OUT"

# ---- build the two address lists -------------------------------------------------------------
# columns: group register offset base_idx absolute passes note
awk -F'\t' 'NR>1 && $1 !~ /^#/ && $5 ~ /^0x/ { printf "%s %s/%s\n", $5, $1, $2 }' "$TSV" > "$OUT/listA.txt"
awk -F'\t' 'NR>1 && $1 !~ /^#/ && $5 ~ /^0x/ && $6==2 { printf "%s %s/%s\n", $5, $1, $2 }' "$TSV" > "$OUT/listB.txt"

# CONTROLS (rule 25) — appended to both passes, so "everything read 0" can never be a silent reader
# failure, and so 0xFFFFFFFF is known to be distinguishable from a live read:
#   reread    the first census row again: repeatability inside one pass.
#   0x0fffffff  far outside the BAR5 window (1 MiB = 0x40000 dwords). amd/amdgpu_regs.h RREG32
#               returns 0xFFFFFFFF WITHOUT touching hardware, so this is the negative control.
#   0x00003935  DCN seg2 + 0x475 = DCN_VM_FB_LOCATION_BASE — the one DCN register whose value on this
#               card is already on record (0x00008000, logged: the known-value positive control.
CTRL_REREAD=$(head -1 "$OUT/listA.txt" | awk '{print $1}')
for L in "$OUT/listA.txt" "$OUT/listB.txt"; do
  {
    echo "$CTRL_REREAD control/reread-first-row"
    echo "0x0fffffff control/out-of-window-expect-ffffffff"
    echo "0x00003935 control/DCN_VM_FB_LOCATION_BASE-expect-8000"
  } >> "$L"
done

NA=$(wc -l < "$OUT/listA.txt"); NB=$(wc -l < "$OUT/listB.txt")
echo "census $RUN: pass A $NA rows, pass B $NB rows, gap ${GAP}s -> $OUT"

# ---- pre-run machine state ---------------------------------------------------------------------
ssh "$HOST" 'echo "uptime: $(uptime)"; echo "console user: $(stat -f %Su /dev/console)"; \
  echo "who: $(who | wc -l)"; kmutil showloaded --list-only 2>/dev/null | grep -iE "navi48|rdna4"; \
  echo "gpuRestart files: $(ls /Library/Logs/DiagnosticReports 2>/dev/null | grep -c gpuRestart || true)"' \
  > "$OUT/pre.txt" 2>&1
cat "$OUT/pre.txt"

# ---- the run ------------------------------------------------------------------------------------
scp -q "$OUT/listA.txt" "$OUT/listB.txt" "$HOST:~/navi48-staging/" || { echo "scp of the lists FAILED"; exit 1; }
ssh "$HOST" "sudo ~/navi48-staging/navi48test regs < ~/navi48-staging/listA.txt" > "$OUT/passA.txt" 2>&1 || \
  echo "(pass A returned non-zero — see passA.txt)"
sleep "$GAP"
ssh "$HOST" "sudo ~/navi48-staging/navi48test regs < ~/navi48-staging/listB.txt" > "$OUT/passB.txt" 2>&1 || \
  echo "(pass B returned non-zero — see passB.txt)"

# ---- post-run machine state ---------------------------------------------------------------------
ssh "$HOST" 'echo "uptime: $(uptime)"; echo "console user: $(stat -f %Su /dev/console)"; \
  echo "newest DiagnosticReports:"; ls -lt /Library/Logs/DiagnosticReports 2>/dev/null | head -5' \
  > "$OUT/post.txt" 2>&1
cat "$OUT/post.txt"

echo "--- pass A tail ---"; tail -4 "$OUT/passA.txt"
echo "--- pass B tail ---"; tail -4 "$OUT/passB.txt"
echo "saved to $OUT"
