#!/bin/bash
#
# build-shader.sh — assemble shaders/store_magic.s for gfx1201 (Navi 48,
# GC 12.0.1) and embed the resulting machine code into the kext.
#
# Run it from anywhere; it locates the repo by its own path. Re-run it after
# any edit to shaders/store_magic.s, then `make`.
#
# Outputs (all generated — do not hand-edit):
#   shaders/store_magic.o            ELF relocatable (intermediate, kept)
#   shaders/store_magic.bin          raw .text bytes = what the GPU executes
#   shaders/store_magic.dis          llvm-objdump -d, for the record
#   shaders/store_magic.encoding.txt llvm-mc --show-encoding, for the record
#   shaders/store_magic.kd.txt       the HSA kernel descriptor LLVM computed,
#                                    decoded into COMPUTE_PGM_RSRC1/2/3. These
#                                    are the authoritative values that
#                                    src/amd/compute_test.cpp hardcodes.
#   firmware/shader_store_magic.bin  copy of the blob; the Makefile's
#                                    `firmware/%.bin -> src/fw/fw_%.c` rule
#                                    picks it up automatically, so no Makefile
#                                    change is needed.
#   firmware/WHENCE.shader_store_magic.txt  provenance (it is OURS, not vendor
#                                    firmware — the rest of firmware/ is
#                                    linux-firmware).
#   src/fw/fw_shader_store_magic.c   `const uint8_t fw_shader_store_magic[]`
#                                    + `const size_t fw_shader_store_magic_size`
#
# Toolchain: Homebrew LLVM (the Xcode Command Line Tools clang has no AMDGPU
# backend).  brew install llvm
#
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SHADER_DIR="$REPO/shaders"
FW_BIN_DIR="$REPO/firmware"
FW_SRC_DIR="$REPO/src/fw"

# Which shader to build. No argument = store_magic, exactly as before.
#   build-shader.sh                 -> shaders/store_magic.s   (hand-written)
#   build-shader.sh store_magic_hsa -> shaders/store_magic_hsa.s (LLVM-compiled,
#                                      standard HSA kernarg ABI — see
#                                      notes/B1-COMPILER-BRIDGE.md)
NAME="${1:-store_magic}"
SRC="$SHADER_DIR/$NAME.s"
SYMBOL="fw_shader_$NAME"
if [ ! -f "$SRC" ]; then echo "build-shader.sh: no such shader source: $SRC" >&2; exit 1; fi
MCPU="gfx1201"
TRIPLE="amdgcn-amd-amdhsa"

# ---- toolchain -------------------------------------------------------------
LLVM_BIN="${LLVM_BIN:-/opt/homebrew/opt/llvm/bin}"
if [ ! -x "$LLVM_BIN/llvm-mc" ]; then
    # Fall back to whatever is on PATH (e.g. an Intel-Homebrew prefix).
    LLVM_BIN="$(dirname "$(command -v llvm-mc || true)")" || true
fi
MC="$LLVM_BIN/llvm-mc"
OBJCOPY="$LLVM_BIN/llvm-objcopy"
OBJDUMP="$LLVM_BIN/llvm-objdump"
for t in "$MC" "$OBJCOPY" "$OBJDUMP"; do
    if [ ! -x "$t" ]; then
        echo "build-shader.sh: missing $t" >&2
        echo "  install with: brew install llvm   (or set LLVM_BIN=<llvm>/bin)" >&2
        exit 1
    fi
done

echo "build-shader.sh: $("$MC" --version | sed -n '2p' | tr -s ' ')"
echo "build-shader.sh: target $TRIPLE -mcpu=$MCPU"
echo "build-shader.sh: source $SRC"

# Refuse to run if the assembler cannot even see the AMDGPU backend, rather
# than emitting a plausible-looking empty blob.
if ! "$MC" -triple="$TRIPLE" -mcpu="$MCPU" -show-encoding </dev/null >/dev/null 2>&1; then
    echo "build-shader.sh: $MC has no working $TRIPLE/$MCPU support" >&2
    exit 1
fi

mkdir -p "$SHADER_DIR" "$FW_BIN_DIR" "$FW_SRC_DIR"

# ---- 1. assemble -----------------------------------------------------------
"$MC" -triple="$TRIPLE" -mcpu="$MCPU" -filetype=obj "$SRC" \
      -o "$SHADER_DIR/$NAME.o"

# ---- 2. records: encodings + disassembly -----------------------------------
{
    echo "# llvm-mc -triple=$TRIPLE -mcpu=$MCPU -show-encoding $NAME.s"
    echo "# generated by tools/build-shader.sh — do not edit"
    echo
    "$MC" -triple="$TRIPLE" -mcpu="$MCPU" -show-encoding "$SRC"
} > "$SHADER_DIR/$NAME.encoding.txt"

{
    echo "# llvm-objdump -d --mcpu=$MCPU $NAME.o"
    echo "# generated by tools/build-shader.sh — do not edit"
    echo
    "$OBJDUMP" -d --mcpu="$MCPU" "$SHADER_DIR/$NAME.o"
} > "$SHADER_DIR/$NAME.dis"

# ---- 3. extract the executable bytes ---------------------------------------
# Only .text: the .rodata kernel descriptor is metadata for a HSA loader and
# must NOT be part of the blob the CP points COMPUTE_PGM_LO at.
"$OBJCOPY" -O binary --only-section=.text \
           "$SHADER_DIR/$NAME.o" "$SHADER_DIR/$NAME.bin"

BYTES=$(wc -c < "$SHADER_DIR/$NAME.bin" | tr -d ' ')
if [ "$BYTES" -eq 0 ]; then
    echo "build-shader.sh: .text is empty — nothing was assembled" >&2
    exit 1
fi
if [ $((BYTES % 4)) -ne 0 ]; then
    echo "build-shader.sh: .text is $BYTES bytes, not a whole number of dwords" >&2
    exit 1
fi

# The shader must END. A shader that falls off the end hangs the queue, so this
# check is not optional.
#
# Two shapes are valid:
#   hand-written : the last dword IS s_endpgm (0xBFB00000 -> bytes 00 00 b0 bf)
#   LLVM-compiled: s_endpgm, then s_code_end padding (0xBF9F0000 -> 00 00 9f bf)
#                  out to the instruction-prefetch granule. That padding is
#                  expected on gfx10+ and must not be mistaken for a shader that
#                  runs off the end.
# So: require an s_endpgm, and require everything after it to be s_code_end.
python3 - "$SHADER_DIR/$NAME.bin" <<'ENDCHK'
import sys, struct, pathlib
b = pathlib.Path(sys.argv[1]).read_bytes()
w = [struct.unpack_from("<I", b, i)[0] for i in range(0, len(b), 4)]
S_ENDPGM, S_CODE_END = 0xBFB00000, 0xBF9F0000
if S_ENDPGM not in w:
    sys.exit("build-shader.sh: no s_endpgm anywhere in .text")
i = len(w) - 1 - w[::-1].index(S_ENDPGM)
tail = w[i+1:]
bad = [x for x in tail if x != S_CODE_END]
if bad:
    sys.exit(f"build-shader.sh: {len(bad)} non-padding dword(s) after the last "
             f"s_endpgm (first 0x{bad[0]:08x}) — the shader may run off the end")
print(f"build-shader.sh: s_endpgm at dword {i} ({(i+1)*4} bytes of code)"
      + (f", + {len(tail)} s_code_end padding dwords" if tail else ""))
ENDCHK

# ---- 4. the kernel descriptor LLVM computed --------------------------------
# AMDGPUUsage.rst kernel-descriptor layout:
#   bytes 44-47 COMPUTE_PGM_RSRC3, 48-51 COMPUTE_PGM_RSRC1,
#   bytes 52-55 COMPUTE_PGM_RSRC2, 56-57 KERNEL_CODE_PROPERTIES.
KD="$SHADER_DIR/.$NAME.kd.bin"
"$OBJCOPY" -O binary --only-section=.rodata "$SHADER_DIR/$NAME.o" "$KD"
kd_u32() { od -An -tx4 -j "$1" -N 4 "$KD" | tr -d ' \n'; }
RSRC3="0x$(kd_u32 44)"
RSRC1="0x$(kd_u32 48)"
RSRC2="0x$(kd_u32 52)"
{
    echo "# HSA kernel descriptor computed by LLVM for $NAME (gfx1201)."
    echo "# generated by tools/build-shader.sh — do not edit"
    echo "#"
    echo "# src/amd/compute_test.cpp MUST program these three values:"
    echo "#   kComputePgmRsrc1 = $RSRC1"
    echo "#   kComputePgmRsrc2 = $RSRC2"
    echo "#   kComputePgmRsrc3 = $RSRC3"
    echo "#"
    echo "# raw 64-byte descriptor (.rodata):"
    od -Ad -tx1 "$KD"
} > "$SHADER_DIR/$NAME.kd.txt"
rm -f "$KD"

# ---- 5. embed --------------------------------------------------------------
cp "$SHADER_DIR/$NAME.bin" "$FW_BIN_DIR/shader_$NAME.bin"

cat > "$FW_BIN_DIR/WHENCE.shader_$NAME.txt" <<WHENCE
Blob:     shader_$NAME.bin
Symbol:   $SYMBOL  (src/fw/fw_shader_$NAME.c)
Size:     $BYTES bytes
Origin:   NOT vendor firmware. Unlike every other blob in this directory
          (which comes from linux-firmware — see the other WHENCE files),
          this one is ours: it is the assembled machine code of
          shaders/$NAME.s, a gfx1201 compute shader written for this project.
Build:    tools/build-shader.sh
          llvm-mc -triple=amdgcn-amd-amdhsa -mcpu=gfx1201 -filetype=obj
          llvm-objcopy -O binary --only-section=.text
License:  same as the rest of this repository (see ../LICENSE).
Note:     it lives in firmware/ purely so the Makefile's
          firmware/%.bin -> src/fw/fw_%.c rule embeds it without a Makefile
          change. Regenerate it, never hand-edit it.
WHENCE

# Run from the repo root with RELATIVE paths, exactly as the Makefile's
# `firmware/%.bin -> src/fw/fw_%.c` rule does, so a later `make` regenerating
# this file produces byte-identical output (the generator records its input
# path in a header comment).
( cd "$REPO" && \
  python3 tools/embed-firmware.py \
          "firmware/shader_$NAME.bin" "src/fw/fw_shader_$NAME.c" "$SYMBOL" && \
  python3 tools/embed-firmware.py --verify \
          "firmware/shader_$NAME.bin" "src/fw/fw_shader_$NAME.c" )

# ---- 6. summary ------------------------------------------------------------
echo
echo "build-shader.sh: $BYTES bytes of gfx1201 machine code"
echo "build-shader.sh:   COMPUTE_PGM_RSRC1 = $RSRC1"
echo "build-shader.sh:   COMPUTE_PGM_RSRC2 = $RSRC2"
echo "build-shader.sh:   COMPUTE_PGM_RSRC3 = $RSRC3"
echo "build-shader.sh: first dwords:"
od -An -tx4 -N 32 "$SHADER_DIR/$NAME.bin" | sed 's/^/build-shader.sh:   /'
echo "build-shader.sh: now run  make"
