#!/usr/bin/env python3
"""embed-firmware.py — turn a firmware .bin into a kernel-embeddable C array.

Generate:
    embed-firmware.py <in.bin> <out.c> <symbol>

Writes <out.c> in the same format as the hand-written src/fw/fw_psp_sos.c:

    const size_t <symbol>_size = N;
    const uint8_t <symbol>[] __attribute__((aligned(64))) = { ... };

with a header comment naming the source file, its sha256, and its size, and
the array body rendered 16 bytes per line ("0x%02x," with no space, every
byte comma-terminated, including the last one).

Verify:
    embed-firmware.py --verify <in.bin> <out.c>

Re-parses <out.c> (regardless of its symbol name) and checks that:
  - the declared "<symbol>_size" equals the array's actual element count
  - the array bytes are byte-identical to <in.bin>
  - <in.bin>'s size on disk equals both of the above

Exits 0 and prints "OK: ..." on success, exits 1 and prints "FAIL: ..." with
details on any mismatch. Stdlib only (hashlib, re, sys, argparse, pathlib).
"""

import argparse
import hashlib
import re
import sys
from pathlib import Path

BYTES_PER_LINE = 16
ALIGN = 64

_SIZE_DECL_RE = re.compile(
    r"const\s+size_t\s+(?P<symbol>\w+)_size\s*=\s*(?P<size>\d+)\s*;"
)
_ARRAY_DECL_RE = re.compile(
    r"const\s+uint8_t\s+(?P<symbol>\w+)\s*\[\]\s*"
    r"__attribute__\(\(aligned\(\d+\)\)\)\s*=\s*\{(?P<body>.*?)\};",
    re.DOTALL,
)


def sha256_of(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def render_c_file(data: bytes, symbol: str, source_path: str) -> str:
    size = len(data)
    digest = sha256_of(data)

    lines = []
    lines.append(f"// Auto-generated by tools/embed-firmware.py from {source_path}.")
    lines.append(f"// sha256: {digest}")
    lines.append(f"// size:   {size} bytes")
    lines.append(
        f"// Do not edit — regenerate with "
        f"tools/embed-firmware.py {source_path} <out.c> {symbol}."
    )
    lines.append("#include <stdint.h>")
    lines.append("#include <stddef.h>")
    lines.append(f"const size_t {symbol}_size = {size};")
    lines.append(f"const uint8_t {symbol}[] __attribute__((aligned({ALIGN}))) = {{")

    hex_bytes = [f"0x{b:02x}," for b in data]
    for i in range(0, len(hex_bytes), BYTES_PER_LINE):
        chunk = hex_bytes[i:i + BYTES_PER_LINE]
        lines.append("  " + "".join(chunk))

    lines.append("};")
    return "\n".join(lines) + "\n"


def cmd_generate(in_bin: Path, out_c: Path, symbol: str, source_path_override: str = None) -> int:
    if not in_bin.is_file():
        print(f"FAIL: input file not found: {in_bin}", file=sys.stderr)
        return 1
    data = in_bin.read_bytes()
    source_path = source_path_override if source_path_override is not None else str(in_bin)
    text = render_c_file(data, symbol, source_path)
    out_c.parent.mkdir(parents=True, exist_ok=True)
    out_c.write_text(text)
    print(
        f"wrote {out_c} ({len(data)} bytes from {in_bin}, "
        f"symbol={symbol}, sha256={sha256_of(data)})"
    )
    return 0


def parse_generated_c(out_c: Path):
    """Parse a generated .c file. Returns (symbol, declared_size, array_bytes)."""
    text = out_c.read_text()

    size_m = _SIZE_DECL_RE.search(text)
    if not size_m:
        raise ValueError(f"{out_c}: could not find '<symbol>_size = N;' declaration")
    symbol = size_m.group("symbol")
    declared_size = int(size_m.group("size"))

    array_m = _ARRAY_DECL_RE.search(text)
    if not array_m:
        raise ValueError(f"{out_c}: could not find the uint8_t[] array body")
    if array_m.group("symbol") != symbol:
        raise ValueError(
            f"{out_c}: size symbol '{symbol}_size' does not match "
            f"array symbol '{array_m.group('symbol')}[]'"
        )

    body = array_m.group("body")
    tokens = [t.strip() for t in body.split(",")]
    tokens = [t for t in tokens if t]  # drop empty (trailing comma / whitespace)
    try:
        array_bytes = bytes(int(t, 16) for t in tokens)
    except ValueError as e:
        raise ValueError(f"{out_c}: non-hex token in array body: {e}")

    return symbol, declared_size, array_bytes


def cmd_verify(in_bin: Path, out_c: Path) -> int:
    if not in_bin.is_file():
        print(f"FAIL: input file not found: {in_bin}", file=sys.stderr)
        return 1
    if not out_c.is_file():
        print(f"FAIL: generated file not found: {out_c}", file=sys.stderr)
        return 1

    bin_data = in_bin.read_bytes()

    try:
        symbol, declared_size, array_bytes = parse_generated_c(out_c)
    except ValueError as e:
        print(f"FAIL: {e}", file=sys.stderr)
        return 1

    problems = []
    if declared_size != len(array_bytes):
        problems.append(
            f"declared {symbol}_size={declared_size} but array has "
            f"{len(array_bytes)} elements"
        )
    if len(bin_data) != len(array_bytes):
        problems.append(
            f"{in_bin} is {len(bin_data)} bytes but {out_c} array has "
            f"{len(array_bytes)} bytes"
        )
    if bin_data != array_bytes:
        # Find first differing offset for a useful error message.
        first_diff = next(
            (i for i in range(min(len(bin_data), len(array_bytes)))
             if bin_data[i] != array_bytes[i]),
            None,
        )
        if first_diff is not None:
            problems.append(
                f"byte mismatch at offset {first_diff}: "
                f"bin=0x{bin_data[first_diff]:02x} "
                f"c_array=0x{array_bytes[first_diff]:02x}"
            )
        else:
            problems.append("byte mismatch (length differs, see above)")

    if problems:
        print(f"FAIL: {out_c} does not match {in_bin}:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1

    print(
        f"OK: {out_c} is byte-identical to {in_bin} "
        f"({len(bin_data)} bytes, symbol={symbol}, sha256={sha256_of(bin_data)})"
    )
    return 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        prog="embed-firmware.py",
        description="Embed a firmware .bin as a kernel-safe C byte array, "
                     "or verify a previously generated one.",
    )
    parser.add_argument(
        "--verify", action="store_true",
        help="verify mode: check that <out.c> is byte-identical to <in.bin> "
             "instead of generating a new file",
    )
    parser.add_argument("in_bin", type=Path, help="source firmware .bin")
    parser.add_argument("out_c", type=Path, help="C file to write (generate) or read (verify)")
    parser.add_argument(
        "symbol", nargs="?", default=None,
        help="C symbol base name (required for generate; ignored for --verify)",
    )

    args = parser.parse_args(argv)

    if args.verify:
        return cmd_verify(args.in_bin, args.out_c)

    if not args.symbol:
        parser.error("symbol is required unless --verify is given")
    return cmd_generate(args.in_bin, args.out_c, args.symbol)


if __name__ == "__main__":
    sys.exit(main())
