/*
 * dcn41_allow.c - the DCN 4.1 display write allowlist. See dcn41_allow.h for the promise it keeps.
 *
 * The order of the checks in dcn41_allow_classify() is the whole design: the two hard denials run
 * BEFORE the allow table, so no range - not even a mis-generated one - can make an indirect window
 * or an SMU block writable.
 */
#include "dcn41_allow.h"
#include "dcn41_allow_ranges.h"   /* GENERATED by tools/dcn41/gen_allow.py; included exactly here */

#pragma GCC poison float double

static const char *const k_reason_name[DCN41_ALLOW_REASON_COUNT] = {
    "OK", "UNARMED", "WINDOW", "INDIRECT", "BLOCK", "RANGE"
};

const char *dcn41_allow_reason_name(int reason)
{
    if (reason < 0 || reason >= (int)DCN41_ALLOW_REASON_COUNT)
        return "?";
    return k_reason_name[reason];
}

uint32_t dcn41_allow_range_count(void)
{
    return DCN41_ALLOW_RANGE_COUNT;
}

uint32_t dcn41_allow_total_dwords(void)
{
    return DCN41_ALLOW_TOTAL_DWORDS;
}

int dcn41_allow_range_at(uint32_t index, uint32_t *abs_lo, uint32_t *abs_hi, uint32_t *base_idx,
                         const char **name)
{
    if (index >= DCN41_ALLOW_RANGE_COUNT)
        return -1;
    if (abs_lo)
        *abs_lo = dcn41_allow_ranges[index].abs_lo;
    if (abs_hi)
        *abs_hi = dcn41_allow_ranges[index].abs_hi;
    if (base_idx)
        *base_idx = dcn41_allow_ranges[index].base_idx;
    if (name)
        *name = dcn41_allow_ranges[index].name;
    return 0;
}

static void zero_state(struct dcn41_allow_state *st)
{
    uint8_t *p = (uint8_t *)st;
    size_t i;
    for (i = 0; i < sizeof(*st); i++)
        p[i] = 0;
}

static void copy_tag(char *dst, const char *src)
{
    uint32_t i = 0;
    if (src) {
        for (; i + 1u < DCN41_ALLOW_TAG_LEN && src[i] != '\0'; i++)
            dst[i] = src[i];
    }
    dst[i] = '\0';
}

int dcn41_allow_init(struct dcn41_allow_state *st, const uint32_t seg[5], uint32_t mmio_dwords)
{
    uint32_t i, highest = 0;

    if (!st)
        return DCN41_ALLOW_UNARMED;
    zero_state(st);
    if (!seg)
        return DCN41_ALLOW_UNARMED;

    /* The range table is absolute addresses computed for one specific set of segment bases. If this
     * card reports different ones, the table is about a different address space and must not be
     * used: stay unarmed rather than guess. */
    for (i = 0; i < 5u; i++) {
        if (seg[i] != dcn41_allow_expected_segs[i])
            return DCN41_ALLOW_UNARMED;
    }
    for (i = 0; i < DCN41_ALLOW_RANGE_COUNT; i++) {
        if (dcn41_allow_ranges[i].abs_hi > highest)
            highest = dcn41_allow_ranges[i].abs_hi;
    }
    if (mmio_dwords == 0u || mmio_dwords <= highest)
        return DCN41_ALLOW_UNARMED;

    st->magic = DCN41_ALLOW_STATE_MAGIC;
    st->armed = 1u;
    st->mmio_dwords = mmio_dwords;
    return DCN41_ALLOW_OK;
}

int dcn41_allow_classify(uint32_t abs_dword, uint32_t mmio_dwords,
                         const char **range_name, const char **why)
{
    uint32_t i;

    if (range_name)
        *range_name = 0;
    if (why)
        *why = 0;

    /* 1. Never past the window the caller mapped. */
    if (mmio_dwords == 0u || abs_dword >= mmio_dwords) {
        if (why)
            *why = "beyond the mapped BAR5 window";
        return DCN41_ALLOW_WINDOW;
    }

    /* 2. Indirect-access windows, BEFORE the allow table. */
    for (i = 0; i < DCN41_HARD_DENY_COUNT; i++) {
        if (abs_dword >= dcn41_hard_deny[i].abs_lo && abs_dword <= dcn41_hard_deny[i].abs_hi) {
            if (why)
                *why = dcn41_hard_deny[i].why;
            return DCN41_ALLOW_INDIRECT;
        }
    }

    /* 3. Named SMU / PSP / SMUIO blocks, also before the allow table. */
    for (i = 0; i < DCN41_DENY_BLOCK_COUNT; i++) {
        if (abs_dword >= dcn41_deny_blocks[i].abs_lo && abs_dword <= dcn41_deny_blocks[i].abs_hi) {
            if (why)
                *why = dcn41_deny_blocks[i].why;
            return DCN41_ALLOW_BLOCK;
        }
    }

    /* 4. The allow table - the only thing that can return OK. */
    for (i = 0; i < DCN41_ALLOW_RANGE_COUNT; i++) {
        if (abs_dword >= dcn41_allow_ranges[i].abs_lo && abs_dword <= dcn41_allow_ranges[i].abs_hi) {
            if (range_name)
                *range_name = dcn41_allow_ranges[i].name;
            return DCN41_ALLOW_OK;
        }
    }

    /* 5. Deny by default. */
    if (why)
        *why = "outside every DCN 4.1 display range";
    return DCN41_ALLOW_RANGE;
}

void dcn41_allow_note_read(struct dcn41_allow_state *st)
{
    if (st && st->magic == DCN41_ALLOW_STATE_MAGIC)
        st->reads_seen++;
}

bool dcn41_allow_write(struct dcn41_allow_state *st, uint32_t abs_dword, uint32_t value,
                       const char *tag)
{
    int reason;
    uint32_t seq;
    struct dcn41_allow_sample *s;

    /* No state, or a state that never armed, means refuse. There is no path to hardware that skips
     * this function, so "unarmed" is a safe, fully inert driver rather than an unguarded one. */
    if (!st || st->magic != DCN41_ALLOW_STATE_MAGIC || !st->armed) {
        if (st) {
            st->writes_seen++;
            st->refused++;
            st->by_reason[DCN41_ALLOW_UNARMED]++;
            st->last_refused_abs = abs_dword;
            st->last_refused_reason = (uint8_t)DCN41_ALLOW_UNARMED;
        }
        return false;
    }

    st->writes_seen++;
    seq = (uint32_t)st->writes_seen;
    reason = dcn41_allow_classify(abs_dword, st->mmio_dwords, 0, 0);
    st->by_reason[reason]++;

    if (reason == DCN41_ALLOW_OK) {
        st->allowed++;
        if (st->n_allow_samples < DCN41_ALLOW_SAMPLES) {
            s = &st->allow[st->n_allow_samples++];
            s->abs_dword = abs_dword;
            s->value = value;
            s->seq = seq;
            s->reason = (uint8_t)reason;
            copy_tag(s->tag, tag);
        }
        return true;
    }

    st->refused++;
    st->last_refused_abs = abs_dword;
    st->last_refused_reason = (uint8_t)reason;
    if (st->n_refuse_samples < DCN41_ALLOW_SAMPLES) {
        s = &st->refuse[st->n_refuse_samples++];
        s->abs_dword = abs_dword;
        s->value = value;
        s->seq = seq;
        s->reason = (uint8_t)reason;
        copy_tag(s->tag, tag);
    } else {
        st->refuse_dropped++;
    }
    return false;
}
