/* dcn41_dmub_layout.h - GENERATED by tools/dcn41/gen_dmub_layout.py; do not edit (regenerate, then --check).
 *
 * Every number below was MEASURED by compiling Linux 238650ef6c7c display/dmub/inc/dmub_cmd.h and
 * include/atomfirmware.h (unmodified) into a probe and printing sizeof/offsetof/bit masks/enum values, then
 * re-asserted against Linux's structs under -target x86_64. Here they are asserted against OUR structs, so a
 * layout drift in dcn41_dmub.h fails every build of the module. */
#ifndef N48_DCN41_DMUB_LAYOUT_H
#define N48_DCN41_DMUB_LAYOUT_H

#ifdef __cplusplus
#define DCN41_LAYOUT_ASSERT(c, m) static_assert(c, m)
#else
#define DCN41_LAYOUT_ASSERT(c, m) _Static_assert(c, m)
#endif

DCN41_LAYOUT_ASSERT(sizeof(struct dcn41_dmub_cmd) == 64u, "sizeof(union dmub_rb_cmd) == 64");
DCN41_LAYOUT_ASSERT(sizeof(struct dcn41_dmub_encoder_stream_setup_v1_5) == 12u, "sizeof(struct dig_encoder_stream_setup_parameters_v1_5) == 12");
DCN41_LAYOUT_ASSERT(sizeof(struct dcn41_dmub_encoder_stream_setup_v1_5) == 12u, "sizeof(union dig_encoder_control_parameters_v1_5) == 12");
DCN41_LAYOUT_ASSERT(sizeof(struct dcn41_dmub_transmitter_control_v1_7) == 60u, "sizeof(struct dmub_dig_transmitter_control_data_v1_7) == 60");
DCN41_LAYOUT_ASSERT(sizeof(struct dcn41_dmub_transmitter_control_v1_7) == 60u, "sizeof(union dmub_cmd_dig1_transmitter_control_data) == 60");
DCN41_LAYOUT_ASSERT(sizeof(struct dcn41_dmub_set_pixel_clock_v1_7) == 16u, "sizeof(struct set_pixel_clock_parameter_v1_7) == 16");
DCN41_LAYOUT_ASSERT(sizeof(struct dcn41_dmub_disp_power_gating_v2_1) == 4u, "sizeof(struct enable_disp_power_gating_parameters_v2_1) == 4");
DCN41_LAYOUT_ASSERT(sizeof(struct dcn41_dmub_feature_caps) == 14u, "sizeof(struct dmub_feature_caps) == 14");
DCN41_LAYOUT_ASSERT(sizeof(struct dcn41_dmub_feature_caps) == 14u, "sizeof(struct dmub_cmd_query_feature_caps_data) == 14");
DCN41_LAYOUT_ASSERT(sizeof(struct dcn41_dmub_fw_meta_info) == 32u, "sizeof(struct dmub_fw_meta_info) == 32");

DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_encoder_stream_setup_v1_5, digid) == 0u, "offsetof(struct dig_encoder_stream_setup_parameters_v1_5, digid) == 0");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_encoder_stream_setup_v1_5, action) == 1u, "offsetof(struct dig_encoder_stream_setup_parameters_v1_5, action) == 1");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_encoder_stream_setup_v1_5, digmode) == 2u, "offsetof(struct dig_encoder_stream_setup_parameters_v1_5, digmode) == 2");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_encoder_stream_setup_v1_5, lanenum) == 3u, "offsetof(struct dig_encoder_stream_setup_parameters_v1_5, lanenum) == 3");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_encoder_stream_setup_v1_5, pclk_10khz) == 4u, "offsetof(struct dig_encoder_stream_setup_parameters_v1_5, pclk_10khz) == 4");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_encoder_stream_setup_v1_5, bitpercolor) == 8u, "offsetof(struct dig_encoder_stream_setup_parameters_v1_5, bitpercolor) == 8");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_encoder_stream_setup_v1_5, dplinkrate_270mhz) == 9u, "offsetof(struct dig_encoder_stream_setup_parameters_v1_5, dplinkrate_270mhz) == 9");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_encoder_stream_setup_v1_5, reserved) == 10u, "offsetof(struct dig_encoder_stream_setup_parameters_v1_5, reserved) == 10");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_transmitter_control_v1_7, phyid) == 0u, "offsetof(struct dmub_dig_transmitter_control_data_v1_7, phyid) == 0");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_transmitter_control_v1_7, action) == 1u, "offsetof(struct dmub_dig_transmitter_control_data_v1_7, action) == 1");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_transmitter_control_v1_7, mode_laneset) == 2u, "offsetof(struct dmub_dig_transmitter_control_data_v1_7, mode_laneset) == 2");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_transmitter_control_v1_7, lanenum) == 3u, "offsetof(struct dmub_dig_transmitter_control_data_v1_7, lanenum) == 3");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_transmitter_control_v1_7, symclk) == 4u, "offsetof(struct dmub_dig_transmitter_control_data_v1_7, symclk_units) == 4");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_transmitter_control_v1_7, hpdsel) == 8u, "offsetof(struct dmub_dig_transmitter_control_data_v1_7, hpdsel) == 8");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_transmitter_control_v1_7, digfe_sel) == 9u, "offsetof(struct dmub_dig_transmitter_control_data_v1_7, digfe_sel) == 9");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_transmitter_control_v1_7, connobj_id) == 10u, "offsetof(struct dmub_dig_transmitter_control_data_v1_7, connobj_id) == 10");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_transmitter_control_v1_7, hpo_instance) == 11u, "offsetof(struct dmub_dig_transmitter_control_data_v1_7, HPO_instance) == 11");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_transmitter_control_v1_7, txffe_lane_sel) == 12u, "offsetof(struct dmub_dig_transmitter_control_data_v1_7, TxFFELaneSel) == 12");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_transmitter_control_v1_7, skip_phy_ssc_reduction) == 13u, "offsetof(struct dmub_dig_transmitter_control_data_v1_7, skip_phy_ssc_reduction) == 13");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_transmitter_control_v1_7, reserved2) == 14u, "offsetof(struct dmub_dig_transmitter_control_data_v1_7, reserved2) == 14");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_transmitter_control_v1_7, reserved3) == 16u, "offsetof(struct dmub_dig_transmitter_control_data_v1_7, reserved3) == 16");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_set_pixel_clock_v1_7, pixclk_100hz) == 0u, "offsetof(struct set_pixel_clock_parameter_v1_7, pixclk_100hz) == 0");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_set_pixel_clock_v1_7, pll_id) == 4u, "offsetof(struct set_pixel_clock_parameter_v1_7, pll_id) == 4");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_set_pixel_clock_v1_7, encoderobjid) == 5u, "offsetof(struct set_pixel_clock_parameter_v1_7, encoderobjid) == 5");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_set_pixel_clock_v1_7, encoder_mode) == 6u, "offsetof(struct set_pixel_clock_parameter_v1_7, encoder_mode) == 6");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_set_pixel_clock_v1_7, miscinfo) == 7u, "offsetof(struct set_pixel_clock_parameter_v1_7, miscinfo) == 7");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_set_pixel_clock_v1_7, crtc_id) == 8u, "offsetof(struct set_pixel_clock_parameter_v1_7, crtc_id) == 8");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_set_pixel_clock_v1_7, deep_color_ratio) == 9u, "offsetof(struct set_pixel_clock_parameter_v1_7, deep_color_ratio) == 9");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_set_pixel_clock_v1_7, reserved1) == 10u, "offsetof(struct set_pixel_clock_parameter_v1_7, reserved1) == 10");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_set_pixel_clock_v1_7, reserved2) == 12u, "offsetof(struct set_pixel_clock_parameter_v1_7, reserved2) == 12");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_disp_power_gating_v2_1, disp_pipe_id) == 0u, "offsetof(struct enable_disp_power_gating_parameters_v2_1, disp_pipe_id) == 0");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_disp_power_gating_v2_1, enable) == 1u, "offsetof(struct enable_disp_power_gating_parameters_v2_1, enable) == 1");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_disp_power_gating_v2_1, padding) == 2u, "offsetof(struct enable_disp_power_gating_parameters_v2_1, padding) == 2");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_feature_caps, psr) == 0u, "offsetof(struct dmub_feature_caps, psr) == 0");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_feature_caps, fw_assisted_mclk_switch_ver) == 1u, "offsetof(struct dmub_feature_caps, fw_assisted_mclk_switch_ver) == 1");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_feature_caps, reserved) == 2u, "offsetof(struct dmub_feature_caps, reserved) == 2");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_feature_caps, subvp_psr_support) == 6u, "offsetof(struct dmub_feature_caps, subvp_psr_support) == 6");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_feature_caps, gecc_enable) == 7u, "offsetof(struct dmub_feature_caps, gecc_enable) == 7");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_feature_caps, replay_supported) == 8u, "offsetof(struct dmub_feature_caps, replay_supported) == 8");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_feature_caps, replay_reserved) == 9u, "offsetof(struct dmub_feature_caps, replay_reserved) == 9");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_feature_caps, abm_aux_backlight_support) == 12u, "offsetof(struct dmub_feature_caps, abm_aux_backlight_support) == 12");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_feature_caps, lsdma_support_in_dmu) == 13u, "offsetof(struct dmub_feature_caps, lsdma_support_in_dmu) == 13");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_fw_meta_info, magic_value) == 0u, "offsetof(struct dmub_fw_meta_info, magic_value) == 0");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_fw_meta_info, fw_region_size) == 4u, "offsetof(struct dmub_fw_meta_info, fw_region_size) == 4");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_fw_meta_info, trace_buffer_size) == 8u, "offsetof(struct dmub_fw_meta_info, trace_buffer_size) == 8");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_fw_meta_info, fw_version) == 12u, "offsetof(struct dmub_fw_meta_info, fw_version) == 12");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_fw_meta_info, dal_fw) == 16u, "offsetof(struct dmub_fw_meta_info, dal_fw) == 16");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_fw_meta_info, reserved) == 17u, "offsetof(struct dmub_fw_meta_info, reserved) == 17");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_fw_meta_info, shared_state_size) == 20u, "offsetof(struct dmub_fw_meta_info, shared_state_size) == 20");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_fw_meta_info, shared_state_features) == 24u, "offsetof(struct dmub_fw_meta_info, shared_state_features) == 24");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_fw_meta_info, reserved2) == 26u, "offsetof(struct dmub_fw_meta_info, reserved2) == 26");
DCN41_LAYOUT_ASSERT(offsetof(struct dcn41_dmub_fw_meta_info, feature_bits) == 28u, "offsetof(struct dmub_fw_meta_info, feature_bits) == 28");

DCN41_LAYOUT_ASSERT(sizeof(struct dcn41_dmub_encoder_stream_setup_v1_5) == 12u, "Linux payload_bytes: sizeof(c.digx_encoder_control) - sizeof(c.digx_encoder_control.header)");
DCN41_LAYOUT_ASSERT(sizeof(struct dcn41_dmub_transmitter_control_v1_7) == 60u, "Linux payload_bytes: sizeof(c.dig1_transmitter_control) - sizeof(c.dig1_transmitter_control.header)");
DCN41_LAYOUT_ASSERT(sizeof(struct dcn41_dmub_set_pixel_clock_v1_7) == 16u, "Linux payload_bytes: sizeof(c.set_pixel_clock) - sizeof(c.set_pixel_clock.header)");
DCN41_LAYOUT_ASSERT(sizeof(struct dcn41_dmub_disp_power_gating_v2_1) == 4u, "Linux payload_bytes: sizeof(c.enable_disp_power_gating) - sizeof(c.enable_disp_power_gating.header)");
DCN41_LAYOUT_ASSERT(sizeof(struct dcn41_dmub_feature_caps) == 14u, "Linux payload_bytes: sizeof(struct dmub_cmd_query_feature_caps_data)");

DCN41_LAYOUT_ASSERT(DCN41_DMUB_HDR_TYPE_MASK == 0x000000ffu, "c.cmd_common.header.type = ~0u sets 0x000000ff");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_HDR_SUB_TYPE_MASK == 0x0000ff00u, "c.cmd_common.header.sub_type = ~0u sets 0x0000ff00");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_HDR_RET_STATUS_MASK == 0x00010000u, "c.cmd_common.header.ret_status = ~0u sets 0x00010000");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_HDR_MULTI_CMD_PENDING_MASK == 0x00020000u, "c.cmd_common.header.multi_cmd_pending = ~0u sets 0x00020000");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_HDR_IS_REG_BASED_MASK == 0x00040000u, "c.cmd_common.header.is_reg_based = ~0u sets 0x00040000");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_HDR_PAYLOAD_BYTES_MASK == 0x3f000000u, "c.cmd_common.header.payload_bytes = ~0u sets 0x3f000000");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_BOOT_DAL_FW == 0x00000001u, "b.bits.dal_fw = ~0u sets 0x00000001");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_BOOT_MAILBOX_RDY == 0x00000002u, "b.bits.mailbox_rdy = ~0u sets 0x00000002");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_BOOT_OPTIMIZED_INIT_DONE == 0x00000004u, "b.bits.optimized_init_done = ~0u sets 0x00000004");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_BOOT_RESTORE_REQUIRED == 0x00000008u, "b.bits.restore_required = ~0u sets 0x00000008");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_BOOT_DEFER_LOAD == 0x00000010u, "b.bits.defer_load = ~0u sets 0x00000010");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_BOOT_FAMS_ENABLED == 0x00000020u, "b.bits.fams_enabled = ~0u sets 0x00000020");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_BOOT_DETECTION_REQUIRED == 0x00000040u, "b.bits.detection_required = ~0u sets 0x00000040");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_BOOT_HW_POWER_INIT_DONE == 0x00000080u, "b.bits.hw_power_init_done = ~0u sets 0x00000080");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_BOOT_ONO_REGIONS_ENABLED == 0x00000100u, "b.bits.ono_regions_enabled = ~0u sets 0x00000100");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_GPINT_PARAM_MASK == 0x0000ffffu, "g.bits.param = ~0u sets 0x0000ffff");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_GPINT_COMMAND_MASK == 0x0fff0000u, "g.bits.command_code = ~0u sets 0x0fff0000");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_GPINT_STATUS_MASK == 0xf0000000u, "g.bits.status = ~0u sets 0xf0000000");

DCN41_LAYOUT_ASSERT(DCN41_DMUB_CMD_SIZE == 64u, "DMUB_RB_CMD_SIZE == 64");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_RB_SIZE == 8192u, "DMUB_RB_SIZE == 8192");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_CMD_QUERY_FEATURE_CAPS == 6u, "DMUB_CMD__QUERY_FEATURE_CAPS == 6");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_CMD_VBIOS == 128u, "DMUB_CMD__VBIOS == 128");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_VBIOS_DIGX_ENCODER_CONTROL == 0u, "DMUB_CMD__VBIOS_DIGX_ENCODER_CONTROL == 0");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_VBIOS_DIG1_TRANSMITTER_CONTROL == 1u, "DMUB_CMD__VBIOS_DIG1_TRANSMITTER_CONTROL == 1");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_VBIOS_SET_PIXEL_CLOCK == 2u, "DMUB_CMD__VBIOS_SET_PIXEL_CLOCK == 2");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_VBIOS_ENABLE_DISP_POWER_GATING == 3u, "DMUB_CMD__VBIOS_ENABLE_DISP_POWER_GATING == 3");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_FW_META_MAGIC == 1145918786u, "DMUB_FW_META_MAGIC == 1145918786");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_GPINT_STOP_FW_RESPONSE == 3735936685u, "DMUB_GPINT__STOP_FW_RESPONSE == 3735936685");
DCN41_LAYOUT_ASSERT(DCN41_DMUB_GPINT_GET_FW_VERSION == 1u, "DMUB_GPINT__GET_FW_VERSION == 1");

#undef DCN41_LAYOUT_ASSERT
#endif /* N48_DCN41_DMUB_LAYOUT_H */
