/* dcn41_modes.h - GENERATED by tools/dcn41/gen_modes.py; do not edit (regenerate, then --check).
 *
 * Precomputed timings for three attached sinks, with the OTG register values
 * optc1_program_timing would write, the DCCG pixel-rate divider, the link requirement, and the VSTARTUP bound.
 * Sources per mode: EDID_DTD and EDID_CTA_DTD are the sink's own bytes (edid-capture.txt);
 * CVT_RB2 is computed here because that sink's own high-refresh timing was never captured - SUSPECTED, replace
 * it with the sink's CTA timing when the PC reads it. CVT-RB v1 control: 2560x1440@60 -> 2720x1481 at 241500 kHz, equal to the SINK-A's own detailed timing.
 */
#ifndef N48_DCN41_MODES_H
#define N48_DCN41_MODES_H

#include <stdint.h>

enum dcn41_mode_source { DCN41_MODE_EDID_DTD = 0, DCN41_MODE_EDID_CTA_DTD, DCN41_MODE_CVT_RB2 };
enum dcn41_mode_signal { DCN41_MODE_SIGNAL_DP = 0, DCN41_MODE_SIGNAL_HDMI };

struct dcn41_mode {
    const char *monitor;          /* EDID descriptor 0xFC */
    const char *mode;             /* label */
    uint8_t source;               /* enum dcn41_mode_source */
    uint8_t signal;               /* enum dcn41_mode_signal */
    uint8_t link, phyid, dig, hpd, ddc;   /* link index, ATOM phy id, DIG instance, HPD pin (1-based), DDC line */
    uint32_t pix_clk_100hz;       /* SET_PIXEL_CLOCK's unit */
    uint32_t refresh_mhz;         /* pixel clock / (h_total * v_total), millihertz */
    uint16_t h_active, h_front, h_sync, h_back, h_total;
    uint16_t v_active, v_front, v_sync, v_back, v_total;
    uint8_t h_pos, v_pos;         /* sync polarities, 1 = positive */
    /* optc1_program_timing's register values */
    uint16_t otg_h_total, otg_h_sync_a_end, otg_h_blank_start, otg_h_blank_end;
    uint16_t otg_v_total, otg_v_sync_a_end, otg_v_blank_start, otg_v_blank_end;
    uint8_t otg_h_sync_a_pol, otg_v_sync_a_pol, otg_start_point, tmds_pixel_rate_div;
    uint16_t max_vstartup;        /* CalculateMaxVStartup bound; DML21 picks the actual VSTARTUP */
    /* link requirement at 8 and 10 bits per channel */
    uint32_t req_kbps_8, req_kbps_10;         /* dc_bandwidth_in_kbps_from_timing, RGB */
    uint32_t link_kbps_8, link_kbps_10;       /* DP: the chosen link's bandwidth; HDMI: 0 */
    uint8_t dp_lanes_8, dp_rate_code_8, dp_lanes_10, dp_rate_code_10;   /* DP only */
    uint32_t hdmi_tmds_khz_8, hdmi_tmds_khz_10;                          /* HDMI only */
    uint8_t hdmi_scramble_8, hdmi_scramble_10, hdmi_within_dio_8, hdmi_within_dio_10;
};

static const struct dcn41_mode dcn41_modes[] = {
    { /* SINK-A 2560x1440@60 (EDID_DTD) */
        "SINK-A", "2560x1440@60", DCN41_MODE_EDID_DTD, DCN41_MODE_SIGNAL_DP,
        1, 1, 1, 2, 1,
        2415000u, 59951u,
        2560, 48, 32, 80, 2720,
        1440, 3, 5, 33, 1481,
        1, 1,
        2719, 32, 2672, 112,
        1480, 5, 1478, 38,
        0, 0, 1, 1,
        40,
        5796000u, 7245000u, 8640000u, 8640000u,
        4, 0x0a, 4, 0x0a,
        0u, 0u, 0, 0, 0, 0,
    },
    { /* SINK-A 2560x1440@165 (EDID_CTA_DTD) */
        "SINK-A", "2560x1440@165", DCN41_MODE_EDID_CTA_DTD, DCN41_MODE_SIGNAL_DP,
        1, 1, 1, 2, 1,
        6466400u, 165000u,
        2560, 8, 32, 66, 2666,
        1440, 3, 5, 22, 1470,
        1, 0,
        2665, 32, 2658, 98,
        1469, 5, 1467, 27,
        0, 1, 1, 1,
        29,
        15519360u, 19399200u, 17280000u, 25920000u,
        4, 0x14, 4, 0x1e,
        0u, 0u, 0, 0, 0, 0,
    },
    { /* SINK-A 2560x1440@144 (EDID_CTA_DTD) */
        "SINK-A", "2560x1440@144", DCN41_MODE_EDID_CTA_DTD, DCN41_MODE_SIGNAL_DP,
        1, 1, 1, 2, 1,
        5920000u, 143912u,
        2560, 8, 32, 66, 2666,
        1440, 25, 8, 70, 1543,
        1, 0,
        2665, 32, 2658, 98,
        1542, 8, 1518, 78,
        0, 1, 1, 1,
        102,
        14208000u, 17760000u, 17280000u, 25920000u,
        4, 0x14, 4, 0x1e,
        0u, 0u, 0, 0, 0, 0,
    },
    { /* SINK-A 2560x1440@120 (EDID_CTA_DTD) */
        "SINK-A", "2560x1440@120", DCN41_MODE_EDID_CTA_DTD, DCN41_MODE_SIGNAL_DP,
        1, 1, 1, 2, 1,
        4977500u, 119998u,
        2560, 48, 32, 80, 2720,
        1440, 3, 5, 77, 1525,
        1, 1,
        2719, 32, 2672, 112,
        1524, 5, 1522, 82,
        0, 0, 1, 1,
        84,
        11946000u, 14932500u, 17280000u, 17280000u,
        4, 0x14, 4, 0x14,
        0u, 0u, 0, 0, 0, 0,
    },
    { /* SINK-A 1280x1440@60 (EDID_CTA_DTD) */
        "SINK-A", "1280x1440@60", DCN41_MODE_EDID_CTA_DTD, DCN41_MODE_SIGNAL_DP,
        1, 1, 1, 2, 1,
        1560000u, 59913u,
        1280, 96, 136, 232, 1744,
        1440, 3, 10, 40, 1493,
        0, 1,
        1743, 136, 1648, 368,
        1492, 10, 1490, 50,
        1, 0, 1, 1,
        52,
        3744000u, 4680000u, 5184000u, 5184000u,
        4, 0x06, 4, 0x06,
        0u, 0u, 0, 0, 0, 0,
    },
    { /* SINK-B 1920x1080@60 (EDID_DTD) */
        "SINK-B", "1920x1080@60", DCN41_MODE_EDID_DTD, DCN41_MODE_SIGNAL_HDMI,
        2, 2, 2, 3, 2,
        1485000u, 60000u,
        1920, 88, 44, 148, 2200,
        1080, 4, 5, 36, 1125,
        1, 1,
        2199, 44, 2112, 192,
        1124, 5, 1121, 41,
        0, 0, 0, 4,
        44,
        445500u, 445500u, 0u, 0u,
        0, 0, 0, 0,
        148500u, 185625u,
        0, 0, 1, 1,
    },
    { /* SINK-B 1920x1080@120 (CVT_RB2) */
        "SINK-B", "1920x1080@120", DCN41_MODE_CVT_RB2, DCN41_MODE_SIGNAL_HDMI,
        2, 2, 2, 3, 2,
        2745600u, 120000u,
        1920, 8, 32, 40, 2000,
        1080, 1, 8, 55, 1144,
        1, 0,
        1999, 32, 1992, 72,
        1143, 8, 1143, 63,
        0, 1, 0, 4,
        63,
        823680u, 823680u, 0u, 0u,
        0, 0, 0, 0,
        274560u, 343200u,
        0, 1, 1, 1,
    },
    { /* SINK-C 3840x2160@60 (EDID_DTD) */
        "SINK-C", "3840x2160@60", DCN41_MODE_EDID_DTD, DCN41_MODE_SIGNAL_HDMI,
        3, 3, 3, 4, 3,
        5940000u, 60000u,
        3840, 176, 88, 296, 4400,
        2160, 8, 10, 72, 2250,
        1, 1,
        4399, 88, 4224, 384,
        2249, 10, 2242, 82,
        0, 0, 0, 4,
        89,
        1782000u, 1782000u, 0u, 0u,
        0, 0, 0, 0,
        594000u, 742500u,
        1, 1, 1, 0,
    },
    { /* SINK-C 3840x2160@120 (CVT_RB2) */
        "SINK-C", "3840x2160@120", DCN41_MODE_CVT_RB2, DCN41_MODE_SIGNAL_HDMI,
        3, 3, 3, 4, 3,
        10758050u, 120000u,
        3840, 8, 32, 40, 3920,
        2160, 1, 8, 118, 2287,
        1, 0,
        3919, 32, 3912, 72,
        2286, 8, 2286, 126,
        0, 1, 0, 4,
        126,
        3227415u, 3227414u, 0u, 0u,
        0, 0, 0, 0,
        1075805u, 1344756u,
        1, 1, 0, 0,
    },
};

#define DCN41_MODE_COUNT (sizeof(dcn41_modes) / sizeof(dcn41_modes[0]))

#endif /* N48_DCN41_MODES_H */
