/* dcn41_allow_ranges.h - GENERATED by tools/dcn41/gen_allow.py; do not edit (regenerate, then --check).
 *
 * The DCN 4.1 DISPLAY write allowlist, as absolute BAR5 dword ranges. Absolute = seg[BASE_IDX] + offset
 * with the DMU segment bases this card's own IP discovery table reports:
 *   0x00000012 0x000000c0 0x000034c0 0x00009000 0x02403c00
 * (notes/logs/runs/adopt1/driverlog-post.txt:1371, hwId 271 inst 0 v4.1.0). Offsets and BASE_IDX come
 * from Linux 238650ef6c7c dcn_4_1_0_offset.h; offsets inside one segment are merged into a range when
 * they are at most 0x40 dwords apart, so a range is a stretch of the display block, not a segment.
 *
 * Segments 0 and 4 are DENIED and appear nowhere below: segment 0 (base 0x12) holds only Azalia audio
 * registers and its absolute span 0x12..0x5f overlaps NBIO's indirect SMN windows at 0x14/0x15 and
 * 0x20/0x21, which reach the SMU, SMUIO, THM and the SPI ROM; segment 4 (0x2403c00) addresses no DCN
 * register and lies outside BAR5 entirely.
 *
 * 32 ranges, 8960 dwords (35840 bytes) writable in total, out of a 262144-dword BAR5.
 * Coverage check: all 122 register addresses src/dcn41/dcn41_regs.h can form fall inside a range.
 */
#ifndef N48_DCN41_ALLOW_RANGES_H
#define N48_DCN41_ALLOW_RANGES_H

#include <stdint.h>

struct dcn41_allow_range {
    uint32_t abs_lo;      /* first writable absolute BAR5 dword, inclusive */
    uint32_t abs_hi;      /* last writable absolute BAR5 dword, inclusive  */
    uint8_t base_idx;     /* DCN segment this range came from              */
    const char *name;     /* the hardware block(s) it covers               */
};

struct dcn41_deny_range {
    uint32_t abs_lo;
    uint32_t abs_hi;
    const char *why;
};

#define DCN41_ALLOW_RANGE_COUNT 32u
#define DCN41_ALLOW_TOTAL_DWORDS 8960u
#define DCN41_ALLOW_BAR5_DWORDS 262144u

/* Checked FIRST, before the allow table: indirect-access windows. A write here selects a target
 * anywhere in SMN or VRAM and the next write goes there, which would defeat an address allowlist. */
#define DCN41_HARD_DENY_COUNT 1u
static const struct dcn41_deny_range dcn41_hard_deny[DCN41_HARD_DENY_COUNT] = {
    { 0x00000000u, 0x000000ffu, "the low BAR5 page: MM_INDEX/MM_DATA/MM_INDEX_HI (0x0/0x1/0x6) and NBIO's BIF_BX1_PCIE_INDEX2/DATA2 (0xe/0xf), RSMU_INDEX/DATA (0x14/0x15) and BIF_BX0_PCIE_INDEX/DATA (0x20/0x21) - indirect windows into all of SMN" },
};

/* Checked SECOND. None of these intersects an allowed range (gen_allow.py asserts it); they are named
 * so a refusal says WHICH block was aimed at, and so the host test has real addresses to fire at. */
#define DCN41_DENY_BLOCK_COUNT 4u
static const struct dcn41_deny_range dcn41_deny_blocks[DCN41_DENY_BLOCK_COUNT] = {
    { 0x00016000u, 0x000163ffu, "MP1/SMU (hwId 1 v14.0.3 segs 0x16000, 0x16200): the SMU message mailbox regMP1_SMN_C2PMSG_66/82/90 lives at 0x16282/0x16292/0x1629a - power, voltage, clock limits and DPM tables are all behind it" },
    { 0x0001ce00u, 0x0001cfffu, "MP0/PSP (hwId 255 v14.0.3 segment 2): firmware load and the ROM path" },
    { 0x00dc0000u, 0x00e7ffffu, "MP0/MP1 upper segments 0xdc0000/0xe00000/0xe40000" },
    { 0x02458000u, 0x024587ffu, "hwId 293/273 v1.0.x (0x2458000/0x2458400): SMUIO-class blocks" },
};

/* Checked LAST, and only these make a write legal. Sorted by abs_lo, disjoint. */
static const struct dcn41_allow_range dcn41_allow_ranges[DCN41_ALLOW_RANGE_COUNT] = {
    { 0x00000100u, 0x0000017eu, 1u, "PHYPLLA..DCCG" },  /* seg1 + 0x00040..0x000be, 105 regs in 56 block(s) */
    { 0x0000350au, 0x00003599u, 2u, "HDMICHARCLK0..DMU" },  /* seg2 + 0x0004a..0x000d9, 56 regs in 35 block(s) */
    { 0x000035e6u, 0x00003771u, 2u, "DC..MMHUBBUB" },  /* seg2 + 0x00126..0x002b1, 285 regs in 32 block(s) */
    { 0x000037f3u, 0x00003808u, 2u, "MMHUBBUB..MMHUBBUB" },  /* seg2 + 0x00333..0x00348, 12 regs in 4 block(s) */
    { 0x000038d2u, 0x000038ddu, 2u, "CC..REG" },  /* seg2 + 0x00412..0x0041d, 4 regs in 2 block(s) */
    { 0x0000392fu, 0x00003de1u, 2u, "DCHUBBUB..CURSOR0" },  /* seg2 + 0x0046f..0x00921, 800 regs in 25 block(s) */
    { 0x00004185u, 0x00004288u, 2u, "DPP..CM0" },  /* seg2 + 0x00cc5..0x00dc8, 245 regs in 5 block(s) */
    { 0x000042f0u, 0x000043f3u, 2u, "DPP..CM1" },  /* seg2 + 0x00e30..0x00f33, 245 regs in 5 block(s) */
    { 0x0000445bu, 0x0000455eu, 2u, "DPP..CM2" },  /* seg2 + 0x00f9b..0x0109e, 245 regs in 5 block(s) */
    { 0x000045c6u, 0x000046c9u, 2u, "DPP..CM3" },  /* seg2 + 0x01106..0x01209, 245 regs in 5 block(s) */
    { 0x00004b72u, 0x00004bd6u, 2u, "DP" },  /* seg2 + 0x016b2..0x01716, 64 regs in 1 block(s) */
    { 0x00004c1au, 0x00004c73u, 2u, "HPD0..DCOH" },  /* seg2 + 0x0175a..0x017b3, 30 regs in 6 block(s) */
    { 0x00004cfcu, 0x00004e63u, 2u, "FMT0..OPP" },  /* seg2 + 0x0183c..0x019a3, 124 regs in 13 block(s) */
    { 0x00004f1eu, 0x00004f27u, 2u, "OPP..DSCRM3" },  /* seg2 + 0x01a5e..0x01a67, 6 regs in 5 block(s) */
    { 0x00004f8au, 0x000051e1u, 2u, "ODM0..OTG3" },  /* seg2 + 0x01aca..0x01d21, 504 regs in 8 block(s) */
    { 0x000052ebu, 0x000052f2u, 2u, "GSL..OPTC" },  /* seg2 + 0x01e2b..0x01e32, 8 regs in 3 block(s) */
    { 0x00005358u, 0x000053d3u, 2u, "DC..DIG6" },  /* seg2 + 0x01e98..0x01f13, 61 regs in 10 block(s) */
    { 0x00005528u, 0x000059afu, 2u, "VPG0..DP3" },  /* seg2 + 0x02068..0x024ef, 741 regs in 20 block(s) */
    { 0x00005d28u, 0x00005e21u, 2u, "DC..DCIO" },  /* seg2 + 0x02868..0x02961, 151 regs in 15 block(s) */
    { 0x00005ec0u, 0x00005ef9u, 2u, "DCIO..DCIO" },  /* seg2 + 0x02a00..0x02a39, 58 regs in 2 block(s) */
    { 0x00005f98u, 0x00005fd1u, 2u, "DCIO..DCIO" },  /* seg2 + 0x02ad8..0x02b11, 58 regs in 2 block(s) */
    { 0x00006070u, 0x000060a9u, 2u, "DCIO..DCIO" },  /* seg2 + 0x02bb0..0x02be9, 58 regs in 2 block(s) */
    { 0x000063d0u, 0x000063e1u, 2u, "DC..PWRSEQ" },  /* seg2 + 0x02f10..0x02f21, 16 regs in 4 block(s) */
    { 0x000064a8u, 0x00006619u, 2u, "DLPC..DSCC3" },  /* seg2 + 0x02fe8..0x03159, 272 regs in 10 block(s) */
    { 0x000066e8u, 0x000066fdu, 2u, "DWB..DWB" },  /* seg2 + 0x03228..0x0323d, 22 regs in 2 block(s) */
    { 0x00006754u, 0x000067acu, 2u, "DWB" },  /* seg2 + 0x03294..0x032ec, 89 regs in 1 block(s) */
    { 0x00006ae3u, 0x00006e26u, 2u, "DP..DP" },  /* seg2 + 0x03623..0x03966, 620 regs in 13 block(s) */
    { 0x00009000u, 0x000091efu, 3u, "MPCC0..MPCC" },  /* seg3 + 0x00000..0x001ef, 412 regs in 5 block(s) */
    { 0x000092b2u, 0x0000935cu, 3u, "MPC..MPC" },  /* seg3 + 0x002b2..0x0035c, 112 regs in 8 block(s) */
    { 0x00009453u, 0x0000970bu, 3u, "MPCC" },  /* seg3 + 0x00453..0x0070b, 676 regs in 1 block(s) */
    { 0x000098d3u, 0x00009968u, 3u, "HDMI..HDMI" },  /* seg3 + 0x008d3..0x00968, 82 regs in 4 block(s) */
    { 0x00009e43u, 0x00009f64u, 3u, "HPO..ABM3" },  /* seg3 + 0x00e43..0x00f64, 164 regs in 6 block(s) */
};

/* The segment bases the table above was generated for. dcn41_allow_init refuses any other set:
 * an allowlist of absolute addresses means nothing if the bases moved. */
static const uint32_t dcn41_allow_expected_segs[5] = {
    0x00000012u, 0x000000c0u, 0x000034c0u, 0x00009000u, 0x02403c00u
};

#endif /* N48_DCN41_ALLOW_RANGES_H */
