// FROZEN COPY of gfx_present73.h at 6af255a0 (0.0.537), for tests/gfx_p94_test.cpp (switches 94 and 95 OFF identity). Generated by
// `git show 6af255a0:src/navi48-bringup/src/apple/gfx_present73.h` with the include guard renamed and <stdint.h> removed (the
// test includes it inside `namespace p537`). Do not edit.
// gfx_present73.h — build 0.0.516 ( option (a), MEDIUM-1): HOLD THE PRESENT WHEN ITS PLANE's LAST P DID NOT
// COMMIT. Switch 73 (`73 | M << 8`: M 1 ON = 329, M 2 OFF = 585, the default and the boot value; bare `73` reads).
//
// THE RULE ('s contract, POSITIVE EVIDENCE ONLY). The display shim (DisplayPipeGuard.cpp dpg_perform) copies plane 0 of a
// present into the scanout. With the switch ON it copies ONLY when that plane's LAST P - the 1040-dword single-IB final display
// pass whose first colour target (CB0) IS this plane - COMMITTED: the gate answered COMMIT, the hook's token and keystone held,
// and the ring walk SPARED the IB. Every other state HOLDS the copy (the glass keeps its last delivered picture):
//   REFUSED    the gate refused the P;
//   WITHDRAWN  the gate answered COMMIT and the hook withdrew it (token mismatch, keystone, flight-ring guard, or a ring walk that
//              did not spare it);
//   UNKNOWN    a P whose final outcome is not known yet (PENDING between the gate and the hook's final line), a P whose CB0 did
//              not resolve to VRAM (every plane is invalidated: which plane it drew is unknown), a WindowServer IB frame the
//              judge never saw (the lock was busy, the frame cap, the arm OFF: every plane is invalidated), or a NON-P frame that
//              names the plane as a colour target;
//   NO-MATCH   the plane's VRAM offset is in no slot (no P for it since the switch went ON, or the table was full).
// There is no rule that can turn a held plane back into a copied one except a later P for THAT plane whose final outcome is
// COMMITTED. Fail-closed by construction: every unknown answers HOLD.
//
// THE KEY is the plane's VRAM offset: dpg_perform's `phys` (the plane VidMemory's getPhysicalSegment) on the present side and, on
// the submit side, P's CB0 resolved exactly as the kext's own FRAME TARGET line resolves it (gfxc_page_sub over the frame's vm,
// then vmib_to_vram_off), plus CB0's offset inside its 4 KiB page (n48_p73_key). run10u: VA 0x401800000 -> 0x10930000,
// 0x402800000 -> 0x11200000, 0x403800000 -> 0x11a70000, each equal to the pipeshim's `VidMemory VRAM` for the same plane.
//
// THE TABLE is N48_P73_SLOTS lock-free slots. A slot's key is claimed once (compare-and-swap from 0) and never changes until the
// switch is turned ON again (n48_p73_reset); the state is one 32-bit atomic, written by the submit path and read by the present
// (which runs in Apple's event context, on another thread). A full table records nothing new (counted): the new plane is NO-MATCH,
// i.e. held. Eight slots, not four: run10u's 1040-dword frames name FIVE surfaces as CB0 (the two layers' fills and the three
// planes), and a slot is never evicted (an eviction would forget a REFUSED state).
//
// ORDER (C3): the gate's answer is recorded BEFORE Apple's original runs - a COMMIT as PENDING (held), a refusal as REFUSED - and
// PENDING becomes COMMITTED or WITHDRAWN only at the hook's final outcome, matched by the gate's token seq. So no present can ever
// see COMMITTED for a P whose outcome is not final.
//
// build 0.0.519 (: RUN O's copies #5-#7 were made BEFORE their P's RETIRED line - planes copied mid-draw) - COPY
// ONLY AFTER THE P's FLIGHT RETIRES. While switch 73 is ON the hook's final SPARED no longer makes the slot COMMITTED: it records
// the seq as spared (`spared`) and the slot stays PENDING (held). The slot becomes COMMITTED only when BOTH the walk spared that
// P AND the P's own flight RETIRED - its owned-slot fence read OURS (n48_p73_retired, called by the flight ring's two retirement
// sites: the judged-frame poll and switch 65's expiry poll) - whichever of the two arrives second promotes, by a
// compare-and-swap PENDING -> COMMITTED so it is counted once. A flight that expires, is NOPed, or never retires by fence
// leaves its plane held until a later P for that plane commits AND retires. Everything else of 73 is unchanged. This changes
// 73's semantics ONLY while 73 is ON: OFF, nothing here is called.
//
// Pure: no lock, no clock, no register, no log. Host-tested by tests/gfx_present73_test.cpp over run10u's real P sequence.
#ifndef N48_FROZEN_PRESENT73_6AF255A0_H
#define N48_FROZEN_PRESENT73_6AF255A0_H


#define N48_P73_SLOTS 8u
#define N48_P73_HOLD_LINES 8u    /* the capped log of the first holds */
#define N48_P73_COPY_LINES 8u    /* build 0.0.517: the capped log of the first copies */

enum { N48_P73_ST_UNKNOWN = 0u, N48_P73_ST_PENDING = 1u, N48_P73_ST_COMMITTED = 2u, N48_P73_ST_REFUSED = 3u,
       N48_P73_ST_WITHDRAWN = 4u, N48_P73_STATES = 5u };
/* build 0.0.521 Part E: N48_P73_HOLD_OLDER - the plane's COMMITTED P is not NEWER than the P last delivered to the glass. */
/* build 0.0.525 (switch 80, notes/design/CYCLE80.md C6): N48_P73_HOLD_INCOMPLETE - APPENDED at index 5: the plane's COMMITTED
 * P is not a COMPLETE cycle under switch 80 (gfx_cycle80.h). Only switch 80 ON produces it; OFF and SHADOW never do. */
enum { N48_P73_HOLD_REFUSED = 0u, N48_P73_HOLD_WITHDRAWN = 1u, N48_P73_HOLD_UNKNOWN = 2u, N48_P73_HOLD_NOMATCH = 3u,
       N48_P73_HOLD_OLDER = 4u, N48_P73_HOLD_INCOMPLETE = 5u, N48_P73_HOLDS = 6u };
/* build 0.0.525 (switch 80): the switch's three modes as n48_p73.c80on holds them (0 = OFF is the default and the boot value),
 * and the per-slot verdict gfx_cycle80.h writes at the P's gate (0 = none: never judged, which C6 reads as not COMPLETE). */
enum { N48_P73_C80_OFF = 0u, N48_P73_C80_ON = 1u, N48_P73_C80_SHADOW = 2u };
enum { N48_P73_C80V_NONE = 0u, N48_P73_C80V_COMPLETE = 1u, N48_P73_C80V_INCOMPLETE = 2u, N48_P73_C80V_UNDET = 3u };

typedef struct {
    uint64_t key;        /* the plane's VRAM offset; 0 = free. Claimed by CAS, then constant until n48_p73_reset */
    uint64_t va;         /* P's CB0 GPU VA when the slot was claimed (for the log only) */
    uint32_t state;      /* N48_P73_ST_*, atomic */
    uint32_t seq;        /* the gate's token seq of the P that set the state (0 = none) */
    uint32_t logged_p;   /* the one-shot "P CB0 -> VRAM" line was printed */
    uint32_t logged_pr;  /* the one-shot "present matched" line was printed */
    uint32_t spared;     /* build 0.0.519: the seq the hook's final outcome SPARED (0 = none) */
    uint32_t retired;    /* build 0.0.519: the seq whose flight RETIRED by its own fence (0 = none) */
    /* build 0.0.525 (switch 80, CYCLE80.md C6): the P switch 80 judged for this slot - its gate seq, its verdict
     * (N48_P73_C80V_*) and its layer (index + 1, 0 = none). Written only while switch 80 is ON or SHADOW (gfx_cycle80.h), read by
     * the present only while it is; atomic, like `state`. A P whose c80seq is not the slot's seq was never judged: not COMPLETE. */
    uint32_t c80seq, c80verdict, c80layer;
} n48_p73_slot;

typedef struct {
    n48_p73_slot s[N48_P73_SLOTS];
    /* THIS submission's pending P (submit path only): set at the gate, consumed at the hook's final outcome */
    uint32_t pend_seq;   /* 0 = none */
    uint32_t pend_slot;
    uint64_t pend_key;
    uint32_t judged;     /* the judge saw this submission (cleared at the hook's top) */
    uint32_t hold_lines;
    uint32_t copy_lines; /* build 0.0.517: COPIED lines printed (present path only; reset with hold_lines) */
    /* counters (since boot; the table itself is cleared by n48_p73_reset) */
    uint64_t copied, held[N48_P73_HOLDS];
    uint64_t pRecorded, pCommitted, pRefused, pWithdrawn, pUnresolved, overflow, nonP, unjudged, finalUnmatched;
    uint64_t flushHeld;
    uint64_t pSpared, pRetiredFirst, retireNoSlot;   /* build 0.0.519: spared finals, retirements before the final, retirements
                                                      * that matched no PENDING P slot */
    uint64_t promoteReverted;                        /* build 0.0.520: promotions undone - a new P took the slot */
    /* build 0.0.521 Part E (observed behaviour: the cursor "goes back and forth, as if old frames are repeating"): MONOTONIC
     * copies. Presents rotate over 2-3 planes and each plane's last COMMITTED P is from a different time; copying a plane whose
     * P is OLDER than the one already on the glass steps the picture back. `lastDelivered` is the P seq of the plane last copied
     * to the glass (valid while `deliveredOk`); `decided` the seq the last copy decision let through (the present path, one
     * present at a time), made `lastDelivered` by n48_p73_delivered after the copy succeeded. Cleared by n48_p73_reset (73 ON). */
    uint32_t lastDelivered, deliveredOk, decided, decidedOk;
    uint64_t delivered;                              /* copies made the glass's newest (n48_p73_delivered) */
    /* build 0.0.525 (switch 80, CYCLE80.md C6 + X1): the switch's mode (N48_P73_C80_*; the verb is its only writer), and the
     * present's own count of COMMITTED planes it found INCOMPLETE under SHADOW ("would hold": the copy proceeded). Under ON the
     * same presents are held[N48_P73_HOLD_INCOMPLETE]. OFF, the present loads c80on once and touches nothing else of this. */
    uint32_t c80on;
    uint64_t c80WouldHold;
} n48_p73;

static inline uint32_t n48_p73_ld32(const uint32_t *p) { return __atomic_load_n(p, __ATOMIC_ACQUIRE); }
static inline uint64_t n48_p73_ld64(const uint64_t *p) { return __atomic_load_n(p, __ATOMIC_ACQUIRE); }
static inline void n48_p73_st32(uint32_t *p, uint32_t v) { __atomic_store_n(p, v, __ATOMIC_RELEASE); }

/* The key of a colour target: its page's VRAM offset (the FRAME TARGET conversion) plus the VA's offset inside the page. 0 (no
 * key) unless the page resolved, is not host memory, and converted. */
static inline uint64_t n48_p73_key(uint64_t va, uint64_t page_voff, uint32_t resolved, uint32_t host, uint32_t converted)
{
    if (!resolved || host || !converted) return 0ull;
    return page_voff + (va & 0xfffull);
}

/* Turned ON: forget every slot (states first, so a present racing the reset reads UNKNOWN, never a stale COMMITTED). */
static inline void n48_p73_reset(n48_p73 *t)
{
    for (uint32_t i = 0; i < N48_P73_SLOTS; i++) n48_p73_st32(&t->s[i].state, N48_P73_ST_UNKNOWN);
    for (uint32_t i = 0; i < N48_P73_SLOTS; i++) {
        t->s[i].seq = 0u; t->s[i].va = 0ull; t->s[i].logged_p = 0u; t->s[i].logged_pr = 0u;
        t->s[i].spared = 0u; t->s[i].retired = 0u;
        n48_p73_st32(&t->s[i].c80verdict, N48_P73_C80V_NONE); n48_p73_st32(&t->s[i].c80seq, 0u);   /* build 0.0.525 */
        n48_p73_st32(&t->s[i].c80layer, 0u);
        __atomic_store_n(&t->s[i].key, 0ull, __ATOMIC_RELEASE);
    }
    t->pend_seq = 0u; t->pend_slot = 0u; t->pend_key = 0ull; t->hold_lines = 0u; t->copy_lines = 0u;
    t->lastDelivered = 0u; t->deliveredOk = 0u; t->decided = 0u; t->decidedOk = 0u;   /* build 0.0.521 Part E */
}
/* build 0.0.521 Part E: `a` is NEWER than `b` in serial-number order (the gate's seq wraps 0xFFFFFFFF -> 1, 0.0.517's
 * n48_cm_seq_next, and 0 is never a seq): the signed difference is positive. 0xFFFFFFFF then 1 is newer (difference 2). */
static inline uint32_t n48_p73_seq_newer(uint32_t a, uint32_t b) { return (int32_t)(a - b) > 0 ? 1u : 0u; }

/* The slot holding `key`, or N48_P73_SLOTS. */
static inline uint32_t n48_p73_find(const n48_p73 *t, uint64_t key)
{
    if (!key) return N48_P73_SLOTS;
    for (uint32_t i = 0; i < N48_P73_SLOTS; i++) if (n48_p73_ld64(&t->s[i].key) == key) return i;
    return N48_P73_SLOTS;
}
/* Find or claim (CAS on a free key; a claimed slot starts UNKNOWN). N48_P73_SLOTS = the table is full (counted). */
static inline uint32_t n48_p73_claim(n48_p73 *t, uint64_t key, uint64_t va)
{
    uint32_t i = n48_p73_find(t, key);
    if (i < N48_P73_SLOTS || !key) return i;
    for (i = 0; i < N48_P73_SLOTS; i++) {
        uint64_t want = 0ull;
        if (__atomic_compare_exchange_n(&t->s[i].key, &want, key, false, __ATOMIC_ACQ_REL, __ATOMIC_ACQUIRE)) {
            t->s[i].va = va;
            return i;
        }
        if (want == key) return i;   /* claimed by a racing writer for the same key */
    }
    t->overflow++;
    return N48_P73_SLOTS;
}
/* Every slot to UNKNOWN (a P whose plane cannot be named, or a frame the judge never saw). Keys stay. */
static inline void n48_p73_invalidate_all(n48_p73 *t)
{
    for (uint32_t i = 0; i < N48_P73_SLOTS; i++)
        if (n48_p73_ld64(&t->s[i].key)) {
            n48_p73_st32(&t->s[i].state, N48_P73_ST_UNKNOWN); t->s[i].seq = 0u; t->s[i].spared = 0u; t->s[i].retired = 0u;
        }
    t->pend_seq = 0u;
}
/* THE GATE'S ANSWER for a P (a 1040-dword single-IB frame with one colour target), AFTER the gate and BEFORE Apple's original.
 * `key` 0 = CB0 did not resolve: every plane is invalidated. A COMMIT is PENDING (held) until n48_p73_final; a refusal is final.
 * Returns the slot (N48_P73_SLOTS: nothing recorded). */
static inline uint32_t n48_p73_gate_p(n48_p73 *t, uint64_t key, uint64_t va, uint32_t commit, uint32_t gate_seq)
{
    t->judged = 1u;
    t->pend_seq = 0u;
    if (!key) { t->pUnresolved++; n48_p73_invalidate_all(t); return N48_P73_SLOTS; }
    const uint32_t i = n48_p73_claim(t, key, va);
    if (i >= N48_P73_SLOTS) return i;
    t->pRecorded++;
    t->s[i].spared = 0u; t->s[i].retired = 0u;   /* build 0.0.519: a new P for this plane starts with neither */
    if (commit && gate_seq) {
        t->s[i].seq = gate_seq;
        n48_p73_st32(&t->s[i].state, N48_P73_ST_PENDING);
        t->pend_seq = gate_seq; t->pend_slot = i; t->pend_key = key;
    } else if (commit) {
        /* a COMMIT with no token seq can never be matched at the hook: UNKNOWN (held) */
        t->s[i].seq = 0u;
        n48_p73_st32(&t->s[i].state, N48_P73_ST_UNKNOWN);
    } else {
        t->pRefused++;
        t->s[i].seq = 0u;
        n48_p73_st32(&t->s[i].state, N48_P73_ST_REFUSED);
    }
    return i;
}
/* A judged frame that is NOT a P: each colour target that is a tracked plane becomes UNKNOWN (something other than P wrote it).
 * `keys[k]` 0 are skipped. Returns how many slots it invalidated. */
static inline uint32_t n48_p73_gate_nonp(n48_p73 *t, const uint64_t *keys, uint32_t n)
{
    uint32_t hit = 0u;
    t->judged = 1u;
    t->pend_seq = 0u;
    for (uint32_t k = 0; keys && k < n; k++) {
        const uint32_t i = n48_p73_find(t, keys[k]);
        if (i < N48_P73_SLOTS) {
            n48_p73_st32(&t->s[i].state, N48_P73_ST_UNKNOWN); t->s[i].seq = 0u; t->s[i].spared = 0u; t->s[i].retired = 0u; hit++;
        }
    }
    if (hit) t->nonP++;
    return hit;
}
/* The hook's top: nothing judged yet for this submission, no pending P. */
static inline void n48_p73_call_begin(n48_p73 *t) { t->judged = 0u; t->pend_seq = 0u; }
/* After the judge was asked: a WindowServer IB frame it never judged may have been a P: every plane is UNKNOWN. */
static inline uint32_t n48_p73_after_decide(n48_p73 *t)
{
    if (t->judged) return 0u;
    t->unjudged++;
    n48_p73_invalidate_all(t);
    return 1u;
}
/* build 0.0.519: PENDING -> COMMITTED, only when the slot still names `seq` and BOTH its spared and retired marks are `seq`.
 * A compare-and-swap from PENDING, so the final and the retirement can race and the promotion is counted once. 1 = promoted.
 * build 0.0.520: the promotion is three steps, split so the host test can interleave a new P's gate between any
 * two of them: (1) READY - the marks name `seq`; (2) the CAS PENDING -> COMMITTED; (3) the RE-CHECK - the slot must STILL name
 * `seq` after the CAS. A new P for the same plane (n48_p73_gate_p: marks cleared, seq = the new seq, then PENDING) that lands
 * between (1) and (2) would otherwise have its OWN PENDING turned COMMITTED - a copy of a P that neither spared nor retired. The
 * re-check sees the new seq and reverts COMMITTED -> PENDING (a CAS, so a REFUSED / UNKNOWN / newer PENDING already stored by
 * the gate is left alone), counted in promoteReverted and not in pCommitted. */
static inline uint32_t n48_p73_promote_ready(const n48_p73_slot *s, uint32_t seq)
{
    /* seq_cst: the final (no lock) and the retirement (under gXdLock) each STORE their mark and then LOAD the other's; with
     * sequential consistency at least one of the two sees both marks, so a P spared and retired is never left held. */
    return (seq && __atomic_load_n(&s->seq, __ATOMIC_SEQ_CST) == seq && __atomic_load_n(&s->spared, __ATOMIC_SEQ_CST) == seq &&
            __atomic_load_n(&s->retired, __ATOMIC_SEQ_CST) == seq) ? 1u : 0u;
}
static inline uint32_t n48_p73_promote_cas(n48_p73_slot *s)
{
    uint32_t want = N48_P73_ST_PENDING;
    return __atomic_compare_exchange_n(&s->state, &want, N48_P73_ST_COMMITTED, false, __ATOMIC_SEQ_CST, __ATOMIC_ACQUIRE) ? 1u : 0u;
}
static inline uint32_t n48_p73_promote_recheck(n48_p73 *t, n48_p73_slot *s, uint32_t seq)
{
    if (__atomic_load_n(&s->seq, __ATOMIC_SEQ_CST) != seq) {   /* a new P took the slot: its PENDING is not ours to commit */
        uint32_t want = N48_P73_ST_COMMITTED;
        (void)__atomic_compare_exchange_n(&s->state, &want, N48_P73_ST_PENDING, false, __ATOMIC_SEQ_CST, __ATOMIC_ACQUIRE);
        t->promoteReverted++;
        return 0u;
    }
    t->pCommitted++;
    return 1u;
}
static inline uint32_t n48_p73_promote(n48_p73 *t, n48_p73_slot *s, uint32_t seq)
{
    if (!n48_p73_promote_ready(s, seq)) return 0u;
    if (!n48_p73_promote_cas(s)) return 0u;
    return n48_p73_promote_recheck(t, s, seq);
}
/* THE HOOK'S FINAL OUTCOME for token seq `seq`: `committed` 1 only when the IB was SPARED by the ring walk. Applies only to the
 * pending P of THIS submission (same seq, the slot still holding the same key); anything else is counted and leaves the slot as
 * it is (PENDING stays held). Returns 1 when applied.
 * build 0.0.519: SPARED no longer means COMMITTED - the slot records `spared` and stays PENDING (held) until the P's flight
 * RETIRES (n48_p73_retired); if that retirement already arrived, it is promoted here. */
static inline uint32_t n48_p73_final(n48_p73 *t, uint32_t seq, uint32_t committed)
{
    if (!t->pend_seq) return 0u;
    if (!seq || seq != t->pend_seq || t->pend_slot >= N48_P73_SLOTS ||
        n48_p73_ld64(&t->s[t->pend_slot].key) != t->pend_key || t->s[t->pend_slot].seq != seq) {
        t->finalUnmatched++;
        t->pend_seq = 0u;
        return 0u;
    }
    n48_p73_slot *s = &t->s[t->pend_slot];
    if (committed) {
        t->pSpared++;
        __atomic_store_n(&s->spared, seq, __ATOMIC_SEQ_CST);   /* PENDING stays: held until the flight retires */
        if (n48_p73_promote(t, s, seq)) t->pRetiredFirst++;
    }
    else { t->pWithdrawn++; n48_p73_st32(&s->state, N48_P73_ST_WITHDRAWN); }
    t->pend_seq = 0u;
    return 1u;
}
/* build 0.0.519: THE P's FLIGHT RETIRED - its owned-slot fence read OURS (the flight ring's n48_fr_poll_entry answered 1 for
 * token seq `seq`). Marks the PENDING slot that names `seq` and promotes it when the hook's final already spared it. A seq no
 * PENDING slot names (not a P, a later P already took the plane, a withdrawn or refused P) is counted and changes nothing.
 * Returns 1 when promoted. */
static inline uint32_t n48_p73_retired(n48_p73 *t, uint32_t seq)
{
    if (!seq) return 0u;
    for (uint32_t i = 0; i < N48_P73_SLOTS; i++) {
        n48_p73_slot *s = &t->s[i];
        if (!n48_p73_ld64(&s->key) || s->seq != seq || n48_p73_ld32(&s->state) != N48_P73_ST_PENDING) continue;
        __atomic_store_n(&s->retired, seq, __ATOMIC_SEQ_CST);
        return n48_p73_promote(t, s, seq);
    }
    t->retireNoSlot++;
    return 0u;
}
/* build 0.0.525 (switch 80, notes/design/CYCLE80.md C6) - IS THIS COMMITTED P AN INCOMPLETE CYCLE? Asked by the present for a
 * COMMITTED slot, BEFORE Part E's newer-than check and before anything of Part E is set. ONE load of c80on: OFF (the default)
 * answers 0 and touches nothing else. ON or SHADOW: the P is INCOMPLETE unless switch 80 judged THIS P (c80seq == the slot's
 * seq) COMPLETE. ON answers 1 (hold, reason INCOMPLETE); SHADOW counts "would hold" and answers 0 (the present proceeds exactly
 * as with 80 OFF). */
/* FIX PASS MF-2: the verdict read (s1, v, s2) is this P's COMPLETE verdict only when both seq reads name it. */
static inline uint32_t n48_p73_c80_complete(uint32_t s1, uint32_t v, uint32_t s2, uint32_t seq)
{
    return (seq != 0u && s1 == seq && s2 == seq && v == N48_P73_C80V_COMPLETE) ? 1u : 0u;
}
static inline uint32_t n48_p73_c80_hold(n48_p73 *t, const n48_p73_slot *s, uint32_t seq)
{
    const uint32_t on = n48_p73_ld32(&t->c80on);
    if (on == N48_P73_C80_OFF) return 0u;
    /* FIX PASS MF-2: seq, verdict, seq (acquire each): a verdict counts only when the seq read on BOTH sides of it is this P's */
    const uint32_t s1 = n48_p73_ld32(&s->c80seq);
    const uint32_t v = n48_p73_ld32(&s->c80verdict);
    const uint32_t s2 = n48_p73_ld32(&s->c80seq);
    if (n48_p73_c80_complete(s1, v, s2, seq)) return 0u;
    if (on == N48_P73_C80_SHADOW) { t->c80WouldHold++; return 0u; }
    return 1u;   /* ON, and any unknown mode value: hold (fail-closed) */
}
/* THE PRESENT'S QUESTION (the switch ON): copy plane `key`? 1 copy, 0 hold; *reason = N48_P73_HOLD_*, *slot = the slot or
 * N48_P73_SLOTS. Counts. Only COMMITTED copies. */
static inline uint32_t n48_p73_present(n48_p73 *t, uint64_t key, uint32_t *reason, uint32_t *slot)
{
    const uint32_t i = n48_p73_find(t, key);
    if (slot) *slot = i;
    uint32_t why = N48_P73_HOLD_NOMATCH;
    if (i < N48_P73_SLOTS) {
        const uint32_t st = n48_p73_ld32(&t->s[i].state);
        if (st == N48_P73_ST_COMMITTED) {
            /* build 0.0.521 Part E: only a P NEWER than the one on the glass (the first copy after ON: any) */
            const uint32_t seq = t->s[i].seq;
            if (n48_p73_c80_hold(t, &t->s[i], seq)) why = N48_P73_HOLD_INCOMPLETE;   /* build 0.0.525 C6: before Part E */
            else if (!t->deliveredOk || n48_p73_seq_newer(seq, t->lastDelivered)) {
                t->copied++; t->decided = seq; t->decidedOk = 1u;
                if (reason) *reason = N48_P73_HOLDS;
                return 1u;
            }
            else why = N48_P73_HOLD_OLDER;
        } else
        why = st == N48_P73_ST_REFUSED ? N48_P73_HOLD_REFUSED : st == N48_P73_ST_WITHDRAWN ? N48_P73_HOLD_WITHDRAWN
                                                                                          : N48_P73_HOLD_UNKNOWN;
    }
    t->held[why]++;
    if (reason) *reason = why;
    return 0u;
}
/* build 0.0.521 Part E: the copy the last decision let through reached the glass (dpg_perform: a copy made, clean or with a
 * readback difference). Its P becomes the glass's newest. Nothing to do without a decision (a copy 73 did not decide). */
static inline void n48_p73_delivered(n48_p73 *t)
{
    if (!t->decidedOk) return;
    t->lastDelivered = t->decided; t->deliveredOk = 1u; t->decidedOk = 0u;
    t->delivered++;
}
/* The dpg_perform decision as a whole: the switch OFF copies every present and touches nothing (0.0.515's behaviour). */
static inline uint32_t n48_p73_should_copy(uint32_t on, n48_p73 *t, uint64_t key, uint32_t *reason, uint32_t *slot)
{
    if (!on) return 1u;
    return n48_p73_present(t, key, reason, slot);
}

/* build 0.0.517 ( MEDIUM-1, read-only) - IS THIS COPY ONE OF THE FIRST N48_P73_COPY_LINES? Called by the present
 * side after n48_p73_should_copy answered 1 with the switch ON; counts the line it allows. The line pairs the present (the perform
 * counter) with the P whose COMMITTED state it used (the slot's seq) and the gate's latest seq, so a run can prove or refute the
 * present-after-submit order. Changes no answer. */
static inline uint32_t n48_p73_copy_line_due(n48_p73 *t, uint32_t on, uint32_t copied, uint32_t slot)
{
    if (!on || !copied || slot >= N48_P73_SLOTS || t->copy_lines >= N48_P73_COPY_LINES) return 0u;
    t->copy_lines++;
    return 1u;
}

static inline const char *n48_p73_hold_name(uint32_t r)
{
    return r == N48_P73_HOLD_REFUSED ? "REFUSED" : r == N48_P73_HOLD_WITHDRAWN ? "WITHDRAWN" : r == N48_P73_HOLD_UNKNOWN ? "UNKNOWN"
         : r == N48_P73_HOLD_NOMATCH ? "NO-MATCH" : r == N48_P73_HOLD_OLDER ? "OLDER"
         : r == N48_P73_HOLD_INCOMPLETE ? "INCOMPLETE" : "COPY";   /* build 0.0.525: INCOMPLETE appended */
}
static inline const char *n48_p73_state_name(uint32_t s)
{
    return s == N48_P73_ST_PENDING ? "PENDING" : s == N48_P73_ST_COMMITTED ? "COMMITTED" : s == N48_P73_ST_REFUSED ? "REFUSED"
         : s == N48_P73_ST_WITHDRAWN ? "WITHDRAWN" : "UNKNOWN";
}

/* The report (bare `gfxneuter 73`, after cyc515's two lines) and the capped lines; bounded under the 491-byte body by the test. */
#define N48_P73_FMT "present73: switch 73 %s%s. presents copied %llu, HELD refused %llu withdrawn %llu unknown %llu no-match %llu " \
    "older %llu; flush copies held %llu; hold lines %u of 8; delivered %llu, glass P seq %u."
#define N48_P73_FMT2 "present73: P recorded %llu committed %llu refused %llu withdrawn %llu unresolved %llu; table full %llu; " \
    "non-P writers %llu; unjudged %llu; final unmatched %llu."
/* build 0.0.519: args: spared finals, committed (spared AND retired), retired before the final, retirements with no PENDING P,
 * (0.0.520) promotions reverted because a new P took the slot. */
#define N48_P73_FMT3 "present73: (0.0.519) a P copies only after its flight RETIRES: spared %llu, retired+spared = COMMITTED %llu " \
    "(retired before the final %llu); retirements matching no pending P %llu; promotions reverted (a new P took the slot) %llu."
#define N48_P73_SLOT_FMT "present73: slot %u VRAM %#llx (P CB0 VA %#llx) %s seq %u"
#define N48_P73_PLINE_FMT "present73: P CB0 VA %#llx -> VRAM %#llx (slot %u, the FRAME TARGET conversion + page offset %#llx)"
#define N48_P73_PRLINE_FMT "present73: present #%llu plane VRAM %#llx MATCHES slot %u (P CB0 VA %#llx): the keys agree"
/* args: perform counter, plane key, slot, the slot's P seq, gXdCmGateSeq now, the line number. */
#define N48_P73_COPY_FMT "present73: COPIED present #%llu (perform counter) plane VRAM %#llx slot %u: the slot's P seq %u, " \
    "gate seq now %u (copy line %u of 8)"
#define N48_P73_HOLD_FMT "present73: HELD present #%llu plane VRAM %#llx - %s (slot %u state %s seq %u); copied %llu held %llu"

#endif /* N48_FROZEN_PRESENT73_6AF255A0_H */
